### ISSUE TITLE
Ender Dragon error

### ISSUE THREAD

**Issue by Trinchezito** [BG-Software-LLC/SuperiorSkyblock2#1010]
### Minecraft's Version

1.18.1

### Plugin's Version

latest dev build

### Describe the bug

when the I have "dragon-fight: true" the dragon spawns with the following error and it goes out of the island border. 
![Uploading image.png…]()

`[18:09:18] [Server thread/WARN]: java.lang.IllegalArgumentException: Can not set net.minecraft.world.entity.boss.enderdragon.phases.IDragonController field net.minecraft.world.entity.boss.enderdragon.phases.DragonControllerManager.d to com.bgsoftware.superiorskyblock.nms.v1_18_R1.mapping.world.entity.boss.enderdragon.phases.DragonControllerManager
[18:09:18] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[18:09:18] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[18:09:18] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
[18:09:18] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:75)
[18:09:18] [Server thread/WARN]: 	at java.base/java.lang.reflect.Field.set(Field.java:799)
[18:09:18] [Server thread/WARN]: 	at SuperiorSkyblock2-1.9.0-b567.jar//com.bgsoftware.common.reflection.ReflectField.set(ReflectField.java:74)
[18:09:18] [Server thread/WARN]: 	at SuperiorSkyblock2-1.9.0-b567.jar//com.bgsoftware.superiorskyblock.nms.v1_18_R1.NMSDragonFightImpl.setDragonPhase(NMSDragonFightImpl.java:148)
[18:09:18] [Server thread/WARN]: 	at SuperiorSkyblock2-1.9.0-b567.jar//com.bgsoftware.superiorskyblock.listeners.DragonListener.lambda$onEnderDragonChangePhase$0(DragonListener.java:20)
[18:09:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:09:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[18:09:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1584)
[18:09:18] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:519)
[18:09:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1507)
[18:09:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1294)
[18:09:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[18:09:18] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:09:19] [Server thread/WARN]: java.lang.IllegalArgumentException: Can not set net.minecraft.world.entity.boss.enderdragon.phases.IDragonController field net.minecraft.world.entity.boss.enderdragon.phases.DragonControllerManager.d to com.bgsoftware.superiorskyblock.nms.v1_18_R1.mapping.world.entity.boss.enderdragon.phases.DragonControllerManager
[18:09:19] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[18:09:19] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[18:09:19] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
[18:09:19] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:75)
[18:09:19] [Server thread/WARN]: 	at java.base/java.lang.reflect.Field.set(Field.java:799)
[18:09:19] [Server thread/WARN]: 	at SuperiorSkyblock2-1.9.0-b567.jar//com.bgsoftware.common.reflection.ReflectField.set(ReflectField.java:74)
[18:09:19] [Server thread/WARN]: 	at SuperiorSkyblock2-1.9.0-b567.jar//com.bgsoftware.superiorskyblock.nms.v1_18_R1.NMSDragonFightImpl.setDragonPhase(NMSDragonFightImpl.java:150)
[18:09:19] [Server thread/WARN]: 	at SuperiorSkyblock2-1.9.0-b567.jar//com.bgsoftware.superiorskyblock.listeners.DragonListener.lambda$onEnderDragonChangePhase$0(DragonListener.java:20)
[18:09:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:09:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[18:09:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1584)
[18:09:19] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:519)
[18:09:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1507)
[18:09:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1294)
[18:09:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[18:09:19] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:09:19] [Server thread/WARN]: java.lang.IllegalArgumentException: Can not set net.minecraft.world.entity.boss.enderdragon.phases.IDragonController field net.minecraft.world.entity.boss.enderdragon.phases.DragonControllerManager.d to com.bgsoftware.superiorskyblock.nms.v1_18_R1.mapping.world.entity.boss.enderdragon.phases.DragonControllerManager
[18:09:19] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[18:09:19] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[18:09:19] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
[18:09:19] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:75)
[18:09:19] [Server thread/WARN]: 	at java.base/java.lang.reflect.Field.set(Field.java:799)
[18:09:19] [Server thread/WARN]: 	at SuperiorSkyblock2-1.9.0-b567.jar//com.bgsoftware.common.reflection.ReflectField.set(ReflectField.java:74)
[18:09:19] [Server thread/WARN]: 	at SuperiorSkyblock2-1.9.0-b567.jar//com.bgsoftware.superiorskyblock.nms.v1_18_R1.NMSDragonFightImpl.setDragonPhase(NMSDragonFightImpl.java:149)
[18:09:19] [Server thread/WARN]: 	at SuperiorSkyblock2-1.9.0-b567.jar//com.bgsoftware.superiorskyblock.listeners.DragonListener.lambda$onEnderDragonChangePhase$0(DragonListener.java:20)
[18:09:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:09:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[18:09:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1584)
[18:09:19] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:519)
[18:09:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1507)
[18:09:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1294)
[18:09:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[18:09:19] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)`

### To Reproduce

have dragon-fight: set to true and then go to your end island world.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by Trinchezito** [comment]
Does the dragon suppose to go out of the border?
