### ISSUE TITLE
Bug Nether, End, and other world 1.18.2

### ISSUE THREAD

**Issue by OnLyMaGiK** [BG-Software-LLC/SuperiorSkyblock2#1011]
### Minecraft's Version

This server is running Paper version git-Paper-225 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 1d7a6a0)

### Plugin's Version

Dev build #567

### Describe the bug

[21:21:13 INFO]: OnLyMaGiK issued server command: //schem load desert
[21:21:13 ERROR]: Uncaught exception occurred in task: Loading schematic desert
java.io.IOException: Invalid tag type: 69.
        at com.sk89q.jnbt.NBTInputStream.readTagPayload(NBTInputStream.java:170) ~[worldedit-bukkit-7.2.8.jar:?]
        at com.sk89q.jnbt.NBTInputStream.readNamedTag(NBTInputStream.java:86) ~[worldedit-bukkit-7.2.8.jar:?]
        at com.sk89q.jnbt.NBTInputStream.readTagPayload(NBTInputStream.java:145) ~[worldedit-bukkit-7.2.8.jar:?]
        at com.sk89q.jnbt.NBTInputStream.readNamedTag(NBTInputStream.java:86) ~[worldedit-bukkit-7.2.8.jar:?]
        at com.sk89q.jnbt.NBTInputStream.readNamedTag(NBTInputStream.java:63) ~[worldedit-bukkit-7.2.8.jar:?]
        at com.sk89q.worldedit.extent.clipboard.io.SpongeSchematicReader.getBaseTag(SpongeSchematicReader.java:151) ~[worldedit-bukkit-7.2.8.jar:?]
        at com.sk89q.worldedit.extent.clipboard.io.SpongeSchematicReader.read(SpongeSchematicReader.java:91) ~[worldedit-bukkit-7.2.8.jar:?]
        at com.sk89q.worldedit.command.SchematicCommands$SchematicLoadTask.call(SchematicCommands.java:322) ~[worldedit-bukkit-7.2.8.jar:?]
        at com.sk89q.worldedit.command.SchematicCommands$SchematicLoadTask.call(SchematicCommands.java:304) ~[worldedit-bukkit-7.2.8.jar:?]
        at com.sk89q.worldedit.command.util.AsyncCommandBuilder.runTask(AsyncCommandBuilder.java:158) ~[worldedit-bukkit-7.2.8.jar:?]
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82) ~[guava-31.0.1-jre.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

The nether world is not working, it is activated 

### To Reproduce

//schem load desert
and the others, I can't pass the portals

**Comment by OmerBenGera** [comment]
You cant load plugin's schematics using other plugins such as WorldEdit.
About you cannot enterring portals, make sure you enable the worlds in the config. For further help, ask in the discord server for help.

**Comment by OnLyMaGiK** [comment]
I use worldedit and the world is activated

**Comment by OnLyMaGiK** [comment]
[20:51:13 INFO]: [SuperiorSkyblock2] Schematic desert_the_end was created in a different version, may cause issues.
[20:51:13 ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_18_R2.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[20:51:17 INFO]: [SuperiorSkyblock2] Successfully loaded schematic desert_the_end.schematic (DefaultSchematicParser)
[20:51:17 INFO]: [SuperiorSkyblock2] Schematic normal_the_end was created in a different version, may cause issues.
[20:51:17 INFO]: [SuperiorSkyblock2] Successfully loaded schematic normal_the_end.schematic (DefaultSchematicParser)
[20:51:17 INFO]: [SuperiorSkyblock2] Schematic desert was created in a different version, may cause issues.
[20:51:17 INFO]: [SuperiorSkyblock2] Successfully loaded schematic desert.schematic (DefaultSchematicParser)
[20:51:17 INFO]: [SuperiorSkyblock2] Schematic mycel was created in a different version, may cause issues.
[20:51:17 INFO]: [SuperiorSkyblock2] Successfully loaded schematic mycel.schematic (DefaultSchematicParser)
[20:51:17 INFO]: [SuperiorSkyblock2] Schematic normal_nether was created in a different version, may cause issues.
[20:51:17 INFO]: [SuperiorSkyblock2] Successfully loaded schematic normal_nether.schematic (DefaultSchematicParser)
[20:51:17 INFO]: [SuperiorSkyblock2] Schematic desert_nether was created in a different version, may cause issues.
[20:51:17 INFO]: [SuperiorSkyblock2] Successfully loaded schematic desert_nether.schematic (DefaultSchematicParser)
[20:51:17 INFO]: [SuperiorSkyblock2] Schematic mycel_nether was created in a different version, may cause issues.
[20:51:17 INFO]: [SuperiorSkyblock2] Successfully loaded schematic mycel_nether.schematic (DefaultSchematicParser)
[20:51:17 INFO]: [SuperiorSkyblock2] Schematic normal was created in a different version, may cause issues.
[20:51:17 INFO]: [SuperiorSkyblock2] Successfully loaded schematic normal.schematic (DefaultSchematicParser)
[20:51:17 INFO]: [SuperiorSkyblock2] Schematic mycel_the_end was created in a different version, may cause issues.
[20:51:17 INFO]: [SuperiorSkyblock2] Successfully loaded schematic mycel_the_end.schematic (DefaultSchematicParser)
[20:51:17 INFO]: [SuperiorSkyblock2] Biome 'NETHER' is not valid, skipping...
[20:51:17 INFO]: [SuperiorSkyblock2] Biome 'WOODED_HILLS' is not valid, skipping...

**Comment by OmerBenGera** [comment]
> I use worldedit and the world is activated

You cant load the schematics of the plugin using WorldEdit, as I said before.
