### ISSUE TITLE
An error occurred while disabling the module missions:

### ISSUE THREAD

**Issue by lauretandretheo** [BG-Software-LLC/SuperiorSkyblock2#1027]
### Minecraft's Version

1.18.2 PurpurMc

### Plugin's Version

SuperiorSkyblock2-1.9.0-b579.jar

### Describe the bug

`[14:28:57 INFO]: [SuperiorSkyblock2] Disabling the module bank...
[14:28:57 INFO]: [SuperiorSkyblock2] Disabling the module missions...
[14:28:57 INFO]: [SuperiorSkyblock2] An error occurred while disabling the module missions:
[14:28:57 INFO]: [SuperiorSkyblock2] Contact Ome_R regarding this, this has nothing to do with the plugin.
[14:28:57 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getName()" because the return value of "org.bukkit.Location.getWorld()" is null
[14:28:57 WARN]:        at com.bgsoftware.superiorskyblock.missions.FarmingMissions.parseLocation(FarmingMissions.java:356)
[14:28:57 WARN]:        at com.bgsoftware.superiorskyblock.missions.FarmingMissions.saveProgress(FarmingMissions.java:147)
[14:28:57 WARN]:        at SuperiorSkyblock2.jar//com.bgsoftware.superiorskyblock.mission.MissionsHandler.saveMissionsData(MissionsHandler.java:327)
[14:28:57 WARN]:        at SuperiorSkyblock2.jar//com.bgsoftware.superiorskyblock.module.missions.MissionsModule.onDisable(MissionsModule.java:138)
[14:28:57 WARN]:        at SuperiorSkyblock2.jar//com.bgsoftware.superiorskyblock.module.BuiltinModule.onDisable(BuiltinModule.java:34)
[14:28:57 WARN]:        at SuperiorSkyblock2.jar//com.bgsoftware.superiorskyblock.module.container.DefaultModulesContainer.unregisterModule(DefaultModulesContainer.java:52)
[14:28:57 WARN]:        at SuperiorSkyblock2.jar//com.bgsoftware.superiorskyblock.module.ModulesHandler.unregisterModule(ModulesHandler.java:82)
[14:28:57 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[14:28:57 WARN]:        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
[14:28:57 WARN]:        at SuperiorSkyblock2.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onDisable(SuperiorSkyblockPlugin.java:338)
[14:28:57 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[14:28:57 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401)
[14:28:57 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538)
[14:28:57 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:515)
[14:28:57 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.disablePlugins(CraftServer.java:493)
[14:28:57 WARN]:        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:984)
[14:28:57 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.t(DedicatedServer.java:842)
[14:28:57 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1297)
[14:28:57 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320)
[14:28:57 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[14:28:57 INFO]: [SuperiorSkyblock2] Disabling the module generators...
[14:28:57 INFO]: [SuperiorSkyblock2] Disabling the module upgrades...
`

### To Reproduce

STOP the server

**Comment by OmerBenGera** [comment]
It seems like you have missions data from old worlds that don't exist on the server anymore.
If you changed the world's name, make sure to reset the data file for missions as well.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
This should be fixed on latest dev build

**Comment by lauretandretheo** [comment]
I will try the Dev so thanks

**Comment by OmerBenGera** [comment]
Closing this as it should be fixed
If it wasn't make sure you reply here
