### ISSUE TITLE
erro enabling plugin

### ISSUE THREAD

**Issue by slema20** [BG-Software-LLC/SuperiorSkyblock2#1038]
### Minecraft's Version

1.18.2

### Plugin's Version

SuperiorSkyblock2 v1.9.0

### Describe the bug

[00:30:15] [Server thread/INFO]: [SuperiorSkyblock2] Enabling SuperiorSkyblock2 v1.9.0
[00:30:15] [Server thread/INFO]: [SuperiorSkyblock2] ################################################
[00:30:15] [Server thread/INFO]: [SuperiorSkyblock2] ##                                            ##
[00:30:15] [Server thread/INFO]: [SuperiorSkyblock2] ## An error occured while loading the plugin! ##
[00:30:15] [Server thread/INFO]: [SuperiorSkyblock2] ##                                            ##
[00:30:15] [Server thread/INFO]: [SuperiorSkyblock2] ################################################
[00:30:15] [Server thread/INFO]: [SuperiorSkyblock2] 
[00:30:15] [Server thread/INFO]: [SuperiorSkyblock2] Error:
[00:30:15] [Server thread/INFO]: [SuperiorSkyblock2] java.io.EOFException: End of input at line 1 column 1 path $
[00:30:15] [Server thread/INFO]: [SuperiorSkyblock2] 
[00:30:15] [Server thread/INFO]: [SuperiorSkyblock2] StackTrace:
[00:30:15] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[00:30:15] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[00:30:15] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[00:30:15] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:517)
[00:30:15] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:431)
[00:30:15] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:614)
[00:30:15] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:416)
[00:30:15] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:263)
[00:30:15] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1013)
[00:30:15] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:306)
[00:30:15] [Server thread/INFO]: [SuperiorSkyblock2] 	at java.base/java.lang.Thread.run(Thread.java:833)
[00:30:15] [Server thread/INFO]: [SuperiorSkyblock2] 
[00:30:15] [Server thread/INFO]: [SuperiorSkyblock2] ################################################

### To Reproduce

no enabling plugin

### Additional Information

![error](https://user-images.githubusercontent.com/69693967/161862535-1af6078a-a996-4541-9c37-90b052dc5f09.JPG)

**Comment by OmerBenGera** [comment]
Reset your config files, one of them is broken.
