### ISSUE TITLE
Error with setting chest rows (/is chest)

### ISSUE THREAD

**Issue by Nekosity12** [BG-Software-LLC/SuperiorSkyblock2#112]
So I'm kind of new to github reports sorry if this is really messy. Anyway we've been experiencing some lag on the server which seemed to have gone away after commenting out some quests (more specifically ones that run multiple commands to reward island chest rows). This error was found in logs and I was told I should report it (so here I am) as it may have something to do with our lag. Below the error I provided the mission responsible for the error.
```
[08:55:26] [Server thread/INFO]: Island | Successfully sent to brooklyn06's island members the title!
[08:55:26] [Server thread/INFO]: Bank | You deposited $5,000 into brooklyn06's island bank.
[08:55:26] [Server thread/INFO]: Chest | Successfully updated the rows of page #2 to 3 for brooklyn06's island.
[08:55:26] [Server thread/INFO]: Chest | Successfully updated the rows of page #3 to 3 for brooklyn06's island.
[08:55:26] [Server thread/INFO]: Chest | Successfully updated the rows of page #4 to 3 for brooklyn06's island.
[08:55:26] [Server thread/INFO]: Chest | Successfully updated the rows of page #5 to 3 for brooklyn06's island.
[08:55:26] [SuperiorSkyblock Database Thread 1/WARN]: Exception in thread "SuperiorSkyblock Database Thread 1" java.lang.NullPointerException
[08:55:26] [SuperiorSkyblock Database Thread 1/WARN]:     at com.bgsoftware.superiorskyblock.island.SIsland.setChestRows(SIsland.java:3234)
[08:55:26] [SuperiorSkyblock Database Thread 1/WARN]:     at com.bgsoftware.superiorskyblock.commands.admin.CmdAdminSetChestRow.lambda$null$0(CmdAdminSetChestRow.java:87)
[08:55:26] [SuperiorSkyblock Database Thread 1/WARN]:     at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
[08:55:26] [SuperiorSkyblock Database Thread 1/WARN]:     at com.bgsoftware.superiorskyblock.commands.admin.CmdAdminSetChestRow.lambda$execute$1(CmdAdminSetChestRow.java:87)
[08:55:26] [SuperiorSkyblock Database Thread 1/WARN]:     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[08:55:26] [SuperiorSkyblock Database Thread 1/WARN]:     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[08:55:26] [SuperiorSkyblock Database Thread 1/WARN]:     at java.base/java.lang.Thread.run(Thread.java:834)
```

```
stylishcommunity:
  mission-file: IslandMissions
  island: true
  auto-reward: true
  rewards:
    commands:
      - 'is admin titleall %player% 25 20 10 -title &e&lCongratulations -subtitle &fYou completed "&bStylish Community&f"!'
      - 'is admin deposit %player% 5000'
      - 'is admin setchestrow %player% 2 3'
      - 'is admin setchestrow %player% 3 3'
      - 'is admin setchestrow %player% 4 3'
      - 'is admin setchestrow %player% 5 3'
  events:
    - IslandWorthUpdateEvent
  success-check: 'event.getOldWorth() <= 10000 && event.getNewWorth() > 10000'
  required-missions:
    - "communitybuilding"
  only-show-if-required-completed: true
  icons:
    not-completed:
      type: COAL_BLOCK
      name: '&bStylish Community'
      lore:
        - '&7Did you like the island chests?'
        - '&7There is more where that came from!'
        - '&7Every worth quest will continue to give'
        - '&7more island chests so be sure to complete'
        - '&7them if you love them! You can see how much'
        - '&7you get in the rewards section of the quest'
        - ''
        - '&6Worth Requirement:'
        - '&8 - &710,000 Worth'
        - ''
        - '&6Rewards:'
        - '&8 - &7$5,000 deposited in island bank'
        - '&8 - &74 more chests with 3 rows'
        - ''
        - '&c&l ✘ &7Not Completed'
    can-complete:
      type: COAL_BLOCK
      name: '&bStylish Community'
      lore:
        - '&7Did you like the island chests?'
        - '&7There is more where that came from!'
        - '&7Every worth quest will continue to give'
        - '&7more island chests so be sure to complete'
        - '&7them if you love them! You can see how much'
        - '&7you get in the rewards section of the quest'
        - ''
        - '&6Worth Requirement:'
        - '&8 - &710,000 Worth'
        - ''
        - '&6Rewards:'
        - '&8 - &7$5,000 deposited in island bank'
        - '&8 - &74 more chests with 3 rows'
        - ''
        - '&a&l ✔ &7Click to redeem your reward.'
      enchants:
        DURABILITY: 1
      flags:
        - HIDE_ENCHANTS
    completed:
      type: MAP
      name: '&bStylish Community'
      lore:
        - '&7Did you like the island chests?'
        - '&7There is more where that came from!'
        - '&7Every worth quest will continue to give'
        - '&7more island chests so be sure to complete'
        - '&7them if you love them! You can see how much'
        - '&7you get in the rewards section of the quest'
        - ''
        - '&a&l ✔ &7Already Claimed.'
```

**Comment by Nekosity12** [comment]
Thanks ^^ Will check it out and get back to you

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Skizzles** [comment]
This has been confirmed resolved.

**Comment by OmerBenGera** [comment]
:)
