### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 8

### ISSUE THREAD

**Issue by YouSeeMeRunning2** [BG-Software-LLC/SuperiorSkyblock2#1122]
### Minecraft's Version

mohist 1.12.2

### Plugin's Version

642

### Describe the bug

https://pastebin.com/U7S8dsRD

### To Reproduce

Create an island

**Comment by YouSeeMeRunning2** [comment]
[15:54:13] [Server thread/WARN] []: java.lang.NoSuchFieldError: field_76645_j
[15:54:13] [Server thread/WARN] []: 	at com.bgsoftware.superiorskyblock.nms.v1_12_R1.NMSChunksImpl.removeEntities(NMSChunksImpl.java:63)
[15:54:13] [Server thread/WARN] []: 	at com.bgsoftware.superiorskyblock.nms.v1_12_R1.NMSChunksImpl.lambda$deleteChunks$7(NMSChunksImpl.java:130)
[15:54:13] [Server thread/WARN] []: 	at java.util.ArrayList.forEach(Unknown Source)
[15:54:13] [Server thread/WARN] []: 	at com.bgsoftware.superiorskyblock.nms.v1_12_R1.NMSUtils.runActionOnChunks(NMSUtils.java:69)
[15:54:13] [Server thread/WARN] []: 	at com.bgsoftware.superiorskyblock.nms.v1_12_R1.NMSChunksImpl.deleteChunks(NMSChunksImpl.java:127)
[15:54:13] [Server thread/WARN] []: 	at com.bgsoftware.superiorskyblock.utils.islands.IslandUtils.deleteChunks(IslandUtils.java:244)
[15:54:13] [Server thread/WARN] []: 	at com.bgsoftware.superiorskyblock.world.blocks.BlockChangeTask.lambda$submitUpdate$4(BlockChangeTask.java:65)
[15:54:13] [Server thread/WARN] []: 	at com.bgsoftware.superiorskyblock.world.chunks.ChunksProvider$ChunkLoadWorker.lambda$finishLoad$1(ChunksProvider.java:100)
[15:54:13] [Server thread/WARN] []: 	at java.lang.Iterable.forEach(Unknown Source)
[15:54:13] [Server thread/WARN] []: 	at com.bgsoftware.superiorskyblock.world.chunks.ChunksProvider$ChunkLoadWorker.finishLoad(ChunksProvider.java:100)
[15:54:13] [Server thread/WARN] []: 	at com.bgsoftware.superiorskyblock.world.chunks.ChunksProvider$ChunkLoadWorker.lambda$work$0(ChunksProvider.java:83)
[15:54:13] [Server thread/WARN] []: 	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
[15:54:13] [Server thread/WARN] []: 	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source)
[15:54:13] [Server thread/WARN] []: 	at java.util.concurrent.CompletableFuture.whenComplete(Unknown Source)
[15:54:13] [Server thread/WARN] []: 	at com.bgsoftware.superiorskyblock.world.chunks.ChunksProvider$ChunkLoadWorker.work(ChunksProvider.java:77)
[15:54:13] [Server thread/WARN] []: 	at com.bgsoftware.common.executors.WorkerExecutor.run(WorkerExecutor.java:154)
[15:54:13] [Server thread/WARN] []: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[15:54:13] [Server thread/WARN] []: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:422)
[15:54:13] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:831)
[15:54:13] [Server thread/WARN] []: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
[15:54:13] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778)
[15:54:13] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624)
[15:54:13] [Server thread/WARN] []: 	at java.lang.Thread.run(Unknown Source)
