### ISSUE TITLE
Zombie death triggers time null pointer

### ISSUE THREAD

**Issue by konsheng** [BG-Software-LLC/SuperiorSkyblock2#1201]
### Minecraft's Version

[17:49:33 INFO]: Checking version, please wait...
[17:49:34 INFO]: This server is running Paper version git-Paper-29 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 9797f08)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads

### Plugin's Version

> version SuperiorSkyblock2
[17:50:07 INFO]: SuperiorSkyblock2 version 1.11.0.688
[17:50:07 INFO]: Feature packed Skyblock core.
[17:50:07 INFO]: Website: https://bg-software.com/
[17:50:07 INFO]: Author: Ome_R

### Describe the bug

[17:28:47 ERROR]: Could not pass event EntityDeathEvent to SuperiorSkyblock2 v1.11.0.688
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "tag" is null
        at com.bgsoftware.superiorskyblock.tag.CompoundTag.fromNBT(CompoundTag.java:269) ~[SuperiorSkyblock2-1.11.0-b688.jar:?]
        at com.bgsoftware.superiorskyblock.nms.v1_19_R1.NMSTagsImpl.getNBTTag(NMSTagsImpl.java:38) ~[SuperiorSkyblock2-1.11.0-b688.jar:?]
        at com.bgsoftware.superiorskyblock.module.upgrades.type.UpgradeTypeMobDrops$MobDropsListener.onEntityDeath(UpgradeTypeMobDrops.java:91) ~[SuperiorSkyblock2-1.11.0-b688.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-29]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:876) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1748) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1645) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1475) ~[?:?]
        at net.minecraft.world.entity.Entity.baseTick(Entity.java:823) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:393) ~[?:?]
        at net.minecraft.world.entity.Mob.baseTick(Mob.java:329) ~[?:?]
        at net.minecraft.world.entity.Entity.tick(Entity.java:776) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2909) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:402) ~[?:?]
        at net.minecraft.world.entity.monster.Skeleton.tick(Skeleton.java:65) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1155) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:898) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:692) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:672) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1551) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-29]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### To Reproduce

I don't know what caused it, I didn't modify any configuration files, and the error was reported.

### Additional Information

[17:51:51 INFO]: Plugins (17): DecentHolograms, Essentials, EssentialsProtect, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), HolographicDisplays, InteractionVisualizer, InteractiveChat, LuckPerms, Multiverse-Core, NBTAPI, PlaceholderAPI, PlayerPoints, ProtocolLib, spark, SuperiorSkyblock2, Vault

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
