### ISSUE TITLE
Cannot get my schematic to work

### ISSUE THREAD

**Issue by SebLeRouge666** [BG-Software-LLC/SuperiorSkyblock2#1202]
### Minecraft's Version

1.19

### Plugin's Version

SuperiorSkyblock2 - 1.11.0

### Describe the bug

I can't put my schematic ass an island, I keep getting this error : 

[17:40:11 WARN]: java.lang.IllegalArgumentException: Cannot add Locations of differing worlds
[17:40:11 WARN]:        at org.bukkit.Location.add(Location.java:360)
[17:40:11 WARN]:        at SuperiorSkyblock2-1.11.0.jar//com.bgsoftware.superiorskyblock.core.SchematicEntity.spawnEntity(SchematicEntity.java:25)
[17:40:11 WARN]:        at SuperiorSkyblock2-1.11.0.jar//com.bgsoftware.superiorskyblock.world.schematic.impl.SuperiorSchematic.lambda$pasteSchematic$1(SuperiorSchematic.java:119)
[17:40:11 WARN]:        at SuperiorSkyblock2-1.11.0.jar//com.bgsoftware.superiorskyblock.world.BlockChangeTask.lambda$submitUpdate$5(BlockChangeTask.java:96)
[17:40:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
[17:40:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
[17:40:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[17:40:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
[17:40:11 WARN]:        at SuperiorSkyblock2-1.11.0.jar//com.bgsoftware.superiorskyblock.world.chunk.ChunksProvider$ChunkLoadWorker.finishLoad(ChunksProvider.java:111)
[17:40:11 WARN]:        at SuperiorSkyblock2-1.11.0.jar//com.bgsoftware.superiorskyblock.world.chunk.ChunksProvider$ChunkLoadWorker.lambda$work$0(ChunksProvider.java:93)
[17:40:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
[17:40:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
[17:40:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[17:40:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
[17:40:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1163)
[17:40:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[17:40:11 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.execute(IAsyncTaskHandler.java:100)
[17:40:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
[17:40:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1147)
[17:40:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[17:40:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
[17:40:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1163)
[17:40:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[17:40:11 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[17:40:11 WARN]:        at net.minecraft.server.level.ChunkProviderServer$b.d(ChunkProviderServer.java:1248)
[17:40:11 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[17:40:11 WARN]:        at net.minecraft.server.level.ChunkProviderServer$b.x(ChunkProviderServer.java:1261)
[17:40:11 WARN]:        at net.minecraft.server.level.ChunkProviderServer.d(ChunkProviderServer.java:821)
[17:40:11 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1346)
[17:40:11 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1328)
[17:40:11 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[17:40:11 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1306)
[17:40:11 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1191)
[17:40:11 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
[17:40:11 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### To Reproduce

Put on my schematic called "Island" in schematic file
After go on island-creation.yml and put the schem to "island"
reload de plugin or the server
And them try creation an island

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
