### ISSUE TITLE
SkinsRestorer IllegalAccessException

### ISSUE THREAD

**Issue by nhanledev** [BG-Software-LLC/SuperiorSkyblock2#1208]
### Minecraft's Version

Paper 1.18.2

### Plugin's Version

SuperiorSkyblock2-1.11.0-b696
SkinsRestorer-14.2.1

### Describe the bug

Something is wrong while booting the Paper 1.18.2 and Skin with the logs below:

```
[22:17:12] [Server thread/WARN]: java.lang.IllegalAccessException: class com.bgsoftware.common.reflection.ReflectField$FieldWrapper cannot access a member of class net.skinsrestorer.shared.storage.SkinStorage with modifiers "private"
[22:17:12] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
[22:17:12] [Server thread/WARN]: 	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
[22:17:12] [Server thread/WARN]: 	at java.base/java.lang.reflect.Field.checkAccess(Field.java:1102)
[22:17:12] [Server thread/WARN]: 	at java.base/java.lang.reflect.Field.get(Field.java:423)
[22:17:12] [Server thread/WARN]: 	at SuperiorSkyblock2-1.11.0-b696.jar//com.bgsoftware.common.reflection.ReflectField$FieldWrapper.get(ReflectField.java:162)
[22:17:12] [Server thread/WARN]: 	at SuperiorSkyblock2-1.11.0-b696.jar//com.bgsoftware.common.reflection.ReflectField.get(ReflectField.java:65)
[22:17:12] [Server thread/WARN]: 	at SuperiorSkyblock2-1.11.0-b696.jar//com.bgsoftware.common.reflection.ReflectField.get(ReflectField.java:57)
[22:17:12] [Server thread/WARN]: 	at SuperiorSkyblock2-1.11.0-b696.jar//com.bgsoftware.superiorskyblock.external.SkinsRestorerHook$SkinsRestorerNew.checkForLocalMode(SkinsRestorerHook.java:104)
[22:17:12] [Server thread/WARN]: 	at SuperiorSkyblock2-1.11.0-b696.jar//com.bgsoftware.superiorskyblock.external.SkinsRestorerHook$SkinsRestorerNew.<init>(SkinsRestorerHook.java:91)
[22:17:12] [Server thread/WARN]: 	at SuperiorSkyblock2-1.11.0-b696.jar//com.bgsoftware.superiorskyblock.external.SkinsRestorerHook$SkinsRestorerNew.<init>(SkinsRestorerHook.java:87)
[22:17:12] [Server thread/WARN]: 	at SuperiorSkyblock2-1.11.0-b696.jar//com.bgsoftware.superiorskyblock.external.SkinsRestorerHook.register(SkinsRestorerHook.java:35)
[22:17:12] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:17:12] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[22:17:12] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:17:12] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[22:17:12] [Server thread/WARN]: 	at SuperiorSkyblock2-1.11.0-b696.jar//com.bgsoftware.superiorskyblock.external.ProvidersManagerImpl.registerHook(ProvidersManagerImpl.java:563)
[22:17:12] [Server thread/WARN]: 	at SuperiorSkyblock2-1.11.0-b696.jar//com.bgsoftware.superiorskyblock.external.ProvidersManagerImpl.registerGeneralHooks(ProvidersManagerImpl.java:369)
[22:17:12] [Server thread/WARN]: 	at SuperiorSkyblock2-1.11.0-b696.jar//com.bgsoftware.superiorskyblock.external.ProvidersManagerImpl.lambda$loadData$1(ProvidersManagerImpl.java:91)
[22:17:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[22:17:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[22:17:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[22:17:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[22:17:12] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[22:17:12] [Server thread/INFO]: [SuperiorSkyblock2] An error occurred while registering SkinsRestorerHook:
[22:17:12] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[22:17:12] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:17:12] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[22:17:12] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:17:12] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[22:17:12] [Server thread/WARN]: 	at SuperiorSkyblock2-1.11.0-b696.jar//com.bgsoftware.superiorskyblock.external.ProvidersManagerImpl.registerHook(ProvidersManagerImpl.java:563)
[22:17:12] [Server thread/WARN]: 	at SuperiorSkyblock2-1.11.0-b696.jar//com.bgsoftware.superiorskyblock.external.ProvidersManagerImpl.registerGeneralHooks(ProvidersManagerImpl.java:369)
[22:17:12] [Server thread/WARN]: 	at SuperiorSkyblock2-1.11.0-b696.jar//com.bgsoftware.superiorskyblock.external.ProvidersManagerImpl.lambda$loadData$1(ProvidersManagerImpl.java:91)
[22:17:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[22:17:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[22:17:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[22:17:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[22:17:12] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[22:17:12] [Server thread/WARN]: Caused by: java.lang.NoClassDefFoundError: skinsrestorer/shared/exception/SkinRequestException
[22:17:12] [Server thread/WARN]: 	at SuperiorSkyblock2-1.11.0-b696.jar//com.bgsoftware.superiorskyblock.external.SkinsRestorerHook.register(SkinsRestorerHook.java:37)
[22:17:12] [Server thread/WARN]: 	... 12 more
[22:17:12] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: skinsrestorer.shared.exception.SkinRequestException
[22:17:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
[22:17:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[22:17:12] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[22:17:12] [Server thread/WARN]: 	... 13 more
[22:17:12] [Server thread/INFO]: [SuperiorSkyblock2] Using LuckPerms as a permissions provider.
[22:17:12] [Server thread/INFO]: [SuperiorSkyblock2] Hooked into CMI for support of vanish status of players.
[22:17:12] [Server thread/INFO]: [SuperiorSkyblock2] Hooked into CMI for support of afk status of players.
[22:17:12] [Server thread/INFO]: [SuperiorSkyblock2] Using Vault as an economy provider.
[22:17:12] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: superior [1.11.0.696]
```

### To Reproduce

Install the server on paper 1.18.2 with 2 plugins

SuperiorSkyblock2-1.11.0-b696
SkinsRestorer-14.2.1

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
