### ISSUE TITLE
Could not create empty island

### ISSUE THREAD

**Issue by konsheng** [BG-Software-LLC/SuperiorSkyblock2#1210]
### Minecraft's Version

1.12.2 Catserver
https://catmc.org/
download link

### Plugin's Version

1.11.0.696

### Describe the bug

Could not create empty island

### To Reproduce

/is create aaa

### Additional Information

[12:12:26] [Server thread/WARN]: java.lang.NoSuchFieldError: field_76645_j
[12:12:26] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.nms.v1_12_R1.NMSChunksImpl.removeEntities(NMSChunksImpl.java:67)
[12:12:26] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.nms.v1_12_R1.NMSChunksImpl.lambda$deleteChunks$7(NMSChunksImpl.java:132)
[12:12:26] [Server thread/WARN]:        at java.lang.Iterable.forEach(Unknown Source)
[12:12:26] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.nms.v1_12_R1.NMSUtils.runActionOnChunks(NMSUtils.java:70)
[12:12:26] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.nms.v1_12_R1.NMSChunksImpl.deleteChunks(NMSChunksImpl.java:129)
[12:12:26] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.island.IslandUtils.deleteChunks(IslandUtils.java:246)
[12:12:26] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.world.BlockChangeTask.lambda$submitUpdate$4(BlockChangeTask.java:67)
[12:12:26] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.world.chunk.ChunksProvider$ChunkLoadWorker.lambda$finishLoad$1(ChunksProvider.java:110)
[12:12:26] [Server thread/WARN]:        at java.lang.Iterable.forEach(Unknown Source)
[12:12:26] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.world.chunk.ChunksProvider$ChunkLoadWorker.finishLoad(ChunksProvider.java:110)
[12:12:26] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.world.chunk.ChunksProvider$ChunkLoadWorker.lambda$work$0(ChunksProvider.java:93)
[12:12:26] [Server thread/WARN]:        at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
[12:12:26] [Server thread/WARN]:        at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source)
[12:12:26] [Server thread/WARN]:        at java.util.concurrent.CompletableFuture.whenComplete(Unknown Source)
[12:12:26] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.world.chunk.ChunksProvider$ChunkLoadWorker.work(ChunksProvider.java:87)
[12:12:26] [Server thread/WARN]:        at com.bgsoftware.common.executors.WorkerExecutor.run(WorkerExecutor.java:154)
[12:12:26] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[12:12:26] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:421)
[12:12:26] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:900)
[12:12:26] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475)
[12:12:26] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834)
[12:12:26] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
[12:12:26] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by OmerBenGera** [comment]
CatServer is not supported
