### ISSUE TITLE
Island Ban - Crash

### ISSUE THREAD

**Issue by e1054** [BG-Software-LLC/SuperiorSkyblock2#1237]
### Minecraft's Version

1.8.8

### Plugin's Version

1.10.2

### Describe the bug

Rarely when a Player bans a player with OP permission from their island, the teleport utils can't find a location to teleport the player. This courses the code to loop and crash the server. This has only happend twice in a couble of months and is thereby rarely happening.

### To Reproduce

1) Have a player without speciel permissions create an island
2) Make a Player with OP permissions visit the player
3) Make the Player /is ban the other player

### Additional Information

[16:25:25] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to SuperiorSkyblock2 v1.10.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:501) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:469) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityPlayer.enderTeleportTo(EntityPlayer.java:937) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityLiving.q(EntityLiving.java:1291) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityLiving.mount(EntityLiving.java:1724) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityPlayer.mount(EntityPlayer.java:612) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:549) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:236) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at com.bgsoftware.superiorskyblock.hooks.provider.AsyncProvider_Default.teleport(AsyncProvider_Default.java:12) ~[?:?]
	at com.bgsoftware.superiorskyblock.utils.teleport.TeleportUtils.teleportEntity(TeleportUtils.java:33) ~[?:?]
	at com.bgsoftware.superiorskyblock.utils.teleport.TeleportUtils.lambda$teleport$0(TeleportUtils.java:26) ~[?:?]
	at com.bgsoftware.superiorskyblock.hooks.provider.WorldsProvider_Default.prepareTeleport(WorldsProvider_Default.java:109) ~[?:?]
	at com.bgsoftware.superiorskyblock.utils.teleport.TeleportUtils.teleport(TeleportUtils.java:25) ~[?:?]
	at com.bgsoftware.superiorskyblock.player.algorithm.DefaultPlayerTeleportAlgorithm.teleport(DefaultPlayerTeleportAlgorithm.java:50) ~[?:?]
	at com.bgsoftware.superiorskyblock.player.algorithm.DefaultPlayerTeleportAlgorithm.teleport(DefaultPlayerTeleportAlgorithm.java:82) ~[?:?]
	at com.bgsoftware.superiorskyblock.player.SSuperiorPlayer.teleport(SSuperiorPlayer.java:366) ~[?:?]
	at com.bgsoftware.superiorskyblock.player.SSuperiorPlayer.teleport(SSuperiorPlayer.java:359) ~[?:?]
	at com.bgsoftware.superiorskyblock.player.SSuperiorPlayer.teleport(SSuperiorPlayer.java:349) ~[?:?]
	at com.bgsoftware.superiorskyblock.utils.logic.PlayersLogic.handlePlayerEnterIsland(PlayersLogic.java:152) ~[?:?]
	at com.bgsoftware.superiorskyblock.listeners.CustomEventsListener.onPlayerTeleport(CustomEventsListener.java:85) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:501) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:469) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityPlayer.enderTeleportTo(EntityPlayer.java:937) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityLiving.q(EntityLiving.java:1291) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityLiving.mount(EntityLiving.java:1724) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityPlayer.mount(EntityPlayer.java:612) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:549) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:236) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at com.bgsoftware.superiorskyblock.hooks.provider.AsyncProvider_Default.teleport(AsyncProvider_Default.java:12) ~[?:?]
	at com.bgsoftware.superiorskyblock.utils.teleport.TeleportUtils.teleportEntity(TeleportUtils.java:33) ~[?:?]
	at com.bgsoftware.superiorskyblock.utils.teleport.TeleportUtils.lambda$teleport$0(TeleportUtils.java:26) ~[?:?]
	at com.bgsoftware.superiorskyblock.hooks.provider.WorldsProvider_Default.prepareTeleport(WorldsProvider_Default.java:109) ~[?:?]
	at com.bgsoftware.superiorskyblock.utils.teleport.TeleportUtils.teleport(TeleportUtils.java:25) ~[?:?]
	at com.bgsoftware.superiorskyblock.player.algorithm.DefaultPlayerTeleportAlgorithm.teleport(DefaultPlayerTeleportAlgorithm.java:50) ~[?:?]
	at com.bgsoftware.superiorskyblock.player.algorithm.DefaultPlayerTeleportAlgorithm.teleport(DefaultPlayerTeleportAlgorithm.java:82) ~[?:?]
	at com.bgsoftware.superiorskyblock.player.SSuperiorPlayer.teleport(SSuperiorPlayer.java:366) ~[?:?]
	at com.bgsoftware.superiorskyblock.player.SSuperiorPlayer.teleport(SSuperiorPlayer.java:359) ~[?:?]
	at com.bgsoftware.superiorskyblock.player.SSuperiorPlayer.teleport(SSuperiorPlayer.java:349) ~[?:?]
	at com.bgsoftware.superiorskyblock.utils.logic.PlayersLogic.handlePlayerEnterIsland(PlayersLogic.java:152) ~[?:?]
	at com.bgsoftware.superiorskyblock.listeners.CustomEventsListener.onPlayerTeleport(CustomEventsListener.java:85) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:501) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:469) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityPlayer.enderTeleportTo(EntityPlayer.java:937) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityLiving.q(EntityLiving.java:1291) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityLiving.mount(EntityLiving.java:1724) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityPlayer.mount(EntityPlayer.java:612) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:549) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:236) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at com.bgsoftware.superiorskyblock.hooks.provider.AsyncProvider_Default.teleport(AsyncProvider_Default.java:12) ~[?:?]
	at com.bgsoftware.superiorskyblock.utils.teleport.TeleportUtils.teleportEntity(TeleportUtils.java:33) ~[?:?]
	at com.bgsoftware.superiorskyblock.utils.teleport.TeleportUtils.lambda$teleport$0(TeleportUtils.java:26) ~[?:?]
	at com.bgsoftware.superiorskyblock.hooks.provider.WorldsProvider_Default.prepareTeleport(WorldsProvider_Default.java:109) ~[?:?]
	at com.bgsoftware.superiorskyblock.utils.teleport.TeleportUtils.teleport(TeleportUtils.java:25) ~[?:?]
	at com.bgsoftware.superiorskyblock.player.algorithm.DefaultPlayerTeleportAlgorithm.teleport(DefaultPlayerTeleportAlgorithm.java:50) ~[?:?]
	at com.bgsoftware.superiorskyblock.player.algorithm.DefaultPlayerTeleportAlgorithm.teleport(DefaultPlayerTeleportAlgorithm.java:82) ~[?:?]
	at com.bgsoftware.superiorskyblock.player.SSuperiorPlayer.teleport(SSuperiorPlayer.java:366) ~[?:?]
	at com.bgsoftware.superiorskyblock.player.SSuperiorPlayer.teleport(SSuperiorPlayer.java:359) ~[?:?]
	at com.bgsoftware.superiorskyblock.player.SSuperiorPlayer.teleport(SSuperiorPlayer.java:349) ~[?:?]
	at com.bgsoftware.superiorskyblock.utils.logic.PlayersLogic.handlePlayerEnterIsland(PlayersLogic.java:152) ~[?:?]
	at com.bgsoftware.superiorskyblock.listeners.CustomEventsListener.onPlayerTeleport(CustomEventsListener.java:85) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:501) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:469) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityPlayer.enderTeleportTo(EntityPlayer.java:937) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityLiving.q(EntityLiving.java:1291) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityLiving.mount(EntityLiving.java:1724) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityPlayer.mount(EntityPlayer.java:612) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:549) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:236) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at com.bgsoftware.superiorskyblock.hooks.provider.AsyncProvider_Default.teleport(AsyncProvider_Default.java:12) ~[?:?]
	at com.bgsoftware.superiorskyblock.utils.teleport.TeleportUtils.teleportEntity(TeleportUtils.java:33) ~[?:?]
	at com.bgsoftware.superiorskyblock.utils.teleport.TeleportUtils.lambda$teleport$0(TeleportUtils.java:26) ~[?:?]
	at com.bgsoftware.superiorskyblock.hooks.provider.WorldsProvider_Default.prepareTeleport(WorldsProvider_Default.java:109) ~[?:?]
	at com.bgsoftware.superiorskyblock.utils.teleport.TeleportUtils.teleport(TeleportUtils.java:25) ~[?:?]
	at com.bgsoftware.superiorskyblock.player.algorithm.DefaultPlayerTeleportAlgorithm.teleport(DefaultPlayerTeleportAlgorithm.java:50) ~[?:?]
	at com.bgsoftware.superiorskyblock.player.algorithm.DefaultPlayerTeleportAlgorithm.teleport(DefaultPlayerTeleportAlgorithm.java:82) ~[?:?]
	at com.bgsoftware.superiorskyblock.player.SSuperiorPlayer.teleport(SSuperiorPlayer.java:366) ~[?:?]
	at com.bgsoftware.superiorskyblock.player.SSuperiorPlayer.teleport(SSuperiorPlayer.java:359) ~[?:?]
	at com.bgsoftware.superiorskyblock.player.SSuperiorPlayer.teleport(SSuperiorPlayer.java:349) ~[?:?]
	at com.bgsoftware.superiorskyblock.utils.logic.PlayersLogic.handlePlayerEnterIsland(PlayersLogic.java:152) ~[?:?]
	at com.bgsoftware.superiorskyblock.listeners.CustomEventsListener.onPlayerTeleport(CustomEventsListener.java:85) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]

**Comment by OmerBenGera** [comment]
Please send me your entire logs file by uploading to pastebin / mediafire and send a link here.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by e1054** [comment]
I did some research on the topic and it only happends if a player is writting another player (We are using a custome plugin to make people able to ride ontop of other players)

**Comment by OmerBenGera** [comment]
> I did some research on the topic and it only happends if a player is writting another player (We are using a custome plugin to make people able to ride ontop of other players)
> 
> (Also that was the full log file regarding SuperiorSkyblock2)

So which player needs to be banned exactly in order to get that issue? The player that rides another or the player that has another player carried as a "passenger"? (Or in other words, ban the passenger or the other player)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works now

**Comment by OmerBenGera** [comment]
Closing this for now
If it still happens, lmk
