### ISSUE TITLE
Cannot invoke "net.skinsrestorer.api.property.IProperty.getHandle()"

### ISSUE THREAD

**Issue by hitanol** [BG-Software-LLC/SuperiorSkyblock2#1264]
### Minecraft's Version

git-Purpur-1713 (MC: 1.19)

### Plugin's Version

v1.11.0.720

### Describe the bug

it is showed in console when a player joins the server

### To Reproduce

install SS2 and SkinsRestorer and join the server

### Additional Information

```
[21:34:15 WARN]: [SuperiorSkyblock2] Plugin SuperiorSkyblock2 v1.11.0.720 generated an exception while executing task 4422
java.lang.NullPointerException: Cannot invoke "net.skinsrestorer.api.property.IProperty.getHandle()" because "property" is null
        at com.bgsoftware.superiorskyblock.external.SkinsRestorerHook$SkinsRestorerNew.getSkin(SkinsRestorerHook.java:134) ~[SuperiorSkyblock2-1.11.0-b720.jar:?]
        at com.bgsoftware.superiorskyblock.external.SkinsRestorerHook.setSkinTexture(SkinsRestorerHook.java:54) ~[SuperiorSkyblock2-1.11.0-b720.jar:?]
        at com.bgsoftware.superiorskyblock.external.SkinsRestorerHook.lambda$setSkinTexture$0(SkinsRestorerHook.java:49) ~[SuperiorSkyblock2-1.11.0-b720.jar:?]
        at com.bgsoftware.superiorskyblock.external.SkinsRestorerHook$$Lambda$12735/0x00000000e9275758.run(Unknown Source) ~[SuperiorSkyblock2-1.11.0-b720.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.jar:git-Purpur-1713]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.jar:git-Purpur-1713]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:884) ~[?:?]
```

**Comment by hitanol** [comment]
update: it ocurrs when the player is not in online mode

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
