### ISSUE TITLE
Cant create an Island

### ISSUE THREAD

**Issue by realgamerk** [BG-Software-LLC/SuperiorSkyblock2#1335]
### Minecraft's Version

Version: 1.8.8
Jar: WindSpigot
(WindSpigot Release v2.1.2)

### Plugin's Version

1.11.1

### Describe the bug

When i create an Island it says this https://pastebin.com/ryrFs54H
and Error Ingame.

### To Reproduce

when i /is create and select an island it says error and check console it says
and the console says https://pastebin.com/ryrFs54H

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by realgamerk** [comment]
Yo It Works Mate! thanks alot <3

**Comment by realgamerk** [comment]
But it spams this [03:31:02 ERROR]: Could not pass event ChunkUnloadEvent to SuperiorSkyblock2 v1.11.1.783
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[server.jar:]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:67) ~[server.jar:]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:511) ~[server.jar:]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) ~[server.jar:]
at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:436) ~[server.jar:]
at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:270) ~[server.jar:]
at ga.windpvp.windspigot.world.WorldTicker.run(WorldTicker.java:30) ~[server.jar:]
at ga.windpvp.windspigot.world.WorldTickerManager.tickSync(WorldTickerManager.java:84) ~[server.jar:]
at ga.windpvp.windspigot.world.WorldTickerManager.tick(WorldTickerManager.java:75) ~[server.jar:]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:973) ~[server.jar:]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:454) ~[server.jar:]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:854) ~[server.jar:]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:707) ~[server.jar:]
at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]
Caused by: java.lang.NoSuchFieldError: tileEntityList
at com.bgsoftware.superiorskyblock.nms.v1_8_R3.NMSChunksImpl.startTickingChunk(NMSChunksImpl.java:232) ~[?:?]
at com.bgsoftware.superiorskyblock.world.event.WorldEventsManagerImpl.unloadChunk(WorldEventsManagerImpl.java:106) ~[?:?]
at com.bgsoftware.superiorskyblock.listener.ChunksListener.onChunkUnloadMonitor(ChunksListener.java:48) ~[?:?]
at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[server.jar:]
... 14 more
[03:31:02 ERROR]: Could not pass event ChunkUnloadEvent to SuperiorSkyblock2 v1.11.1.783
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[server.jar:]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:67) ~[server.jar:]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:511) ~[server.jar:]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) ~[server.jar:]
at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:436) ~[server.jar:]
at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:270) ~[server.jar:]
at ga.windpvp.windspigot.world.WorldTicker.run(WorldTicker.java:30) ~[server.jar:]
at ga.windpvp.windspigot.world.WorldTickerManager.tickSync(WorldTickerManager.java:84) ~[server.jar:]
at ga.windpvp.windspigot.world.WorldTickerManager.tick(WorldTickerManager.java:75) ~[server.jar:]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:973) ~[server.jar:]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:454) ~[server.jar:]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:854) ~[server.jar:]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:707) ~[server.jar:]
at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]
Caused by: java.lang.NoSuchFieldError: tileEntityList
at com.bgsoftware.superiorskyblock.nms.v1_8_R3.NMSChunksImpl.startTickingChunk(NMSChunksImpl.java:232) ~[?:?]
at com.bgsoftware.superiorskyblock.world.event.WorldEventsManagerImpl.unloadChunk(WorldEventsManagerImpl.java:106) ~[?:?]
at com.bgsoftware.superiorskyblock.listener.ChunksListener.onChunkUnloadMonitor(ChunksListener.java:48) ~[?:?]
at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[server.jar:]

**Comment by OmerBenGera** [comment]
Check out latest dev build, hopefully the other errors are gone now as well

**Comment by realgamerk** [comment]
Thanks alot
