### ISSUE TITLE
Unexpected end of file from server

### ISSUE THREAD

**Issue by JeansouLiu** [BG-Software-LLC/SuperiorSkyblock2#1339]
### Minecraft's Version

1.19.2

### Plugin's Version

1.11.1-b766

### Describe the bug

[19:42:58] [Server thread/INFO]: [SuperiorSkyblock2] Loading SuperiorSkyblock2 v1.11.1.766
[19:43:34] [Server thread/WARN]: java.net.SocketException: Unexpected end of file from server
[19:43:34] [Server thread/WARN]: 	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:903)
[19:43:34] [Server thread/WARN]: 	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:726)
[19:43:34] [Server thread/WARN]: 	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:900)
[19:43:34] [Server thread/WARN]: 	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:726)
[19:43:34] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1688)
[19:43:34] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[19:43:34] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[19:43:34] [Server thread/WARN]: 	at SuperiorSkyblock2-1.11.1-b766.jar//com.bgsoftware.common.mappings.MappingsChecker.checkMappings(MappingsChecker.java:31)
[19:43:34] [Server thread/WARN]: 	at SuperiorSkyblock2-1.11.1-b766.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.loadNMSAdapter(SuperiorSkyblockPlugin.java:389)
[19:43:34] [Server thread/WARN]: 	at SuperiorSkyblock2-1.11.1-b766.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onLoad(SuperiorSkyblockPlugin.java:180)
[19:43:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:429)
[19:43:34] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:278)
[19:43:34] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1126)
[19:43:34] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[19:43:34] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[19:43:34] [Server thread/INFO]: [SuperiorSkyblock2] ################################################
[19:43:34] [Server thread/INFO]: [SuperiorSkyblock2] ##                                            ##
[19:43:34] [Server thread/INFO]: [SuperiorSkyblock2] ## An error occured while loading the plugin! ##
[19:43:34] [Server thread/INFO]: [SuperiorSkyblock2] ##                                            ##
[19:43:34] [Server thread/INFO]: [SuperiorSkyblock2] ################################################
[19:43:34] [Server thread/INFO]: [SuperiorSkyblock2] 
[19:43:34] [Server thread/INFO]: [SuperiorSkyblock2] Error:
[19:43:34] [Server thread/INFO]: [SuperiorSkyblock2] The plugin doesn't support your version mappings.
[19:43:34] [Server thread/INFO]: [SuperiorSkyblock2] Please try a different version.
[19:43:34] [Server thread/INFO]: [SuperiorSkyblock2] Mappings Hash: 69c84c88aeb92ce9fa9525438b93f4fe
[19:43:34] [Server thread/INFO]: [SuperiorSkyblock2] 
[19:43:34] [Server thread/INFO]: [SuperiorSkyblock2] StackTrace:
[19:43:34] [Server thread/INFO]: [SuperiorSkyblock2] 	at SuperiorSkyblock2-1.11.1-b766.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onLoad(SuperiorSkyblockPlugin.java:180)
[19:43:34] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:429)
[19:43:34] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:278)
[19:43:34] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1126)
[19:43:34] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[19:43:34] [Server thread/INFO]: [SuperiorSkyblock2] 	at java.base/java.lang.Thread.run(Thread.java:833)
[19:43:34] [Server thread/INFO]: [SuperiorSkyblock2] 
[19:43:34] [Server thread/INFO]: [SuperiorSkyblock2] ################################################

And the server is automatically stopped after starting up.

### To Reproduce

Not knowing how to reproduce.
It just happens after I restart my server today.

**Comment by OmerBenGera** [comment]
For no reason the server cannot access https://bg-software.com/mappings.json

Any reason for that?

**Comment by JeansouLiu** [comment]
Maybe it is because of the China's firewall.
The problem don't appear again today.

Is it possible to write this json into the plugin instead of requesting it from a server?

**Comment by OmerBenGera** [comment]
> Maybe it is because of the China's firewall. The problem don't appear again today.
> 
> Is it possible to write this json into the plugin instead of requesting it from a server?

No, it must be remotely.
However, it shouldnt fail if the request fails. I will fix it.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by NetheriteTree** [comment]
> Fixed in latest dev build

It seems that the latest build will stuck in the loading process.
```
[SuperiorSkyblock2] Loading SuperiorSkyblock2 v1.11.1.788
```
