### ISSUE TITLE
Spawners Worth Don't work

### ISSUE THREAD

**Issue by Jok3rTV** [BG-Software-LLC/SuperiorSkyblock2#1360]
### Minecraft's Version

version git-Paper-142 (MC: 1.19.2)

### Plugin's Version

SuperiorSkyblock2-1.11.1-b795

### Describe the bug

I use AdvancedSpawners and the spawners don't count on worth.yml and they don't get count on /is values
![image](https://user-images.githubusercontent.com/42006262/190179637-ff62adfd-f721-4fdf-91e9-d54ecb87c265.png)
![image](https://user-images.githubusercontent.com/42006262/190179680-4d050047-eb96-49c8-84b0-ad74a62ea65d.png)
![image](https://user-images.githubusercontent.com/42006262/190179752-c60f8e2f-311d-4428-b812-3b65ef72ca24.png)
![image](https://user-images.githubusercontent.com/42006262/190179811-9dd6ecb2-29e9-4527-afb4-d753dbe0ac80.png)

they are not on /is counts aswell
![image](https://user-images.githubusercontent.com/42006262/190179867-59dfe036-2661-483f-9b5c-6aac99432c0e.png)

### To Reproduce

I loaded AdvancedSpawners and when I try to do /is recalc or /is admin recalc * nothing change or happened the worth don't owrk for me

**Comment by OmerBenGera** [comment]
If you run /is value while holding a spawner, does it show the correct worth value?

**Comment by Jok3rTV** [comment]
[15:43:17 INFO]: _feliz_ issued server command: /is value
[15:43:17 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'is value' in com.bgsoftware.superiorskyblock.commands.CommandsManagerImpl$PluginCommand(island)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:911) ~[paper-1.19.2.jar:git-Paper-142]
        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.2.jar:git-Paper-142]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:305) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:289) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2293) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2247) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1361) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1338) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1331) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1309) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1197) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-142]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: gc/spawners/utils/APILayer
        at gcspawners.ASAPI.getSpawnerType(ASAPI.java:97) ~[AdvancedSpawners-3.8.0.jar:?]
        at com.bgsoftware.superiorskyblock.external.spawners.SpawnersProvider_AdvancedSpawners.getSpawnerType(SpawnersProvider_AdvancedSpawners.java:46) ~[SuperiorSkyblock2-1.11.1-b795.jar:?]
        at com.bgsoftware.superiorskyblock.external.ProvidersManagerImpl.getSpawnerKey(ProvidersManagerImpl.java:269) ~[SuperiorSkyblock2-1.11.1-b795.jar:?]
        at com.bgsoftware.superiorskyblock.core.key.KeyImpl.of(KeyImpl.java:62) ~[SuperiorSkyblock2-1.11.1-b795.jar:?]
        at com.bgsoftware.superiorskyblock.commands.player.CmdValue.execute(CmdValue.java:71) ~[SuperiorSkyblock2-1.11.1-b795.jar:?]
        at com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.execute(ISuperiorCommand.java:18) ~[SuperiorSkyblock2-1.11.1-b795.jar:?]
        at com.bgsoftware.superiorskyblock.commands.CommandsManagerImpl$PluginCommand.execute(CommandsManagerImpl.java:281) ~[SuperiorSkyblock2-1.11.1-b795.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 22 more
Caused by: java.lang.ClassNotFoundException: gc.spawners.utils.APILayer
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at gcspawners.ASAPI.getSpawnerType(ASAPI.java:97) ~[AdvancedSpawners-3.8.0.jar:?]
        at com.bgsoftware.superiorskyblock.external.spawners.SpawnersProvider_AdvancedSpawners.getSpawnerType(SpawnersProvider_AdvancedSpawners.java:46) ~[SuperiorSkyblock2-1.11.1-b795.jar:?]
        at com.bgsoftware.superiorskyblock.external.ProvidersManagerImpl.getSpawnerKey(ProvidersManagerImpl.java:269) ~[SuperiorSkyblock2-1.11.1-b795.jar:?]
        at com.bgsoftware.superiorskyblock.core.key.KeyImpl.of(KeyImpl.java:62) ~[SuperiorSkyblock2-1.11.1-b795.jar:?]
        at com.bgsoftware.superiorskyblock.commands.player.CmdValue.execute(CmdValue.java:71) ~[SuperiorSkyblock2-1.11.1-b795.jar:?]
        at com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.execute(ISuperiorCommand.java:18) ~[SuperiorSkyblock2-1.11.1-b795.jar:?]
        at com.bgsoftware.superiorskyblock.commands.CommandsManagerImpl$PluginCommand.execute(CommandsManagerImpl.java:281) ~[SuperiorSkyblock2-1.11.1-b795.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 22 more

**Comment by OmerBenGera** [comment]
The issue turned to be on AdvancedSpawner's side.
For now, downgrade AdvancedSpawners so it will work.

**Comment by GC-spigot** [comment]
We've confirmed it's AdvancedSpawners issue. Currently our team is in the middle of it's recode - you will have to wait for that (~2-4 weeks), downgrading may help.

**Comment by OmerBenGera** [comment]
I think I'll close this for the time being.
If you need anything else, let me know by opening a new issue
