### ISSUE TITLE
Could not pass event IslandSchematicPasteEvent to SuperiorSkyblock2

### ISSUE THREAD

**Issue by saffue** [BG-Software-LLC/SuperiorSkyblock2#1381]
### Minecraft's Version

1.19.2

### Plugin's Version

826

### Describe the bug

spams console with this error a few times, it still creates the island 
`[21:42:33 ERROR]: Could not pass event IslandSchematicPasteEvent to SuperiorSkyblock2 v2022.8
java.lang.AssertionError: Failed generating bytecode for <eval>:1
        at org.openjdk.nashorn.internal.codegen.CompilationPhase$BytecodeGenerationPhase.transform(CompilationPhase.java:437) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.CompilationPhase.apply(CompilationPhase.java:614) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.Compiler.compile(Compiler.java:641) ~[?:?]
        at org.openjdk.nashorn.internal.runtime.Context.compile(Context.java:1531) ~[?:?]
        at org.openjdk.nashorn.internal.runtime.Context.compileScript(Context.java:1451) ~[?:?]
        at org.openjdk.nashorn.internal.runtime.Context.compileScript(Context.java:761) ~[?:?]
        at org.openjdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:528) ~[?:?]
        at org.openjdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:517) ~[?:?]
        at org.openjdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:395) ~[?:?]
        at org.openjdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:151) ~[?:?]
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:231) ~[java.scripting:?]
        at com.bgsoftware.superiorskyblock.scripts.NashornScript.eval(NashornScript.java:41) ~[?:?]
        at com.bgsoftware.superiorskyblock.missions.IslandMissions.tryComplete(IslandMissions.java:210) ~[?:?]
        at com.bgsoftware.superiorskyblock.missions.IslandMissions.tryComplete(IslandMissions.java:196) ~[?:?]
        at com.bgsoftware.superiorskyblock.missions.IslandMissions.onIslandWorthUpdate(IslandMissions.java:192) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor445.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-177]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at com.bgsoftware.superiorskyblock.core.events.EventsBus.callEvent(EventsBus.java:670) ~[SuperiorSkyblock2-2022.8.jar:?]
        at com.bgsoftware.superiorskyblock.core.events.EventsBus.callIslandSchematicPasteEvent(EventsBus.java:485) ~[SuperiorSkyblock2-2022.8.jar:?]
        at com.bgsoftware.superiorskyblock.world.schematic.impl.SuperiorSchematic.lambda$pasteSchematic$1(SuperiorSchematic.java:125) ~[SuperiorSkyblock2-2022.8.jar:?]
        at com.bgsoftware.superiorskyblock.world.BlockChangeTask.lambda$submitUpdate$5(BlockChangeTask.java:96) ~[SuperiorSkyblock2-2022.8.jar:?]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
        at com.bgsoftware.superiorskyblock.world.chunk.ChunksProvider$ChunkLoadWorker.finishLoad(ChunksProvider.java:113) ~[SuperiorSkyblock2-2022.8.jar:?]
        at com.bgsoftware.superiorskyblock.world.chunk.ChunksProvider$ChunkLoadWorker.lambda$work$0(ChunksProvider.java:95) ~[SuperiorSkyblock2-2022.8.jar:?]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftWorld.lambda$getChunkAtAsync$15(CraftWorld.java:2359) ~[paper-1.19.2.jar:git-Paper-177]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-177]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-177]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-177]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-177]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-177]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1389) ~[paper-1.19.2.jar:git-Paper-177]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-177]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-177]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalAccessError: failed to access class org.openjdk.nashorn.internal.codegen.CodeGenerator$3$4 from class org.openjdk.nashorn.internal.codegen.CodeGenerator$3 (org.openjdk.nashorn.internal.codegen.CodeGenerator$3$4 is in unnamed module of loader 'PlaceholderAPI-2.11.2.jar' @3a0a2f81; org.openjdk.nashorn.internal.codegen.CodeGenerator$3 is in unnamed module of loader com.bgsoftware.superiorskyblock.module.ModuleClassLoader @70d635cd)
        at org.openjdk.nashorn.internal.codegen.CodeGenerator$3.enterAccessNode(CodeGenerator.java:1590) ~[?:?]
        at org.openjdk.nashorn.internal.ir.AccessNode.accept(AccessNode.java:67) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.CodeGenerator.loadCallNode(CodeGenerator.java:1435) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.CodeGenerator$2.enterCallNode(CodeGenerator.java:1002) ~[?:?]
        at org.openjdk.nashorn.internal.ir.CallNode.accept(CallNode.java:177) ~[?:?]
        at org.openjdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57) ~[?:?]
        at org.openjdk.nashorn.internal.ir.LexicalContextExpression.accept(LexicalContextExpression.java:47) ~[?:?]
        at org.openjdk.nashorn.internal.ir.CallNode.accept(CallNode.java:41) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.CodeGenerator.loadExpression(CodeGenerator.java:857) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.CodeGenerator.loadExpression(CodeGenerator.java:833) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.CodeGenerator.loadExpressionAsType(CodeGenerator.java:828) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.CodeGenerator$15.evaluate(CodeGenerator.java:3934) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.CodeGenerator$Store.store(CodeGenerator.java:4581) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.CodeGenerator.loadASSIGN(CodeGenerator.java:3936) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.CodeGenerator$2.enterASSIGN(CodeGenerator.java:919) ~[?:?]
        at org.openjdk.nashorn.internal.ir.visitor.NodeOperatorVisitor.enterBinaryNode(NodeOperatorVisitor.java:113) ~[?:?]
        at org.openjdk.nashorn.internal.ir.BinaryNode.accept(BinaryNode.java:329) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.CodeGenerator.loadExpression(CodeGenerator.java:857) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.CodeGenerator.loadExpression(CodeGenerator.java:833) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.CodeGenerator.loadAndDiscard(CodeGenerator.java:3680) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.CodeGenerator.enterExpressionStatement(CodeGenerator.java:1716) ~[?:?]
        at org.openjdk.nashorn.internal.ir.ExpressionStatement.accept(ExpressionStatement.java:81) ~[?:?]
        at org.openjdk.nashorn.internal.ir.Node.accept(Node.java:286) ~[?:?]
        at org.openjdk.nashorn.internal.ir.Block.accept(Block.java:236) ~[?:?]
        at org.openjdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57) ~[?:?]
        at org.openjdk.nashorn.internal.ir.Block.accept(Block.java:507) ~[?:?]
        at org.openjdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:405) ~[?:?]
        at org.openjdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57) ~[?:?]
        at org.openjdk.nashorn.internal.ir.LexicalContextExpression.accept(LexicalContextExpression.java:47) ~[?:?]
        at org.openjdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:57) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.CompilationPhase.transformFunction(CompilationPhase.java:618) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.CompilationPhase$BytecodeGenerationPhase.transform(CompilationPhase.java:424) ~[?:?]
        ... 47 more`

### To Reproduce

create an island

**Comment by OmerBenGera** [comment]
Your nashorn engine is corrupted.
Install the nashorn module and if it continues install Purpur.
Also, update to latest dev build if you havent.

**Comment by saffue** [comment]
i actually straight up didnt have the nashorn module installed, it didnt error in console or anything and i dont see anywhere telling me to install it so might wanna write that somewhere pretty visible

**Comment by OmerBenGera** [comment]
> i actually straight up didnt have the nashorn module installed, it didnt error in console or anything and i dont see anywhere telling me to install it so might wanna write that somewhere pretty visible

This is because SSB automatically installs a library using Spigot's API and uses it instead of the module in latest versions (it does the same thing as the module)
