### ISSUE TITLE
Crops growth rate not working

### ISSUE THREAD

**Issue by ArefyNetwork** [BG-Software-LLC/SuperiorSkyblock2#1407]
### Minecraft's Version

1.8.8

### Plugin's Version

858 dev build

### Describe the bug

Crop growth isn't working, even with the default config, you can see discord group, there are more owners with same issue. Thanks!

### To Reproduce

-

**Comment by OmerBenGera** [comment]
I used `/is admin setcropgrowth <player-name> 3000` on my island and it worked fine for me.
Is your crop-growth multiplier correct in `/is admin show`?

**Comment by Verwarmingman** [comment]
Hi,

I encountered the same issue! Default config, upgrades and is admin commands do seem to change the value in /is admin show, however, there is no effect on the real crop growth speed ingame!

![image](https://user-images.githubusercontent.com/65850212/195792930-6af568bd-1177-4573-839b-462929a0572e.png)

**Comment by OmerBenGera** [comment]
> Hi,
> 
> I encountered the same issue! Default config, upgrades and is admin commands do seem to change the value in /is admin show, however, there is no effect on the real crop growth speed ingame! See image: i have upgraded to tier 4 (in my config this sets the crop growth to 4)
> 
> ![image](https://user-images.githubusercontent.com/65850212/195792930-6af568bd-1177-4573-839b-462929a0572e.png)

Set the crop growth to a really large number, such as 3000.
Let me know if it works.

**Comment by Verwarmingman** [comment]
![image](https://user-images.githubusercontent.com/65850212/195799604-01a5bb29-0e6e-4428-9baf-86d8ef3c58a8.png)
Command: /is admin setcropgrowth island 3000 --> image = result

**Comment by OmerBenGera** [comment]
> ![image](https://user-images.githubusercontent.com/65850212/195799604-01a5bb29-0e6e-4428-9baf-86d8ef3c58a8.png) Command: /is admin setcropgrowth island 3000 --> image = result

Does it still not work?
What spigot jar you use? (output of /version)

**Comment by Verwarmingman** [comment]
This still does not work! See version info down below: 
![image](https://user-images.githubusercontent.com/65850212/195979092-225a6faf-834e-4349-bc4a-a79dbba7ec9b.png)

**Comment by OmerBenGera** [comment]
Also, make sure there's light to the crops so they can grow.

**Comment by Verwarmingman** [comment]
Version: 1.17.1 --> only skyblock installed
Skyblock: b858
randomtickspeed: 3
lights: available
![2022-10-18_18 41 53](https://user-images.githubusercontent.com/65850212/196491978-1ce9c3dd-bc67-49db-82a8-55e29c0d952f.png)
![2022-10-18_18 41 59](https://user-images.githubusercontent.com/65850212/196492119-fdb9ce8e-e48e-495e-8c67-c2510628acaa.png)

is admin setcropgrowth 3000
![2022-10-18_18 42 52](https://user-images.githubusercontent.com/65850212/196492160-f78c0c9e-3e2e-40cd-a629-d54b52a9a758.png)

--> result is the same

**Comment by OmerBenGera** [comment]
@Verwarmingman I managed to replicate and fix the issue in 1.17, check out latest dev build.

@ArefyNetwork I can't seem to replicate the issue in 1.8.8. Do you have any more details regarding the issue?

**Comment by Verwarmingman** [comment]
`[SuperiorSkyblock2] Enabling SuperiorSkyblock2 v2022.8.1-b881
[09:25:44 WARN]: org.bukkit.configuration.InvalidConfigurationException: while scanning a simple key
[09:25:44 WARN]:  in 'string', line 141, column 5:
[09:25:44 WARN]:         '4:
[09:25:44 WARN]:         ^
[09:25:44 WARN]: could not find expected ':'
[09:25:44 WARN]:  in 'string', line 149, column 6:
[09:25:44 WARN]:         '5:
[09:25:44 WARN]:          ^
[09:25:44 WARN]: 
[09:25:44 WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59)
[09:25:44 WARN]: 	at SuperiorSkyblock2-2022.8.1-b881.jar//com.bgsoftware.common.config.CommentedConfiguration.loadFromString(CommentedConfiguration.java:137)
[09:25:44 WARN]: 	at SuperiorSkyblock2-2022.8.1-b881.jar//com.bgsoftware.common.config.CommentedConfiguration.loadConfiguration(CommentedConfiguration.java:325)
[09:25:44 WARN]: 	at SuperiorSkyblock2-2022.8.1-b881.jar//com.bgsoftware.common.config.CommentedConfiguration.loadConfiguration(CommentedConfiguration.java:291)
[09:25:44 WARN]: 	at SuperiorSkyblock2-2022.8.1-b881.jar//com.bgsoftware.superiorskyblock.module.BuiltinModule.onPluginInit(BuiltinModule.java:63)
[09:25:44 WARN]: 	at SuperiorSkyblock2-2022.8.1-b881.jar//com.bgsoftware.superiorskyblock.module.upgrades.UpgradesModule.onPluginInit(UpgradesModule.java:63)
[09:25:44 WARN]: 	at SuperiorSkyblock2-2022.8.1-b881.jar//com.bgsoftware.superiorskyblock.module.BuiltinModule.onPluginInit(BuiltinModule.java:58)
[09:25:44 WARN]: 	at SuperiorSkyblock2-2022.8.1-b881.jar//com.bgsoftware.superiorskyblock.api.modules.PluginModule.initModule(PluginModule.java:271)
[09:25:44 WARN]: 	at SuperiorSkyblock2-2022.8.1-b881.jar//com.bgsoftware.superiorskyblock.module.container.DefaultModulesContainer.registerModule(DefaultModulesContainer.java:40)
[09:25:44 WARN]: 	at SuperiorSkyblock2-2022.8.1-b881.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.registerModule(ModulesManagerImpl.java:53)
[09:25:44 WARN]: 	at SuperiorSkyblock2-2022.8.1-b881.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.loadData(ModulesManagerImpl.java:46)
[09:25:44 WARN]: 	at SuperiorSkyblock2-2022.8.1-b881.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:234)
[09:25:44 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[09:25:44 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[09:25:44 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[09:25:44 WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[09:25:44 WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[09:25:44 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733)
[09:25:44 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[09:25:44 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
[09:25:44 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[09:25:44 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[09:25:44 WARN]: Caused by: while scanning a simple key
[09:25:44 WARN]:  in 'string', line 141, column 5:
[09:25:44 WARN]:         '4:
[09:25:44 WARN]:         ^
[09:25:44 WARN]: could not find expected ':'
[09:25:44 WARN]:  in 'string', line 149, column 6:
[09:25:44 WARN]:         '5:
[09:25:44 WARN]:          ^
[09:25:44 WARN]: 
[09:25:44 WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:484)
[09:25:44 WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:299)
[09:25:44 WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:247)
[09:25:44 WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl$ParseIndentlessSequenceEntry.produce(ParserImpl.java:571)
[09:25:44 WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165)`

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by LuluxClient** [comment]
Same issue on 1.19.2

**Comment by OmerBenGera** [comment]
I am closing this as the OP couldn't respond in time.
@LuluxClient , if it occurs for you as well, please open another issue and give more information.
