### ISSUE TITLE
Island level calculation gets stuck

### ISSUE THREAD

**Issue by RealTitanGod** [BG-Software-LLC/SuperiorSkyblock2#1408]
### Minecraft's Version

1.19.2
pufferfish

### Plugin's Version

v2022.8.1-b858

### Describe the bug

The plugin never finishes calculation of some players level during /is values or /is recalc which causes them to then be unable to build. This seems to occur with islands that had a misconfigured border size. During setup the maxIslandSize was made 200 and the biggest upgrade was 250. This has been since been corrected by reducing the upgrade to 200. And /is syncupgrades * was run. The islands show the proper border now but the /is recalc fails.

### To Reproduce

1. Change highest island upgrade border size to a number high then islandMaxSize. 
2. Sync the upgrades for your island
3. Change highest island upgrade border size back. 
4. Run /is recalc or /is values

### Additional Information

`[05:11:52] [Server thread/WARN]: [SuperiorSkyblock2] Task #4283 for SuperiorSkyblock2 v2022.8.1-b858 generated an exception
java.lang.IllegalArgumentException: Chunk must be within the island boundaries.
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
    at com.bgsoftware.superiorskyblock.island.SIsland.isChunkDirty(SIsland.java:1964) ~[SuperiorSkyblock2-2022.8.1-b858.jar:?]
    at com.bgsoftware.superiorskyblock.island.IslandUtils.getChunkCoords(IslandUtils.java:70) ~[SuperiorSkyblock2-2022.8.1-b858.jar:?]
    at com.bgsoftware.superiorskyblock.island.SIsland.getLoadedChunks(SIsland.java:949) ~[SuperiorSkyblock2-2022.8.1-b858.jar:?]
    at com.bgsoftware.superiorskyblock.island.SIsland.getLoadedChunks(SIsland.java:936) ~[SuperiorSkyblock2-2022.8.1-b858.jar:?]
    at com.bgsoftware.superiorskyblock.island.algorithm.DefaultIslandEntitiesTrackerAlgorithm.recalculateEntityCounts(DefaultIslandEntitiesTrackerAlgorithm.java:130) ~[SuperiorSkyblock2-2022.8.1-b858.jar:?]
    at com.bgsoftware.superiorskyblock.world.event.WorldEventsManagerImpl.lambda$loadChunk$1(WorldEventsManagerImpl.java:78) ~[SuperiorSkyblock2-2022.8.1-b858.jar:?]
    at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.19.2.jar:git-Pufferfish-38]
    at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[pufferfish-1.19.2.jar:git-Pufferfish-38]
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1501) ~[pufferfish-1.19.2.jar:git-Pufferfish-38]
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:452) ~[pufferfish-1.19.2.jar:git-Pufferfish-38]
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1425) ~[pufferfish-1.19.2.jar:git-Pufferfish-38]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[pufferfish-1.19.2.jar:git-Pufferfish-38]
    at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[pufferfish-1.19.2.jar:git-Pufferfish-38]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by OmerBenGera** [comment]
Are you sure `/is admin show` shows the correct border size for these islands?
Take a picture of the island information from the command and send it here.

**Comment by RealTitanGod** [comment]
https://screenrec.com/share/GdpLRlNA2g

**Comment by RealTitanGod** [comment]
An additional issue I just noticed is that after /is syncupgrades changes the border from 250 to 200. If you stop the server, then start it again the border jumps back to 250.

**Comment by OmerBenGera** [comment]
> An additional issue I just noticed is that after /is syncupgrades changes the border from 250 to 200. If you stop the server, then start it again the border jumps back to 250.

Are you sure you changed the upgrade border-size to 200?
Also, if you open the db and check for the border size of the island, what do you see in there?

**Comment by RealTitanGod** [comment]
The upgrade config was at 200, the database shows 250 after running /is admin syncupgrades even though the border visibly moved closer and is admin info shows 200. After running /is admin syncupgrades for a second time the database finally updated the value. After a reboot the upgrade stayed at 200 and /is recalc is working. I guess this is resolved.

**Comment by OmerBenGera** [comment]
Great.
I will make sure that the plugin forces the upgrades to not have size larger than the max island size.
