### ISSUE TITLE
Could not pass event PlayerInteractEvent Error

### ISSUE THREAD

**Issue by L1etty** [BG-Software-LLC/SuperiorSkyblock2#1419]
### Minecraft's Version

This server is running Paper version git-Paper-166 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: f528f53)
You are 52 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-388 (MC: 1.18.2)

### Plugin's Version

2022.8.1-b876

### Describe the bug

[20:40:00 ERROR]: Could not pass event PlayerInteractEvent to SuperiorSkyblock2 v2022.8.1-b876
java.lang.IllegalArgumentException: World must be an islands world.
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
        at com.bgsoftware.superiorskyblock.api.world.WorldInfo.of(WorldInfo.java:26) ~[SuperiorSkyblock2-2022.8.1-b876.jar:?]
        at com.bgsoftware.superiorskyblock.core.ChunkPosition.of(ChunkPosition.java:31) ~[SuperiorSkyblock2-2022.8.1-b876.jar:?]
        at com.bgsoftware.superiorskyblock.core.stackedblocks.container.DefaultStackedBlocksContainer.getStackedBlock(DefaultStackedBlocksContainer.java:20)
~[SuperiorSkyblock2-2022.8.1-b876.jar:?]
        at com.bgsoftware.superiorskyblock.core.stackedblocks.StackedBlocksManagerImpl.getStackedBlockAmount(StackedBlocksManagerImpl.java:78) ~[SuperiorSkyb
lock2-2022.8.1-b876.jar:?]
        at com.bgsoftware.superiorskyblock.core.stackedblocks.StackedBlocksManagerImpl.getStackedBlockAmount(StackedBlocksManagerImpl.java:70) ~[SuperiorSkyb
lock2-2022.8.1-b876.jar:?]
        at com.bgsoftware.superiorskyblock.listener.ProtectionListener.onBlockInteract(ProtectionListener.java:145) ~[SuperiorSkyblock2-2022.8.1-b876.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor242.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-166]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[paper-1.19.2.jar:git-Paper-166]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:525) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1968) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-166]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1361) ~[paper-1.19.2.jar:git-Paper-166]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-166]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1338) ~[paper-1.19.2.jar:git-Paper-166]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1331) ~[paper-1.19.2.jar:git-Paper-166]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1409) ~[paper-1.19.2.jar:git-Paper-166]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1193) ~[paper-1.19.2.jar:git-Paper-166]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-166]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### To Reproduce

I don't know.

Once the server was started and the error occurred once, the error did not come back.

**Comment by L1etty** [comment]
An error occurs when interacting in a world other than Superior SkyBlock2 World. (Block Break, Food eat
