### ISSUE TITLE
Mission Save Error

### ISSUE THREAD

**Issue by Pledix** [BG-Software-LLC/SuperiorSkyblock2#1450]
### Minecraft's Version

git-Pufferfish-22 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

### Plugin's Version

2022.9

### Describe the bug

`[00:51:18] [Craft Scheduler Thread - 122294 - SuperiorSkyblock2/ERROR]: [SuperiorSkyblock2] An unexpected error while saving mission data for farmer_5:
[00:51:18] [Craft Scheduler Thread - 122294 - SuperiorSkyblock2/WARN]: java.util.ConcurrentModificationException
[00:51:18] [Craft Scheduler Thread - 122294 - SuperiorSkyblock2/WARN]: 	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
[00:51:18] [Craft Scheduler Thread - 122294 - SuperiorSkyblock2/WARN]: 	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1630)
[00:51:18] [Craft Scheduler Thread - 122294 - SuperiorSkyblock2/WARN]: 	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1628)
[00:51:18] [Craft Scheduler Thread - 122294 - SuperiorSkyblock2/WARN]: 	at com.bgsoftware.superiorskyblock.missions.FarmingMissions.saveProgress(FarmingMissions.java:147)
[00:51:18] [Craft Scheduler Thread - 122294 - SuperiorSkyblock2/WARN]: 	at SuperiorSkyblock2-2022.9.jar//com.bgsoftware.superiorskyblock.mission.MissionsManagerImpl.saveMissionsData(MissionsManagerImpl.java:340)
[00:51:18] [Craft Scheduler Thread - 122294 - SuperiorSkyblock2/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[00:51:18] [Craft Scheduler Thread - 122294 - SuperiorSkyblock2/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[00:51:18] [Craft Scheduler Thread - 122294 - SuperiorSkyblock2/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[00:51:18] [Craft Scheduler Thread - 122294 - SuperiorSkyblock2/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[00:51:18] [Craft Scheduler Thread - 122294 - SuperiorSkyblock2/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[00:51:18] [Craft Scheduler Thread - 122294 - SuperiorSkyblock2/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)`

### To Reproduce

An unexpected error while saving mission data for farmer_5

**Comment by Pledix** [comment]
I switch this version: 2022.9-b900
`[13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/ERROR]: [SuperiorSkyblock2] An unexpected error while saving mission data for farmer_3:
[13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/WARN]: java.util.ConcurrentModificationException
[13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/WARN]: 	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
[13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/WARN]: 	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1630)
[13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/WARN]: 	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1628)
[13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/WARN]: 	at com.bgsoftware.superiorskyblock.missions.FarmingMissions.saveProgress(FarmingMissions.java:147)
[13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/WARN]: 	at SuperiorSkyblock2-2022.9-b900.jar//com.bgsoftware.superiorskyblock.mission.MissionsManagerImpl.saveMissionsData(MissionsManagerImpl.java:340)
[13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)`
I think the problem still persists

**Comment by OmerBenGera** [comment]
> I switch this version: 2022.9-b900 `[13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/ERROR]: [SuperiorSkyblock2] An unexpected error while saving mission data for farmer_3: [13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/WARN]: java.util.ConcurrentModificationException [13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/WARN]: at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) [13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/WARN]: at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1630) [13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/WARN]: at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1628) [13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/WARN]: at com.bgsoftware.superiorskyblock.missions.FarmingMissions.saveProgress(FarmingMissions.java:147) [13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/WARN]: at SuperiorSkyblock2-2022.9-b900.jar//com.bgsoftware.superiorskyblock.mission.MissionsManagerImpl.saveMissionsData(MissionsManagerImpl.java:340) [13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/WARN]: at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) [13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/WARN]: at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [13:07:50] [Craft Scheduler Thread - 1346 - SuperiorSkyblock2/WARN]: at java.base/java.lang.Thread.run(Thread.java:833)` I think the problem still persists

No need to send the same error.
The issue was not marked as solved, so of course its not solved.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works.

**Comment by OmerBenGera** [comment]
Closing this for now
If the issue still occurs let me know
