### ISSUE TITLE
Plugin can not load on latest dev build of SkinsRestorer

### ISSUE THREAD

**Issue by nhanledev** [BG-Software-LLC/SuperiorSkyblock2#1488]
### Minecraft's Version

Paper 1.19.2

### Plugin's Version

Dev build 915

### Describe the bug

SkinsRestorer API changed, cause this bug on load

```
[11:30:47 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while registering hook SkinsRestorerHook:
[11:30:47 WARN]: java.lang.reflect.InvocationTargetException
[11:30:47 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:30:47 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[11:30:47 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:30:47 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[11:30:47 WARN]:        at SuperiorSkyblock2-2022.9-b915.jar//com.bgsoftware.superiorskyblock.external.ProvidersManagerImpl.registerHook(ProvidersManagerImpl.java:567)
[11:30:47 WARN]:        at SuperiorSkyblock2-2022.9-b915.jar//com.bgsoftware.superiorskyblock.external.ProvidersManagerImpl.registerGeneralHooks(ProvidersManagerImpl.java:370)
[11:30:47 WARN]:        at SuperiorSkyblock2-2022.9-b915.jar//com.bgsoftware.superiorskyblock.external.ProvidersManagerImpl.lambda$loadData$1(ProvidersManagerImpl.java:92)
[11:30:47 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[11:30:47 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[11:30:47 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1114)
[11:30:47 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[11:30:47 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[11:30:47 WARN]: Caused by: java.lang.NoClassDefFoundError: skinsrestorer/shared/exception/SkinRequestException
[11:30:47 WARN]:        at SuperiorSkyblock2-2022.9-b915.jar//com.bgsoftware.superiorskyblock.external.SkinsRestorerHook.register(SkinsRestorerHook.java:38)
[11:30:47 WARN]:        ... 12 more
[11:30:47 WARN]: Caused by: java.lang.ClassNotFoundException: skinsrestorer.shared.exception.SkinRequestException
[11:30:47 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:177)
[11:30:47 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124)
[11:30:47 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[11:30:47 WARN]:        ... 13 more
```

### To Reproduce

Run server with SkinsRestorer dev build #519
https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorerX-DEV/519/artifact/build/libs/SkinsRestorer.jar

**Comment by nhanledev** [comment]
I report this because of the deep integration of SS2 with SkinsRestorer. This is not critical because of the nature of development build, but it is worth to look at it.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if there are any more issues with the new version of SkinsRestorer :)

**Comment by nhanledev** [comment]
Hello,
I have only tested server booting, without both stable and dev build version of SkinsRestorer. The fix looks good to me.
Thank you so much
