### ISSUE TITLE
Missing missions from menu

### ISSUE THREAD

**Issue by kamo125** [BG-Software-LLC/SuperiorSkyblock2#1502]
### Minecraft's Version

Current: git-Purpur-1858 (MC: 1.19.2)*
Previous: git-Purpur-1857 (MC: 1.19.2)
* You are running the latest version

### Plugin's Version

2022.9-b925

### Describe the bug

I have a problem with slayer missions. I have 9 missions fot this category and when my players complete the third of them, the rest of the menu disappears. I don't have any clue as to what makes this happen, bud this is how it looks normal compared to bugged:

![image](https://user-images.githubusercontent.com/118190496/206863673-36e8f8d0-7a43-4fb7-908d-39cd274a1912.png)

![obrázek_2022-12-10_165038829](https://user-images.githubusercontent.com/118190496/206863575-8ae19be3-dc48-4770-b095-7b5c651099fc.png)

### To Reproduce

Finish third slayer mission.

**Comment by petulikan1** [comment]
Here is an error of what seems to be the problem

[05:11:10 INFO]: petulikan1 issued server command: /is missions
[05:11:11 INFO]: [SuperiorSkyblock2] PagedMenuLayoutImpl::populateInventory ENTER {23}
[05:11:11 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while setting up menu:
[05:11:11 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.hasDisplayName()" because "itemMeta" is null
[05:11:11 WARN]:        at com.bgsoftware.superiorskyblock.missions.KillsMissions.formatItem(KillsMissions.java:145)
[05:11:11 WARN]:        at SuperiorSkyblock2-2022.9-b925.jar//com.bgsoftware.superiorskyblock.core.menu.button.impl.MissionsPagedObjectButton.modifyViewItem(MissionsPagedObjectButton.java:91)
[05:11:11 WARN]:        at SuperiorSkyblock2-2022.9-b925.jar//com.bgsoftware.superiorskyblock.core.menu.button.AbstractPagedMenuButton.createViewItem(AbstractPagedMenuButton.java:29)
[05:11:11 WARN]:        at SuperiorSkyblock2-2022.9-b925.jar//com.bgsoftware.superiorskyblock.core.menu.layout.PagedMenuLayoutImpl.populateInventory(PagedMenuLayoutImpl.java:69)
[05:11:11 WARN]:        at SuperiorSkyblock2-2022.9-b925.jar//com.bgsoftware.superiorskyblock.core.menu.layout.AbstractMenuLayout.buildInventory(AbstractMenuLayout.java:73)
[05:11:11 WARN]:        at SuperiorSkyblock2-2022.9-b925.jar//com.bgsoftware.superiorskyblock.core.menu.AbstractMenu.lambda$buildInventory$2(AbstractMenu.java:78)
[05:11:11 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[05:11:11 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[05:11:11 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[05:11:11 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[05:11:11 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[05:11:11 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by OmerBenGera** [comment]
Mind sharing with me the way you configured the items to display for these missions?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue still occurs let me know
