### ISSUE TITLE
getCropGrowth error

### ISSUE THREAD

**Issue by FrancyMak** [BG-Software-LLC/SuperiorSkyblock2#1509]
### Minecraft's Version

Paper 1.19.2

### Plugin's Version

SuperiorSkyblock2-930 dev

### Describe the bug

[16:11:04] [Server thread/ERROR]: [SuperiorSkyblock2] An unexpected error occurred while creating an island:
[16:11:04] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "com.bgsoftware.superiorskyblock.island.upgrade.SUpgradeLevel.getCropGrowth()" because "upgradeLevel" is null
[16:11:04] [Server thread/WARN]: 	at SuperiorSkyblock2-2022.9-b930.jar//com.bgsoftware.superiorskyblock.island.SIsland.lambda$syncUpgrade$156(SIsland.java:3953)
[16:11:04] [Server thread/WARN]: 	at SuperiorSkyblock2-2022.9-b930.jar//com.bgsoftware.superiorskyblock.core.threads.Synchronized.set(Synchronized.java:49)
[16:11:04] [Server thread/WARN]: 	at SuperiorSkyblock2-2022.9-b930.jar//com.bgsoftware.superiorskyblock.island.SIsland.syncUpgrade(SIsland.java:3952)
[16:11:04] [Server thread/WARN]: 	at SuperiorSkyblock2-2022.9-b930.jar//com.bgsoftware.superiorskyblock.island.SIsland.lambda$updateUpgrades$70(SIsland.java:2215)
[16:11:04] [Server thread/WARN]: 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[16:11:04] [Server thread/WARN]: 	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
[16:11:04] [Server thread/WARN]: 	at SuperiorSkyblock2-2022.9-b930.jar//com.bgsoftware.superiorskyblock.island.SIsland.updateUpgrades(SIsland.java:2215)
[16:11:04] [Server thread/WARN]: 	at SuperiorSkyblock2-2022.9-b930.jar//com.bgsoftware.superiorskyblock.island.SIsland.<init>(SIsland.java:323)
[16:11:04] [Server thread/WARN]: 	at SuperiorSkyblock2-2022.9-b930.jar//com.bgsoftware.superiorskyblock.core.factory.FactoriesManagerImpl.createIsland(FactoriesManagerImpl.java:124)
[16:11:04] [Server thread/WARN]: 	at SuperiorSkyblock2-2022.9-b930.jar//com.bgsoftware.superiorskyblock.island.builder.IslandBuilderImpl.build(IslandBuilderImpl.java:753)
[16:11:04] [Server thread/WARN]: 	at SuperiorSkyblock2-2022.9-b930.jar//com.bgsoftware.superiorskyblock.island.algorithm.DefaultIslandCreationAlgorithm.createIsland(DefaultIslandCreationAlgorithm.java:79)
[16:11:04] [Server thread/WARN]: 	at SuperiorSkyblock2-2022.9-b930.jar//com.bgsoftware.superiorskyblock.island.GridManagerImpl.createIslandInternalAsync(GridManagerImpl.java:215)
[16:11:04] [Server thread/WARN]: 	at SuperiorSkyblock2-2022.9-b930.jar//com.bgsoftware.superiorskyblock.island.GridManagerImpl.createIsland(GridManagerImpl.java:187)
[16:11:04] [Server thread/WARN]: 	at SuperiorSkyblock2-2022.9-b930.jar//com.bgsoftware.superiorskyblock.island.GridManagerImpl.createIsland(GridManagerImpl.java:166)
[16:11:04] [Server thread/WARN]: 	at SuperiorSkyblock2-2022.9-b930.jar//com.bgsoftware.superiorskyblock.core.menu.button.impl.IslandCreationButton.clickButton(IslandCreationButton.java:89)
[16:11:04] [Server thread/WARN]: 	at SuperiorSkyblock2-2022.9-b930.jar//com.bgsoftware.superiorskyblock.core.menu.button.impl.IslandCreationButton.onButtonClick(IslandCreationButton.java:49)
[16:11:04] [Server thread/WARN]: 	at SuperiorSkyblock2-2022.9-b930.jar//com.bgsoftware.superiorskyblock.api.menu.BaseMenu.onClick(BaseMenu.java:146)
[16:11:04] [Server thread/WARN]: 	at SuperiorSkyblock2-2022.9-b930.jar//com.bgsoftware.superiorskyblock.core.menu.AbstractMenu.onClick(AbstractMenu.java:48)
[16:11:04] [Server thread/WARN]: 	at SuperiorSkyblock2-2022.9-b930.jar//com.bgsoftware.superiorskyblock.core.menu.AbstractMenu.onClick(AbstractMenu.java:21)
[16:11:04] [Server thread/WARN]: 	at SuperiorSkyblock2-2022.9-b930.jar//com.bgsoftware.superiorskyblock.listener.MenusListener.onMenuClick(MenusListener.java:64)
[16:11:04] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[16:11:04] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[16:11:04] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:11:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
[16:11:04] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3307)
[16:11:04] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
[16:11:04] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:23)
[16:11:04] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[16:11:04] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[16:11:04] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[16:11:04] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[16:11:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[16:11:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[16:11:04] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[16:11:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[16:11:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[16:11:04] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.bq(IAsyncTaskHandler.java:114)
[16:11:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1445)
[16:11:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1173)
[16:11:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[16:11:04] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

### To Reproduce

It has been appearing to me for a few days when I start the server and/or try to create an island. Also, if I don't restart the server, the island creation process remains buggy and if I try to do the /is create command again it says the island creation process is already in process.

**Comment by OmerBenGera** [comment]
Seems like you deleted an island level at some point while having islands in this level.

**Comment by OmerBenGera** [comment]
Show me your upgrades file please.

**Comment by FrancyMak** [comment]
> Show me your upgrades file please. Upload it to pastebin and send it here.

https://pastebin.com/S7W41UHt

**Comment by FrancyMak** [comment]
Entire https://pastebin.com/ZSpYPSjm

**Comment by OmerBenGera** [comment]
Fix your second crop-growth price, check if it helps

**Comment by FrancyMak** [comment]
Then something was also buggy in the database I think. I removed the database and recreated it.
