### ISSUE TITLE
Breaking every block of an island causes an error.

### ISSUE THREAD

**Issue by JoelSoep** [BG-Software-LLC/SuperiorSkyblock2#1516]
### Minecraft's Version

1.18.2

### Plugin's Version

v2022.9

### Describe the bug

[16:49:05] [Craft Scheduler Thread - 95 - SuperiorSkyblock2/WARN]: [SuperiorSkyblock2] Plugin SuperiorSkyblock2 v2022.9 generated an exception while executing task 24071
java.lang.NullPointerException: Cannot invoke "com.bgsoftware.superiorskyblock.api.island.Island.markChunkEmpty(org.bukkit.World, int, int, boolean)" because "island" is null
	at com.bgsoftware.superiorskyblock.world.WorldBlocks.isChunkEmpty(WorldBlocks.java:58) ~[SuperiorSkyblock2-2022.9.jar:?]
	at com.bgsoftware.superiorskyblock.player.algorithm.DefaultPlayerTeleportAlgorithm.lambda$null$2(DefaultPlayerTeleportAlgorithm.java:152) ~[SuperiorSkyblock2-2022.9.jar:?]
	at com.bgsoftware.superiorskyblock.core.threads.BukkitExecutor$NestedTask.lambda$null$4(BukkitExecutor.java:160) ~[SuperiorSkyblock2-2022.9.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-388]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-388]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-388]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	
	Players are not able to return to their island if this happens.

### To Reproduce

1. Create an Island
2. Break every block of the Island
3. use /is

**Comment by OmerBenGera** [comment]
Update to latest dev build, let me know if it helps

**Comment by JoelSoep** [comment]
Hello, my apologies for the delay. I currently have exams, but will look further into the issues in the weekend.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by BLQuatre** [comment]
I have the same bug but i will try to update with latest dev build

**Comment by BLQuatre** [comment]
Its when player try to teleport to an island but the block of the spawn point has been broke

**Comment by BLQuatre** [comment]
> Any news regarding this?

I check with the latest dev build and that work ! Player receive a message tell them that island is not secure and he has to contact a admin

**Comment by OmerBenGera** [comment]
> > Any news regarding this?
> 
> I check with the latest dev build and that work ! Player receive a message tell them that island is not secure and he has to contact a admin

That makes sense. If they break every block in their island, the plugin can't teleport them to their island anymore.
It's your own decision what to do in that situation.

I am closing this for now :)
