### ISSUE TITLE
Created a new server and getting "An error occured while loading the plugin!"

### ISSUE THREAD

**Issue by barisbored** [BG-Software-LLC/SuperiorSkyblock2#1559]
### Minecraft's Version

spigot 1.19.3

### Plugin's Version

SuperiorSkyblock2 2022.9

### Describe the bug

```bash
[13:33:05] [Server thread/INFO]: [SuperiorSkyblock2] Loading 1 libraries... please wait
[13:33:05] [Server thread/INFO]: [SuperiorSkyblock2] Loaded library C:\Users\demir\Desktop\server\libraries\org\openjdk\nashorn\nashorn-core\15.4\nashorn-core-15.4.jar
[13:33:05] [Server thread/INFO]: [SuperiorSkyblock2] Loaded library C:\Users\demir\Desktop\server\libraries\org\ow2\asm\asm\7.3.1\asm-7.3.1.jar
[13:33:05] [Server thread/INFO]: [SuperiorSkyblock2] Loaded library C:\Users\demir\Desktop\server\libraries\org\ow2\asm\asm-commons\7.3.1\asm-commons-7.3.1.jar
[13:33:05] [Server thread/INFO]: [SuperiorSkyblock2] Loaded library C:\Users\demir\Desktop\server\libraries\org\ow2\asm\asm-analysis\7.3.1\asm-analysis-7.3.1.jar
[13:33:05] [Server thread/INFO]: [SuperiorSkyblock2] Loaded library C:\Users\demir\Desktop\server\libraries\org\ow2\asm\asm-tree\7.3.1\asm-tree-7.3.1.jar
[13:33:05] [Server thread/INFO]: [SuperiorSkyblock2] Loaded library C:\Users\demir\Desktop\server\libraries\org\ow2\asm\asm-util\7.3.1\asm-util-7.3.1.jar
[13:33:07] [Server thread/INFO]: [SuperiorSkyblock2] Loading SuperiorSkyblock2 v2022.9
[13:33:07] [Server thread/ERROR]: [SuperiorSkyblock2] Data version: 3218
[13:33:07] [Server thread/ERROR]: [SuperiorSkyblock2] ################################################[13:33:07] [Server thread/ERROR]: [SuperiorSkyblock2] ##                                            ##[13:33:07] [Server thread/ERROR]: [SuperiorSkyblock2] ## An error occured while loading the plugin! ##[13:33:07] [Server thread/ERROR]: [SuperiorSkyblock2] ##                                            ##[13:33:07] [Server thread/ERROR]: [SuperiorSkyblock2] ################################################[13:33:07] [Server thread/ERROR]: [SuperiorSkyblock2]
[13:33:07] [Server thread/ERROR]: [SuperiorSkyblock2] Stack Trace:
[13:33:07] [Server thread/ERROR]: [SuperiorSkyblock2]   at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onLoad(SuperiorSkyblockPlugin.java:180)
[13:33:07] [Server thread/ERROR]: [SuperiorSkyblock2]   at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:433)
[13:33:07] [Server thread/ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219)
[13:33:07] [Server thread/ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973)
[13:33:07] [Server thread/ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301)
[13:33:07] [Server thread/ERROR]: [SuperiorSkyblock2]   at java.base/java.lang.Thread.run(Thread.java:1589)
[13:33:07] [Server thread/ERROR]: [SuperiorSkyblock2]
[13:33:07] [Server thread/ERROR]: [SuperiorSkyblock2] ################################################[13:33:07] [Server thread/INFO]: Preparing level "world"
```
and at the end
```bash
13:40:07] [Worker-Main-7/INFO]: Preparing spawn area: 68%
[13:40:07] [Server thread/INFO]: Time elapsed: 2624 ms
[13:40:07] [Server thread/INFO]: [SuperiorSkyblock2] Enabling SuperiorSkyblock2 v2022.9
[13:40:07] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[13:40:07] [Server thread/INFO]: Done (8.189s)! For help, type "help"
[13:40:07] [Server thread/INFO]: Stopping server
[13:40:07] [Server thread/INFO]: [SuperiorSkyblock2] Disabling SuperiorSkyblock2 v2022.9
[13:40:07] [Server thread/INFO]: Saving players
[13:40:07] [Server thread/INFO]: Saving worlds
[13:40:09] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[13:40:09] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[13:40:09] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[13:40:09] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[13:40:09] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[13:40:09] [Thread-4/ERROR]: [SuperiorSkyblock2] Detected crash. SuperiorSkyblock will attempt to save data...
```

### To Reproduce

Use BuildTools.jar provided by spigot to create a new spigot server and then put plugin to plugins folder without changing anything. Start as normally and you'll see whats going on

**Comment by OmerBenGera** [comment]
Update to latest dev build
