### ISSUE TITLE
Annoying error

### ISSUE THREAD

**Issue by FrancyMak** [BG-Software-LLC/SuperiorSkyblock2#1560]
### Minecraft's Version

git-Paper-307 (MC: 1.19.2)

### Plugin's Version

SuperiorSkyblock2-2022.9-b960.jar

### Describe the bug

I have enabled price synchronization with ShopGUIPlus, but I have this error in console, which would not seem to give any problems, however, I wanted to ask if it was possible to fix it.

### To Reproduce

1. Enable price synchronization in the config
2. Start the server if ShopGUIPlus is started after Superior, you will get the error.

### Additional Information

```
[11:12:28] [Server thread/WARN]: [SuperiorSkyblock2] Task #1068 for SuperiorSkyblock2 v2022.9-b960 generated an exception
net.brcdev.shopgui.exception.shop.ShopsNotLoadedException: Shops aren't loaded yet
	at net.brcdev.shopgui.shop.ShopManager.getShops(ShopManager.java:55) ~[ShopGUIPlus-1.80.1.jar:?]
	at com.bgsoftware.superiorskyblock.external.prices.PricesProvider_ShopGUIPlus78.getPrice(PricesProvider_ShopGUIPlus78.java:31) ~[SuperiorSkyblock2-2022.9-b960.jar:?]
	at com.bgsoftware.superiorskyblock.core.values.BlockValuesManagerImpl.getBlockWorth(BlockValuesManagerImpl.java:114) ~[SuperiorSkyblock2-2022.9-b960.jar:?]
	at com.bgsoftware.superiorskyblock.island.algorithm.DefaultIslandBlocksTrackerAlgorithm.trackBlock(DefaultIslandBlocksTrackerAlgorithm.java:40) ~[SuperiorSkyblock2-2022.9-b960.jar:?]
	at com.bgsoftware.superiorskyblock.island.SIsland.handleBlockPlace(SIsland.java:1984) ~[SuperiorSkyblock2-2022.9-b960.jar:?]
	at com.bgsoftware.superiorskyblock.island.SIsland.lambda$null$7(SIsland.java:300) ~[SuperiorSkyblock2-2022.9-b960.jar:?]
	at java.util.Map.forEach(Map.java:713) ~[?:?]
	at com.bgsoftware.superiorskyblock.island.SIsland.lambda$new$8(SIsland.java:299) ~[SuperiorSkyblock2-2022.9-b960.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-307]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works.

**Comment by FrancyMak** [comment]
Fixed! Il giorno 20 gen 2023, alle ore 14:25, Ome_R ***@***.***> ha scritto:﻿
Check out latest dev build, let me know if it works.
