### ISSUE TITLE
[BUG] when trying to tabcomplete with the /is adm cmdall

### ISSUE THREAD

**Issue by iSeitan** [BG-Software-LLC/SuperiorSkyblock2#1566]
### Minecraft's Version

paper-1.19.3-379

### Plugin's Version

SuperiorSkyblock2-2022.9-b960

### Describe the bug

[15:22:16 ERROR]: Exception when iSeitan attempted to tab complete is admin cmdall iSeitan false m
org.bukkit.command.CommandException: Unhandled exception executing tab-completer for 'is admin cmdall iSeitan false m' in com.bgsoftware.superiorskyblock.commands.CommandsManagerImpl$PluginCommand(island)
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:246) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.tabCompleteCommand(CraftServer.java:2270) ~[paper-1.19.3.jar:git-Paper-379]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.tabComplete(CraftServer.java:2242) ~[paper-1.19.3.jar:git-Paper-379]
        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:74) ~[paper-1.19.3.jar:git-Paper-379]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[brigadier-1.0.18.jar:git-Paper-379]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:601) ~[paper-1.19.3.jar:?]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:581) ~[paper-1.19.3.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleCustomCommandSuggestions$5(ServerGamePacketListenerImpl.java:901) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-379]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-379]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-379]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-379]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "list" is null
        at java.util.Collections.unmodifiableList(Collections.java:1319) ~[?:?]
        at com.bgsoftware.superiorskyblock.commands.IAdminIslandCommand.tabComplete(IAdminIslandCommand.java:52) ~[SuperiorSkyblock2-2022.9-b960.jar:?]
        at com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.tabComplete(ISuperiorCommand.java:22) ~[SuperiorSkyblock2-2022.9-b960.jar:?]
        at com.bgsoftware.superiorskyblock.commands.player.CmdAdmin.tabComplete(CmdAdmin.java:143) ~[SuperiorSkyblock2-2022.9-b960.jar:?]
        at com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.tabComplete(ISuperiorCommand.java:22) ~[SuperiorSkyblock2-2022.9-b960.jar:?]
        at com.bgsoftware.superiorskyblock.commands.CommandsManagerImpl$PluginCommand.tabComplete(CommandsManagerImpl.java:321) ~[SuperiorSkyblock2-2022.9-b960.jar:?]
        at org.bukkit.command.Command.tabComplete(Command.java:93) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:240) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 20 more

### To Reproduce

Try to tabcomplete a command

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
