### ISSUE TITLE
SkinsRestorer Hook Problem

### ISSUE THREAD

**Issue by KloutDevs** [BG-Software-LLC/SuperiorSkyblock2#1577]
### Minecraft's Version

Minecraft Version: 1.19.2 
Server Version: 1.19.2 with Bungee

### Plugin's Version

2022.9

### Describe the bug

When I start the plugin, in the console show this error.

[16:59:41] [Server thread/ERROR]: [SuperiorSkyblock2] An unexpected error occurred while registering hook SkinsRestorerHook:
[16:59:41] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[16:59:41] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:59:41] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[16:59:41] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:59:41] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[16:59:41] [Server thread/WARN]: 	at SuperiorSkyblock2-2022.9.jar//com.bgsoftware.superiorskyblock.external.ProvidersManagerImpl.registerHook(ProvidersManagerImpl.java:567)
[16:59:41] [Server thread/WARN]: 	at SuperiorSkyblock2-2022.9.jar//com.bgsoftware.superiorskyblock.external.ProvidersManagerImpl.registerGeneralHooks(ProvidersManagerImpl.java:370)
[16:59:41] [Server thread/WARN]: 	at SuperiorSkyblock2-2022.9.jar//com.bgsoftware.superiorskyblock.external.ProvidersManagerImpl.lambda$loadData$1(ProvidersManagerImpl.java:92)
[16:59:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[16:59:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[16:59:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1500)
[16:59:41] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:486)
[16:59:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424)
[16:59:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1194)
[16:59:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310)
[16:59:41] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[16:59:41] [Server thread/WARN]: Caused by: java.lang.NoClassDefFoundError: skinsrestorer/shared/exception/SkinRequestException
[16:59:41] [Server thread/WARN]: 	at SuperiorSkyblock2-2022.9.jar//com.bgsoftware.superiorskyblock.external.SkinsRestorerHook.register(SkinsRestorerHook.java:38)
[16:59:41] [Server thread/WARN]: 	... 15 more
[16:59:41] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: skinsrestorer.shared.exception.SkinRequestException
[16:59:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:179)
[16:59:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126)
[16:59:41] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[16:59:41] [Server thread/WARN]: 	... 16 more

### To Reproduce

Starting or reloading the plugin

### Additional Information

The SkinsRestorer plugin stay in Proxy Mode.

**Comment by Tptuaazn** [comment]
Try latest dev build.

**Comment by ZappySK** [comment]
Having the same problem..

**Comment by OmerBenGera** [comment]
> Having the same problem..

Open a new issue.
This issue was opened 6 months ago.
