### ISSUE TITLE
Wrong Portal Event and incorrect priority breaking compatibility.

### ISSUE THREAD

**Issue by meStormBits** [BG-Software-LLC/SuperiorSkyblock2#1581]
### Minecraft's Version

PaperSpigot 1.19.2, also happens on Spigot 1.8.9

### Plugin's Version

SuperiorSkyblock-2022.9-b967

### Describe the bug

I am the developer of a Sell Portal plugin which works based on the default, EntityPortalEvent from the Spigot API. Whenever you have the end feature of Superior enabled this completely breaks. It almost looks like the EntityPortalEvent is not being called at all anymore. Even a simple debug output at the top of the listener doesn't work. My guess is that this is the issue with the priority of the listeners. Simply changing it to NORMAL should be good enough for the case you are using it for.

Furthermore I have found a way to make it work by using the EntityPortalEnterEvent from Spigot, This event unfortunately is not cancellable and so the entire functionality basically breaks. I'm relying on being able to cancel the event so that other plugins that add end functionality don't break however it seems that Superior has actually broken any compatibility by having the listeners at the highest priority.  

The fix from Superior would be to actually use the correct event, the EntityPortalEvent and making sure the listener has the correct priority. The way it is done now simply does not allow the EntityPortalEvent to be called due to Superior doing their internal teleport logic for the entity. 

https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/master/src/main/java/com/bgsoftware/superiorskyblock/listener/PortalsListener.java

### To Reproduce

Make a listener for EntityPortalEvent and add a simple debug message. 

You will see that this event never gets called due to Superior's logic with the wrong event.

**Comment by OmerBenGera** [comment]
SSB overrides all the portal mechanisms for island worlds so it can properly teleport players to the correct destinations.
Why would it matter to you?

**Comment by meStormBits** [comment]
My SellPortals plugin depends on the EntityPortalEvent. It basically works based on an entity getting thrown inside the end portal and it will remove the entity and count them to an internal storage. Is there any way we can make both plugins compatible with each other? As the EntityPortalEvent never actually gets called.

**Comment by PrinceHatem** [comment]
Running through the same issue @OmerBenGera we'd really appreciate if we can make this work 🙏🏼

**Comment by OmerBenGera** [comment]
Why aren't you using EntityPortalEnterEvent? @meStormBits

**Comment by OmerBenGera** [comment]
The solution would be to use EntityPortalEnterEvent, and instead of cancelling the event, you should just remove the entity.

**Comment by meStormBits** [comment]
I currently am already removing the entity but unfortunately that throws an error from superior, I believe the only thing you have to do fix it is check if the entity is null in your teleport code from the portal event. 

`>....2023-01-31 23:31:43,632 Server thread ERROR Recursive call to appender Async
[23:31:43 WARN]: Illegal Entity Teleport EntityPig['Pig'/770, uuid='3a8aa3fc-2461-4291-a5be-b53ea8bdf00d', l='ServerLevel[SuperiorWorld_the_end]', x=-599.50, y=101.50, z=600.50, cpos=[-38, 37], tl=2, v=false] to ServerLevel[SuperiorWorld]:net.minecraft.core.Position@7cc1496b
java.lang.Throwable: null
        at net.minecraft.world.entity.Entity.teleportTo(Entity.java:3339) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftEntity.teleport(CraftEntity.java:583) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.entity.Entity.teleport(Entity.java:157) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftEntity.teleport(CraftEntity.java:552) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftLivingEntity.teleport(CraftLivingEntity.java:651) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftEntity.teleport(CraftEntity.java:546) ~[paper-1.19.2.jar:git-Paper-307]
        at org.stormdev.sellportals.listeners.PortalListener$1.run(PortalListener.java:58) ~[SellPortals-1.0 (16).jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by OmerBenGera** [comment]
> I currently am already removing the entity but unfortunately that throws an error from superior, I believe the only thing you have to do fix it is check if the entity is null in your teleport code from the portal event.
> 
> `>....2023-01-31 23:31:43,632 Server thread ERROR Recursive call to appender Async [23:31:43 WARN]: Illegal Entity Teleport EntityPig['Pig'/770, uuid='3a8aa3fc-2461-4291-a5be-b53ea8bdf00d', l='ServerLevel[SuperiorWorld_the_end]', x=-599.50, y=101.50, z=600.50, cpos=[-38, 37], tl=2, v=false] to ServerLevel[SuperiorWorld]:net.minecraft.core.Position@7cc1496b java.lang.Throwable: null at net.minecraft.world.entity.Entity.teleportTo(Entity.java:3339) ~[paper-1.19.2.jar:git-Paper-307] at org.bukkit.craftbukkit.v1_19_R1.entity.CraftEntity.teleport(CraftEntity.java:583) ~[paper-1.19.2.jar:git-Paper-307] at org.bukkit.entity.Entity.teleport(Entity.java:157) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?] at org.bukkit.craftbukkit.v1_19_R1.entity.CraftEntity.teleport(CraftEntity.java:552) ~[paper-1.19.2.jar:git-Paper-307] at org.bukkit.craftbukkit.v1_19_R1.entity.CraftLivingEntity.teleport(CraftLivingEntity.java:651) ~[paper-1.19.2.jar:git-Paper-307] at org.bukkit.craftbukkit.v1_19_R1.entity.CraftEntity.teleport(CraftEntity.java:546) ~[paper-1.19.2.jar:git-Paper-307] at org.stormdev.sellportals.listeners.PortalListener$1.run(PortalListener.java:58) ~[SellPortals-1.0 (16).jar:?] at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-307] at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-307] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-307] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-307] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-307] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-307] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307] at java.lang.Thread.run(Thread.java:833) ~[?:?]`

Remove it in 1-tick delay

**Comment by OmerBenGera** [comment]
@meStormBits Hey, have you managed to sort it out?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
