### ISSUE TITLE
Could you make it possible to use BuilderWand with your plugin

### ISSUE THREAD

**Issue by gunerrockerth** [BG-Software-LLC/SuperiorSkyblock2#1583]
### Minecraft's Version

 CraftBukkit version 3610-Spigot-6198b5a-19df23a (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT)

### Plugin's Version

SuperiorSkyblock2 version 2022.9

### Describe the bug

When i tryna use Builder Wand on my island this bug alway show up in my console. I will put the log in Additional information. if someone can help me fix it pls help.

### To Reproduce

Im not sure how to fix it pls help

### Additional Information

[15:46:14 WARN]: [BuildersWand] Task #51 for BuildersWand v2.27.0 generated an exception
java.lang.NullPointerException: Cannot invoke "com.bgsoftware.superiorskyblock.api.SuperiorSkyblock.getGrid()" because "com.bgsoftware.superiorskyblock.api.SuperiorSkyblockAPI.plugin" is null
	at com.bgsoftware.superiorskyblock.api.SuperiorSkyblockAPI.getIslandAt(SuperiorSkyblockAPI.java:141) ~[?:?]
	at de.False.BuildersWand.events.WandEvents.isAllowedToBuildForExternalPlugins(WandEvents.java:747) ~[?:?]
	at de.False.BuildersWand.events.WandEvents.setBlockSelection(WandEvents.java:596) ~[?:?]
	at de.False.BuildersWand.events.WandEvents.access$800(WandEvents.java:64) ~[?:?]
	at de.False.BuildersWand.events.WandEvents$1.run(WandEvents.java:145) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1245) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:394) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1013) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at java.lang.Thread.run(Thread.java:1589) [?:?]

**Comment by OmerBenGera** [comment]
The builder wand plugin shaded SSB's API into their plugin, causing any interaction with SSB to not work properly
Contact their developers and inform them about the bug - they should not shade the API into their own jar.
