### ISSUE TITLE
Some warps dont work for certain player

### ISSUE THREAD

**Issue by iSeitan** [BG-Software-LLC/SuperiorSkyblock2#1585]
### Minecraft's Version

paper-1.19.3-386

### Plugin's Version

SuperiorSkyblock2-2022.9-b967

### Describe the bug

All the /is warps work, except for one player, his menu cant be open and it spams in the console

### To Reproduce

Idk

### Additional Information

[19:26:02 WARN]: [SuperiorSkyblock2] Plugin SuperiorSkyblock2 v2022.9-b967 generated an exception while executing task 23599913
java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
        at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:756) ~[?:?]
        at java.util.ArrayList.add(ArrayList.java:481) ~[?:?]
        at com.bgsoftware.superiorskyblock.core.menu.impl.MenuWarpCategories$View.lambda$null$1(MenuWarpCategories.java:107) ~[SuperiorSkyblock2-2022.9-b967.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at com.bgsoftware.superiorskyblock.core.menu.impl.MenuWarpCategories$View.lambda$requestObjects$2(MenuWarpCategories.java:105) ~[SuperiorSkyblock2-2022.9-b967.jar:?]
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?]
        at com.bgsoftware.superiorskyblock.core.menu.impl.MenuWarpCategories$View.requestObjects(MenuWarpCategories.java:100) ~[SuperiorSkyblock2-2022.9-b967.jar:?]
        at com.bgsoftware.superiorskyblock.core.menu.view.AbstractPagedMenuView.updatePagedObjects(AbstractPagedMenuView.java:52) ~[SuperiorSkyblock2-2022.9-b967.jar:?]
        at com.bgsoftware.superiorskyblock.core.menu.view.AbstractPagedMenuView.getPagedObjects(AbstractPagedMenuView.java:45) ~[SuperiorSkyblock2-2022.9-b967.jar:?]
        at com.bgsoftware.superiorskyblock.core.menu.layout.PagedMenuLayoutImpl.populateInventory(PagedMenuLayoutImpl.java:45) ~[SuperiorSkyblock2-2022.9-b967.jar:?]
        at com.bgsoftware.superiorskyblock.core.menu.layout.AbstractMenuLayout.buildInventory(AbstractMenuLayout.java:73) ~[SuperiorSkyblock2-2022.9-b967.jar:?]
        at com.bgsoftware.superiorskyblock.core.menu.AbstractMenu.lambda$buildInventory$2(AbstractMenu.java:79) ~[SuperiorSkyblock2-2022.9-b967.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-386]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.3.jar:git-Paper-386]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

When i try to open a player warps it doesnt work, but the other player dont do that and it works

**Comment by LO383krystianch** [comment]
same problem

**Comment by DarkyCat** [comment]
same problem

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works
