### ISSUE TITLE
 the plugin shuts down the server

### ISSUE THREAD

**Issue by ReplejPL** [BG-Software-LLC/SuperiorSkyblock2#1590]
### Minecraft's Version

"this server is running CraftBukkit..."
(MC: 1.19)
1.19-R0.1-SNAPSHOT

### Plugin's Version

2022.9 30/10/2022 18:00:14

### Describe the bug

Hello, I have a problem, I get this error when starting the server, when I turn off the superskyblock plugin, suddenly everything works

### To Reproduce

https://pastebin.com/rRBWR9vM

### Additional Information

https://pastebin.com/rRBWR9vM

**Comment by ReplejPL** [comment]
[02:15:22 ERROR]: [SuperiorSkyblock2] Data version: 3218
[02:15:22 ERROR]: [SuperiorSkyblock2] ################################################
[02:15:22 ERROR]: [SuperiorSkyblock2] ##                                            ##
[02:15:22 ERROR]: [SuperiorSkyblock2] ## An error occured while loading the plugin! ##
[02:15:22 ERROR]: [SuperiorSkyblock2] ##                                            ##
[02:15:22 ERROR]: [SuperiorSkyblock2] ################################################
[02:15:22 ERROR]: [SuperiorSkyblock2]
[02:15:22 ERROR]: [SuperiorSkyblock2] Stack Trace:
[02:15:22 ERROR]: [SuperiorSkyblock2]   at SuperiorSkyblock2-2022.9 (5).jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onLoad(SuperiorSkyblockPlugin.java:180)
[02:15:22 ERROR]: [SuperiorSkyblock2]   at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:442)
[02:15:22 ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
[02:15:22 ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[02:15:22 ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[02:15:22 ERROR]: [SuperiorSkyblock2]   at java.base/java.lang.Thread.run(Thread.java:833)
[02:15:22 ERROR]: [SuperiorSkyblock2]
[02:15:22 ERROR]: [SuperiorSkyblock2] ################################################

**Comment by OmerBenGera** [comment]
Send me your entire logs file by uploading it to pastebin and send a link to it here

**Comment by Tptuaazn** [comment]
Close it, solved in discord.

**Comment by thomas-massey** [comment]
Any help would be appriciated
