### ISSUE TITLE
WarpCategory.getWarps()" because "this.pagedObject" is null

### ISSUE THREAD

**Issue by DarkyCat** [BG-Software-LLC/SuperiorSkyblock2#1601]
### Minecraft's Version

1.19.3

### Plugin's Version

SuperiorSkyblock2-2022.9-b972.jar

### Describe the bug

spam after command /is warps

### To Reproduce

[13:18:30 INFO]: [SuperiorSkyblock2] PagedMenuLayoutImpl::populateInventory ENTER {0}
[13:18:30 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while setting up menu:
[13:18:30 WARN]: java.lang.NullPointerException: Cannot invoke "com.bgsoftware.superiorskyblock.api.island.warps.WarpCategory.getWarps()" because "this.pagedObject" is null
[13:18:30 WARN]:        at SuperiorSkyblock2-2022.9-b972.jar//com.bgsoftware.superiorskyblock.core.menu.button.impl.WarpCategoryPagedObjectButton.modifyViewItem(WarpCategoryPagedObjectButton.java:29)
[13:18:30 WARN]:        at SuperiorSkyblock2-2022.9-b972.jar//com.bgsoftware.superiorskyblock.core.menu.button.AbstractPagedMenuButton.createViewItem(AbstractPagedMenuButton.java:29)
[13:18:30 WARN]:        at SuperiorSkyblock2-2022.9-b972.jar//com.bgsoftware.superiorskyblock.core.menu.layout.PagedMenuLayoutImpl.populateInventory(PagedMenuLayoutImpl.java:69)
[13:18:30 WARN]:        at SuperiorSkyblock2-2022.9-b972.jar//com.bgsoftware.superiorskyblock.core.menu.layout.AbstractMenuLayout.buildInventory(AbstractMenuLayout.java:73)
[13:18:30 WARN]:        at SuperiorSkyblock2-2022.9-b972.jar//com.bgsoftware.superiorskyblock.core.menu.AbstractMenu.lambda$buildInventory$2(AbstractMenu.java:79)
[13:18:30 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[13:18:30 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[13:18:30 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:18:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[13:18:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[13:18:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
