### ISSUE TITLE
When trying to load iselends's .schematic with WE have error, so I can't change islends

### ISSUE THREAD

**Issue by Evalutik** [BG-Software-LLC/SuperiorSkyblock2#1651]
### Minecraft's Version

Core: PurPur 1.19.3

### Plugin's Version

2022.9

### Describe the bug

 when trying to load iselends's .schematic with WE have error, so I can't change islends:

[19:46:36 ERROR]: Uncaught exception occurred in task: Loading schematic normal
java.io.IOException: Invalid tag type: 116.
	at com.sk89q.jnbt.NBTInputStream.readTagPayload(NBTInputStream.java:170) ~[worldedit-bukkit-7.2.13.jar:?]
	at com.sk89q.jnbt.NBTInputStream.readNamedTag(NBTInputStream.java:86) ~[worldedit-bukkit-7.2.13.jar:?]
	at com.sk89q.jnbt.NBTInputStream.readTagPayload(NBTInputStream.java:145) ~[worldedit-bukkit-7.2.13.jar:?]
	at com.sk89q.jnbt.NBTInputStream.readNamedTag(NBTInputStream.java:86) ~[worldedit-bukkit-7.2.13.jar:?]
	at com.sk89q.jnbt.NBTInputStream.readNamedTag(NBTInputStream.java:63) ~[worldedit-bukkit-7.2.13.jar:?]
	at com.sk89q.worldedit.extent.clipboard.io.SpongeSchematicReader.getBaseTag(SpongeSchematicReader.java:151) ~[worldedit-bukkit-7.2.13.jar:?]
	at com.sk89q.worldedit.extent.clipboard.io.SpongeSchematicReader.read(SpongeSchematicReader.java:91) ~[worldedit-bukkit-7.2.13.jar:?]
	at com.sk89q.worldedit.command.SchematicCommands$SchematicLoadTask.call(SchematicCommands.java:322) ~[worldedit-bukkit-7.2.13.jar:?]
	at com.sk89q.worldedit.command.SchematicCommands$SchematicLoadTask.call(SchematicCommands.java:304) ~[worldedit-bukkit-7.2.13.jar:?]
	at com.sk89q.worldedit.command.util.AsyncCommandBuilder.runTask(AsyncCommandBuilder.java:158) ~[worldedit-bukkit-7.2.13.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131) ~[guava-31.1-jre.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74) ~[guava-31.1-jre.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82) ~[guava-31.1-jre.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]

### To Reproduce

1) Put .schematic file from Skyblock's folder into plugins/worldedit/schematic. 
2) Try //scheme load <name of scheme>
3) Error

**Comment by OmerBenGera** [comment]
You must have FAWE installed in order to use WE schematics.
Anyways, not recommeneded at all. You should use the built-in system for schematics.
https://wiki.bg-software.com/superiorskyblock/overview/schematics
