### ISSUE TITLE
ChunkLoadEvent, asked on Spigot 

### ISSUE THREAD

**Issue by HyperWithit** [BG-Software-LLC/SuperiorSkyblock2#1681]
### Minecraft's Version

1.19.4

### Plugin's Version

2023.1

### Describe the bug

ChunkLoadEvent

### To Reproduce

[13:44:52 ERROR]: Could not pass event ChunkLoadEvent to SuperiorSkyblock2 v2023.1
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
        at com.bgsoftware.superiorskyblock.nms.v1194.NMSChunksImpl.getBlockEntities(NMSChunksImpl.java:408) ~[SuperiorSkyblock2-2023.1.jar:?]
        at com.bgsoftware.superiorskyblock.module.upgrades.type.UpgradeTypeSpawnerRates$SpawnerRatesListener.onChunkLoad(UpgradeTypeSpawnerRates.java:80) ~[SuperiorSkyblock2-2023.1.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-509]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-509]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-509]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:910) ~[?:?]
        at net.minecraft.world.level.chunk.LevelChunk.onChunkLoad(LevelChunk.java:861) ~[?:?]
        at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1311) ~[paper-1.19.4.jar:git-Paper-509]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1050) ~[paper-1.19.4.jar:git-Paper-509]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1034) ~[paper-1.19.4.jar:git-Paper-509]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:919) ~[paper-1.19.4.jar:git-Paper-509]
        at net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:583) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1005) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:579) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1330) ~[paper-1.19.4.jar:git-Paper-509]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-509]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1389) ~[paper-1.19.4.jar:git-Paper-509]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-509]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-509]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]

### Additional Information

Hope this

**Comment by HyperWithit** [comment]
thanks man
