### ISSUE TITLE
Could not pass event ChunkUnloadEvent

### ISSUE THREAD

**Issue by qhoeger** [BG-Software-LLC/SuperiorSkyblock2#1685]
### Minecraft's Version

Paper 1.19.4
SuperiorSkyblock2-2023.1

### Plugin's Version

cant do commands server gets overloaded too quickly due to the bug im having
I just downloaded the plugin to update to the newest version so whatever the newest version out at the moment is. (2023.1 25/03/2023 15:57:08)

### Describe the bug

This repeats continuously. I have tried uninstalling plugins to no avail. I cant seem to locate the problem at all.

[22:33:12] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to SuperiorSkyblock2 v2023.1
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
	at com.bgsoftware.superiorskyblock.nms.v1194.NMSChunksImpl.startTickingChunk(NMSChunksImpl.java:376) ~[SuperiorSkyblock2-2023.1.jar:?]
	at com.bgsoftware.superiorskyblock.world.event.WorldEventsManagerImpl.unloadChunk(WorldEventsManagerImpl.java:110) ~[SuperiorSkyblock2-2023.1.jar:?]
	at com.bgsoftware.superiorskyblock.listener.ChunksListener.onChunkUnloadMonitor(ChunksListener.java:48) ~[SuperiorSkyblock2-2023.1.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-510]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-510]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-510]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.chunk.LevelChunk.unloadCallback(LevelChunk.java:945) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk.onChunkUnload(LevelChunk.java:871) ~[?:?]
	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1345) ~[paper-1.19.4.jar:git-Paper-510]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1050) ~[paper-1.19.4.jar:git-Paper-510]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1034) ~[paper-1.19.4.jar:git-Paper-510]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:919) ~[paper-1.19.4.jar:git-Paper-510]
	at net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:583) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.saveIncrementally(ServerChunkCache.java:608) ~[?:?]
	at net.minecraft.server.level.ServerLevel.saveIncrementally(ServerLevel.java:1294) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1417) ~[paper-1.19.4.jar:git-Paper-510]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-510]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-510]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]

### To Reproduce

Update a server from 1.19.2 => 1.19.4 with a custom map installed and these plugins:
Bungee Guard
LPC
ProtocolLib
SetSpawn
Vault
LuckPerms
FastAsyncWorldEdit
Essentials
CoreProtect

### Additional Information

[config.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/11228592/config.zip)

**Comment by OmerBenGera** [comment]
Update to latest dev build, already been fixed.
