### ISSUE TITLE
Plugin crashes when multiple people try to create island at the same time

### ISSUE THREAD

**Issue by AxteriaFX** [BG-Software-LLC/SuperiorSkyblock2#1707]
### Minecraft's Version

1.16.5 purpur.jar

### Plugin's Version

2023.1

### Describe the bug

[16:48:07] [Server thread/INFO]: Maggie issued server command: /is create
[16:48:07] [Server thread/INFO]: Jovt issued server command: /is create
[16:48:07] [Server thread/INFO]: Jey1 issued server command: /is create
[16:48:07] [Server thread/INFO]: Yunus99997 issued server command: /is create
[16:48:07] [Server thread/INFO]: Bvyt issued server command: /is create
[16:48:07] [Server thread/INFO]: JOG issued server command: /is create
[16:48:07] [Server thread/INFO]: Tuksilon issued server command: /is create
[16:48:07] [Server thread/INFO]: Joy2 issued server command: /is create
[16:48:07] [Server thread/INFO]: FarmBank issued server command: /is create
[16:48:07] [Server thread/INFO]: Joy1 issued server command: /is create
[16:48:07] [Server thread/INFO]: KBRL issued server command: /is create
[16:48:07] [Server thread/INFO]: Eren55 issued server command: /is create
[16:48:07] [Server thread/INFO]: BOY issued server command: /is create
[16:48:07] [Server thread/INFO]: Joy issued server command: /is create
[16:48:07] [Server thread/INFO]: FarmHesap issued server command: /is create
[16:48:07] [Server thread/INFO]: FarmMarket issued server command: /is create
[16:48:07] [Server thread/INFO]: Hoyt issued server command: /is create
[16:48:07] [Server thread/INFO]: Berat262 issued server command: /is create
[16:48:07] [Server thread/INFO]: Derin26 issued server command: /is create
[16:48:07] [Server thread/INFO]: Macro66 issued server command: /is create
[16:48:07] [Server thread/INFO]: BANKAM issued server command: /is create
[16:48:07] [Server thread/INFO]: YunusEmre262 issued server command: /is create
[16:48:07] [Server thread/INFO]: Ahmet972 issued server command: /is create
[16:48:07] [Server thread/INFO]: Elif667 issued server command: /is create
[16:48:07] [Server thread/INFO]: Jcole1 issued server command: /is create
[16:48:07] [Server thread/INFO]: Noyk issued server command: /is create
[16:48:07] [Server thread/INFO]: Ebderpearal1 issued server command: /is create
[16:48:07] [Server thread/INFO]: Atakan9v issued server command: /is create
[16:48:07] [Server thread/INFO]: Micro786 issued server command: /is create
[16:48:07] [Server thread/INFO]: Ebderpearal2 issued server command: /is create
[16:48:07] [Server thread/INFO]: Mete265 issued server command: /is create
[16:48:07] [Server thread/INFO]: Lava1 issued server command: /is create
[16:48:07] [Server thread/INFO]: Bugra6g issued server command: /is create
[16:48:07] [Server thread/INFO]: KubilayDemir issued server command: /is create
[16:48:07] [Server thread/INFO]: Tugce255 issued server command: /is create
[16:48:07] [Server thread/INFO]: Jooot issued server command: /is create
[16:48:07] [Server thread/WARN]: [SuperiorSkyblock2] Task #15537087 for SuperiorSkyblock2 v2023.1 generated an exception
java.lang.NullPointerException: null
	at java.util.ArrayDeque.addLast(ArrayDeque.java:303) ~[?:?]
	at java.util.ArrayDeque.forEach(ArrayDeque.java:888) ~[?:?]
	at java.util.ArrayDeque.copyElements(ArrayDeque.java:329) ~[?:?]
	at java.util.ArrayDeque.addAll(ArrayDeque.java:324) ~[?:?]
	at com.bgsoftware.common.executors.WorkerExecutor.stop(WorkerExecutor.java:127) ~[?:?]
	at com.bgsoftware.common.executors.WorkerExecutor.run(WorkerExecutor.java:162) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1503) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.Thread.run(Thread.java:833) [?:?]

### To Reproduce

The plugin breaks down when everyone tries to create an island at the same time.

**Comment by WarnDa** [comment]
Use latest dev build it will fix the issue : https://hub.bg-software.com/job/SuperiorSkyblock2/
