### ISSUE TITLE
latest dev build not launching

### ISSUE THREAD

**Issue by GreenedDev** [BG-Software-LLC/SuperiorSkyblock2#1712]
### Minecraft's Version

git-paper 1.12.2 1620

### Plugin's Version

2023.1-b18

### Describe the bug

error on startup

### To Reproduce

start server with java 11 and 1.12.2

### Additional Information

[14:39:53 INFO]: [SuperiorSkyblock2] Enabling SuperiorSkyblock2 v2023.1-b18
[14:39:53 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while registering module SuperiorSkyblock2-NashornEngine-b7.jar:
[14:39:53 WARN]: java.lang.RuntimeException: An error occurred while reading SuperiorSkyblock2-NashornEngine-b7.jar
[14:39:53 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.registerModule(ModulesManagerImpl.java:69)
[14:39:53 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.registerExternalModules(ModulesManagerImpl.java:208)
[14:39:53 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.loadData(ModulesManagerImpl.java:50)
[14:39:53 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:235)
[14:39:53 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[14:39:53 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[14:39:53 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[14:39:53 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[14:39:53 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[14:39:53 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[14:39:53 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[14:39:53 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[14:39:53 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[14:39:53 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[14:39:53 WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)
[14:39:53 WARN]: Caused by: java.lang.UnsupportedClassVersionError: com/bgsoftware/superiorskyblock/modules/nashornengine/NashornModule has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 55.0
[14:39:53 WARN]:        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[14:39:53 WARN]:        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
[14:39:53 WARN]:        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
[14:39:53 WARN]:        at com.bgsoftware.superiorskyblock.core.io.FileClassLoader.findClass(FileClassLoader.java:90)
[14:39:53 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[14:39:53 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:576)
[14:39:53 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[14:39:53 WARN]:        at com.bgsoftware.superiorskyblock.core.io.JarFiles.getClass(JarFiles.java:30)
[14:39:53 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.registerModule(ModulesManagerImpl.java:66)
[14:39:53 WARN]:        ... 14 more

**Comment by OmerBenGera** [comment]
You should be able to remove the nashorn engine module and it will work just fine.

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by GreenedDev** [comment]
no i just switched java version to 8 havent tested any more.

**Comment by OmerBenGera** [comment]
At least it works now :)
