### ISSUE TITLE
Pufferfish API

### ISSUE THREAD

**Issue by Jok3rTV** [BG-Software-LLC/SuperiorSkyblock2#1720]
### Minecraft's Version

1.19.3-R0.1-SNAPSHOT.jar

### Plugin's Version

2023.1 Dev Build #18

### Describe the bug

I think the Pufferfish API can't read the plugin missions files
plugins\SuperiorSkyblock2\datastore\modules\missions\farmer_3.yml

[17:30:01 ERROR]: Cannot load plugins\SuperiorSkyblock2\datastore\modules\missions\slayer_1.yml
org.bukkit.configuration.InvalidConfigurationException: unacceptable code point '' (0x0) special characters are not allowed
in "'reader'", position 0
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:106) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:306) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at com.bgsoftware.superiorskyblock.mission.MissionsManagerImpl.loadMissionsData(MissionsManagerImpl.java:387) ~[SuperiorSkyblock2-2023.1.jar:?]
        at com.bgsoftware.superiorskyblock.module.missions.MissionsModule.loadData(MissionsModule.java:144) ~[SuperiorSkyblock2-2023.1.jar:?]
        at com.bgsoftware.superiorskyblock.module.BuiltinModule.loadData(BuiltinModule.java:38) ~[SuperiorSkyblock2-2023.1.jar:?]
        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.lambda$loadModulesData$1(ModulesManagerImpl.java:192) ~[SuperiorSkyblock2-2023.1.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?]
        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.loadModulesData(ModulesManagerImpl.java:190) ~[SuperiorSkyblock2-2023.1.jar:?]
        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:563) ~[SuperiorSkyblock2-2023.1.jar:?]
        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:254) ~[SuperiorSkyblock2-2023.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:471) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1103) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:204) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:169) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:164) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:119) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1229) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:345) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:263) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:235) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:175) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:159) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.Yaml.compose(Yaml.java:559) ~[snakeyaml-1.33.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 24 more

### To Reproduce

I loaded the plugin after I switched to Pufferfish from Paper and I got errors on my console

**Comment by OmerBenGera** [comment]
Your one of the mission files is corrupted.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue persists let me know
