### ISSUE TITLE
Error when creating an island

### ISSUE THREAD

**Issue by kojaemin1324** [BG-Software-LLC/SuperiorSkyblock2#1723]
### Minecraft's Version

1.12.2

### Plugin's Version

SuperiorSkyblock2-2023.1-b18

### Describe the bug

Error when creating an island

### To Reproduce

After /is create test, the island is not created and an error appears

### Additional Information

[20:53:06] [Server thread/ERROR]: [SuperiorSkyblock2] An unexpected error occurred while creating an island:
[20:53:06] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 3
[20:53:06] [Server thread/WARN]:        at java.util.EnumMap.get(Unknown Source)
[20:53:06] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.external.worlds.WorldsProvider_Default.getIslandsWorld(WorldsProvider_Default.java:49)
[20:53:06] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.island.GridManagerImpl.getIslandsWorld(GridManagerImpl.java:547)
[20:53:06] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.getCenter(SIsland.java:777)
[20:53:06] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.getLoadedChunks(SIsland.java:1003)
[20:53:06] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.getLoadedChunks(SIsland.java:993)
[20:53:06] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.setIslandSizeInternal(SIsland.java:1576)
[20:53:06] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.clearUpgrades(SIsland.java:4106)
[20:53:06] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.updateUpgrades(SIsland.java:2331)
[20:53:06] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.<init>(SIsland.java:330)
[20:53:06] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.core.factory.FactoriesManagerImpl.createIsland(FactoriesManagerImpl.java:124)
[20:53:06] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.island.builder.IslandBuilderImpl.build(IslandBuilderImpl.java:753)
[20:53:06] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.island.algorithm.DefaultIslandCreationAlgorithm.createIsland(DefaultIslandCreationAlgorithm.java:90)
[20:53:06] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.island.GridManagerImpl.createIslandInternalAsync(GridManagerImpl.java:217)
[20:53:06] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.island.GridManagerImpl.createIsland(GridManagerImpl.java:189)
[20:53:06] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.island.GridManagerImpl.createIsland(GridManagerImpl.java:168)
[20:53:06] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.core.menu.impl.MenuIslandCreation.simulateClick(MenuIslandCreation.java:92)
[20:53:06] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.core.menu.button.impl.IslandCreationButton.onButtonClick(IslandCreationButton.java:45)
[20:53:06] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.api.menu.BaseMenu.onClick(BaseMenu.java:146)
[20:53:06] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.core.menu.AbstractMenu.onClick(AbstractMenu.java:48)
[20:53:06] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.core.menu.AbstractMenu.onClick(AbstractMenu.java:21)
[20:53:06] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.listener.MenusListener.onMenuClick(MenusListener.java:64)
[20:53:06] [Server thread/WARN]:        at catserver.server.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35)
[20:53:06] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[20:53:06] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503)
[20:53:06] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488)
[20:53:06] [Server thread/WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2215)
[20:53:06] [Server thread/WARN]:        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38)
[20:53:06] [Server thread/WARN]:        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12)
[20:53:06] [Server thread/WARN]:        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[20:53:06] [Server thread/WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[20:53:06] [Server thread/WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[20:53:06] [Server thread/WARN]:        at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[20:53:06] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:904)
[20:53:06] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475)
[20:53:06] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828)
[20:53:06] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:687)
[20:53:06] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by kojaemin1324** [comment]
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/133639785/099f9751-6611-4e24-bc0f-5d193ae0baa1)
