### ISSUE TITLE
Console error, spawner not calculated on is counts

### ISSUE THREAD

**Issue by Distolfix** [BG-Software-LLC/SuperiorSkyblock2#1748]
### Minecraft's Version

pufferfish 1.19.3

### Plugin's Version

#27

### Describe the bug

https://pastebin.com/Z7VMkSby ----> this error 

Line 95

[15:01:57 WARN]: java.lang.NullPointerException: Cannot invoke "net.brcdev.shopgui.spawner.internal.InternalSpawnerHandler.getSpawnerItem(org.bukkit.entity.EntityType)" because "this.internalHandler" is null

### To Reproduce

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/73421268/d122feb5-c0db-410c-82ae-08aff7704bfb)

Firs page
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/73421268/5ed52e99-40ab-4050-b4e0-d27eb2e3d8e9)

Second page

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/73421268/5ebf5392-32ad-4f39-983f-b06b868ec862)

Third page

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/73421268/5aeed511-ca46-44be-87dd-c0d70138c144)

### Additional Information

You told me to split this request

**Comment by Distolfix** [comment]
Line 1135

[15:01:57] [Server thread/WARN]: 	at SuperiorSkyblock2-2023.1-b27.jar//com.bgsoftware.superiorskyblock.core.values.BlockValuesManagerImpl.getBlockWorth(BlockValuesManagerImpl.java:114)
[15:01:57] [Server thread/WARN]: 	at SuperiorSkyblock2-2023.1-b27.jar//com.bgsoftware.superiorskyblock.island.algorithm.DefaultIslandBlocksTrackerAlgorithm.trackBlock(DefaultIslandBlocksTrackerAlgorithm.java:40)

**Comment by OmerBenGera** [comment]
Please upload your entire latest.log file to pastebin and send it here.

**Comment by Distolfix** [comment]
[latest.log](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/11779629/latest.log)

**Comment by OmerBenGera** [comment]
```
[16:22:29] [Server thread/INFO]: [ShopGUIPlus] ================================[ ShopGUI+ 1.86.0 ]================================
[16:22:29] [Server thread/INFO]: [ShopGUIPlus]  
[16:22:29] [Server thread/WARN]: [ShopGUIPlus] Failed to register VAULT economy.
[16:22:29] [Server thread/WARN]: [ShopGUIPlus] No supported economy plugins found, disabling the plugin.
[16:22:29] [Server thread/INFO]: [ShopGUIPlus] Disabling ShopGUIPlus v1.86.0
```
ShopGUIPlus was not enabled correctly, therefore you get errors.
Make sure you handle all the issues of ShopGUIPlus and it is loaded correctly.
