### ISSUE TITLE
CANT RUN IT HELP ME FIX PLZ 

### ISSUE THREAD

**Issue by ChuMengCaft** [BG-Software-LLC/SuperiorSkyblock2#1792]
### Minecraft's Version

This server is running Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Plugin's Version

CANT RUN IT
VERSION:SuperiorSkyblock2-2023.2.jar

### Describe the bug

After installing the plugin and starting, the server will automatically shut down

### To Reproduce

[10:59:02 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while registering mission fisherman_1:
[10:59:02 WARN]: com.bgsoftware.superiorskyblock.api.missions.MissionLoadException: Invalid fishing item COD.
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.missions.FishingMissions.load(FishingMissions.java:71)
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.mission.MissionsManagerImpl.loadMission(MissionsManagerImpl.java:467)
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.module.missions.MissionsModule.canLoadCategory(MissionsModule.java:222)
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.module.missions.MissionsModule.onEnable(MissionsModule.java:121)
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.module.BuiltinModule.onEnable(BuiltinModule.java:24)
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModule(ModulesManagerImpl.java:134)
[10:59:02 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[10:59:02 WARN]:        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[10:59:02 WARN]:        at java.util.LinkedList$LLSpliterator.forEachRemaining(Unknown Source)
[10:59:02 WARN]:        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[10:59:02 WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[10:59:02 WARN]:        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[10:59:02 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[10:59:02 WARN]:        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[10:59:02 WARN]:        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModules(ModulesManagerImpl.java:173)
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:527)
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:254)
[10:59:02 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[10:59:02 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[10:59:02 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[10:59:02 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[10:59:02 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[10:59:02 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[10:59:02 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[10:59:02 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[10:59:02 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[10:59:02 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[10:59:02 WARN]:        at java.lang.Thread.run(Unknown Source)
[10:59:02 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while registering mission fisherman_2:
[10:59:02 WARN]: com.bgsoftware.superiorskyblock.api.missions.MissionLoadException: Invalid fishing item NAUTILUS_SHELL.
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.missions.FishingMissions.load(FishingMissions.java:71)
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.mission.MissionsManagerImpl.loadMission(MissionsManagerImpl.java:467)
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.module.missions.MissionsModule.canLoadCategory(MissionsModule.java:222)
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.module.missions.MissionsModule.onEnable(MissionsModule.java:121)
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.module.BuiltinModule.onEnable(BuiltinModule.java:24)
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModule(ModulesManagerImpl.java:134)
[10:59:02 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[10:59:02 WARN]:        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[10:59:02 WARN]:        at java.util.LinkedList$LLSpliterator.forEachRemaining(Unknown Source)
[10:59:02 WARN]:        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[10:59:02 WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[10:59:02 WARN]:        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[10:59:02 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[10:59:02 WARN]:        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[10:59:02 WARN]:        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModules(ModulesManagerImpl.java:173)
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:527)
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:254)
[10:59:02 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[10:59:02 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[10:59:02 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[10:59:02 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[10:59:02 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[10:59:02 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[10:59:02 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[10:59:02 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[10:59:02 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[10:59:02 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[10:59:02 WARN]:        at java.lang.Thread.run(Unknown Source)
[10:59:02 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while registering mission fisherman_3:
[10:59:02 WARN]: com.bgsoftware.superiorskyblock.api.missions.MissionLoadException: Invalid fishing item NAUTILUS_SHELL.
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.missions.FishingMissions.load(FishingMissions.java:71)
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.mission.MissionsManagerImpl.loadMission(MissionsManagerImpl.java:467)
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.module.missions.MissionsModule.canLoadCategory(MissionsModule.java:222)
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.module.missions.MissionsModule.onEnable(MissionsModule.java:121)
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.module.BuiltinModule.onEnable(BuiltinModule.java:24)
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModule(ModulesManagerImpl.java:134)
[10:59:02 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[10:59:02 WARN]:        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[10:59:02 WARN]:        at java.util.LinkedList$LLSpliterator.forEachRemaining(Unknown Source)
[10:59:02 WARN]:        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[10:59:02 WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[10:59:02 WARN]:        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[10:59:02 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[10:59:02 WARN]:        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[10:59:02 WARN]:        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModules(ModulesManagerImpl.java:173)
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:527)
[10:59:02 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:254)
[10:59:02 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[10:59:02 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[10:59:02 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[10:59:02 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[10:59:02 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[10:59:02 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[10:59:02 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[10:59:02 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[10:59:02 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[10:59:02 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[10:59:02 WARN]:        at java.lang.Thread.run(Unknown Source)
[10:59:02 WARN]: [SuperiorSkyblock2] The mission category fisherman doesn't have missions, skipping...

**Comment by OmerBenGera** [comment]
The fisher mission contains item names that dont exist in 1.12.
Fix it.
