### ISSUE TITLE
Exception when viewing is top menu

### ISSUE THREAD

**Issue by anhcraft** [BG-Software-LLC/SuperiorSkyblock2#1807]
### Minecraft's Version

git-Tuinity-91cefbf (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Plugin's Version

SuperiorSkyblock2 version 2023.2

### Describe the bug

```
java.util.ConcurrentModificationException: null
        at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970) ~[?:?]
        at java.util.LinkedList$ListItr.next(LinkedList.java:892) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:74) ~[?:?]
        at com.bgsoftware.superiorskyblock.api.menu.BaseMenu.filterViews(BaseMenu.java:115) ~[?:?]
        at com.bgsoftware.superiorskyblock.api.menu.BaseMenu.refreshViews(BaseMenu.java:93) ~[?:?]
        at com.bgsoftware.superiorskyblock.core.menu.impl.MenuTopIslands.refreshViews(MenuTopIslands.java:70) ~[?:?]
        at com.bgsoftware.superiorskyblock.external.menus.MenusProvider_Default.refreshTopIslands(MenusProvider_Default.java:375) ~[?:?]
        at com.bgsoftware.superiorskyblock.core.menu.MenusManagerImpl.refreshTopIslands(MenusManagerImpl.java:365) ~[?:?]
        at com.bgsoftware.superiorskyblock.island.GridManagerImpl.lambda$sortIslands$19(GridManagerImpl.java:523) ~[?:?]
        at com.bgsoftware.superiorskyblock.island.container.DefaultIslandsContainer.sortIslandsInternal(DefaultIslandsContainer.java:202) ~[?:?]
        at com.bgsoftware.superiorskyblock.island.container.DefaultIslandsContainer.lambda$sortIslands$12(DefaultIslandsContainer.java:160) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Tuinity-91cefbf]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Tuinity-91cefbf]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Tuinity-91cefbf]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

### To Reproduce

Open /is top. It seems the error is random and only when something changes in the menu causing CME

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it still occurs.

**Comment by anhcraft** [comment]
Tested on my server and the issue seems resolved
