### ISSUE TITLE
it doesn't load the world

### ISSUE THREAD

**Issue by Lele289** [BG-Software-LLC/SuperiorSkyblock2#1808]
### Minecraft's Version

1.20.1 purpur.jar

### Plugin's Version

SuperiorSkyblock2-2023.2-b51.jar

### Describe the bug

When I start the server, the plugin gives the following error, only that the name in the level-name is another and the plugin it conflicted with is protocolb, only that everything worked before even if the plugin was inserted, so I don't I understand why.
The error is as follows:

[12:32:20 ERROR]: [SuperiorSkyblock2] An error occurred while preparing worlds:
[12:32:20 ERROR]: [SuperiorSkyblock2] ################################################
[12:32:20 ERROR]: [SuperiorSkyblock2] ##                                            ##
[12:32:20 ERROR]: [SuperiorSkyblock2] ## An error occured while loading the plugin! ##
[12:32:20 ERROR]: [SuperiorSkyblock2] ##                                            ##
[12:32:20 ERROR]: [SuperiorSkyblock2] ################################################
[12:32:20 ERROR]: [SuperiorSkyblock2]
[12:32:20 ERROR]: [SuperiorSkyblock2] java.lang.RuntimeException: The world SuperiorWorld is already loaded. This can occur by one of the following reasons:
[12:32:20 ERROR]: [SuperiorSkyblock2] - Another plugin loaded it manually before SuperiorSkyblock.
[12:32:20 ERROR]: [SuperiorSkyblock2] - Your level-name property in server.properties is set to SuperiorWorld.
[12:32:20 ERROR]: [SuperiorSkyblock2]
[12:32:20 ERROR]: [SuperiorSkyblock2] Stack Trace:
[12:32:20 ERROR]: [SuperiorSkyblock2]   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[12:32:20 ERROR]: [SuperiorSkyblock2]   at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[12:32:20 ERROR]: [SuperiorSkyblock2]   at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[12:32:20 ERROR]: [SuperiorSkyblock2]   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[12:32:20 ERROR]: [SuperiorSkyblock2]   at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:653)
[12:32:20 ERROR]: [SuperiorSkyblock2]   at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:564)
[12:32:20 ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641)
[12:32:20 ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440)
[12:32:20 ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:345)
[12:32:20 ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1117)
[12:32:20 ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[12:32:20 ERROR]: [SuperiorSkyblock2]   at java.base/java.lang.Thread.run(Thread.java:1589)
[12:32:20 ERROR]: [SuperiorSkyblock2] Caused by: java.lang.RuntimeException: The world SuperiorWorld is already loaded. This can occur by one of the following reasons:
[12:32:20 ERROR]: [SuperiorSkyblock2]   at SuperiorSkyblock2-2023.2-b51.jar//com.bgsoftware.superiorskyblock.external.worlds.WorldsProvider_Default.loadWorld(WorldsProvider_Default.java:155)
[12:32:20 ERROR]: [SuperiorSkyblock2]   at SuperiorSkyblock2-2023.2-b51.jar//com.bgsoftware.superiorskyblock.external.worlds.WorldsProvider_Default.prepareWorlds(WorldsProvider_Default.java:36)
[12:32:20 ERROR]: [SuperiorSkyblock2]   at SuperiorSkyblock2-2023.2-b51.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:244)
[12:32:20 ERROR]: [SuperiorSkyblock2]   ... 12 more
[12:32:20 ERROR]: [SuperiorSkyblock2]
[12:32:20 ERROR]: [SuperiorSkyblock2] ################################################

### To Reproduce

start the server with the superior plugin and protocolb and then after a couple of reboots it gave me the following error, so I don't know what happened

### Additional Information

I also used the stable version, but it gave an error with that too.

**Comment by OmerBenGera** [comment]
Disable Paper's plugin loading system and it will work as it should :)
