### ISSUE TITLE
Can't hook into UltimateStacker

### ISSUE THREAD

**Issue by Zampato** [BG-Software-LLC/SuperiorSkyblock2#1819]
### Minecraft's Version

Purpur 1.20.1

### Plugin's Version

V2023.2

### Describe the bug

```
[01:29:21 INFO]: [SuperiorSkyblock2] ProvidersManagerImpl::createInstance ENTER {spawners.SpawnersProvider_UltimateStacker}
[01:29:21 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while creating hook instance:
[01:29:21 WARN]: java.lang.InstantiationException: com.bgsoftware.superiorskyblock.external.spawners.SpawnersProvider_UltimateStacker
[01:29:21 WARN]:        at java.base/java.lang.Class.newInstance(Class.java:639)
[01:29:21 WARN]:        at SuperiorSkyblock2-2023.2 (1).jar//com.bgsoftware.superiorskyblock.external.ProvidersManagerImpl.createInstance(ProvidersManagerImpl.java:614)
[01:29:21 WARN]:        at SuperiorSkyblock2-2023.2 (1).jar//com.bgsoftware.superiorskyblock.external.ProvidersManagerImpl.registerSpawnersProvider(ProvidersManagerImpl.java:455)
[01:29:21 WARN]:        at SuperiorSkyblock2-2023.2 (1).jar//com.bgsoftware.superiorskyblock.external.ProvidersManagerImpl.lambda$loadData$1(ProvidersManagerImpl.java:97)
[01:29:21 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[01:29:21 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[01:29:21 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1128)
[01:29:21 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[01:29:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:29:21 WARN]: Caused by: java.lang.NoSuchMethodException: com.bgsoftware.superiorskyblock.external.spawners.SpawnersProvider_UltimateStacker.<init>()
[01:29:21 WARN]:        at java.base/java.lang.Class.getConstructor0(Class.java:3585)
[01:29:21 WARN]:        at java.base/java.lang.Class.newInstance(Class.java:626)
[01:29:21 WARN]:        ... 8 more
```

Getting this error on startup using latest versions of superiorskyblock and ultimate stacker.

### To Reproduce

1. Setup a purpur 1.20.1 server
2. Install SuperiorSkyblock2 build 2023.2
3. Install UltimateStacker v3.0.0
4. Boot up the server and you will be faced with the error

**Comment by OmerBenGera** [comment]
Fixed with #1826
