### ISSUE TITLE
plugin crash

### ISSUE THREAD

**Issue by jacoobb2137** [BG-Software-LLC/SuperiorSkyblock2#1824]
### Minecraft's Version

1.16.5

### Plugin's Version

latest dev build

### Describe the bug

if a lot of players create an island at one time the plugin crashes

### To Reproduce

if a lot of players create an island at one time the plugin crashes

### Additional Information

[17:48:45] [Server thread/ERROR]: [SuperiorSkyblock2] Task #18654 for SuperiorSkyblock2 v2023.2-b56 generated an exception
[17:48:45] [Server thread/ERROR]: [SuperiorSkyblock2] Suspected Plugins: 
[17:48:45] [Server thread/ERROR]: [SuperiorSkyblock2] 	SuperiorSkyblock2{enabled,ver=2023.2-b56,path=plugins/SuperiorSkyblock2-2023.2-b56.jar}
[17:48:45] [Server thread/ERROR]: [SuperiorSkyblock2] Exception details below: 
java.lang.NullPointerException: null
	at java.util.ArrayDeque.addLast(ArrayDeque.java:303) ~[?:?]
	at java.util.ArrayDeque.forEach(ArrayDeque.java:888) ~[?:?]
	at java.util.ArrayDeque.copyElements(ArrayDeque.java:329) ~[?:?]
	at java.util.ArrayDeque.addAll(ArrayDeque.java:324) ~[?:?]
	at com.bgsoftware.common.executors.WorkerExecutor.stop(WorkerExecutor.java:127) ~[?:?]
	at com.bgsoftware.common.executors.WorkerExecutor.run(WorkerExecutor.java:162) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[clickblock.jar:SSSpigot2-1.16.5-20220406-d88eb08]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:466) ~[clickblock.jar:SSSpigot2-1.16.5-20220406-d88eb08]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1605) ~[clickblock.jar:SSSpigot2-1.16.5-20220406-d88eb08]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:458) ~[clickblock.jar:SSSpigot2-1.16.5-20220406-d88eb08]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1445) ~[clickblock.jar:SSSpigot2-1.16.5-20220406-d88eb08]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[clickblock.jar:SSSpigot2-1.16.5-20220406-d88eb08]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[clickblock.jar:SSSpigot2-1.16.5-20220406-d88eb08]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by OmerBenGera** [comment]
Send me your entire session logs.
Upload it to pastebin and send a link to it here.

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues, let me know
