### ISSUE TITLE
error

### ISSUE THREAD

**Issue by boyssida** [BG-Software-LLC/SuperiorSkyblock2#1844]
### Minecraft's Version

1.19.4 purpur

### Plugin's Version

SuperiorSkyblock2-2023.2-b72.jar

### Describe the bug

every time i start the server it will keep running the plugins without stopping making my server in the state of running the plugins , when i remove the superiorSkyblock2 it works normally

### To Reproduce

[latest_1.log](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/12378127/latest_1.log)
logs

### Additional Information

[14:27:21 ERROR]: [SuperiorSkyblock2] An error occurred while preparing worlds:
[14:27:21 ERROR]: [SuperiorSkyblock2] ################################################
[14:27:21 ERROR]: [SuperiorSkyblock2] ##                                            ##
[14:27:21 ERROR]: [SuperiorSkyblock2] ## An error occured while loading the plugin! ##
[14:27:21 ERROR]: [SuperiorSkyblock2] ##                                            ##
[14:27:21 ERROR]: [SuperiorSkyblock2] ################################################
[14:27:21 ERROR]: [SuperiorSkyblock2]  
[14:27:21 ERROR]: [SuperiorSkyblock2] java.lang.RuntimeException: The world Island is already loaded. This can occur by one of the following reasons:
[14:27:21 ERROR]: [SuperiorSkyblock2] - Another plugin loaded it manually before SuperiorSkyblock.
[14:27:21 ERROR]: [SuperiorSkyblock2] - Your level-name property in server.properties is set to Island.
[14:27:21 ERROR]: [SuperiorSkyblock2]  
[14:27:21 ERROR]: [SuperiorSkyblock2] Stack Trace:
[14:27:21 ERROR]: [SuperiorSkyblock2]   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[14:27:21 ERROR]: [SuperiorSkyblock2]   at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[14:27:21 ERROR]: [SuperiorSkyblock2]   at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[14:27:21 ERROR]: [SuperiorSkyblock2]   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[14:27:21 ERROR]: [SuperiorSkyblock2]   at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:577)
[14:27:21 ERROR]: [SuperiorSkyblock2]   at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:488)
[14:27:21 ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:643)
[14:27:21 ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:442)
[14:27:21 ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:345)
[14:27:21 ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1120)
[14:27:21 ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
[14:27:21 ERROR]: [SuperiorSkyblock2]   at java.base/java.lang.Thread.run(Thread.java:833)
[14:27:21 ERROR]: [SuperiorSkyblock2] Caused by: java.lang.RuntimeException: The world Island is already loaded. This can occur by one of the following reasons:
[14:27:21 ERROR]: [SuperiorSkyblock2]   at SuperiorSkyblock2-2023.2-b72.jar//com.bgsoftware.superiorskyblock.external.worlds.WorldsProvider_Default.loadWorld(WorldsProvider_Default.java:155)
[14:27:21 ERROR]: [SuperiorSkyblock2]   at SuperiorSkyblock2-2023.2-b72.jar//com.bgsoftware.superiorskyblock.external.worlds.WorldsProvider_Default.prepareWorlds(WorldsProvider_Default.java:36)
[14:27:21 ERROR]: [SuperiorSkyblock2]   at SuperiorSkyblock2-2023.2-b72.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:243)
[14:27:21 ERROR]: [SuperiorSkyblock2]   ... 12 more
[14:27:21 ERROR]: [SuperiorSkyblock2]  
[14:27:21 ERROR]: [SuperiorSkyblock2] ################################################

**Comment by OmerBenGera** [comment]
It tells you exactly what the issue is.

```
The world Island is already loaded. This can occur by one of the following reasons:
- Another plugin loaded it manually before SuperiorSkyblock.
- Your level-name property in server.properties is set to Island.
```

Fix it and the server will start up again.

**Comment by boyssida** [comment]
> It tells you exactly what the issue is.
> 
> ```
> The world Island is already loaded. This can occur by one of the following reasons:
> - Another plugin loaded it manually before SuperiorSkyblock.
> - Your level-name property in server.properties is set to Island.
> ```
> 
> Fix it and the server will start up again.

"After I deleted the Island world file configured in SuperiorSkyblock, my server operates normally, and upon restarting, it encounters the same error as above."

**Comment by OmerBenGera** [comment]
I already told you how to fix the issue - find out what loads the world and fix it.
Try narrowing down the issue - test it with only SSB installed, then if it doesnt occur anymore add plugins one by one until you find the problematic plugin.
For further help, ask on the discord server.
