### ISSUE TITLE
server crash when reloading server

### ISSUE THREAD

**Issue by Kewik69** [BG-Software-LLC/SuperiorSkyblock2#1848]
### Minecraft's Version

This server is running CraftBukkit version 3812-Spigot-c62f4bd-504d966 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

### Plugin's Version

SuperiorSkyblock2 version 2023.2-b73

### Describe the bug

when i reload the server it crashes

### To Reproduce

/reload command

### Additional Information

This happens with every plugin version. Both stable and dev. Crash log in console:

[21:02:23] [Server thread/INFO]: [SuperiorSkyblock2] Enabling SuperiorSkyblock2 v2023.2-b73
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] An error occurred while preparing worlds:
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] ################################################
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] ## ##
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] ## An error occured while loading the plugin! ##
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] ## ##
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] ################################################
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] 
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] java.lang.RuntimeException: The world SuperiorWorld is already loaded. This can occur by one of the following reasons:
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] - Another plugin loaded it manually before SuperiorSkyblock.
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] - Your level-name property in server.properties is set to SuperiorWorld.
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] 
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] Stack Trace:
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:540)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:454)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at org.bukkit.craftbukkit.v1_20_R1.CraftServer.reload(CraftServer.java:962)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at org.bukkit.Bukkit.reload(Bukkit.java:832)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:871)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:314)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:298)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1960)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1922)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at net.minecraft.server.TickTask.run(SourceFile:18)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1152)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1131)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1124)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1108)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1019)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at java.base/java.lang.Thread.run(Thread.java:833)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] Caused by: java.lang.RuntimeException: The world SuperiorWorld is already loaded. This can occur by one of the following reasons:
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at com.bgsoftware.superiorskyblock.external.worlds.WorldsProvider_Default.loadWorld(WorldsProvider_Default.java:155)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at com.bgsoftware.superiorskyblock.external.worlds.WorldsProvider_Default.prepareWorlds(WorldsProvider_Default.java:36)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:243)
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] ... 31 more
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] 
[21:02:24] [Server thread/ERROR]: [SuperiorSkyblock2] ################################################

**Comment by OmerBenGera** [comment]
As the error states, the islands world is already loaded when the plugin starts up, and therefore it disabled the server.
Find out what exactly loads the islands world and make sure it doesn't.
