### ISSUE TITLE
Bug when setting hanging signs in another world

### ISSUE THREAD

**Issue by ShopHunter1212** [BG-Software-LLC/SuperiorSkyblock2#1855]
### Minecraft's Version

1.20.1

### Plugin's Version

Version Superiorskyblock 72

### Describe the bug

[00:40:56 ERROR]: Could not pass event BlockBreakEvent to SuperiorSkyblock2 v2023.2-b72
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_20_R1.block.impl.CraftCeilingHangingSign cannot be cast to class org.bukkit.block.data.Directional (org.bukkit.craftbukkit.v1_20_R1.block.impl.CraftCeilingHangingSign and org.bukkit.block.data.Directional are in unnamed module of loader java.net.URLClassLoader @2b71fc7e)
        at com.bgsoftware.superiorskyblock.listener.SignsListener.onSignBreak(SignsListener.java:93) ~[SuperiorSkyblock2-2023.2-b72.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1104.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-117]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-117]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-117]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:378) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:337) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:215) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1915) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-117]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-117]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-117]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-117]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-117]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-117]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-117]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-117]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### To Reproduce

Simply place a hanging sign in a world and then take it down again

**Comment by OmerBenGera** [comment]
What version of Paper are you using?
Send me the exact output of `/version`

**Comment by ShopHunter1212** [comment]
i am using 1.20.1

**Comment by OmerBenGera** [comment]
Send me the exact output of `/version` please.
I need to know the exact version of Spigot you use.

**Comment by ShopHunter1212** [comment]
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/137808935/397298cb-0762-4b33-b8ed-c5f7de43c94a)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
