### ISSUE TITLE
Error when executing /is level

### ISSUE THREAD

**Issue by MatinHQ** [BG-Software-LLC/SuperiorSkyblock2#1867]
### Minecraft's Version

git-Purpur-1985 (MC: 1.19.4)*

### Plugin's Version

SuperiorSkyblock2 version 2023.2-b77

### Describe the bug

It throws error when you use /is level command

### To Reproduce

I am using UltimateStacker version 2.4.3 and if players execute /is level it throws error below

### Additional Information

```[19:13:27 ERROR]: [SuperiorSkyblock2] An unexepcted error occurred while calculating island worth:
[19:13:27 WARN]: java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com/craftaro/ultimatestacker/api/UltimateStackerApi
[19:13:27 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
[19:13:27 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
[19:13:27 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source)
[19:13:27 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
[19:13:27 WARN]:        at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
[19:13:27 WARN]:        at SuperiorSkyblock2-2023.2-b77.jar//com.bgsoftware.superiorskyblock.nms.v1194.NMSChunksImpl.lambda$calculateChunks$12(NMSChunksImpl.java:287)
[19:13:27 WARN]:        at SuperiorSkyblock2-2023.2-b77.jar//com.bgsoftware.superiorskyblock.nms.v1194.NMSUtils.lambda$runActionOnUnloadedChunks$4(NMSUtils.java:153)
[19:13:27 WARN]:        at SuperiorSkyblock2-2023.2-b77.jar//com.bgsoftware.superiorskyblock.core.threads.BukkitExecutor$NestedTask.lambda$null$2(BukkitExecutor.java:181)
[19:13:27 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[19:13:27 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[19:13:27 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1510)
[19:13:27 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:488)
[19:13:27 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424)
[19:13:27 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1195)
[19:13:27 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
[19:13:27 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[19:13:27 WARN]: Caused by: java.lang.NoClassDefFoundError: com/craftaro/ultimatestacker/api/UltimateStackerApi
[19:13:27 WARN]:        at SuperiorSkyblock2-2023.2-b77.jar//com.bgsoftware.superiorskyblock.external.spawners.SpawnersProvider_UltimateStacker3.getSpawner(SpawnersProvider_UltimateStacker3.java:41)
[19:13:27 WARN]:        at SuperiorSkyblock2-2023.2-b77.jar//com.bgsoftware.superiorskyblock.island.algorithm.DefaultIslandCalculationAlgorithm.lambda$null$6(DefaultIslandCalculationAlgorithm.java:91)
[19:13:27 WARN]:        at java.base/java.lang.Iterable.forEach(Unknown Source)
[19:13:27 WARN]:        at SuperiorSkyblock2-2023.2-b77.jar//com.bgsoftware.superiorskyblock.island.algorithm.DefaultIslandCalculationAlgorithm.lambda$null$7(DefaultIslandCalculationAlgorithm.java:81)
[19:13:27 WARN]:        at SuperiorSkyblock2-2023.2-b77.jar//com.bgsoftware.superiorskyblock.core.collections.CompletableFutureList.lambda$forEachCompleted$0(CompletableFutureList.java:23)
[19:13:27 WARN]:        ... 14 more
[19:13:27 WARN]: Caused by: java.lang.ClassNotFoundException: com.craftaro.ultimatestacker.api.UltimateStackerApi
[19:13:27 WARN]:        ... 19 more```

**Comment by OmerBenGera** [comment]
Run `/version UltimateStacker`, what do you get?

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
