### ISSUE TITLE
Restart bug

### ISSUE THREAD

**Issue by ShopHunter1212** [BG-Software-LLC/SuperiorSkyblock2#1873]
### Minecraft's Version

1.20.1

### Plugin's Version

b85

### Describe the bug

[My_Worlds] World creation failed after 0 retries!
java.lang.ExceptionInInitializerError: null
	at com.bgsoftware.superiorskyblock.nms.v1201.generator.IslandsGeneratorImpl$1.getBiomes(IslandsGeneratorImpl.java:49) ~[SuperiorSkyblock2-2023.2-b85.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.generator.CustomWorldChunkManager.b(CustomWorldChunkManager.java:55) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.world.level.biome.BiomeSource.d(BiomeSource.java:29) ~[?:?]
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.1-jre.jar:?]
	at net.minecraft.world.level.biome.BiomeSource.possibleBiomes(BiomeSource.java:40) ~[?:?]
	at net.minecraft.world.level.chunk.ChunkGeneratorStructureState.hasBiomesForStructureSet(ChunkGeneratorStructureState.java:160) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.world.level.chunk.ChunkGeneratorStructureState.lambda$createForNormal$1(ChunkGeneratorStructureState.java:65) ~[paper-1.20.1.jar:git-Paper-117]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraft.world.level.chunk.ChunkGeneratorStructureState.createForNormal(ChunkGeneratorStructureState.java:66) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.world.level.chunk.ChunkGenerator.createState(ChunkGenerator.java:106) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.level.ChunkMap.<init>(ChunkMap.java:324) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.level.ServerChunkCache.<init>(ServerChunkCache.java:179) ~[?:?]
	at net.minecraft.server.level.ServerLevel.<init>(ServerLevel.java:695) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.createWorld(CraftServer.java:1360) ~[paper-1.20.1.jar:git-Paper-117]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:804) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:474) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at com.bergerkiller.bukkit.mw.WorldManager.createWorld(WorldManager.java:374) ~[MyWorlds-1.20.1-v2-242.jar:?]
	at com.bergerkiller.bukkit.mw.WorldManager.createWorld(WorldManager.java:276) ~[MyWorlds-1.20.1-v2-242.jar:?]
	at com.bergerkiller.bukkit.mw.WorldManager.getOrCreateWorld(WorldManager.java:254) ~[MyWorlds-1.20.1-v2-242.jar:?]
	at com.bergerkiller.bukkit.mw.WorldConfig.loadWorld(WorldConfig.java:669) ~[MyWorlds-1.20.1-v2-242.jar:?]
	at com.bergerkiller.bukkit.mw.WorldConfigStore.init(WorldConfigStore.java:183) ~[MyWorlds-1.20.1-v2-242.jar:?]
	at com.bergerkiller.bukkit.mw.MyWorlds.enable(MyWorlds.java:342) ~[MyWorlds-1.20.1-v2-242.jar:?]
	at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:861) ~[BKCommonLib-1.20.1-v2-1595.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-117]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-117]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-117]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-117]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.bgsoftware.superiorskyblock.config.SettingsManagerImpl.getWorlds()" because the return value of "com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.getSettings()" is null
	at com.bgsoftware.superiorskyblock.island.IslandUtils.<clinit>(IslandUtils.java:46) ~[SuperiorSkyblock2-2023.2-b85.jar:?]
	... 41 more

### To Reproduce

[My_Worlds] World creation failed after 0 retries!
java.lang.ExceptionInInitializerError: null
	at com.bgsoftware.superiorskyblock.nms.v1201.generator.IslandsGeneratorImpl$1.getBiomes(IslandsGeneratorImpl.java:49) ~[SuperiorSkyblock2-2023.2-b85.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.generator.CustomWorldChunkManager.b(CustomWorldChunkManager.java:55) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.world.level.biome.BiomeSource.d(BiomeSource.java:29) ~[?:?]
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.1-jre.jar:?]
	at net.minecraft.world.level.biome.BiomeSource.possibleBiomes(BiomeSource.java:40) ~[?:?]
	at net.minecraft.world.level.chunk.ChunkGeneratorStructureState.hasBiomesForStructureSet(ChunkGeneratorStructureState.java:160) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.world.level.chunk.ChunkGeneratorStructureState.lambda$createForNormal$1(ChunkGeneratorStructureState.java:65) ~[paper-1.20.1.jar:git-Paper-117]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraft.world.level.chunk.ChunkGeneratorStructureState.createForNormal(ChunkGeneratorStructureState.java:66) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.world.level.chunk.ChunkGenerator.createState(ChunkGenerator.java:106) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.level.ChunkMap.<init>(ChunkMap.java:324) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.level.ServerChunkCache.<init>(ServerChunkCache.java:179) ~[?:?]
	at net.minecraft.server.level.ServerLevel.<init>(ServerLevel.java:695) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.createWorld(CraftServer.java:1360) ~[paper-1.20.1.jar:git-Paper-117]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:804) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:474) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at com.bergerkiller.bukkit.mw.WorldManager.createWorld(WorldManager.java:374) ~[MyWorlds-1.20.1-v2-242.jar:?]
	at com.bergerkiller.bukkit.mw.WorldManager.createWorld(WorldManager.java:276) ~[MyWorlds-1.20.1-v2-242.jar:?]
	at com.bergerkiller.bukkit.mw.WorldManager.getOrCreateWorld(WorldManager.java:254) ~[MyWorlds-1.20.1-v2-242.jar:?]
	at com.bergerkiller.bukkit.mw.WorldConfig.loadWorld(WorldConfig.java:669) ~[MyWorlds-1.20.1-v2-242.jar:?]
	at com.bergerkiller.bukkit.mw.WorldConfigStore.init(WorldConfigStore.java:183) ~[MyWorlds-1.20.1-v2-242.jar:?]
	at com.bergerkiller.bukkit.mw.MyWorlds.enable(MyWorlds.java:342) ~[MyWorlds-1.20.1-v2-242.jar:?]
	at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:861) ~[BKCommonLib-1.20.1-v2-1595.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-117]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-117]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-117]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-117]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.bgsoftware.superiorskyblock.config.SettingsManagerImpl.getWorlds()" because the return value of "com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.getSettings()" is null
	at com.bgsoftware.superiorskyblock.island.IslandUtils.<clinit>(IslandUtils.java:46) ~[SuperiorSkyblock2-2023.2-b85.jar:?]
	... 41 more

**Comment by ShopHunter1212** [comment]
i cant fix it

**Comment by OmerBenGera** [comment]
I will look into it in the weekend.
Meanwhile, you can remove My_Worlds.

**Comment by OmerBenGera** [comment]
Please upload your entire session logs to pastebin and send a link to it here.
I can't seem to replicate the issue.

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue persists let me know
