### ISSUE TITLE
Executing task exception

### ISSUE THREAD

**Issue by EditChris** [BG-Software-LLC/SuperiorSkyblock2#1906]
### Minecraft's Version

Paper Spigot for 1.20.2, Build 249

### Plugin's Version

2023.3-b107

### Describe the bug

When you try to create, delete, etc an island, you might get this in the console:

`[22:25:03 WARN]: [SuperiorSkyblock2] Plugin SuperiorSkyblock2 v2023.3-b107 generated an exception while executing task 7492
java.lang.NullPointerException: Cannot invoke "org.bukkit.profile.PlayerProfile.getTextures()" because "ownerProfile" is null
        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:148) ~[paper-1.20.2.jar:git-Paper-249]
        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:659) ~[paper-1.20.2.jar:git-Paper-249]
        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:60) ~[paper-1.20.2.jar:git-Paper-249]
        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftInventory.setItem(CraftInventory.java:99) ~[paper-1.20.2.jar:git-Paper-249]
        at com.bgsoftware.superiorskyblock.core.menu.layout.RegularMenuLayoutImpl.populateInventory(RegularMenuLayoutImpl.java:24) ~[SuperiorSkyblock2-2023.3-b107.jar:?]
        at com.bgsoftware.superiorskyblock.core.menu.layout.AbstractMenuLayout.buildInventory(AbstractMenuLayout.java:77) ~[SuperiorSkyblock2-2023.3-b107.jar:?]
        at com.bgsoftware.superiorskyblock.core.menu.AbstractMenu.lambda$buildInventory$2(AbstractMenu.java:79) ~[SuperiorSkyblock2-2023.3-b107.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-249]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.2.jar:git-Paper-249]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

### To Reproduce

Just try to create an island if you don't have it, or try to delete an existing island.

**Comment by OmerBenGera** [comment]
This was an error of Paper and was patched not long time ago.
Update it and it will be fixed :)
