### ISSUE TITLE
EpicSpawners creating hook instance:

### ISSUE THREAD

**Issue by Teaftc** [BG-Software-LLC/SuperiorSkyblock2#1955]
### Minecraft's Version

git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)

### Plugin's Version

SuperiorSkyblock2-2023.3
EpicSpawners-8.0.2

### Describe the bug

EpicSpawners creating hook instance error

### To Reproduce

Run the server

### Additional Information

[03:06:35 INFO]: [SuperiorSkyblock2] ProvidersManagerImpl::createInstance ENTER {spawners.SpawnersProvider_EpicSpawners6}
[03:06:35 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while creating hook instance:
[03:06:35 WARN]: java.lang.reflect.InvocationTargetException
[03:06:35 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[03:06:35 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[03:06:35 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[03:06:35 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[03:06:35 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[03:06:35 WARN]:        at SuperiorSkyblock2-2023.3.jar//com.bgsoftware.superiorskyblock.external.ProvidersManagerImpl.createInstance(ProvidersManagerImpl.java:629)
[03:06:35 WARN]:        at SuperiorSkyblock2-2023.3.jar//com.bgsoftware.superiorskyblock.external.ProvidersManagerImpl.registerSpawnersProvider(ProvidersManagerImpl.java:465)
[03:06:35 WARN]:        at SuperiorSkyblock2-2023.3.jar//com.bgsoftware.superiorskyblock.external.ProvidersManagerImpl.lambda$loadData$1(ProvidersManagerImpl.java:107)
[03:06:35 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1111)
[03:06:35 WARN]: Caused by: java.lang.NoClassDefFoundError: com/songoda/epicspawners/EpicSpawners
[03:06:35 WARN]:        at SuperiorSkyblock2-2023.3.jar//com.bgsoftware.superiorskyblock.external.spawners.SpawnersProvider_EpicSpawners6.<init>(SpawnersProvider_EpicSpawners6.java:31)
[03:06:35 WARN]:        ... 13 more
[03:06:35 WARN]: Caused by: java.lang.ClassNotFoundException: com.songoda.epicspawners.EpicSpawners
[03:06:35 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183)
[03:06:35 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[03:06:35 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[03:06:35 WARN]:        ... 14 more

**Comment by OmerBenGera** [comment]
Seems like EpicSpawners 8 broke their API.
Let me know what your discord is so I can open a ticket for you, as I need a copy of the new jar to add support for it.

**Comment by Teaftc** [comment]
> 看起来 EpicSpawners 8 破坏了他们的 API。 让我知道您的不和谐是什么，以便我可以为您开一张票，因为我需要新 jar 的副本来添加对其的支持。

teaftc_69439

**Comment by OmerBenGera** [comment]
Added in latest dev build
