### ISSUE TITLE
SuperiorSkyblock2 SlimeworldManager Startup Error

### ISSUE THREAD

**Issue by Davisiiiik** [BG-Software-LLC/SuperiorSkyblock2#1959]
### Minecraft's Version

This server is running SlimeWorldManager version git-SlimeWorldManager-15541 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: a596d6b on HEAD) (https://github.com/InfernalSuite/AdvancedSlimePaper)

### Plugin's Version

AdvancedSlimeWorldManager 2.10.0 - build 15541 (Git: a596d6b on HEAD)
SuperiorSkyblock 2023.3-b121
SSBSlimeWorldManager-2023.1-b7

### Describe the bug

This error is shown in console crash, which results in a server crash:

```yml
[19:00:32] [Server thread/INFO]: [SuperiorSkyblock2] Enabling the module SlimeWorldIslands...
[19:00:32] [Server thread/ERROR]: [SuperiorSkyblock2] An unexpected error occurred while disabling the module SlimeWorldIslands.
[19:00:32] [Server thread/ERROR]: [SuperiorSkyblock2] Contact Ome_R regarding this, this has nothing to do with the plugin.
[19:00:32] [Server thread/WARN]: java.lang.RuntimeException: SlimeWorldManager must be installed in order to use this module.
[19:00:32] [Server thread/WARN]: 	at com.bgsoftware.ssbslimeworldmanager.SlimeWorldModule.onEnable(SlimeWorldModule.java:42)
[19:00:32] [Server thread/WARN]: 	at SuperiorSkyblock2-2023.3-b121.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModule(ModulesManagerImpl.java:134)
[19:00:32] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[19:00:32] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[19:00:32] [Server thread/WARN]: 	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
[19:00:32] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[19:00:32] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[19:00:32] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[19:00:32] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[19:00:32] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[19:00:32] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[19:00:32] [Server thread/WARN]: 	at SuperiorSkyblock2-2023.3-b121.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModulesInternal(ModulesManagerImpl.java:188)
[19:00:32] [Server thread/WARN]: 	at SuperiorSkyblock2-2023.3-b121.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.runModuleLifecycle(ModulesManagerImpl.java:179)
[19:00:32] [Server thread/WARN]: 	at SuperiorSkyblock2-2023.3-b121.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:218)
[19:00:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[19:00:32] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190)
[19:00:32] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[19:00:32] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[19:00:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646)
[19:00:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557)
[19:00:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:642)
[19:00:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424)
[19:00:32] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[19:00:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[19:00:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[19:00:32] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
[19:00:32] [Server thread/INFO]: [SuperiorSkyblock2] Disabling the module SlimeWorldIslands...
[19:00:32] [Server thread/ERROR]: [SuperiorSkyblock2] An unexpected error occurred while disabling the module SlimeWorldIslands.
[19:00:32] [Server thread/ERROR]: [SuperiorSkyblock2] Contact Ome_R regarding this, this has nothing to do with the plugin.
[19:00:32] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "com.bgsoftware.ssbslimeworldmanager.swm.ISlimeAdapter.getSavedWorlds()" because "this.slimeAdapter" is null
[19:00:32] [Server thread/WARN]: 	at com.bgsoftware.ssbslimeworldmanager.SlimeWorldModule.onDisable(SlimeWorldModule.java:66)
[19:00:32] [Server thread/WARN]: 	at SuperiorSkyblock2-2023.3-b121.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.unregisterModule(ModulesManagerImpl.java:92)
[19:00:32] [Server thread/WARN]: 	at SuperiorSkyblock2-2023.3-b121.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModule(ModulesManagerImpl.java:141)
[19:00:32] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[19:00:32] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[19:00:32] [Server thread/WARN]: 	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
[19:00:32] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[19:00:32] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[19:00:32] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[19:00:32] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[19:00:32] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[19:00:32] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[19:00:32] [Server thread/WARN]: 	at SuperiorSkyblock2-2023.3-b121.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModulesInternal(ModulesManagerImpl.java:188)
[19:00:32] [Server thread/WARN]: 	at SuperiorSkyblock2-2023.3-b121.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.runModuleLifecycle(ModulesManagerImpl.java:179)
[19:00:32] [Server thread/WARN]: 	at SuperiorSkyblock2-2023.3-b121.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:218)
[19:00:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[19:00:32] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190)
[19:00:32] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[19:00:32] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[19:00:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646)
[19:00:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557)
[19:00:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:642)
[19:00:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424)
[19:00:32] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[19:00:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[19:00:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[19:00:32] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
```

### To Reproduce

Install ASWM (both AS-Paper as server file and ASWM plugin)
Install SuperiorSkyblock version 2023.3-b101 or older
Error will be shown in the console

### Additional Information

This issue is already described in SSB-SlimeWorldManager repository as issue [#33](https://github.com/BG-Software-LLC/SSB-SlimeWorldManager/issues/33).
However this issue is not on the SlimeWorldManager module side, as it occured for the first time after commit [#1894](https://github.com/BG-Software-LLC/SuperiorSkyblock2/commit/c0d3f5201d1bdc9cfab1f97c41877ab97265cf3e) (Version 2023.3-b101)

**Comment by OmerBenGera** [comment]
Why do you have both AdvancedSlimeWorldManager as well as AdvancedSlimePaper installed?

**Comment by OmerBenGera** [comment]
> Because ASWM plugin is dependant on ASPaper, you need to have both to get it work properly, it doesn't work otherwise.
> 
> Just to be extra sure, I tested it now. It doesn't work, if you implement only one of them.

Don't AdvancedSlimePaper has their own plugin? Why do you need AdvancedSlimeWorldManager?

**Comment by Davisiiiik** [comment]
Yes, I am using this. I installed that refering to their installation guide [here](https://github.com/InfernalSuite/AdvancedSlimePaper/blob/main/.docs/usage/install.md).
