### ISSUE TITLE
Unable to load Slime Worlds Plugin as Module

### ISSUE THREAD

**Issue by JanReich** [BG-Software-LLC/SuperiorSkyblock2#1967]
### Minecraft's Version

v1_19_R3

### Plugin's Version

2023.3

### Describe the bug

Unable to Load the SlimeWorlds Module

We want to convert our big Skyblock world to multiple little Skyblock worlds but we cannot load the SlimeWorld module for SuperiorSkyblock there is an error while starting the server.

### To Reproduce

Drag Plugin into modules Folder

### Additional Information

[20:20:26 INFO]: [SuperiorSkyblock2] Enabling SuperiorSkyblock2 v2023.3
[20:20:26 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while registering module slimeworldmanager-plugin-2.2.1.jar:
[20:20:26 WARN]: java.lang.RuntimeException: An error occurred while reading slimeworldmanager-plugin-2.2.1.jar
[20:20:26 WARN]: 	at SuperiorSkyblock2-2023.3.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.registerModule(ModulesManagerImpl.java:69)
[20:20:26 WARN]: 	at SuperiorSkyblock2-2023.3.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.registerExternalModules(ModulesManagerImpl.java:208)
[20:20:26 WARN]: 	at SuperiorSkyblock2-2023.3.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.loadData(ModulesManagerImpl.java:50)
[20:20:26 WARN]: 	at SuperiorSkyblock2-2023.3.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:218)
[20:20:26 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[20:20:26 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[20:20:26 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[20:20:26 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[20:20:26 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563)
[20:20:26 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474)
[20:20:26 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)[20:20:26 WARN]: 
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)	
[20:20:26 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[20:20:26 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1104)
[20:20:26 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[20:20:26 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:20:26 WARN]: Caused by: java.lang.IllegalAccessError: class com.google.common.collect.AbstractMapBasedMultiset$1$1 cannot access its abstract superclass com.google.common.collect.Multisets$AbstractEntry (com.google.common.collect.AbstractMapBasedMultiset$1$1 is in unnamed module of loader 'slimeworldmanager-plugin-2.2.1.jar' @3896d053; com.google.common.collect.Multisets$AbstractEntry is in unnamed module of loader java.net.URLClassLoader @25f38edc)
[20:20:26 WARN]: 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[20:20:26 WARN]: 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
[20:20:26 WARN]: 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[20:20:26 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:229)
[20:20:26 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
[20:20:26 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155)
[20:20:26 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:130)
[20:20:26 WARN]: 	at io.papermc.paper.plugin.entrypoint.classloader.group.SpigotPluginClassLoaderGroup.lookupClass(SpigotPluginClassLoaderGroup.java:43)
[20:20:26 WARN]: 	at io.papermc.paper.plugin.entrypoint.classloader.group.SimpleListPluginClassLoaderGroup.getClassByName(SimpleListPluginClassLoaderGroup.java:37)
[20:20:26 WARN]: 	at io.papermc.paper.plugin.entrypoint.classloader.group.LockingClassLoaderGroup.getClassByName(LockingClassLoaderGroup.java:34)
[20:20:26 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:173)
[20:20:26 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[20:20:26 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:579)
[20:20:26 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:579)
[20:20:26 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[20:20:26 WARN]: 	at SuperiorSkyblock2-2023.3.jar//com.bgsoftware.superiorskyblock.core.io.JarFiles.getClass(JarFiles.java:30)
[20:20:26 WARN]: 	at SuperiorSkyblock2-2023.3.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.registerModule(ModulesManagerImpl.java:66)
[20:20:26 WARN]: 	... 15 more
[20:20:26 INFO]: [SuperiorSkyblock2] Enabling the module SlimeWorldIslands...
[20:20:26 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while disabling the module SlimeWorldIslands.
[20:20:26 ERROR]: [SuperiorSkyblock2] Contact Ome_R regarding this, this has nothing to do with the plugin.
[20:20:26 WARN]: java.lang.RuntimeException: SlimeWorldManager must be installed in order to use this module.
[20:20:26 WARN]: 	at SSBSlimeWorldManager-2023.1.jar//com.bgsoftware.ssbslimeworldmanager.SlimeWorldModule.onEnable(SlimeWorldModule.java:42)
[20:20:26 WARN]: 	at SuperiorSkyblock2-2023.3.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModule(ModulesManagerImpl.java:134)
[20:20:26 WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[20:20:26 WARN]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[20:20:26 WARN]: 	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
[20:20:26 WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[20:20:26 WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[20:20:26 WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[20:20:26 WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[20:20:26 WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[20:20:26 WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[20:20:26 WARN]: 	at SuperiorSkyblock2-2023.3.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModules(ModulesManagerImpl.java:173)
[20:20:26 WARN]: 	at SuperiorSkyblock2-2023.3.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:224)
[20:20:26 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[20:20:26 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[20:20:26 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[20:20:26 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[20:20:26 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563)
[20:20:26 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474)
[20:20:26 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
[20:20:26 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[20:20:26 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[20:20:26 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1104)
[20:20:26 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[20:20:26 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:20:26 INFO]: [SuperiorSkyblock2] Disabling the module SlimeWorldIslands...
[20:20:26 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while disabling the module SlimeWorldIslands.
[20:20:26 ERROR]: [SuperiorSkyblock2] Contact Ome_R regarding this, this has nothing to do with the plugin.
[20:20:26 WARN]: java.lang.NullPointerException: Cannot invoke "com.bgsoftware.ssbslimeworldmanager.swm.ISlimeAdapter.getSavedWorlds()" because "this.slimeAdapter" is null
[20:20:26 WARN]: 	at SSBSlimeWorldManager-2023.1.jar//com.bgsoftware.ssbslimeworldmanager.SlimeWorldModule.onDisable(SlimeWorldModule.java:66)
[20:20:26 WARN]: 	at SuperiorSkyblock2-2023.3.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.unregisterModule(ModulesManagerImpl.java:92)
[20:20:26 WARN]: 	at SuperiorSkyblock2-2023.3.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModule(ModulesManagerImpl.java:141)
[20:20:26 WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[20:20:26 WARN]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[20:20:26 WARN]: 	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
[20:20:26 WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[20:20:26 WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[20:20:26 WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[20:20:26 WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[20:20:26 WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[20:20:26 WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[20:20:26 WARN]: 	at SuperiorSkyblock2-2023.3.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModules(ModulesManagerImpl.java:173)
[20:20:26 WARN]: 	at SuperiorSkyblock2-2023.3.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:224)
[20:20:26 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[20:20:26 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[20:20:26 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[20:20:26 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[20:20:26 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563)
[20:20:26 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474)
[20:20:26 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
[20:20:26 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[20:20:26 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[20:20:26 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1104)
[20:20:26 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[20:20:26 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:20:27 INFO]: Preparing start region for dimension minecraft:superiorworld
[20:20:27 INFO]: Time elapsed: 894 ms
[20:20:27 INFO]: [SuperiorSkyblock2] Enabling the module bank...

**Comment by Davisiiiik** [comment]
Hello @JanReich,
It looks lik you didn't install SlimeWorlds properly.

You need to:
1. [Download](https://bg-software.com/superiorskyblock/ssbslimeworlds/) and place SSB-SlimeWorlds module into the `../plugins/SuperiorSkyblock2/modules` folder
2. Download and place AdvancedSlimeWorldsManager (ASWM) plugin into the `../plugins` folder
3. Download and use AdvancedSlimePaper (ASPaper) as minecraft_server.jar (instead of paper in server root folder)

Both plugin and server files from points 1. and 2. can be downloaded from [Infernal Suite Discord server](https://discord.com/channels/741733106930810950/1168669543632228433). You dont need to use ASPaper, they provide ASPufferfish and ASPurpur as well.

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/79375965/625ca60c-e2c9-42d5-a51d-73c1ef34302c)


But there is a catch. There is a unresolved issue #1959, where your ASWM won't on SuperiorSkyblock version 2023.3-b101 and newer, but if you are using latest stable version, you should be fine.

Hope that helps!

**Comment by OmerBenGera** [comment]
You tried to put a proper plugin as a module of the plugin.
The modules folder should be used only for modules specifically coded for SuperiorSkyblock and not regular plugins.
Also, follow @Davisiiiik 's tutorial.
