### ISSUE TITLE
NPE | ArrayDeque.addLast | IS MEMBERS

### ISSUE THREAD

**Issue by DxrkCat** [BG-Software-LLC/SuperiorSkyblock2#1970]
### Minecraft's Version

ver
[09:37:14 INFO]: Checking version, please wait...
[09:37:14 INFO]: Current: git-Purpur-2095 (MC: 1.20.2)*
* You are running the latest version

### Plugin's Version

ver Superior
[09:37:03 INFO]: SuperiorSkyblock2 version 2023.3
[09:37:03 INFO]: Feature packed Skyblock core.
[09:37:03 INFO]: Website: https://bg-software.com/
[09:37:03 INFO]: Author: Ome_R
​
124 build

### Describe the bug

The error occurs when the player wrote /is members
Before that, I also tested WorldEdit instead of FAWE.

### To Reproduce

idk /is members

### Additional Information

```
[09:10:49] [Server thread/WARN]: [SuperiorSkyblock2] Task #607199 for SuperiorSkyblock2 v2023.3 generated an exception
java.lang.NullPointerException: null
	at java.util.ArrayDeque.addLast(ArrayDeque.java:302) ~[?:?]
	at java.util.ArrayDeque.forEach(ArrayDeque.java:887) ~[?:?]
	at java.util.ArrayDeque.copyElements(ArrayDeque.java:328) ~[?:?]
	at java.util.ArrayDeque.addAll(ArrayDeque.java:323) ~[?:?]
	at com.bgsoftware.common.executors.WorkerExecutor.stop(WorkerExecutor.java:127) ~[SuperiorSkyblock2-2023.3.jar:?]
	at com.bgsoftware.common.executors.WorkerExecutor.run(WorkerExecutor.java:162) ~[SuperiorSkyblock2-2023.3.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1497) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by OmerBenGera** [comment]
Update to latest dev build
If the issue occurs again, let me know

For now, closing this
