### ISSUE TITLE
NashornEngine automatic installation error

### ISSUE THREAD

**Issue by anhcraft** [BG-Software-LLC/SuperiorSkyblock2#2005]
### Minecraft's Version

git-Tuinity-91cefbf (MC: 1.16.5)

### Plugin's Version

latest dev build

### Describe the bug

Error when the plugin installs NashornEngine
```
[05:28:45] [Server thread/INFO]: [SuperiorSkyblock2] Seems like you are missing a nashorn engine. Attempting to download one remotely...
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2] An unexpected error occurred while downloading nashorn engine:
[05:28:46] [Server thread/WARN]: java.io.FileNotFoundException: https://hub.bg-software.com/job/SuperiorSkyblock%20Addons/job/NashornEngine/lastSuccessfulBuild/api/json
[05:28:46] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1996)
[05:28:46] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[05:28:46] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[05:28:46] [Server thread/WARN]: 	at com.bgsoftware.superiorskyblock.core.engine.NashornEngineDownloader.readJenkinsJsonAPI(NashornEngineDownloader.java:64)
[05:28:46] [Server thread/WARN]: 	at com.bgsoftware.superiorskyblock.core.engine.NashornEngineDownloader.downloadEngine(NashornEngineDownloader.java:30)
[05:28:46] [Server thread/WARN]: 	at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.checkScriptEngine(SuperiorSkyblockPlugin.java:473)
[05:28:46] [Server thread/WARN]: 	at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:498)
[05:28:46] [Server thread/WARN]: 	at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:233)
[05:28:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[05:28:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[05:28:46] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[05:28:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[05:28:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[05:28:46] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:600)
[05:28:46] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:299)
[05:28:46] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1076)
[05:28:46] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292)
[05:28:46] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2] ################################################
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2] ##                                            ##
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2] ## An error occured while loading the plugin! ##
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2] ##                                            ##
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2] ################################################
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2]  
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2] It seems like the script engine of the plugin is corrupted.
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2] This may occur by one of the following reasons:
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2] 1. You have a module/plugin that sets a custom script that doesn't work well.
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2] 2. You're using Java 16 without installing an external module engine.
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2] If that's the case, check out the following link:
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2] https://github.com/BG-Software-LLC/SuperiorSkyblock2-NashornEngine
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2]  
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2] Stack Trace:
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2] 	at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:233)
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2] 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2] 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2] 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2] 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:600)
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2] 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:299)
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2] 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1076)
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2] 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292)
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2] 	at java.base/java.lang.Thread.run(Thread.java:840)
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2]  
[05:28:46] [Server thread/ERROR]: [SuperiorSkyblock2] ################################################
```

this works: https://hub.bg-software.com/job/SuperiorSkyblock2%20-%20NashornEngine%20Module%20-%20Dev%20Builds/lastSuccessfulBuild/

### To Reproduce

install the plugin

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by anhcraft** [comment]
> Check out latest dev build, let me know if it is fixed

yep it works well
