### ISSUE TITLE
Custom menus not working

### ISSUE THREAD

**Issue by ElBananaa** [BG-Software-LLC/SuperiorSkyblock2#201]
**Minecraft's Version**:
```
This server is running Purpur version git-Purpur-1051 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Purpur-1050 (MC: 1.16.5)
```

**Plugin's Version**:
SuperiorSkyblock2-b112.jar

**Describe the bug**
Basically, the custom menu feature doesn't work at all. I tried to make a custom menu, then restarted the server to make sure it gets registered correctly, but it doesn't work at all, and I get this error on startup : 
<details>
<summary>The startup error</summary>

```
[02:16:59] [Server thread/WARN]: com.bgsoftware.superiorskyblock.utils.exceptions.HandlerLoadException: java.lang.NullPointerException
[02:16:59] [Server thread/WARN]: 	at com.bgsoftware.superiorskyblock.handlers.MenusHandler.loadData(MenusHandler.java:88)
[02:16:59] [Server thread/WARN]: 	at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:390)
[02:16:59] [Server thread/WARN]: 	at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:174)
[02:16:59] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[02:16:59] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[02:16:59] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[02:16:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[02:16:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[02:16:59] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:582)
[02:16:59] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:292)
[02:16:59] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1061)
[02:16:59] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[02:16:59] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)
[02:16:59] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[02:16:59] [Server thread/WARN]: 	at com.bgsoftware.superiorskyblock.menu.SuperiorMenuCustom.createMenu(SuperiorMenuCustom.java:56)
[02:16:59] [Server thread/WARN]: 	at com.bgsoftware.superiorskyblock.handlers.MenusHandler.loadData(MenusHandler.java:86)
[02:16:59] [Server thread/WARN]: 	... 12 more
```
</details>

**To Reproduce**
Just try to create a custom menu using the plugin.
Just in case, here's my menu : https://paste.gg/p/anonymous/374ff8a5abcf4116a4be80d562d4462c

**Comment by OmerBenGera** [comment]
The issue is because of how you configured your command section.
I also found an issue in the wiki describing how to make them, I will fix it as well.
You need to have a section called "command" with the aliases, permission, etc (they are not different sections).
Therefore, this will fix the issue:
```
command:
    aliases: 'weather,wmenu,weathermenu'
    permission: 'weather.management'
```

**Comment by ElBananaa** [comment]
> The issue is because of how you configured your command section.
> I also found an issue in the wiki describing how to make them, I will fix it as well.
> You need to have a section called "command" with the aliases, permission, etc (they are not different sections).
> Therefore, this will fix the issue:
> 
> ```
> command:
>     aliases: 'weather,wmenu,weathermenu'
>     permission: 'weather.management'
> ```

Amazing, thanks!
I just tried and it works. You made a mistake tho. Using `aliases: 'weather,wmenu,weathermenu'` will only create one command:
`/is weather,wmenu,weathermenu`
It must be `aliases: 'weather, wmenu, weathermenu'` in order to create the right commands. :)
