### ISSUE TITLE
Material GRASS is renamed in minecraft Enum to SHORT_GRASS

### ISSUE THREAD

**Issue by JanReich** [BG-Software-LLC/SuperiorSkyblock2#2020]
### Minecraft's Version

1.20.4

### Plugin's Version

2023.3

### Describe the bug

Error While loading the plugin. The Skychest from play is skipped during loading, because the material GRASS no longer exists. Solution ->When server version is > 1.20 than rename the material GRASS to SHORT_GRASS in database. 

### To Reproduce

- Put in an older Version Gras inside the Skychest
- Upgrade the Server to 1.20.4
- Start the server

### Additional Information

[17:25:09 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while loading data from database:
[17:25:09 WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.GRASS
[17:25:09 WARN]: 	at java.base/java.lang.Enum.valueOf(Enum.java:273)
[17:25:09 WARN]: 	at org.bukkit.Material.valueOf(Material.java:124)
[17:25:09 WARN]: 	at SuperiorSkyblock2-2023.3-b148.jar//com.bgsoftware.superiorskyblock.core.serialization.impl.ItemStack2TagSerializer.deserialize(ItemStack2TagSerializer.java:53)
[17:25:09 WARN]: 	at SuperiorSkyblock2-2023.3-b148.jar//com.bgsoftware.superiorskyblock.core.serialization.impl.ItemStack2TagSerializer.deserialize(ItemStack2TagSerializer.java:18)
[17:25:09 WARN]: 	at SuperiorSkyblock2-2023.3-b148.jar//com.bgsoftware.superiorskyblock.core.serialization.impl.InventorySerializer.deserialize(InventorySerializer.java:122)
[17:25:09 WARN]: 	at SuperiorSkyblock2-2023.3-b148.jar//com.bgsoftware.superiorskyblock.core.serialization.impl.InventorySerializer.deserialize(InventorySerializer.java:107)
[17:25:09 WARN]: 	at SuperiorSkyblock2-2023.3-b148.jar//com.bgsoftware.superiorskyblock.core.serialization.impl.InventorySerializer.deserialize(InventorySerializer.java:96)
[17:25:09 WARN]: 	at SuperiorSkyblock2-2023.3-b148.jar//com.bgsoftware.superiorskyblock.core.serialization.impl.InventorySerializer.deserialize(InventorySerializer.java:24)
[17:25:09 WARN]: 	at java.base/java.util.Optional.map(Optional.java:260)
[17:25:09 WARN]: 	[17:25:09 WARN]: 	at SuperiorSkyblock2-2023.3-b148.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLDatabaseBridge.lambda$loadAllObjects$1(SQLDatabaseBridge.java:43)
at SuperiorSkyblock2-2023.3-b148.jar//com.bgsoftware.superiorskyblock.core.database.serialization.IslandsDeserializer.lambda$deserializeIslandChest$24(IslandsDeserializer.java:642)
[17:25:09 WARN]: 	at SuperiorSkyblock2-2023.3-b148.jar//com.bgsoftware.superiorskyblock.core.database.sql.session.QueryResult.complete(QueryResult.java:35)
[17:25:09 WARN]: 	at SuperiorSkyblock2-2023.3-b148.jar//com.bgsoftware.superiorskyblock.core.database.sql.session.impl.SQLiteSession.executeQuery(SQLiteSession.java:197)
[17:25:09 WARN]: 	at SuperiorSkyblock2-2023.3-b148.jar//com.bgsoftware.superiorskyblock.core.database.sql.session.impl.SQLiteSession.select(SQLiteSession.java:151)
[17:25:09 WARN]: 	at SuperiorSkyblock2-2023.3-b148.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLHelper.select(SQLHelper.java:75)
[17:25:09 WARN]: 	at SuperiorSkyblock2-2023.3-b148.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLDatabaseBridge.loadAllObjects(SQLDatabaseBridge.java:40)
[17:25:09 WARN]: 	at SuperiorSkyblock2-2023.3-b148.jar//com.bgsoftware.superiorskyblock.core.database.serialization.IslandsDeserializer.deserializeIslandChest(IslandsDeserializer.java:627)
[17:25:09 WARN]: 	at SuperiorSkyblock2-2023.3-b148.jar//com.bgsoftware.superiorskyblock.core.database.DataManager.loadIslands(DataManager.java:177)
[17:25:09 WARN]: 	at SuperiorSkyblock2-2023.3-b148.jar//com.bgsoftware.superiorskyblock.core.database.DataManager.loadData(DataManager.java:57)
[17:25:09 WARN]: 	at SuperiorSkyblock2-2023.3-b148.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:477)
[17:25:09 WARN]: 	at SuperiorSkyblock2-2023.3-b148.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:230)
[17:25:09 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[17:25:09 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188)
[17:25:09 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[17:25:09 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[17:25:09 WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639)
[17:25:09 WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550)
[17:25:09 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671)
[17:25:09 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
[17:25:09 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:309)
[17:25:09 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1131)
[17:25:09 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[17:25:09 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works now

**Comment by JanReich** [comment]
Works perfectly fine. You can close this issue.
