### ISSUE TITLE
Error when reloading : The world SuperiorWorld is already loaded. This can occur by one of the following reasons:

### ISSUE THREAD

**Issue by bronzzze** [BG-Software-LLC/SuperiorSkyblock2#2021]
### Minecraft's Version

1.20.4-R0.1-SNAPSHOT

### Plugin's Version

2023.3

### Describe the bug

[11:17:00] [Server thread/INFO]: [SuperiorSkyblock2] Enabling SuperiorSkyblock2 v2023.3
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2] An error occurred while preparing worlds:
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2] ################################################
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2] ##                                            ##
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2] ## An error occured while loading the plugin! ##
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2] ##                                            ##
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2] ################################################
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2]
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2] java.lang.RuntimeException: The world SuperiorWorld is already loaded. This can occur by one of the following reasons:
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2] - Another plugin loaded it manually before SuperiorSkyblock.
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2] - Your level-name property in server.properties is set to SuperiorWorld.
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2]
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2] Stack Trace:
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2]   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2]   at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2]   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2]   at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:548)
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2]   at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:462)
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2]   at org.bukkit.craftbukkit.v1_20_R2.CraftServer.reload(CraftServer.java:970)
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2]   at org.bukkit.Bukkit.reload(Bukkit.java:834)
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2]   at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27)
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2]   at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:879)
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2]   at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchServerCommand(CraftServer.java:864)
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:412)
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388)
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1179)
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:996)
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298)
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2]   at java.base/java.lang.Thread.run(Thread.java:833)
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2] Caused by: java.lang.RuntimeException: The world SuperiorWorld is already loaded. This can occur by one of the following reasons:
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2] - Your level-name property in server.properties is set to SuperiorWorld.
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2]   at com.bgsoftware.superiorskyblock.external.worlds.WorldsProvider_Default.loadWorld(WorldsProvider_Default.java:164)
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2]   at com.bgsoftware.superiorskyblock.external.worlds.WorldsProvider_Default.prepareWorlds(WorldsProvider_Default.java:45)
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2]   at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:227)
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2]   ... 17 more
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2]
[11:17:00] [Server thread/ERROR]: [SuperiorSkyblock2] ################################################

### To Reproduce

Reload server

**Comment by OmerBenGera** [comment]
Dont reload, not supported.
