### ISSUE TITLE
BlocksMissions BlockBreakEvent Error

### ISSUE THREAD

**Issue by HarunOrhan** [BG-Software-LLC/SuperiorSkyblock2#2024]
### Minecraft's Version

1.16.5

### Plugin's Version

2023.3-b148

### Describe the bug

When I type "/is admin reload" the server console gives me the following errors. 
Also the tasks are working but the placeholder is not counting correctly in the breaking tasks.

For example, he needs to break 100 blocks, when I look at how many blocks he broke, it shows 70, but he actually broke 99. If he breaks 1 more he gets the reward. so the placeholder is not counting correctly.

```
[15:29:15] [Server thread/ERROR]: Could not pass event BlockBreakEvent to SuperiorSkyblock2 v2023.3-b148
java.lang.NullPointerException: Cannot invoke "java.util.function.Predicate.test(Object)" because "this.isBarrelCheck" is null
    at com.bgsoftware.superiorskyblock.missions.BlocksMissions.handleBlockBreak(BlocksMissions.java:366) ~[?:?]
    at com.bgsoftware.superiorskyblock.missions.BlocksMissions.onBlockBreak(BlocksMissions.java:282) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2724.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1171]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1171]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1171]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1171]
    at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:392) ~[patched_1.16.5.jar:git-Purpur-1171]
    at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:345) ~[patched_1.16.5.jar:git-Purpur-1171]
    at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:305) ~[patched_1.16.5.jar:git-Purpur-1171]
    at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1779) ~[patched_1.16.5.jar:git-Purpur-1171]
    at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.5.jar:git-Purpur-1171]
    at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.5.jar:git-Purpur-1171]
    at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-
```

### To Reproduce

"/is admin reload"

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue still occurs let me know
