### ISSUE TITLE
[maybe Not a bug]Cannot be used in Mohist(A bukkit x forge server)Because there is no Timings class

### ISSUE THREAD

**Issue by Alirea10** [BG-Software-LLC/SuperiorSkyblock2#2025]
### Minecraft's Version

This server is running Mohist version 1.20.1-604 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT, Forge version 47.2.20, NeoForge version 47.1.79)
https://mohistmc.com/

### Plugin's Version

Latest stable build：SuperiorSkyblock2-2023.3
and
Dev Builds：SuperiorSkyblock2-2023.3-b155

### Describe the bug

Please take a look at this
https://github.com/MohistMC/Mohist/issues/2994

logs：
```
[16:09:04 INFO]: [SuperiorSkyblock2] Enabling the module bank...
[16:09:04 INFO]: [SuperiorSkyblock2] Finished enabling the module bank (Took 7ms)
[16:09:04 INFO]: [SuperiorSkyblock2] Enabling the module missions...
[16:09:04 INFO]: [SuperiorSkyblock2] Registered mission miner_1
[16:09:04 INFO]: [SuperiorSkyblock2] Registered mission miner_2
[16:09:04 INFO]: [SuperiorSkyblock2] Registered mission miner_3
[16:09:04 INFO]: [SuperiorSkyblock2] Registered mission miner_4
[16:09:04 INFO]: [SuperiorSkyblock2] Registered mission miner_5
[16:09:05 INFO]: [SuperiorSkyblock2] Registered mission slayer_1
[16:09:05 INFO]: [SuperiorSkyblock2] Registered mission slayer_2
[16:09:05 INFO]: [SuperiorSkyblock2] Registered mission slayer_3
[16:09:05 INFO]: [SuperiorSkyblock2] Registered mission slayer_4
[16:09:05 INFO]: [SuperiorSkyblock2] Registered mission farmer_1
[16:09:05 INFO]: [SuperiorSkyblock2] Registered mission farmer_2
[16:09:05 INFO]: [SuperiorSkyblock2] Registered mission farmer_3
[16:09:05 INFO]: [SuperiorSkyblock2] Registered mission farmer_4
[16:09:05 INFO]: [SuperiorSkyblock2] Registered mission farmer_5
[16:09:05 INFO]: [SuperiorSkyblock2] Registered mission fisherman_1
[16:09:05 INFO]: [SuperiorSkyblock2] Registered mission fisherman_2
[16:09:05 INFO]: [SuperiorSkyblock2] Registered mission fisherman_3
[16:09:05 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while enabling the plugin:
[16:09:05 WARN]: java.lang.NoClassDefFoundError: org/spigotmc/CustomTimingsHandler
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.missions.island.timings.LegacyTimingsWrapper.<init>(LegacyTimingsWrapper.java:10)
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.missions.island.timings.ITimings.of(ITimings.java:15)
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.missions.IslandMissions.registerEventListener(IslandMissions.java:100)
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.missions.IslandMissions.load(IslandMissions.java:52)
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.mission.MissionsManagerImpl.loadMission(MissionsManagerImpl.java:476)
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.module.missions.MissionsModule.canLoadCategory(MissionsModule.java:222)
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.module.missions.MissionsModule.onEnable(MissionsModule.java:121)
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.module.BuiltinModule.onEnable(BuiltinModule.java:24)
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModule(ModulesManagerImpl.java:134)
[16:09:05 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[16:09:05 WARN]:        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[16:09:05 WARN]:        at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
[16:09:05 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[16:09:05 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[16:09:05 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[16:09:05 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[16:09:05 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[16:09:05 WARN]:        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModules(ModulesManagerImpl.java:173)
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:509)
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:237)
[16:09:05 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:347)
[16:09:05 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
[16:09:05 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482)
[16:09:05 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:549)
[16:09:05 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:462)
[16:09:05 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:441)
[16:09:05 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:341)
[16:09:05 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:224)
[16:09:05 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:850)
[16:09:05 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281)
[16:09:05 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[16:09:05 WARN]: Caused by: java.lang.ClassNotFoundException: org.spigotmc.CustomTimingsHandler
[16:09:05 WARN]:        at TRANSFORMER/forge@47.2.20/com.mohistmc.bukkit.remapping.RemappingURLClassLoader.findClass(RemappingURLClassLoader.java:98)
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.core.io.FileClassLoader.findClass(FileClassLoader.java:94)
[16:09:05 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[16:09:05 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[16:09:05 WARN]:        ... 32 more
```

Mohist has completely removed Timings and related class，So SSB2 cannot run on Mohist。
Is ssb2 intended to be compatible with mohist?Perhaps it is possible to not use related class in Mohist。If you do not intend to be compatible with mohist, you can close the issue.very thank！

I use translation software. If there is any offense, please forgive me

### To Reproduce

Load this plugin in Mosit，Do not use any other plugins or mods

**Comment by OmerBenGera** [comment]
Mohist is not supported.
Only Spigot forks are.
