### ISSUE TITLE
[SuperiorSkyblock2] An unexpected error occurred while enabling the plugin: java.lang.NoClassDefFoundError: org/spigotmc/CustomTimingsHandler

### ISSUE THREAD

**Issue by packetlose** [BG-Software-LLC/SuperiorSkyblock2#2029]
### Minecraft's Version

1.20.4 | leaf-1.20.4.jar

### Plugin's Version

#155 dev build

### Describe the bug

[23:32:02] [Server thread/ERROR]: [SuperiorSkyblock2] An unexpected error occurred while enabling the plugin:
[23:32:02] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/spigotmc/CustomTimingsHandler
[23:32:02] [Server thread/WARN]: 	at com.bgsoftware.superiorskyblock.missions.island.timings.LegacyTimingsWrapper.<init>(LegacyTimingsWrapper.java:10)
[23:32:02] [Server thread/WARN]: 	at com.bgsoftware.superiorskyblock.missions.island.timings.ITimings.of(ITimings.java:15)
[23:32:02] [Server thread/WARN]: 	at com.bgsoftware.superiorskyblock.missions.IslandMissions.registerEventListener(IslandMissions.java:105)
[23:32:02] [Server thread/WARN]: 	at com.bgsoftware.superiorskyblock.missions.IslandMissions.load(IslandMissions.java:53)
[23:32:02] [Server thread/WARN]: 	at SuperiorSkyblock2-2023.3-b155.jar//com.bgsoftware.superiorskyblock.mission.MissionsManagerImpl.loadMission(MissionsManagerImpl.java:510)
[23:32:02] [Server thread/WARN]: 	at SuperiorSkyblock2-2023.3-b155.jar//com.bgsoftware.superiorskyblock.module.missions.MissionsModule.canLoadCategory(MissionsModule.java:234)
[23:32:02] [Server thread/WARN]: 	at SuperiorSkyblock2-2023.3-b155.jar//com.bgsoftware.superiorskyblock.module.missions.MissionsModule.loadMissionCategories(MissionsModule.java:177)
[23:32:02] [Server thread/WARN]: 	at SuperiorSkyblock2-2023.3-b155.jar//com.bgsoftware.superiorskyblock.module.missions.MissionsModule.onEnable(MissionsModule.java:108)
[23:32:02] [Server thread/WARN]: 	at SuperiorSkyblock2-2023.3-b155.jar//com.bgsoftware.superiorskyblock.module.BuiltinModule.onEnable(BuiltinModule.java:24)
[23:32:02] [Server thread/WARN]: 	at SuperiorSkyblock2-2023.3-b155.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModule(ModulesManagerImpl.java:134)
[23:32:02] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[23:32:02] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[23:32:02] [Server thread/WARN]: 	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
[23:32:02] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[23:32:02] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[23:32:02] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[23:32:02] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[23:32:02] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[23:32:02] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[23:32:02] [Server thread/WARN]: 	at SuperiorSkyblock2-2023.3-b155.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModulesInternal(ModulesManagerImpl.java:188)
[23:32:02] [Server thread/WARN]: 	at SuperiorSkyblock2-2023.3-b155.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.runModuleLifecycle(ModulesManagerImpl.java:179)
[23:32:02] [Server thread/WARN]: 	at SuperiorSkyblock2-2023.3-b155.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:227)
[23:32:02] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[23:32:02] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188)
[23:32:02] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[23:32:02] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:506)
[23:32:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:657)
[23:32:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:568)
[23:32:02] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:657)
[23:32:02] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:417)
[23:32:02] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:353)
[23:32:02] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1136)
[23:32:02] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:306)
[23:32:02] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
[23:32:02] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.spigotmc.CustomTimingsHandler
[23:32:02] [Server thread/WARN]: 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
[23:32:02] [Server thread/WARN]: 	at SuperiorSkyblock2-2023.3-b155.jar//com.bgsoftware.superiorskyblock.core.io.FileClassLoader.findClass(FileClassLoader.java:95)
[23:32:02] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
[23:32:02] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[23:32:02] [Server thread/WARN]: 	... 34 more

### To Reproduce

I started it, got an error, and the server stopped working..

**Comment by OmerBenGera** [comment]
I dont know what leaf spigot is.
Does it work with regular Paper?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build
If the issue still occurs, let me know
