### ISSUE TITLE
[SuperiorSkyblock2] Task #109060081 for SuperiorSkyblock2 v2023.3-b134 generated an exception

### ISSUE THREAD

**Issue by GamersOr** [BG-Software-LLC/SuperiorSkyblock2#2045]
### Minecraft's Version

Purpur 1.20.4

### Plugin's Version

2023.3-b134

### Describe the bug

[17:32:47 WARN]: [SuperiorSkyblock2] Task #109060081 for SuperiorSkyblock2 v2023.3-b134 generated an exception
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "blockEntityTickers" is null
        at com.bgsoftware.superiorskyblock.nms.v1_20_3.NMSWorldImpl.listenSpawner(NMSWorldImpl.java:105) ~[SuperiorSkyblock2-2023.3-b134.jar:?]
        at com.bgsoftware.superiorskyblock.module.upgrades.type.UpgradeTypeSpawnerRates$SpawnerRatesListener.lambda$null$2(UpgradeTypeSpawnerRates.java:92) ~[SuperiorSkyblock2-2023.3-b134.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at com.bgsoftware.superiorskyblock.module.upgrades.type.UpgradeTypeSpawnerRates$SpawnerRatesListener.lambda$handleIslandChunkLoad$3(UpgradeTypeSpawnerRates.java:91) ~[SuperiorSkyblock2-2023.3-b134.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2153]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.4.jar:git-Purpur-2153]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1669) ~[purpur-1.20.4.jar:git-Purpur-2153]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2153]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1548) ~[purpur-1.20.4.jar:git-Purpur-2153]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[purpur-1.20.4.jar:git-Purpur-2153]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2153]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[17:32:47 WARN]: [SuperiorSkyblock2] Task #109060149 for SuperiorSkyblock2 v2023.3-b134 generated an exception
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "blockEntityTickers" is null
        at com.bgsoftware.superiorskyblock.nms.v1_20_3.NMSWorldImpl.listenSpawner(NMSWorldImpl.java:105) ~[SuperiorSkyblock2-2023.3-b134.jar:?]
        at com.bgsoftware.superiorskyblock.module.upgrades.type.UpgradeTypeSpawnerRates$SpawnerRatesListener.lambda$null$2(UpgradeTypeSpawnerRates.java:92) ~[SuperiorSkyblock2-2023.3-b134.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at com.bgsoftware.superiorskyblock.module.upgrades.type.UpgradeTypeSpawnerRates$SpawnerRatesListener.lambda$handleIslandChunkLoad$3(UpgradeTypeSpawnerRates.java:91) ~[SuperiorSkyblock2-2023.3-b134.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2153]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.4.jar:git-Purpur-2153]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1669) ~[purpur-1.20.4.jar:git-Purpur-2153]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2153]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1548) ~[purpur-1.20.4.jar:git-Purpur-2153]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[purpur-1.20.4.jar:git-Purpur-2153]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2153]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

### To Reproduce

I dont know the players do something and its spaming the console

**Comment by OmerBenGera** [comment]
Update to latest dev build, already been fixed
