### ISSUE TITLE
plugin doesn'tt work

### ISSUE THREAD

**Issue by AndreiOriginal** [BG-Software-LLC/SuperiorSkyblock2#2047]
### Minecraft's Version

1.20.2

### Plugin's Version

[superiorskyblock2.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/14892747/superiorskyblock2.zip)

### Describe the bug

EVERY SINGLE TIME I TRY TO BOOT MY SERVER IT LOOK LIKE THIS!
[07:52:44 ERROR]: Couldn't parse element predicates:thewii:immersive/biome/on_swamp - Not a json array: {"condition":"minecraft:alternative","terms":[{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:swamp"}},{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:mangrove_swamp"}}]}
[07:52:44 ERROR]: Couldn't parse element predicates:thewii:immersive/biome/on_snowy - Not a json array: {"condition":"minecraft:alternative","terms":[{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:snowy_beach"}},{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:snowy_plains"}},{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:snowy_slopes"}},{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:snowy_taiga"}}]}
[07:52:44 ERROR]: Couldn't parse element predicates:thewii:immersive/is_outside - Not a json array: {"condition":"minecraft:inverted","term":{"condition":"minecraft:alternative","terms":[{"condition":"minecraft:inverted","term":{"condition":"minecraft:location_check","offsetY":1,"predicate":{"block":{"tag":"thewii:immersive/masked"}}}},{"condition":"minecraft:inverted","term":{"condition":"minecraft:location_check","offsetY":2,"predicate":{"block":{"tag":"thewii:immersive/masked"}}}},{"condition":"minecraft:inverted","term":{"condition":"minecraft:location_check","offsetY":3,"predicate":{"block":{"tag":"thewii:immersive/masked"}}}},{"condition":"minecraft:inverted","term":{"condition":"minecraft:location_check","offsetY":4,"predicate":{"block":{"tag":"thewii:immersive/masked"}}}},{"condition":"minecraft:inverted","term":{"condition":"minecraft:location_check","offsetY":5,"predicate":{"block":{"tag":"thewii:immersive/masked"}}}},{"condition":"minecraft:inverted","term":{"condition":"minecraft:location_check","offsetY":6,"predicate":{"block":{"tag":"thewii:immersive/masked"}}}},{"condition":"minecraft:inverted","term":{"condition":"minecraft:location_check","offsetY":7,"predicate":{"block":{"tag":"thewii:immersive/masked"}}}},{"condition":"minecraft:inverted","term":{"condition":"minecraft:location_check","offsetY":8,"predicate":{"block":{"tag":"thewii:immersive/masked"}}}},{"condition":"minecraft:inverted","term":{"condition":"minecraft:location_check","offsetY":9,"predicate":{"block":{"tag":"thewii:immersive/masked"}}}},{"condition":"minecraft:inverted","term":{"condition":"minecraft:location_check","offsetY":10,"predicate":{"block":{"tag":"thewii:immersive/masked"}}}},{"condition":"minecraft:inverted","term":{"condition":"minecraft:location_check","offsetY":11,"predicate":{"block":{"tag":"thewii:immersive/masked"}}}},{"condition":"minecraft:inverted","term":{"condition":"minecraft:location_check","offsetY":12,"predicate":{"block":{"tag":"thewii:immersive/masked"}}}},{"condition":"minecraft:inverted","term":{"condition":"minecraft:location_check","offsetY":13,"predicate":{"block":{"tag":"thewii:immersive/masked"}}}},{"condition":"minecraft:inverted","term":{"condition":"minecraft:location_check","offsetY":14,"predicate":{"block":{"tag":"thewii:immersive/masked"}}}},{"condition":"minecraft:inverted","term":{"condition":"minecraft:location_check","offsetY":15,"predicate":{"block":{"tag":"thewii:immersive/masked"}}}},{"condition":"minecraft:inverted","term":{"condition":"minecraft:location_check","offsetY":16,"predicate":{"block":{"tag":"thewii:immersive/masked"}}}},{"condition":"minecraft:inverted","term":{"condition":"minecraft:location_check","offsetY":17,"predicate":{"block":{"tag":"thewii:immersive/masked"}}}},{"condition":"minecraft:inverted","term":{"condition":"minecraft:location_check","offsetY":18,"predicate":{"block":{"tag":"thewii:immersive/masked"}}}},{"condition":"minecraft:inverted","term":{"condition":"minecraft:location_check","offsetY":19,"predicate":{"block":{"tag":"thewii:immersive/masked"}}}},{"condition":"minecraft:inverted","term":{"condition":"minecraft:location_check","offsetY":20,"predicate":{"block":{"tag":"thewii:immersive/masked"}}}}]}}
[07:52:44 ERROR]: Couldn't parse element predicates:thewii:immersive/biome/on_forest - Not a json array: {"condition":"minecraft:alternative","terms":[{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:forest"}},{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:birch_forest"}},{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:dark_forest"}},{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:flower_forest"}},{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:old_growth_birch_forest"}},{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:windswept_forest"}},{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:plains"}},{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:sunflower_plains"}}]}
[07:52:44 ERROR]: Couldn't parse element predicates:thewii:immersive/biome/on_jungle - Not a json array: {"condition":"minecraft:alternative","terms":[{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:jungle"}},{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:bamboo_jungle"}},{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:sparse_jungle"}}]}
[07:52:44 ERROR]: Couldn't parse element predicates:thewii:immersive/biome/on_end - Not a json array: {"condition":"minecraft:alternative","terms":[{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:end_barrens"}},{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:end_highlands"}},{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:end_midlands"}},{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:small_end_islands"}},{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:the_end"}},{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:the_void"}}]}
[07:52:44 ERROR]: Couldn't parse element predicates:thewii:immersive/biome/on_desert - Not a json array: {"condition":"minecraft:alternative","terms":[{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:desert"}},{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:savanna"}},{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:savanna_plateau"}},{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:windswept_savanna"}},{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:badlands"}},{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:eroded_badlands"}},{"condition":"minecraft:location_check","predicate":{"biome":"minecraft:wooded_badlands"}}]}
[07:52:44 INFO]: Loaded 1174 recipes
[07:52:45 INFO]: Loaded 1271 advancements
[07:52:45 INFO]: Starting minecraft server version 1.20.2
[07:52:45 INFO]: Loading properties
[07:52:45 INFO]: This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
[07:52:45 INFO]: Server Ping Player Sample Count: 12
[07:52:45 INFO]: Using 4 threads for Netty based IO
[07:52:46 WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[07:52:46 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 4 worker threads, and gen parallelism of 4 threads
[07:52:46 INFO]: Default game type: SURVIVAL
[07:52:46 INFO]: Generating keypair
[07:52:46 INFO]: Starting Minecraft server on 0.0.0.0:27414
[07:52:46 INFO]: Using epoll channel type
[07:52:46 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[07:52:46 INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.
[07:52:46 INFO]: [SpigotLibraryLoader] [SuperiorSkyblock2] Loading 1 libraries... please wait
[07:52:46 INFO]: [SpigotLibraryLoader] [SuperiorSkyblock2] Loaded library /home/container/libraries/org/openjdk/nashorn/nashorn-core/15.4/nashorn-core-15.4.jar
[07:52:46 INFO]: [SpigotLibraryLoader] [SuperiorSkyblock2] Loaded library /home/container/libraries/org/ow2/asm/asm/7.3.1/asm-7.3.1.jar
[07:52:46 INFO]: [SpigotLibraryLoader] [SuperiorSkyblock2] Loaded library /home/container/libraries/org/ow2/asm/asm-commons/7.3.1/asm-commons-7.3.1.jar
[07:52:46 INFO]: [SpigotLibraryLoader] [SuperiorSkyblock2] Loaded library /home/container/libraries/org/ow2/asm/asm-analysis/7.3.1/asm-analysis-7.3.1.jar
[07:52:46 INFO]: [SpigotLibraryLoader] [SuperiorSkyblock2] Loaded library /home/container/libraries/org/ow2/asm/asm-tree/7.3.1/asm-tree-7.3.1.jar
[07:52:46 INFO]: [SpigotLibraryLoader] [SuperiorSkyblock2] Loaded library /home/container/libraries/org/ow2/asm/asm-util/7.3.1/asm-util-7.3.1.jar
[07:52:50 INFO]: [Essentials] Loading server plugin Essentials v2.21.0-dev+76-71ca7ff
[07:52:50 INFO]: [SetSpawn] Loading server plugin SetSpawn v4.8
[07:52:50 INFO]: [EssentialsChat] Loading server plugin EssentialsChat v2.21.0-dev+76-71ca7ff
[07:52:50 INFO]: [SuperiorSkyblock2] Loading server plugin SuperiorSkyblock2 v2023.3
[07:52:51 INFO]: Server permissions file permissions.yml is empty, ignoring it
[07:52:51 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[07:52:51 WARN]: The server will make no attempt to authenticate usernames. Beware.
[07:52:51 WARN]: Whilst this makes it possible to use BungeeCord, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.
[07:52:51 WARN]: Please see http://www.spigotmc.org/wiki/firewall-guide/ for further information.
[07:52:51 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[07:52:51 INFO]: Preparing level "world"
[07:52:51 INFO]: Preparing start region for dimension minecraft:overworld
[07:52:51 INFO]: Time elapsed: 167 ms
[07:52:51 INFO]: [Essentials] Enabling Essentials v2.21.0-dev+76-71ca7ff
[07:52:52 ERROR]: [Essentials] You are running an unsupported server version!
[07:52:52 INFO]: [Essentials] Attempting to convert old kits in config.yml to new kits.yml
[07:52:52 INFO]: [Essentials] No kits found to migrate.
[07:52:52 INFO]: [Essentials] Starting Essentials ban format conversion
[07:52:52 INFO]: [Essentials] Attempting to migrate ignore list to UUIDs
[07:52:52 INFO]: [Essentials] Attempting to migrate legacy userdata keys to Configurate
[07:52:52 INFO]: [Essentials] Loaded 39095 items from items.json.
[07:52:52 INFO]: [Essentials] Using locale en_US
[07:52:52 INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[07:52:52 INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[07:52:52 INFO]: [Essentials] Using superperms-based permissions.
[07:52:52 INFO]: [SetSpawn] Enabling SetSpawn v4.8
[07:52:52 INFO]: [SetSpawn] Enabled!
[07:52:52 INFO]: [EssentialsChat] Enabling EssentialsChat v2.21.0-dev+76-71ca7ff
[07:52:53 INFO]: [EssentialsChat] Starting Metrics. Opt-out using the global bStats config.
[07:52:53 INFO]: [SuperiorSkyblock2] Enabling SuperiorSkyblock2 v2023.3
[07:52:53 INFO]: Preparing start region for dimension minecraft:superiorworld
[07:52:53 WARN]: java.lang.RuntimeException: Server attempted to load chunk saved with newer version of minecraft! 3700 > 3578
[07:52:53 WARN]:        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:149)
[07:52:53 WARN]:        at io.papermc.paper.chunk.system.scheduling.ChunkLoadTask$ChunkDataLoadTask.runOffMain(ChunkLoadTask.java:338)
[07:52:53 WARN]:        at io.papermc.paper.chunk.system.scheduling.GenericDataLoadTask$ProcessOffMainTask.run(GenericDataLoadTask.java:307)
[07:52:53 WARN]:        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351)
[07:52:53 WARN]:        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118)
[07:52:53 WARN]:        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool$PrioritisedThread.pollTasks(PrioritisedThreadPool.java:274)
[07:52:53 WARN]:        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:62)
[07:52:53 WARN]: java.lang.RuntimeException: Server attempted to load chunk saved with newer version of minecraft! 3700 > 3578
[07:52:53 WARN]:        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:149)
[07:52:53 WARN]:        at io.papermc.paper.chunk.system.scheduling.ChunkLoadTask$ChunkDataLoadTask.runOffMain(ChunkLoadTask.java:338)
[07:52:53 WARN]:        at io.papermc.paper.chunk.system.scheduling.GenericDataLoadTask$ProcessOffMainTask.run(GenericDataLoadTask.java:307)
[07:52:53 WARN]:        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351)
[07:52:53 WARN]:        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118)
[07:52:53 WARN]:        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool$PrioritisedThread.pollTasks(PrioritisedThreadPool.java:274)
[07:52:53 WARN]:        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:62)
[07:52:53 WARN]: java.lang.RuntimeException: Server attempted to load chunk saved with newer version of minecraft! 3700 > 3578
[07:52:53 WARN]:        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:149)
[07:52:53 WARN]:        at io.papermc.paper.chunk.system.scheduling.ChunkLoadTask$ChunkDataLoadTask.runOffMain(ChunkLoadTask.java:338)
[07:52:53 WARN]:        at io.papermc.paper.chunk.system.scheduling.GenericDataLoadTask$ProcessOffMainTask.run(GenericDataLoadTask.java:307)
[07:52:53 WARN]:        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351)
[07:52:53 WARN]:        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118)
[07:52:53 WARN]:        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool$PrioritisedThread.pollTasks(PrioritisedThreadPool.java:274)
[07:52:53 WARN]:        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:62)
[07:52:53 ERROR]: [SuperiorSkyblock2] Detected crash. SuperiorSkyblock will attempt to save data...
[07:52:53 WARN]: java.lang.RuntimeException: Server attempted to load chunk saved with newer version of minecraft! 3700 > 3578
[07:52:53 WARN]:        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:149)
[07:52:53 WARN]:        at io.papermc.paper.chunk.system.scheduling.ChunkLoadTask$ChunkDataLoadTask.runOffMain(ChunkLoadTask.java:338)
[07:52:53 WARN]:        at io.papermc.paper.chunk.system.scheduling.GenericDataLoadTask$ProcessOffMainTask.run(GenericDataLoadTask.java:307)
[07:52:53 WARN]:        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351)
[07:52:53 WARN]:        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118)
[07:52:53 WARN]:        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool$PrioritisedThread.pollTasks(PrioritisedThreadPool.java:274)
[07:52:53 WARN]:        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:50)
[07:52:53 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while saving database:
[07:52:53 WARN]: java.lang.NullPointerException: Cannot invoke "com.bgsoftware.superiorskyblock.api.data.DatabaseBridge.getDatabaseBridgeMode()" because "databaseBridge" is null
[07:52:53 WARN]:        at SuperiorSkyblock2-2023.3 (1).jar//com.bgsoftware.superiorskyblock.core.database.bridge.GridDatabaseBridge.runOperationIfRunning(GridDatabaseBridge.java:40)
[07:52:53 WARN]:        at SuperiorSkyblock2-2023.3 (1).jar//com.bgsoftware.superiorskyblock.core.database.bridge.GridDatabaseBridge.deleteGrid(GridDatabaseBridge.java:35)
[07:52:53 WARN]:        at SuperiorSkyblock2-2023.3 (1).jar//com.bgsoftware.superiorskyblock.core.database.DataManager.saveDatabase(DataManager.java:87)
[07:52:53 WARN]:        at SuperiorSkyblock2-2023.3 (1).jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onDisable(SuperiorSkyblockPlugin.java:317)
[07:52:53 WARN]:        at SuperiorSkyblock2-2023.3 (1).jar//com.bgsoftware.superiorskyblock.core.task.ShutdownTask.run(ShutdownTask.java:18)
[07:52:53 WARN]: [SuperiorSkyblock2] Trying to cancel all island previews asynchronous. Stack trace:
[07:52:53 WARN]: java.lang.Exception
[07:52:53 WARN]:        at SuperiorSkyblock2-2023.3 (1).jar//com.bgsoftware.superiorskyblock.island.GridManagerImpl.cancelAllIslandPreviewsSync(GridManagerImpl.java:376)
[07:52:53 WARN]:        at SuperiorSkyblock2-2023.3 (1).jar//com.bgsoftware.superiorskyblock.core.threads.BukkitExecutor.sync(BukkitExecutor.java:53)
[07:52:53 WARN]:        at SuperiorSkyblock2-2023.3 (1).jar//com.bgsoftware.superiorskyblock.core.threads.BukkitExecutor.sync(BukkitExecutor.java:45)
[07:52:53 WARN]:        at SuperiorSkyblock2-2023.3 (1).jar//com.bgsoftware.superiorskyblock.island.GridManagerImpl.cancelAllIslandPreviews(GridManagerImpl.java:367)
[07:52:53 WARN]:        at SuperiorSkyblock2-2023.3 (1).jar//com.bgsoftware.superiorskyblock.island.GridManagerImpl.disablePlugin(GridManagerImpl.java:774)
[07:52:53 WARN]:        at SuperiorSkyblock2-2023.3 (1).jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onDisable(SuperiorSkyblockPlugin.java:319)
[07:52:53 WARN]:        at SuperiorSkyblock2-2023.3 (1).jar//com.bgsoftware.superiorskyblock.core.task.ShutdownTask.run(ShutdownTask.java:18)
[07:52:53 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while disabling the plugin:
[07:52:53 WARN]: java.lang.NullPointerException: Cannot invoke "com.bgsoftware.superiorskyblock.api.data.DatabaseBridge.getDatabaseBridgeMode()" because "databaseBridge" is null
[07:52:53 WARN]:        at SuperiorSkyblock2-2023.3 (1).jar//com.bgsoftware.superiorskyblock.core.database.bridge.StackedBlocksDatabaseBridge.runOperationIfRunning(StackedBlocksDatabaseBridge.java:41)
[07:52:53 WARN]:        at SuperiorSkyblock2-2023.3 (1).jar//com.bgsoftware.superiorskyblock.core.database.bridge.StackedBlocksDatabaseBridge.deleteStackedBlocks(StackedBlocksDatabaseBridge.java:32)
[07:52:53 WARN]:        at SuperiorSkyblock2-2023.3 (1).jar//com.bgsoftware.superiorskyblock.core.stackedblocks.StackedBlocksManagerImpl.saveStackedBlocks(StackedBlocksManagerImpl.java:258)
[07:52:53 WARN]:        at SuperiorSkyblock2-2023.3 (1).jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onDisable(SuperiorSkyblockPlugin.java:326)
[07:52:53 WARN]:        at SuperiorSkyblock2-2023.3 (1).jar//com.bgsoftware.superiorskyblock.core.task.ShutdownTask.run(ShutdownTask.java:18)
[07:52:53 INFO]: [SuperiorSkyblock2] Shutting down calculation task...
[07:52:53 INFO]: [SuperiorSkyblock2] Shutting down executor
[07:52:53 INFO]: [SuperiorSkyblock2] Shutting down database executor
[07:52:53 INFO]: [SuperiorSkyblock2] Closing database. This may hang the server. Do not shut it down, or data may get lost.
[07:52:53 INFO]: Time elapsed: 393 ms
[07:52:53 INFO]: [SuperiorSkyblock2] Enabling the module bank...
[07:52:53 INFO]: [SuperiorSkyblock2] Finished enabling the module bank (Took 6ms)
[07:52:53 INFO]: [SuperiorSkyblock2] Enabling the module missions...
[07:52:53 INFO]: [SuperiorSkyblock2] Registered mission miner_1
[07:52:53 INFO]: [SuperiorSkyblock2] Registered mission miner_2
[07:52:53 INFO]: [SuperiorSkyblock2] Registered mission miner_5
[07:52:53 INFO]: [SuperiorSkyblock2] Registered mission miner_3
[07:52:54 INFO]: [SuperiorSkyblock2] Registered mission miner_4
[07:52:54 INFO]: [SuperiorSkyblock2] Registered mission slayer_2
[07:52:54 INFO]: [SuperiorSkyblock2] Registered mission slayer_4
[07:52:54 INFO]: [SuperiorSkyblock2] Registered mission slayer_1
[07:52:54 INFO]: [SuperiorSkyblock2] Registered mission slayer_3
[07:52:54 INFO]: [SuperiorSkyblock2] Registered mission farmer_2
[07:52:54 INFO]: [SuperiorSkyblock2] Registered mission farmer_3
[07:52:54 INFO]: [SuperiorSkyblock2] Registered mission farmer_5
[07:52:54 INFO]: [SuperiorSkyblock2] Registered mission farmer_4
[07:52:54 INFO]: [SuperiorSkyblock2] Registered mission farmer_1
[07:52:54 INFO]: [SuperiorSkyblock2] Registered mission fisherman_1
[07:52:54 INFO]: [SuperiorSkyblock2] Registered mission fisherman_3
[07:52:54 INFO]: [SuperiorSkyblock2] Registered mission fisherman_2
[07:52:54 WARN]: Plugin 'SuperiorSkyblock2' is creating timing 'Plugin: SuperiorSkyblock2 v2023.3 Event: DynamicRegisteredListener::IslandSchematicPasteEvent(IslandSchematicPasteEvent)' - this is deprecated behavior, please report it to the authors: Ome_R
[07:52:54 INFO]: [SuperiorSkyblock2] Registered mission explorer_2
[07:52:54 WARN]: Plugin 'SuperiorSkyblock2' is creating timing 'Plugin: SuperiorSkyblock2 v2023.3 Event: DynamicRegisteredListener::IslandSchematicPasteEvent(IslandSchematicPasteEvent)' - this is deprecated behavior, please report it to the authors: Ome_R
[07:52:54 INFO]: [SuperiorSkyblock2] Registered mission explorer_1
[07:52:54 INFO]: [SuperiorSkyblock2] Finished enabling the module missions (Took 471ms)
[07:52:54 INFO]: [SuperiorSkyblock2] Enabling the module generators...
[07:52:54 INFO]: [SuperiorSkyblock2] Finished enabling the module generators (Took 5ms)
[07:52:54 INFO]: [SuperiorSkyblock2] Enabling the module upgrades...
[07:52:54 INFO]: [SuperiorSkyblock2] Finished enabling the module upgrades (Took 12ms)
[07:52:54 INFO]: Stopping main thread (Ignore any thread death message you see! - DO NOT REPORT THREAD DEATH TO PAPER)
[07:52:54 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while enabling the plugin:
[07:52:54 WARN]: java.lang.AssertionError: Failed generating bytecode for <eval>:-1
[07:52:54 WARN]:        at org.openjdk.nashorn.internal.codegen.CompilationPhase$BytecodeGenerationPhase.transform(CompilationPhase.java:437)
[07:52:54 WARN]:        at org.openjdk.nashorn.internal.codegen.CompilationPhase.apply(CompilationPhase.java:614)
[07:52:54 WARN]:        at org.openjdk.nashorn.internal.codegen.Compiler.compile(Compiler.java:641)
2024-04-06 07:52:54,407 Server thread WARN org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging SimpleMessage: An exception occurred processing Appender Async java.lang.ThreadDeath
        at java.base/java.lang.Thread.stop(Thread.java:949)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:913)
        at net.minecraft.server.dedicated.DedicatedServer.t(DedicatedServer.java:820)
        at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:885)
        at org.bukkit.craftbukkit.v1_20_R2.util.ServerShutdownThread.run(ServerShutdownThread.java:27)
2024-04-06 07:52:54,408 Server thread WARN org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging ReusableSimpleMessage: Error occurred while enabling SuperiorSkyblock2 v2023.3 (Is it up to date?) java.lang.ThreadDeath
        at java.base/java.lang.Thread.stop(Thread.java:949)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:913)
        at net.minecraft.server.dedicated.DedicatedServer.t(DedicatedServer.java:820)
        at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:885)
        at org.bukkit.craftbukkit.v1_20_R2.util.ServerShutdownThread.run(ServerShutdownThread.java:27)
[07:52:54 INFO]: [SuperiorSkyblock2] Disabling SuperiorSkyblock2 v2023.3
[07:52:54 ERROR]: Error occurred (in the plugin loader) while enabling SuperiorSkyblock2 v2023.3 (Is it up to date?)
java.lang.ThreadDeath: null
        at java.lang.Thread.stop(Thread.java:949) ~[?:?]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:913) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:820) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:885) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.util.ServerShutdownThread.run(ServerShutdownThread.java:27) ~[paper-1.20.2.jar:git-Paper-318]
[07:52:54 ERROR]: Main thread terminated by WatchDog due to hard crash
java.lang.ThreadDeath: null
        at java.lang.Thread.stop(Thread.java:949) ~[?:?]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:913) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:820) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:885) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.util.ServerShutdownThread.run(ServerShutdownThread.java:27) ~[paper-1.20.2.jar:git-Paper-318]
[07:52:54 INFO]: Stopping server
[07:52:54 INFO]: [EssentialsChat] Disabling EssentialsChat v2.21.0-dev+76-71ca7ff
[07:52:54 INFO]: [SetSpawn] Disabling SetSpawn v4.8
[07:52:54 INFO]: [SetSpawn] Disabled!
[07:52:54 INFO]: [Essentials] Disabling Essentials v2.21.0-dev+76-71ca7ff
[07:52:54 INFO]: Saving players
[07:52:54 WARN]: Asynchronous Save Players! Blocking thread until it returns 
java.lang.IllegalStateException: null
        at io.papermc.paper.util.MCUtil.ensureMain(MCUtil.java:365) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.players.PlayerList.saveAll(PlayerList.java:1234) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.players.PlayerList.saveAll(PlayerList.java:1230) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:938) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:820) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:885) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.util.ServerShutdownThread.run(ServerShutdownThread.java:27) ~[paper-1.20.2.jar:git-Paper-318]

### To Reproduce

i put the plugin in plugins folder and boot server that's all and the error are masive

### Additional Information

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/127543173/37773487-14c1-4d3a-8447-b3b01b5c468b)

**Comment by OmerBenGera** [comment]
Your SuperiorWorld was loaded by a newer version of the game, then you went bqck to your current version.
You can either go back to the newer version, or reset the world.

Anyways, nothing to do with the plugin
