### ISSUE TITLE
SUPERIOR IN NEW VERSION RECEIVE ERROR

### ISSUE THREAD

**Issue by AffonsoGames** [BG-Software-LLC/SuperiorSkyblock2#2077]
### Minecraft's Version

Minecraft version: 1.8.8
ServerJar: TacoSpigot 1.8.8

### Plugin's Version

SUPERIORSKYBLOCK: Latest stable build - 2024.1 11/05/2024 19:46:51
FAWE 19.11.13-5505943-1282 by Empire92
WorldEdit 6.1.7 by sk89q

### Describe the bug

When I update my superiorskyblock it receives an error in worldedit, before this update it worked normally

### To Reproduce

Printscreen:
https://media.discordapp.net/attachments/554282577322704896/1239948528210677781/image.png?ex=66476a8e&is=6646190e&hm=467dc3763875cf6904dda1695da85acf063295ee30b777ac21178ea1e62b7a9a&=&format=webp&quality=lossless

### Additional Information

[14:40:54 INFO]: [SuperiorSkyblock2] Enabling the module bank...
[14:40:54 INFO]: [SuperiorSkyblock2] Finished enabling the module bank (Took 0ms)
[14:40:54 INFO]: [SuperiorSkyblock2] Enabling the module missions...
[14:40:54 INFO]: [SuperiorSkyblock2] Finished enabling the module missions (Took 0ms)
[14:40:54 INFO]: [SuperiorSkyblock2] Enabling the module generators...
[14:40:54 INFO]: [SuperiorSkyblock2] Finished enabling the module generators (Took 0ms)
[14:40:54 INFO]: [SuperiorSkyblock2] Enabling the module upgrades...
[14:40:54 INFO]: [SuperiorSkyblock2] Finished enabling the module upgrades (Took 0ms)
[14:40:54 INFO]: [SuperiorSkyblock2] Loading messages started...
[14:40:54 INFO]: [SuperiorSkyblock2]  - Found 699 messages in the language files.
[14:40:54 INFO]: [SuperiorSkyblock2] Loading messages done (Took 180ms)
[14:40:54 WARN]: java.lang.ClassNotFoundException: com.sk89q.worldedit.world.block.BlockTypes
[14:40:54 WARN]:        at java.net.URLClassLoader.findClass(Unknown Source)
[14:40:54 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102)
[14:40:54 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[14:40:54 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[14:40:54 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[14:40:54 WARN]:        at java.lang.Class.forName0(Native Method)
[14:40:54 WARN]:        at java.lang.Class.forName(Unknown Source)
[14:40:54 WARN]:        at com.bgsoftware.superiorskyblock.libs.com.bgsoftware.common.reflection.ClassInfo$PackageType$3.findClass(ClassInfo.java:75)
[14:40:54 WARN]:        at com.bgsoftware.superiorskyblock.libs.com.bgsoftware.common.reflection.ClassInfo.findClass(ClassInfo.java:26)
[14:40:54 WARN]:        at com.bgsoftware.superiorskyblock.libs.com.bgsoftware.common.reflection.ClassInfo.findClasses(ClassInfo.java:14)
[14:40:54 WARN]:        at com.bgsoftware.superiorskyblock.libs.com.bgsoftware.common.reflection.ReflectMethod.<init>(ReflectMethod.java:35)
[14:40:54 WARN]:        at com.bgsoftware.superiorskyblock.libs.com.bgsoftware.common.reflection.ReflectMethod.<init>(ReflectMethod.java:11)
[14:40:54 WARN]:        at com.bgsoftware.superiorskyblock.world.schematic.impl.WorldEditSchematic.<clinit>(WorldEditSchematic.java:35)
[14:40:54 WARN]:        at com.bgsoftware.superiorskyblock.world.schematic.parser.FAWESchematicParser.parseSchematic(FAWESchematicParser.java:22)
[14:40:54 WARN]:        at com.bgsoftware.superiorskyblock.world.schematic.SchematicsManagerImpl.parseSchematic(SchematicsManagerImpl.java:268)
[14:40:54 WARN]:        at com.bgsoftware.superiorskyblock.world.schematic.SchematicsManagerImpl.loadFromFile(SchematicsManagerImpl.java:284)
[14:40:54 WARN]:        at com.bgsoftware.superiorskyblock.world.schematic.SchematicsManagerImpl.loadData(SchematicsManagerImpl.java:82)
[14:40:54 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:482)
[14:40:54 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:228)
[14:40:54 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[14:40:54 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[14:40:54 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[14:40:54 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[14:40:54 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[14:40:54 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[14:40:54 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[14:40:54 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[14:40:54 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[14:40:54 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[14:40:54 WARN]:        at java.lang.Thread.run(Unknown Source)
[14:40:55 INFO]: [SuperiorSkyblock2] Successfully loaded schematic desert.schematic (DefaultSchematicParser)
[14:40:55 INFO]: [SuperiorSkyblock2] Successfully loaded schematic desert_nether.schematic (DefaultSchematicParser)
[14:40:55 INFO]: [SuperiorSkyblock2] Successfully loaded schematic desert_the_end.schematic (DefaultSchematicParser)
[14:40:56 INFO]: [SuperiorSkyblock2] Successfully loaded schematic ilhateste.schematic (DefaultSchematicParser)
[14:40:56 INFO]: [SuperiorSkyblock2] Successfully loaded schematic mycel.schematic (DefaultSchematicParser)
[14:40:56 INFO]: [SuperiorSkyblock2] Successfully loaded schematic mycel_nether.schematic (DefaultSchematicParser)
[14:40:56 INFO]: [SuperiorSkyblock2] Successfully loaded schematic mycel_the_end.schematic (DefaultSchematicParser)
[14:40:56 INFO]: [SuperiorSkyblock2] Successfully loaded schematic normal.schematic (DefaultSchematicParser)
[14:40:56 INFO]: [SuperiorSkyblock2] Successfully loaded schematic normal_nether.schematic (DefaultSchematicParser)
[14:40:56 INFO]: [SuperiorSkyblock2] Successfully loaded schematic normal_the_end.schematic (DefaultSchematicParser)

**Comment by OmerBenGera** [comment]
This is does not break anything, do not worry about it.
I will look into fixing it tho :)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by AffonsoGames** [comment]
I downloaded the current version today and persist

**Comment by OmerBenGera** [comment]
> I downloaded the current version today and persist

Send me the stack trace you receive.

**Comment by AffonsoGames** [comment]
I downloaded in https://bg-software.com/superiorskyblock/
Latest stable build ssb

error recebived
[13:01:34 INFO]: [SuperiorSkyblock2] Loading messages done (Took 154ms)
[13:01:34 WARN]: java.lang.ClassNotFoundException: com.sk89q.worldedit.world.block.BlockTypes
[13:01:34 WARN]:        at java.net.URLClassLoader.findClass(Unknown Source)
[13:01:34 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102)
[13:01:34 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[13:01:34 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[13:01:34 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[13:01:34 WARN]:        at java.lang.Class.forName0(Native Method)
[13:01:34 WARN]:        at java.lang.Class.forName(Unknown Source)
[13:01:34 WARN]:        at com.bgsoftware.superiorskyblock.libs.com.bgsoftware.common.reflection.ClassInfo$PackageType$3.findClass(ClassInfo.java:75)
[13:01:34 WARN]:        at com.bgsoftware.superiorskyblock.libs.com.bgsoftware.common.reflection.ClassInfo.findClass(ClassInfo.java:26)
[13:01:34 WARN]:        at com.bgsoftware.superiorskyblock.libs.com.bgsoftware.common.reflection.ClassInfo.findClasses(ClassInfo.java:14)
[13:01:34 WARN]:        at com.bgsoftware.superiorskyblock.libs.com.bgsoftware.common.reflection.ReflectMethod.<init>(ReflectMethod.java:35)
[13:01:34 WARN]:        at com.bgsoftware.superiorskyblock.libs.com.bgsoftware.common.reflection.ReflectMethod.<init>(ReflectMethod.java:11)
[13:01:34 WARN]:        at com.bgsoftware.superiorskyblock.world.schematic.impl.WorldEditSchematic.<clinit>(WorldEditSchematic.java:35)
[13:01:34 WARN]:        at com.bgsoftware.superiorskyblock.world.schematic.parser.FAWESchematicParser.parseSchematic(FAWESchematicParser.java:22)
[13:01:34 WARN]:        at com.bgsoftware.superiorskyblock.world.schematic.SchematicsManagerImpl.parseSchematic(SchematicsManagerImpl.java:268)
[13:01:34 WARN]:        at com.bgsoftware.superiorskyblock.world.schematic.SchematicsManagerImpl.loadFromFile(SchematicsManagerImpl.java:284)
[13:01:34 WARN]:        at com.bgsoftware.superiorskyblock.world.schematic.SchematicsManagerImpl.loadData(SchematicsManagerImpl.java:82)
[13:01:34 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:482)
[13:01:34 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:228)
[13:01:34 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[13:01:34 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[13:01:34 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[13:01:34 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[13:01:34 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[13:01:34 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[13:01:34 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[13:01:34 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[13:01:34 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[13:01:34 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[13:01:34 WARN]:        at java.lang.Thread.run(Unknown Source)
[13:01:34 INFO]: [SuperiorSkyblock2] Successfully loaded schematic desert.schematic (DefaultSchematicParser)

**Comment by OmerBenGera** [comment]
Are you sure you're using latest dev build? Dev build 193
The lines in the stack trace don't seem to match the dev build

**Comment by AffonsoGames** [comment]
I was downloading the stable version, the incorrect one, I downloaded the dev build and it fixed it
solved! THX!
