### ISSUE TITLE
SSB-IslandNPCs

### ISSUE THREAD

**Issue by AffonsoGames** [BG-Software-LLC/SuperiorSkyblock2#2080]
### Minecraft's Version

1.8.8

### Plugin's Version

Plugin version dev build: #193 18/05/2024 13:48:38

Addon: https://github.com/BG-Software-LLC/SSB-IslandNPCs

### Describe the bug

I'm using this addon, I compiled it and it says "Can't find a suitable NPC provider", but I already have the CITIZENS plugin, should the citizens go in the MODULES folder?

### To Reproduce

Insert the jar in /modules and start the server.

**Comment by AffonsoGames** [comment]
[13:11:54 INFO]: [SuperiorSkyblock2] Enabling the module IslandNPCs...
[13:11:54 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while enabling the module IslandNPCs.
[13:11:54 ERROR]: [SuperiorSkyblock2] Contact Ome_R regarding this, this has nothing to do with the plugin.
[13:11:54 WARN]: java.lang.IllegalStateException: Cannot find a suitable NPC provider.
[13:11:54 WARN]:        at com.bgsoftware.ssbislandnpcs.SSBIslandNPCs.onEnable(SSBIslandNPCs.java:32)
[13:11:54 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModule(ModulesManagerImpl.java:136)
[13:11:54 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[13:11:54 WARN]:        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[13:11:54 WARN]:        at java.util.LinkedList$LLSpliterator.forEachRemaining(Unknown Source)
[13:11:54 WARN]:        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[13:11:54 WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[13:11:54 WARN]:        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[13:11:54 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[13:11:54 WARN]:        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[13:11:54 WARN]:        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[13:11:54 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModulesInternal(ModulesManagerImpl.java:190)
[13:11:54 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.runModuleLifecycle(ModulesManagerImpl.java:181)
[13:11:54 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:511)
[13:11:54 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:231)
[13:11:54 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[13:11:54 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[13:11:54 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[13:11:54 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[13:11:54 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[13:11:54 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[13:11:54 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[13:11:54 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[13:11:54 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[13:11:54 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[13:11:54 WARN]:        at java.lang.Thread.run(Unknown Source)
[13:11:54 INFO]: [SuperiorSkyblock2] Disabling the module IslandNPCs...
[13:11:54 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while disabling the module IslandNPCs.
[13:11:54 ERROR]: [SuperiorSkyblock2] Contact Ome_R regarding this, this has nothing to do with the plugin.
[13:11:54 WARN]: java.lang.NullPointerException
[13:11:54 WARN]:        at com.bgsoftware.ssbislandnpcs.SSBIslandNPCs.onDisable(SSBIslandNPCs.java:46)
[13:11:54 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.unregisterModule(ModulesManagerImpl.java:94)
[13:11:54 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModule(ModulesManagerImpl.java:143)
[13:11:54 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[13:11:54 WARN]:        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[13:11:54 WARN]:        at java.util.LinkedList$LLSpliterator.forEachRemaining(Unknown Source)
[13:11:54 WARN]:        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[13:11:54 WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[13:11:54 WARN]:        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[13:11:54 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[13:11:54 WARN]:        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[13:11:54 WARN]:        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[13:11:54 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModulesInternal(ModulesManagerImpl.java:190)
[13:11:54 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.runModuleLifecycle(ModulesManagerImpl.java:181)
[13:11:54 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:511)
[13:11:54 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:231)
[13:11:54 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[13:11:54 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[13:11:54 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[13:11:54 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[13:11:54 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[13:11:54 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[13:11:54 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[13:11:54 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[13:11:54 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[13:11:54 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[13:11:54 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by AffonsoGames** [comment]
Please close this report.
I find a new plugin.
