### ISSUE TITLE
Cannot find the correct potion types

### ISSUE THREAD

**Issue by SpadaccinoNero7** [BG-Software-LLC/SuperiorSkyblock2#2082]
### Minecraft's Version

1.20.1

### Plugin's Version

2023.3-b138

### Describe the bug

I tried creating some brewing mission but with certain potion types i can't load them up correctly
I searched the potion types in these 2 website but no one work https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html and https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionType.html 

### To Reproduce

Try adding the regeneration potion, water breathing, fire resistance, ...

### Additional Information

[alchimistasupremo_4.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/15388331/alchimistasupremo_4.txt)

**Comment by OmerBenGera** [comment]
You should use `JUMP` and `REGEN` for the jump boost and regeneration potions.

**Comment by SpadaccinoNero7** [comment]
Also what about the turtle master potion?
[alchimistasupremo_7.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/15430446/alchimistasupremo_7.txt)

**Comment by OmerBenGera** [comment]
You can find the list of possible potion types here: <https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionType.html>

It is `TURTLE_MASTER` according to this page

**Comment by SpadaccinoNero7** [comment]
[10:58:46 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while setting up menu:
[10:58:46 WARN]: java.lang.IllegalArgumentException: This is not a valid potion data.
[10:58:46 WARN]:        at com.bgsoftware.superiorskyblock.missions.BrewingMissions$PotionData.fromString(BrewingMissions.java:373)
[10:58:46 WARN]:        at com.bgsoftware.superiorskyblock.missions.BrewingMissions$1.getRequirementFromKey(BrewingMissions.java:196)
[10:58:46 WARN]:        at com.bgsoftware.superiorskyblock.missions.BrewingMissions$1.getRequirementFromKey(BrewingMissions.java:193)
[10:58:46 WARN]:        at com.bgsoftware.superiorskyblock.missions.brewing.Placeholders.parsePlaceholders(Placeholders.java:55)
[10:58:46 WARN]:        at com.bgsoftware.superiorskyblock.missions.BrewingMissions.formatItem(BrewingMissions.java:219)
[10:58:46 WARN]:        at SuperiorSkyblock2-2024.1-b186.jar//com.bgsoftware.superiorskyblock.core.menu.button.impl.MissionsPagedObjectButton.modifyViewItem(MissionsPagedObjectButton.java:100)
[10:58:46 WARN]:        at SuperiorSkyblock2-2024.1-b186.jar//com.bgsoftware.superiorskyblock.core.menu.button.AbstractPagedMenuButton.createViewItem(AbstractPagedMenuButton.java:29)
[10:58:46 WARN]:        at SuperiorSkyblock2-2024.1-b186.jar//com.bgsoftware.superiorskyblock.core.menu.layout.PagedMenuLayoutImpl.populateInventoryWithButton(PagedMenuLayoutImpl.java:103)
[10:58:46 WARN]:        at SuperiorSkyblock2-2024.1-b186.jar//com.bgsoftware.superiorskyblock.core.menu.layout.PagedMenuLayoutImpl.populateInventory(PagedMenuLayoutImpl.java:60)
[10:58:46 WARN]:        at SuperiorSkyblock2-2024.1-b186.jar//com.bgsoftware.superiorskyblock.core.menu.layout.AbstractMenuLayout.buildInventory(AbstractMenuLayout.java:78)
[10:58:46 WARN]:        at SuperiorSkyblock2-2024.1-b186.jar//com.bgsoftware.superiorskyblock.core.menu.AbstractMenu.lambda$buildInventory$2(AbstractMenu.java:79)
[10:58:46 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[10:58:46 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[10:58:46 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:58:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:58:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:58:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by OmerBenGera** [comment]
Yet again, you have incorrect potion types (SLOW & DAMAGE_RESISTANCE)
Use latest dev build, you'll see more indicative errors regarding invalid potion types.

**Comment by SpadaccinoNero7** [comment]
ok it works but i cannot find the correct type for the healing potion
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionType.html
i tried 
HEALING
HEALTH
STRONG_HEALING
all from the link above

**Comment by OmerBenGera** [comment]
It would be `INSTANT_HEAL`
