### ISSUE TITLE
Error in creating the first island

### ISSUE THREAD

**Issue by AffonsoGames** [BG-Software-LLC/SuperiorSkyblock2#2085]
### Minecraft's Version

1.8.8

### Plugin's Version

SuperiorSkyblock2-2024.1-b193

### Describe the bug

I'm receive this error when players create a new island.

[20:18:57 WARN]: [SuperiorSkyblock2] Task #2325 for SuperiorSkyblock2 v2024.1-b193 generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.v1_8_R3.WorldServer.c(Lnet/minecraft/server/v1_8_R3/EnumSkyBlock;Lnet/minecraft/server/v1_8_R3/BlockPosition;)Z
        at com.bgsoftware.superiorskyblock.nms.v1_8_R3.world.WorldEditSessionImpl.lambda$null$4(WorldEditSessionImpl.java:149) ~[?:?]
        at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_351]
        at com.bgsoftware.superiorskyblock.nms.v1_8_R3.world.WorldEditSessionImpl.lambda$finish$6(WorldEditSessionImpl.java:149) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[paper.jar:git-TacoSpigot-"bf023c7d"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [paper.jar:git-TacoSpigot-"bf023c7d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785) [paper.jar:git-TacoSpigot-"bf023c7d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paper.jar:git-TacoSpigot-"bf023c7d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [paper.jar:git-TacoSpigot-"bf023c7d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [paper.jar:git-TacoSpigot-"bf023c7d"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_351]

### To Reproduce

/is create
* create a new island (when you don't have one)

**Comment by OmerBenGera** [comment]
What Spigot jar do you use? Run `/version` and send me the output

**Comment by AffonsoGames** [comment]
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/44729611/16685bd2-6159-4f13-b3e5-8fcacfd71018)

**Comment by OmerBenGera** [comment]
Try using Paper/Spigot, let me know if if still occurs

**Comment by AffonsoGames** [comment]
Yes, error!
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/44729611/6589aa93-c03d-45ea-90ca-5f03af279b51)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by AffonsoGames** [comment]
THX, error fixed!
