### ISSUE TITLE
Seems like plugin is not updated for v1_16_R3

### ISSUE THREAD

**Issue by Baterka** [BG-Software-LLC/SuperiorSkyblock2#209]
**Minecraft's Version**
Yatopia latest version (https://github.com/YatopiaMC/Yatopia/actions/runs/730416668)

**Plugin's Version**: -
1.6.0

**Describe the bug**

Seems like plugin is not updated for v1_16_R3
```
[org.bukkit.craftbukkit.v1_16_R3.CraftServer] failed to access class net.minecraft.server.v1_16_R3.BlockProperties from class com.bgsoftware.superiorskyblock.nms.NMSBlocks_v1_16_R3 (net.minecraft.server.v1_16_R3.BlockProperties is in unnamed module of loader 'app'; com.bgsoftware.superiorskyblock.nms.NMSBlocks_v1_16_R3 is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @26bfa07a) initializing SuperiorSkyblock2 v1.6.0 (Is it up to date?)
java.lang.IllegalAccessError: failed to access class net.minecraft.server.v1_16_R3.BlockProperties from class com.bgsoftware.superiorskyblock.nms.NMSBlocks_v1_16_R3 (net.minecraft.server.v1_16_R3.BlockProperties is in unnamed module of loader 'app'; com.bgsoftware.superiorskyblock.nms.NMSBlocks_v1_16_R3 is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @26bfa07a)
    at com.bgsoftware.superiorskyblock.nms.NMSBlocks_v1_16_R3.<clinit>(NMSBlocks_v1_16_R3.java:142) ~[?:?]
    at java.lang.Class.forName0(Native Method) ~[?:?]
    at java.lang.Class.forName(Class.java:315) ~[?:?]
    at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.loadNMSAdapter(SuperiorSkyblockPlugin.java:283) ~[?:?]
    at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onLoad(SuperiorSkyblockPlugin.java:119) ~[?:?]
    at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"9237750"]
    at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:273) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"9237750"]
    at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"9237750"]
    at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"9237750"]
    at java.lang.Thread.run(Thread.java:834) [?:?]
```

**To Reproduce**
Download Yatopia (https://github.com/YatopiaMC/Yatopia/actions/runs/730416668), put plugin in plugins folder, run server.

**Comment by OOP-778** [comment]
Hello, may you try the latest version of the dev build?

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
