### ISSUE TITLE
Is Create not work

### ISSUE THREAD

**Issue by Reaviik** [BG-Software-LLC/SuperiorSkyblock2#2103]
### Minecraft's Version

1.20.1 arclight - 1.0.4

### Plugin's Version

2024.1

### Describe the bug

[22:44:08 INFO]: Reavik issued server command: /island create Reavik normal
[22:44:08 INFO] [SuperiorSkyblock2]: GridManagerImpl::createIsland ENTER {Reavik} {normal} {PLAINS} {true}
[22:44:08 ERROR] [SuperiorSkyblock2]: An unexpected error occurred while creating an island:
[22:44:08 ERROR] [STDERR]: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
[22:44:08 ERROR] [STDERR]:      at java.base/java.util.EnumMap.get(EnumMap.java:244)
[22:44:08 ERROR] [STDERR]:      at com.bgsoftware.superiorskyblock.external.worlds.WorldsProvider_Default.getIslandsWorld(WorldsProvider_Default.java:58)

### To Reproduce

'-

### Additional Information

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/122496671/63a2ac9e-e825-4700-bc16-20369248e518)

**Comment by OmerBenGera** [comment]
arclight is not supported
NMS in acrlight is not supported, therefore the plugin cannot function properly.
The plugin in latest versions should also detect arclight and get disabled properly.
