### ISSUE TITLE
Farmer 3 Mission bug

### ISSUE THREAD

**Issue by peter7ec** [BG-Software-LLC/SuperiorSkyblock2#2112]
### Minecraft's Version

1.20.6 paper server

### Plugin's Version

2024.1

### Describe the bug

When anyone try to complete the Farmer 3 quest the server is crashing and give back this message:
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "com.bgsoftware.superiorskyblock.libs.com.bgsoftware.common.reflection.ReflectMethod.invoke(Object, Object[])" is null
    at SuperiorSkyblock2-2024_1.jar//com.bgsoftware.superiorskyblock.nms.v1_20_4.chunks.CropsBlockEntity.tick(CropsBlockEntity.java:120)
    at SuperiorSkyblock2-2024_1.jar//com.bgsoftware.superiorskyblock.nms.v1_20_4.chunks.CropsTickingBlockEntity.tick(CropsTickingBlockEntity.java:12)
    at net.minecraft.world.level.Level.tickBlockEntities(Level.java:1282)
    at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:931)
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1779)
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467)
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231)
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
    at java.base/java.lang.Thread.run(Thread.java:1583)

### To Reproduce

Create a island, use the /is admin mission <player> complete farmer_3 (First complete the farmer 1 and 2 mission). Or just complete by manually.

**Comment by peter7ec** [comment]
Update: with 2024.1-b231 version working fine. No chrash and mission completed!
