### ISSUE TITLE
Create island error

### ISSUE THREAD

**Issue by VinceSMC** [BG-Software-LLC/SuperiorSkyblock2#2120]
### Minecraft's Version

Paper 1.21

### Plugin's Version

_SuperiorSkyblock2-2024.1-b239_

### Describe the bug

An error occurs when I create an island. I'm not sure if it's related to FAWE, but I tried using both the native island schematic tool and a FAWE schematic, and both methods result in this error:

`[21:12:52 INFO]: [SuperiorSkyblock2] GridManagerImpl::createIslandInternalAsync VinceSMC {0} {0} {} {true} {JUNGLE} {default}
[21:12:52 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while creating an island:
[21:12:52 WARN]: java.lang.UnsupportedOperationException
[21:12:52 WARN]:        at net.minecraft.server.level.ThreadedLevelLightEngine.lightChunk(ThreadedLevelLightEngine.java:226)
[21:12:52 WARN]:        at SuperiorSkyblock2-2024.1-b239.jar//com.bgsoftware.superiorskyblock.nms.v1_21.world.WorldEditSessionImpl.applyBlocks(WorldEditSessionImpl.java:194)
[21:12:52 WARN]:        at SuperiorSkyblock2-2024.1-b239.jar//com.bgsoftware.superiorskyblock.world.schematic.impl.SuperiorSchematic.lambda$null$3(SuperiorSchematic.java:169)
[21:12:52 WARN]:        at SuperiorSkyblock2-2024.1-b239.jar//com.bgsoftware.superiorskyblock.world.chunk.ChunksProvider.lambda$processPendingChunkLoadRequest$0(ChunksProvider.java:132)
[21:12:52 WARN]:        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[21:12:52 WARN]:        at SuperiorSkyblock2-2024.1-b239.jar//com.bgsoftware.superiorskyblock.world.chunk.ChunksProvider.processPendingChunkLoadRequest(ChunksProvider.java:132)
[21:12:52 WARN]:        at SuperiorSkyblock2-2024.1-b239.jar//com.bgsoftware.superiorskyblock.world.chunk.ChunksProvider.access$400(ChunksProvider.java:21)
[21:12:52 WARN]:        at SuperiorSkyblock2-2024.1-b239.jar//com.bgsoftware.superiorskyblock.world.chunk.ChunksProvider$ChunkLoadWorker.finishLoad(ChunksProvider.java:121)
[21:12:52 WARN]:        at SuperiorSkyblock2-2024.1-b239.jar//com.bgsoftware.superiorskyblock.world.chunk.ChunksProvider$ChunkLoadWorker.lambda$work$0(ChunksProvider.java:110)
[21:12:52 WARN]:        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
[21:12:52 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
[21:12:52 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[21:12:52 WARN]:        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
[21:12:52 WARN]:        at org.bukkit.craftbukkit.CraftWorld.lambda$getChunkAtAsync$14(CraftWorld.java:2432)
[21:12:52 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[21:12:52 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[21:12:52 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[21:12:52 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1478)
[21:12:52 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[21:12:52 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[21:12:52 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1456)
[21:12:52 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1449)
[21:12:52 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[21:12:52 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1408)
[21:12:52 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1529)
[21:12:52 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246)
[21:12:52 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[21:12:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)`

### To Reproduce

By creating an island.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by VinceSMC** [comment]
Yep, the latest dev build solved it. Appreciate the quick fix!
