### ISSUE TITLE
Server closes

### ISSUE THREAD

**Issue by jack1888x** [BG-Software-LLC/SuperiorSkyblock2#2124]
### Minecraft's Version

1.21

### Plugin's Version

Newest

### Describe the bug

As I put the plugin in the plugin folder than start my server... my server closed when it is online...

### To Reproduce

Put the plugin in the plugin folder
Minecraft version 1.21
Start the server

**Comment by OmerBenGera** [comment]
Look for errors and warnings in console.
The plugin is pretty indicative on why it doesnt let the server open

**Comment by jack1888x** [comment]
I go look for it

**Comment by jack1888x** [comment]
[10:24:20 ERROR]: [SuperiorSkyblock2] ################################################
[10:24:20 ERROR]: [SuperiorSkyblock2] ##                                            ##
[10:24:20 ERROR]: [SuperiorSkyblock2] ## An error occured while loading the plugin! ##
[10:24:20 ERROR]: [SuperiorSkyblock2] ##                                            ##
[10:24:20 ERROR]: [SuperiorSkyblock2] ################################################
[10:24:20 ERROR]: [SuperiorSkyblock2]  
[10:24:20 ERROR]: [SuperiorSkyblock2] The plugin doesn't support your minecraft version.
[10:24:20 ERROR]: [SuperiorSkyblock2] Please try a different version.
[10:24:20 ERROR]: [SuperiorSkyblock2]  
[10:24:20 ERROR]: [SuperiorSkyblock2] Stack Trace:
[10:24:20 ERROR]: [SuperiorSkyblock2] 	at SuperiorSkyblock2-2024.1-b240(1).jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onLoad(SuperiorSkyblockPlugin.java:164)
[10:24:20 ERROR]: [SuperiorSkyblock2] 	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
[10:24:20 ERROR]: [SuperiorSkyblock2] 	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
[10:24:20 ERROR]: [SuperiorSkyblock2] 	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40)
[10:24:20 ERROR]: [SuperiorSkyblock2] 	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
[10:24:20 ERROR]: [SuperiorSkyblock2] 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:510)
[10:24:20 ERROR]: [SuperiorSkyblock2] 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
[10:24:20 ERROR]: [SuperiorSkyblock2] 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
[10:24:20 ERROR]: [SuperiorSkyblock2] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[10:24:20 ERROR]: [SuperiorSkyblock2] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[10:24:20 ERROR]: [SuperiorSkyblock2] Caused by: com.bgsoftware.superiorskyblock.libs.com.bgsoftware.common.nmsloader.NMSLoadException: Couldn't find valid builtin nms handlers for the data version: 3465
[10:24:20 ERROR]: [SuperiorSkyblock2] 	at SuperiorSkyblock2-2024.1-b240(1).jar//com.bgsoftware.superiorskyblock.libs.com.bgsoftware.common.nmsloader.NMSHandlersFactory.getNMSPackageVersionName(NMSHandlersFactory.java:70)
[10:24:20 ERROR]: [SuperiorSkyblock2] 	at SuperiorSkyblock2-2024.1-b240(1).jar//com.bgsoftware.superiorskyblock.libs.com.bgsoftware.common.nmsloader.NMSHandlersFactory.createNMSLoader(NMSHandlersFactory.java:26)
[10:24:20 ERROR]: [SuperiorSkyblock2] 	at SuperiorSkyblock2-2024.1-b240(1).jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.loadNMSAdapter(SuperiorSkyblockPlugin.java:395)
[10:24:20 ERROR]: [SuperiorSkyblock2] 	... 10 more
[10:24:20 ERROR]: [SuperiorSkyblock2]  
[10:24:20 ERROR]: [SuperiorSkyblock2] ################################################

this is the first error when I start the server

[10:24:31 ERROR]: [SuperiorSkyblock2] ################################################
[10:24:31 ERROR]: [SuperiorSkyblock2] ##                                            ##
[10:24:31 ERROR]: [SuperiorSkyblock2] ## An error occured while loading the plugin! ##
[10:24:31 ERROR]: [SuperiorSkyblock2] ##                                            ##
[10:24:31 ERROR]: [SuperiorSkyblock2] ################################################
[10:24:31 ERROR]: [SuperiorSkyblock2]  
[10:24:31 ERROR]: [SuperiorSkyblock2] Failed to load SuperiorSkyblock2.
[10:24:31 ERROR]: [SuperiorSkyblock2] Failed on NMS_INITIALIZED
[10:24:31 ERROR]: [SuperiorSkyblock2] 
[10:24:31 ERROR]: [SuperiorSkyblock2] Shutting down the server...
[10:24:31 ERROR]: [SuperiorSkyblock2]  
[10:24:31 ERROR]: [SuperiorSkyblock2] Stack Trace:
[10:24:31 ERROR]: [SuperiorSkyblock2] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[10:24:31 ERROR]: [SuperiorSkyblock2] 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[10:24:31 ERROR]: [SuperiorSkyblock2] 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[10:24:31 ERROR]: [SuperiorSkyblock2] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[10:24:31 ERROR]: [SuperiorSkyblock2] 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
[10:24:31 ERROR]: [SuperiorSkyblock2] 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
[10:24:31 ERROR]: [SuperiorSkyblock2] 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
[10:24:31 ERROR]: [SuperiorSkyblock2] 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
[10:24:31 ERROR]: [SuperiorSkyblock2] 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[10:24:31 ERROR]: [SuperiorSkyblock2] 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
[10:24:31 ERROR]: [SuperiorSkyblock2] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[10:24:31 ERROR]: [SuperiorSkyblock2] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[10:24:31 ERROR]: [SuperiorSkyblock2]  
[10:24:31 ERROR]: [SuperiorSkyblock2] ################################################

this is the second error

from what I can read is that I have not the version... but I saw on spigot that it supports 1.20. Im on 1.20.1.

**Comment by OmerBenGera** [comment]
I am using latest version of Paper and SSB and it works fine
I suspect it occurs to you because you have multiple jars of SuperiorSkyblock inside your plugins folder - make sure you only have one of them in there, so they don't conflict with each other.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by JorisvD01** [comment]
I'm experiencing the same error.

Server is running Paper version git-Paper-196 (MC: 1.20.1)
SuperiorSkyblock version: 2024.2. Had no issues on 2024.1

Exact error:

Almost instantly at startup:
```
[19:09:33] [Server thread/INFO]: [SuperiorSkyblock2] Loading server plugin SuperiorSkyblock2 v2024.2
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2] ################################################
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2] ##                                            ##
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2] ## An error occured while loading the plugin! ##
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2] ##                                            ##
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2] ################################################
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2]  
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2] The plugin doesn't support your minecraft version.
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2] Please try a different version.
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2]  
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2] Stack Trace:
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2] 	at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onLoad(SuperiorSkyblockPlugin.java:163)
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2] 	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2] 	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2] 	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40)
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2] 	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2] 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:510)
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2] 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2] 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2] 	at java.base/java.lang.Thread.run(Thread.java:840)
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2] Caused by: com.bgsoftware.superiorskyblock.libs.com.bgsoftware.common.nmsloader.NMSLoadException: Couldn't find valid builtin nms handlers for the data version: 3465
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2] 	at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.libs.com.bgsoftware.common.nmsloader.NMSHandlersFactory.getNMSPackageVersionName(NMSHandlersFactory.java:70)
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2] 	at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.libs.com.bgsoftware.common.nmsloader.NMSHandlersFactory.createNMSLoader(NMSHandlersFactory.java:26)
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2] 	at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.loadNMSAdapter(SuperiorSkyblockPlugin.java:399)
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2] 	... 10 more
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2]  
[19:09:33] [Server thread/ERROR]: [SuperiorSkyblock2] ################################################
```

A little later:
```
[19:09:49] [Server thread/INFO]: [SuperiorSkyblock2] Enabling SuperiorSkyblock2 v2024.2
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2] ################################################
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2] ##                                            ##
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2] ## An error occured while loading the plugin! ##
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2] ##                                            ##
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2] ################################################
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2]  
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2] Failed to load SuperiorSkyblock2.
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2] Failed on NMS_INITIALIZED
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2] 
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2] Shutting down the server...
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2]  
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2] Stack Trace:
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2] 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2] 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2] 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2] 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2] 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2] 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2] 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2] 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2] 	at java.base/java.lang.Thread.run(Thread.java:840)
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2]  
[19:09:49] [Server thread/ERROR]: [SuperiorSkyblock2] ################################################
```

**Comment by OmerBenGera** [comment]
You're using 1.20.1, not 1.21 as you wrote on the bug report.
1.20-1.20.3 are no longer supported. You should udpate to 1.20.4/1.20.6
