### ISSUE TITLE
After updating the latest development version, the console continues to report errors!

### ISSUE THREAD

**Issue by wlm1455925277** [BG-Software-LLC/SuperiorSkyblock2#2131]
### Minecraft's Version

[23:52:16 INFO]: Checking version, please wait...
[23:52:16 INFO]: Current Purpur Version: 1.21-2256-de2e7a7 (MC: 1.21)*
* You are running the latest version

### Plugin's Version

[23:52:50 INFO]: SuperiorSkyblock2 version 2024.1-b247
[23:52:50 INFO]: Feature packed Skyblock core.
[23:52:50 INFO]: Website: https://bg-software.com/
[23:52:50 INFO]: Author: Ome_R

### Describe the bug

After updating the latest development version, the console continues to report errors!

### To Reproduce

Update plugins

### Additional Information

[23:53:29 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while executing query `UPDATE {prefix}islands SET entity_counts=[{"id":"ZOMBIFIED_PIGLIN","amount":"1"},{"id":"HOPPER_MINECART","amount":"5"}] WHERE uuid=?;`:
[23:53:29 WARN]: java.sql.SQLException: No value specified for parameter 2
[23:53:29 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
[23:53:29 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:113)
[23:53:29 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.addBatch(ClientPreparedStatement.java:247)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.libs.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.addBatch(HikariProxyPreparedStatement.java)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.lambda$processTransaction$0(SQLTransactionProcessor.java:46)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.session.QueryResult.complete(QueryResult.java:35)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.session.RemoteSQLSession.customQuery(RemoteSQLSession.java:131)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLHelper.customQuery(SQLHelper.java:91)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.executeQuery(SQLTransactionProcessor.java:65)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.processTransaction(SQLTransactionProcessor.java:35)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.transaction.DatabaseTransactionsExecutor.processTransaction(DatabaseTransactionsExecutor.java:111)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.transaction.DatabaseTransactionsExecutor.handleNextTransactionSafe(DatabaseTransactionsExecutor.java:101)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.transaction.DatabaseTransactionsExecutor.transactionsHandler(DatabaseTransactionsExecutor.java:83)
[23:53:29 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[23:53:29 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while executing query `UPDATE {prefix}islands SET entity_counts=[{"id":"ZOMBIFIED_PIGLIN","amount":"1"},{"id":"HOPPER_MINECART","amount":"5"}] WHERE uuid=?;`:
[23:53:29 WARN]: java.sql.SQLException: No value specified for parameter 2
[23:53:29 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
[23:53:29 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:113)
[23:53:29 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.addBatch(ClientPreparedStatement.java:247)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.libs.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.addBatch(HikariProxyPreparedStatement.java)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.lambda$processTransaction$0(SQLTransactionProcessor.java:46)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.session.QueryResult.complete(QueryResult.java:35)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.session.RemoteSQLSession.customQuery(RemoteSQLSession.java:131)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLHelper.customQuery(SQLHelper.java:91)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.executeQuery(SQLTransactionProcessor.java:65)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.processTransaction(SQLTransactionProcessor.java:35)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.transaction.DatabaseTransactionsExecutor.processTransaction(DatabaseTransactionsExecutor.java:111)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.transaction.DatabaseTransactionsExecutor.handleNextTransactionSafe(DatabaseTransactionsExecutor.java:101)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.transaction.DatabaseTransactionsExecutor.transactionsHandler(DatabaseTransactionsExecutor.java:83)
[23:53:29 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[23:53:29 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while executing query `UPDATE {prefix}islands SET entity_counts=[{"id":"ZOMBIFIED_PIGLIN","amount":"1"},{"id":"HOPPER_MINECART","amount":"2"}] WHERE uuid=?;`:
[23:53:29 WARN]: java.sql.SQLException: No value specified for parameter 2
[23:53:29 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
[23:53:29 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:113)
[23:53:29 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.addBatch(ClientPreparedStatement.java:247)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.libs.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.addBatch(HikariProxyPreparedStatement.java)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.lambda$processTransaction$0(SQLTransactionProcessor.java:46)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.session.QueryResult.complete(QueryResult.java:35)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.session.RemoteSQLSession.customQuery(RemoteSQLSession.java:131)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLHelper.customQuery(SQLHelper.java:91)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.executeQuery(SQLTransactionProcessor.java:65)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.processTransaction(SQLTransactionProcessor.java:35)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.transaction.DatabaseTransactionsExecutor.processTransaction(DatabaseTransactionsExecutor.java:111)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.transaction.DatabaseTransactionsExecutor.handleNextTransactionSafe(DatabaseTransactionsExecutor.java:101)
[23:53:29 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.transaction.DatabaseTransactionsExecutor.transactionsHandler(DatabaseTransactionsExecutor.java:83)
[23:53:29 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[23:53:30 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while executing query `UPDATE {prefix}islands SET entity_counts=[{"id":"ZOMBIFIED_PIGLIN","amount":"1"},{"id":"HOPPER_MINECART","amount":"2"}] WHERE uuid=?;`:
[23:53:30 WARN]: java.sql.SQLException: No value specified for parameter 2
[23:53:30 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
[23:53:30 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:113)
[23:53:30 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.addBatch(ClientPreparedStatement.java:247)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.libs.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.addBatch(HikariProxyPreparedStatement.java)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.lambda$processTransaction$0(SQLTransactionProcessor.java:46)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.session.QueryResult.complete(QueryResult.java:35)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.session.RemoteSQLSession.customQuery(RemoteSQLSession.java:131)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLHelper.customQuery(SQLHelper.java:91)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.executeQuery(SQLTransactionProcessor.java:65)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.processTransaction(SQLTransactionProcessor.java:35)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.transaction.DatabaseTransactionsExecutor.processTransaction(DatabaseTransactionsExecutor.java:111)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.transaction.DatabaseTransactionsExecutor.handleNextTransactionSafe(DatabaseTransactionsExecutor.java:101)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.transaction.DatabaseTransactionsExecutor.transactionsHandler(DatabaseTransactionsExecutor.java:83)
[23:53:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[23:53:30 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while executing query `UPDATE {prefix}islands SET entity_counts=[{"id":"CHEST_MINECART","amount":"2"},{"id":"ZOMBIFIED_PIGLIN","amount":"9"},{"id":"MINECART","amount":"2"}] WHERE uuid=?;`:
[23:53:30 WARN]: java.sql.SQLException: No value specified for parameter 2
[23:53:30 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
[23:53:30 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:113)
[23:53:30 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.addBatch(ClientPreparedStatement.java:247)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.libs.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.addBatch(HikariProxyPreparedStatement.java)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.lambda$processTransaction$0(SQLTransactionProcessor.java:46)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.session.QueryResult.complete(QueryResult.java:35)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.session.RemoteSQLSession.customQuery(RemoteSQLSession.java:131)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLHelper.customQuery(SQLHelper.java:91)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.executeQuery(SQLTransactionProcessor.java:65)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.processTransaction(SQLTransactionProcessor.java:35)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.transaction.DatabaseTransactionsExecutor.processTransaction(DatabaseTransactionsExecutor.java:111)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.transaction.DatabaseTransactionsExecutor.handleNextTransactionSafe(DatabaseTransactionsExecutor.java:101)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.transaction.DatabaseTransactionsExecutor.transactionsHandler(DatabaseTransactionsExecutor.java:83)
[23:53:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[23:53:30 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while executing query `UPDATE {prefix}islands SET entity_counts=[{"id":"ZOMBIFIED_PIGLIN","amount":"1"},{"id":"HOPPER_MINECART","amount":"2"}] WHERE uuid=?;`:
[23:53:30 WARN]: java.sql.SQLException: No value specified for parameter 2
[23:53:30 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
[23:53:30 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:113)
[23:53:30 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.addBatch(ClientPreparedStatement.java:247)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.libs.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.addBatch(HikariProxyPreparedStatement.java)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.lambda$processTransaction$0(SQLTransactionProcessor.java:46)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.session.QueryResult.complete(QueryResult.java:35)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.session.RemoteSQLSession.customQuery(RemoteSQLSession.java:131)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLHelper.customQuery(SQLHelper.java:91)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.executeQuery(SQLTransactionProcessor.java:65)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.processTransaction(SQLTransactionProcessor.java:35)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.transaction.DatabaseTransactionsExecutor.processTransaction(DatabaseTransactionsExecutor.java:111)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.transaction.DatabaseTransactionsExecutor.handleNextTransactionSafe(DatabaseTransactionsExecutor.java:101)
[23:53:30 WARN]:        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar//com.bgsoftware.superiorskyblock.core.database.transaction.DatabaseTransactionsExecutor.transactionsHandler(DatabaseTransactionsExecutor.java:83)
[23:53:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by wlm1455925277** [comment]
[23:54:51 ERROR]: Could not pass event EntityChangeBlockEvent to SuperiorSkyblock2 v2024.1-b247
java.lang.IllegalArgumentException: CARROTS isn't an item
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.inventory.ItemStack.of(ItemStack.java:69) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:149) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:128) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar/com.bgsoftware.superiorskyblock.core.key.Keys.of(Keys.java:105) ~[[S][空岛]SuperiorSkyblock2-2024.1-b247.jar:?]
        at [S][空岛]SuperiorSkyblock2-2024.1-b247.jar/com.bgsoftware.superiorskyblock.listener.BlockChangesListener.onEntityChangeBlock(BlockChangesListener.java:204) ~[[S][空岛]SuperiorSkyblock2-2024.1-b247.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2256-de2e7a7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:1378) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:1370) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.entity.ai.behavior.HarvestFarmland.tick(HarvestFarmland.java:133) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.entity.ai.behavior.HarvestFarmland.tick(HarvestFarmland.java:35) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.entity.ai.behavior.Behavior.tickOrStop(Behavior.java:78) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.entity.ai.behavior.GateBehavior.tickOrStop(GateBehavior.java:72) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.entity.ai.Brain.tickEachRunningBehavior(Brain.java:455) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.entity.ai.Brain.tick(Brain.java:404) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.entity.npc.Villager.customServerAiStep(Villager.java:354) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.entity.npc.Villager.customServerAiStep(Villager.java:341) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:976) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3488) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:708) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:155) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3191) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.entity.Mob.tick(Mob.java:469) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.entity.npc.Villager.tick(Villager.java:402) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1303) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1041) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:774) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:754) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1832) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:507) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1636) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1337) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by wlm1455925277** [comment]
There is also this error!

**Comment by OmerBenGera** [comment]
Check out latest dev build, both bugs should be fixed

**Comment by wlm1455925277** [comment]
The issue has been fixed!
