### ISSUE TITLE
There is a problem in the Sky Island Netherworld!More detailed instructions!

### ISSUE THREAD

**Issue by wlm1455925277** [BG-Software-LLC/SuperiorSkyblock2#2145]
### Minecraft's Version

> version
[08:15:43 INFO]: Checking version, please wait...
[08:15:44 INFO]: Current Purpur Version: 1.21-2260-5e70800 (MC: 1.21)*
* You are running the latest version
Previous: git-Purpur-2176 (MC: 1.20.4)

### Plugin's Version

> version SuperiorSkyblock2
[08:15:51 INFO]: SuperiorSkyblock2 version 2024.1-b260
[08:15:51 INFO]: Feature packed Skyblock core.
[08:15:51 INFO]: Website: https://bg-software.com/
[08:15:51 INFO]: Author: Ome_R

### Describe the bug

The Nether is inaccessible, and I haven’t tested the End!And the default unlocking of Hell and the End has been turned on in the SkyIsle configuration file, and Hell and the End have been turned on!

### To Reproduce

Modify allow-end: false in bukkit.yml
Modify allow-nether=false in server.properties
Prompt when entering the Nether Gate! In the previous 1.20.4 version, just turn off the above configuration. As long as you have enabled the Nether and the End in the Sky Island configuration! You can also enter normally!
[08:13:52 ERROR]: Could not pass event PlayerTeleportEvent to SuperiorSkyblock2 v2024.1-b260
java.lang.NullPointerException: to cannot be null
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:921) ~[guava-32.1.2-jre.jar:?]
at SuperiorSkyblock2-2024.1-b260 (2).jar/com.bgsoftware.superiorskyblock.service.region.RegionManagerServiceImpl.handlePlayerTeleport(RegionManagerServiceImpl.java:446) ~[SuperiorSkyblock2-2024.1-b260 (2).jar:?]
at SuperiorSkyblock2-2024.1-b260 (2).jar/com.bgsoftware.superiorskyblock.listener.PlayersListener.onPlayerTeleport(PlayersListener.java:245) ~[SuperiorSkyblock2-2024.1-b260 (2).jar:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2260-5e70800]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2260-5e70800]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2260-5e70800]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.level.ServerPlayer.changeDimension(ServerPlayer.java:1414) ~[purpur-1.21.jar:1.21-2260-5e70800]
at net.minecraft.world.entity.Entity.handlePortal(Entity.java:3326) ~[purpur-1.21.jar:1.21-2260-5e70800]
at net.minecraft.world.entity.Entity.baseTick(Entity.java:898) ~[purpur-1.21.jar:1.21-2260-5e70800]
at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:447) ~[purpur-1.21.jar:1.21-2260-5e70800]
at net.minecraft.world.entity.Entity.tick(Entity.java:871) ~[purpur-1.21.jar:1.21-2260-5e70800]
at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3200) ~[purpur-1.21.jar:1.21-2260-5e70800]
at net.minecraft.world.entity.player.Player.tick(Player.java:317) ~[purpur-1.21.jar:1.21-2260-5e70800]
at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:855) ~[purpur-1.21.jar:1.21-2260-5e70800]
at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:360) ~[purpur-1.21.jar:1.21-2260-5e70800]
at net.minecraft.network.Connection.tick(Connection.java:647) ~[purpur-1.21.jar:1.21-2260-5e70800]
at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:242) ~[purpur-1.21.jar:1.21-2260-5e70800]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1851) ~[purpur-1.21.jar:1.21-2260-5e70800]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:507) ~[purpur-1.21.jar:1.21-2260-5e70800]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1637) ~[purpur-1.21.jar:1.21-2260-5e70800]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1338) ~[purpur-1.21.jar:1.21-2260-5e70800]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2260-5e70800]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
In bukkit.yml modify allow-end: true
In server.properties modify allow-nether=true
There will be no error or any prompt when entering the created Nether Gate console, but you will not be able to teleport to the Nether. I have not tested the End. When you knock off the Nether Gate teleport block of the Nether Gate and then relight it with flint, you will be prompted that the Nether has not been unlocked when you try to enter!

**Comment by OmerBenGera** [comment]
I cannot replicate the error
Try latest dev build, let me know if it still occurs

**Comment by wlm1455925277** [comment]
The issue has been fixed!
