### ISSUE TITLE
Island Upgrades module not initializing

### ISSUE THREAD

**Issue by THEHunted20000** [BG-Software-LLC/SuperiorSkyblock2#2153]
### Minecraft's Version

1.20.4

### Plugin's Version

latest stable and ive tried latest dev

### Describe the bug

im getting an error in the console that the module island upgrades is not initializing. i was messing with the upgrades and to get them to work correctly and for the prices of them and i reloaded the plugin and they worked just fine. now the server just restarted in auto restart and now its not working what so ever. im leaving what the console is saying in Additional info

### To Reproduce

just starting the server

### Additional Information

19.07 20:50:15] [Server] [WARN] [SuperiorSkyblock2] Potentially missing interactable block CAVE_VINES_PLANT
[19.07 20:50:15] [Server] [ERROR] [SuperiorSkyblock2] An unexpected error occurred while initializing the module upgrades.
[19.07 20:50:15] [Server] [ERROR] [SuperiorSkyblock2] Contact Ome_R regarding this, this has nothing to do with the plugin.
[19.07 20:50:15] [Server] [WARN] java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getKeys(boolean)" because the return value of "org.bukkit.configuration.ConfigurationSection.getConfigurationSection(String)" is null
[19.07 20:50:15] [Server] [WARN] 	at SuperiorSkyblock2-2024.1-b266.jar//com.bgsoftware.superiorskyblock.module.upgrades.UpgradesModule.loadUpgradeLevelFromSection(UpgradesModule.java:229)
[19.07 20:50:15] [Server] [WARN] 	at SuperiorSkyblock2-2024.1-b266.jar//com.bgsoftware.superiorskyblock.module.upgrades.UpgradesModule.updateConfig(UpgradesModule.java:166)
[19.07 20:50:15] [Server] [WARN] 	at SuperiorSkyblock2-2024.1-b266.jar//com.bgsoftware.superiorskyblock.module.BuiltinModule.onPluginInit(BuiltinModule.java:74)
[19.07 20:50:15] [Server] [WARN] 	at SuperiorSkyblock2-2024.1-b266.jar//com.bgsoftware.superiorskyblock.module.upgrades.UpgradesModule.onPluginInit(UpgradesModule.java:70)
[19.07 20:50:15] [Server] [WARN] 	at SuperiorSkyblock2-2024.1-b266.jar//com.bgsoftware.superiorskyblock.module.BuiltinModule.onPluginInit(BuiltinModule.java:58)
[19.07 20:50:15] [Server] [WARN] 	at SuperiorSkyblock2-2024.1-b266.jar//com.bgsoftware.superiorskyblock.api.modules.PluginModule.initModule(PluginModule.java:271)
[19.07 20:50:15] [Server] [WARN] 	at SuperiorSkyblock2-2024.1-b266.jar//com.bgsoftware.superiorskyblock.module.container.DefaultModulesContainer.registerModule(DefaultModulesContainer.java:41)
[19.07 20:50:15] [Server] [WARN] 	at SuperiorSkyblock2-2024.1-b266.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.registerModule(ModulesManagerImpl.java:58)
[19.07 20:50:15] [Server] [WARN] 	at SuperiorSkyblock2-2024.1-b266.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.loadData(ModulesManagerImpl.java:51)
[19.07 20:50:15] [Server] [WARN] 	at SuperiorSkyblock2-2024.1-b266.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:221)
[19.07 20:50:15] [Server] [WARN] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works afterwards

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed
If the issue still occurs, let me know
