### ISSUE TITLE
SuperiorSkyBlock crashing server

### ISSUE THREAD

**Issue by Envqu** [BG-Software-LLC/SuperiorSkyblock2#2157]
### Minecraft's Version

1.20.4 Purpur 2176

### Plugin's Version

2024.1-b266

### Describe the bug

Error appears in console and then server crashing and not responding.
[https://pastebin.com/ELDuePTy](https://pastebin.com/ELDuePTy)

### To Reproduce

Its happens 2 times a day

**Comment by Envqu** [comment]
b262 - i think it were more stable because it doesnt crash server few times a day but still happened 1 time

https://pastebin.com/phWwWBwt
[16:08:16 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while waiting for tasks to complete:
[16:08:16 WARN]: java.util.concurrent.TimeoutException
[16:08:16 WARN]:        at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
[16:08:16 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
[16:08:16 WARN]:        at SuperiorSkyblock2-2024.1-b262.jar//com.bgsoftware.superiorskyblock.core.collections.CompletableFutureList.forEachCompleted(CompletableFutureList.java:33)
[16:08:16 WARN]:        at SuperiorSkyblock2-2024.1-b262.jar//com.bgsoftware.superiorskyblock.island.algorithm.DefaultIslandCalculationAlgorithm.lambda$calculateIsland$10(DefaultIslandCalculationAlgorithm.java:90)
[16:08:16 WARN]:        at SuperiorSkyblock2-2024.1-b262.jar//com.bgsoftware.superiorskyblock.core.threads.BukkitExecutor$NestedTask.lambda$null$6(BukkitExecutor.java:157)
[16:08:16 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[16:08:16 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[16:08:16 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:08:16 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[16:08:16 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[16:08:16 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by OmerBenGera** [comment]
Use latest dev build, I added more debug messages to better understand what the issue is

**Comment by Envqu** [comment]
I cant until https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/2158 wont be fixed

**Comment by OmerBenGera** [comment]
The issue you mentioned was fixed in latest dev build.
Update me on the status of this issue.

**Comment by Envqu** [comment]
For now nothing happened. I will make new issue when this will repeat

**Comment by Envqu** [comment]
Unfortunatelly it happend again.
I sent logs in discord ticket

**Comment by OmerBenGera** [comment]
Check out latest dev build, should be fixed

**Comment by Envqu** [comment]
Nothing happened so I thinks it work as it should
