### ISSUE TITLE
Error occurring due to command

### ISSUE THREAD

**Issue by RigerCrows** [BG-Software-LLC/SuperiorSkyblock2#2161]
### Minecraft's Version

SWM 1.20.6

### Plugin's Version

2024.1 11/05/2024 19:46:51

### Describe the bug

When we use the /is top command, we get the following error.

```
[14:41:31 INFO]: RigerCrows issued server command: /is top
[14:41:31 WARN]: [SuperiorSkyblock2] Plugin SuperiorSkyblock2 v2024.1 generated an exception while executing task 720
java.lang.ClassCastException: class com.bgsoftware.superiorskyblock.nms.v1_20_3.algorithms.PaperGlowEnchantment cannot be cast to class org.bukkit.craftbukkit.util.Handleable (com.bgsoftware.superiorskyblock.nms.v1_20_3.algorithms.PaperGlowEnchantment is in unnamed module of loader 'SuperiorSkyblock2-2024.1.jar' @727a42db; org.bukkit.craftbukkit.util.Handleable is in unnamed module of loader java.net.URLClassLoader @7e32c033)
        at org.bukkit.craftbukkit.CraftRegistry.bukkitToMinecraft(CraftRegistry.java:98) ~[slimeworldmanager-1.20.6.jar:1.20.6-16004-7c72925]
        at org.bukkit.craftbukkit.enchantments.CraftEnchantment.bukkitToMinecraft(CraftEnchantment.java:33) ~[slimeworldmanager-1.20.6.jar:1.20.6-16004-7c72925]
        at org.bukkit.craftbukkit.inventory.CraftMetaItem.applyEnchantments(CraftMetaItem.java:888) ~[slimeworldmanager-1.20.6.jar:1.20.6-16004-7c72925]
        at org.bukkit.craftbukkit.inventory.CraftMetaItem.applyToItem(CraftMetaItem.java:802) ~[slimeworldmanager-1.20.6.jar:1.20.6-16004-7c72925]
        at org.bukkit.craftbukkit.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:706) ~[slimeworldmanager-1.20.6.jar:1.20.6-16004-7c72925]
        at org.bukkit.craftbukkit.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:63) ~[slimeworldmanager-1.20.6.jar:1.20.6-16004-7c72925]
        at org.bukkit.craftbukkit.inventory.CraftInventory.setItem(CraftInventory.java:100) ~[slimeworldmanager-1.20.6.jar:1.20.6-16004-7c72925]
        at SuperiorSkyblock2-2024.1.jar/com.bgsoftware.superiorskyblock.core.menu.layout.PagedMenuLayoutImpl.populateInventoryWithButton(PagedMenuLayoutImpl.java:126) ~[SuperiorSkyblock2-2024.1.jar:?]
        at SuperiorSkyblock2-
```

### To Reproduce

When we use the /is top command, we get the following error.

### Additional Information

When we use the /is top command, we get the following error.

**Comment by OmerBenGera** [comment]
Update to latest dev build
