### ISSUE TITLE
1.21 Server Shutdown SS2 Dev Build#271

### ISSUE THREAD

**Issue by kristophergeou** [BG-Software-LLC/SuperiorSkyblock2#2175]
### Minecraft's Version

![Screenshot 2024-07-25 201320](https://github.com/user-attachments/assets/76982c32-7c11-4e37-b16f-2047e86e6733)

### Plugin's Version

Dev Build #271

### Describe the bug

```yml
[18:00:55] [Server thread/INFO]: [SuperiorSkyblock2] Enabling SuperiorSkyblock2 v2024.1-b271
[18:00:55] [Server thread/ERROR]: [SuperiorSkyblock2] An unexpected error occurred while enabling the plugin:
[18:00:55] [Server thread/WARN]: java.lang.AssertionError: Missing intrusive holder for ResourceKey[minecraft:enchantment / minecraft:superiorskyblock_glowing_enchant]:Enchantment 
[18:00:55] [Server thread/WARN]: 	at net.minecraft.core.MappedRegistry.register(MappedRegistry.java:132)
[18:00:55] [Server thread/WARN]: 	at net.minecraft.core.Registry.register(Registry.java:119)
[18:00:55] [Server thread/WARN]: 	at net.minecraft.core.Registry.register(Registry.java:115)
[18:00:55] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.1-b271.jar//com.bgsoftware.superiorskyblock.nms.v1_21.enchantment.GlowEnchantment.lambda$initializeHandle$0(GlowEnchantment.java:44)
[18:00:55] [Server thread/WARN]: 	at java.base/java.util.Optional.ifPresent(Optional.java:178)
[18:00:55] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.1-b271.jar//com.bgsoftware.superiorskyblock.nms.v1_21.enchantment.GlowEnchantment.initializeHandle(GlowEnchantment.java:41)
[18:00:55] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.1-b271.jar//com.bgsoftware.superiorskyblock.nms.v1_21.enchantment.GlowEnchantment.<clinit>(GlowEnchantment.java:25)
[18:00:55] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.1-b271.jar//com.bgsoftware.superiorskyblock.nms.v1_21.NMSAlgorithmsImpl.getGlowEnchant(NMSAlgorithmsImpl.java:159)
[18:00:55] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.1-b271.jar//com.bgsoftware.superiorskyblock.nms.v1_21.NMSAlgorithmsImpl.createGlowEnchantment(NMSAlgorithmsImpl.java:164)
[18:00:55] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.1-b271.jar//com.bgsoftware.superiorskyblock.core.itemstack.GlowEnchantment.registerGlowEnchantment(GlowEnchantment.java:16)
[18:00:55] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.1-b271.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:209)
[18:00:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[18:00:55] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[18:00:55] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[18:00:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[18:00:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640)
[18:00:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589)
[18:00:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753)
[18:00:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515)
[18:00:55] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[18:00:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
[18:00:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[18:00:55] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### To Reproduce

1) Install the dev build 271 in your 1.21 Server
2) See the issue

### Additional Information

This issue forces the server to shut down and restart again. I tried to run the server without SuperiorSkyblock2 and it runs fine, but when installed back it crashes again. I don't know if it has anything to do with an enchant plugin since it mentions something about enchants but i use EcoEnchants

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
This is because you are missing `CAVE_VINES_PLANT` from the interactables list.
I recommend adding it to your interactables file so players cannot interact with them on other islands.

Closing this :)
