### ISSUE TITLE
/is disband BUG ERROR!

### ISSUE THREAD

**Issue by CngUmut** [BG-Software-LLC/SuperiorSkyblock2#2179]
### Minecraft's Version

1.16.5 Paper

### Plugin's Version

SuperiorSkyblock2-2024.1

### Describe the bug

When I delete the island, it does not teleport me to the spawn area. Also, an error comes to the console. And when I delete the island, the man does not disappear, but when I right click on a block, it goes directly.

```
[13:43:10] [Server thread/INFO]: [SuperiorSkyblock2] LocationSerializer::deserialize ENTER {Spawn,8.500,82.00000,8.500}
[13:43:10] [Server thread/ERROR]: [SuperiorSkyblock2] An unexpected error occurred while deserializing location:
[13:43:10] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[13:43:10] [Server thread/WARN]: 	at com.bgsoftware.superiorskyblock.core.serialization.impl.LocationSerializer.deserialize(LocationSerializer.java:39)
[13:43:10] [Server thread/WARN]: 	at com.bgsoftware.superiorskyblock.core.serialization.impl.LocationSerializer.deserialize(LocationSerializer.java:11)
[13:43:10] [Server thread/WARN]: 	at com.bgsoftware.superiorskyblock.island.SpawnIsland.<init>(SpawnIsland.java:105)
[13:43:10] [Server thread/WARN]: 	at com.bgsoftware.superiorskyblock.island.GridManagerImpl.updateSpawn(GridManagerImpl.java:123)
[13:43:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101)
[13:43:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485)
[13:43:10] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1083)
[13:43:10] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[13:43:10] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1589)
[13:43:10] [Server thread/WARN]: [SuperiorSkyblock2] Task #526 for SuperiorSkyblock2 v2024.1 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getWorld()" because "smartCenter" is null
	at com.bgsoftware.superiorskyblock.island.SpawnIsland.<init>(SpawnIsland.java:110) ~[?:?]
	at com.bgsoftware.superiorskyblock.island.GridManagerImpl.updateSpawn(GridManagerImpl.java:123) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-790]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1083) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-790]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
[13:43:10] [Server thread/INFO]: [SuperiorSkyblock2] Using LuckPerms as a permissions provider.
[13:43:10] [Server thread/INFO]: [SuperiorSkyblock2] Using ShopGUIPlus as a prices provider.
[13:43:10] [Server thread/INFO]: [SuperiorSkyblock2] Hooked into Essentials for support of vanish status of players.
[13:43:10] [Server thread/INFO]: [SuperiorSkyblock2] Hooked into Essentials for support of afk status of players.
[13:43:10] [Server thread/INFO]: [SuperiorSkyblock2] Using Vault as an economy provider.
[13:43:10] [Server thread/INFO]: [PlaceholderAPI] Successfully registered ınternal expansion: superior [2024.1]
[13:43:10] [Server thread/INFO]: [SuperiorSkyblock2] Using PlaceholderAPI for placeholders support.
[13:43:10] [Server thread/INFO]: [SuperiorSkyblock2] Detected PaperSpigot - Using async chunk-loading support with PaperMC.
```

### To Reproduce

/is disband

**Comment by OmerBenGera** [comment]
Correct your config file.
Put spaces between the x.y.z of the spawn location

**Comment by CngUmut** [comment]
![image](https://github.com/user-attachments/assets/03518944-f482-42f4-89f8-1b2bbace4c02)

**Comment by Srcsm** [comment]
> ![image](https://private-user-images.githubusercontent.com/132607555/352774632-03518944-f482-42f4-89f8-1b2bbace4c02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMjI1MTUsIm5iZiI6MTcyMjIyMjIxNSwicGF0aCI6Ii8xMzI2MDc1NTUvMzUyNzc0NjMyLTAzNTE4OTQ0LWY0ODItNDJmNC04OWY4LTFiMmJiYWNlNGMwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQwMzAzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTg1MmIwMDVlOWMxZWY2MWM2NTY1ZTkyZTVjNDQ4MWExYjYzMWUyOTUwYTE1OGZkOGU5OTQ0YzlkODhlZjQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.COpOy3FztFw7rcyVkS3cidiqsYneti2iAC_xqJDzpjw)

Looks like there's still a missing space immediately after `Spawn,`, add one after the comma.

**Comment by OmerBenGera** [comment]
I am closing this for now
Make sure you use the correct format for the spawn location.
