### ISSUE TITLE
Generator.jar of Acidisland module not work with SSB2 ver 1.12.x

### ISSUE THREAD

**Issue by MynamisTG** [BG-Software-LLC/SuperiorSkyblock2#2191]
### Minecraft's Version

1.12

### Plugin's Version

AcidIsand devbuild
SSB2 devbuild

### Describe the bug

Generator.jar Error With SSB2

### To Reproduce

[17:53:35 INFO]: [SuperiorSkyblock2] GridManagerImpl::createIslandInternalAsync Tigerr_VN {0} {0} {nac} {true} {PLAINS} {normal}
[17:53:35 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while creating an island:
[17:53:35 WARN]:        at com.bgsoftware.superiorskyblock.nms.v1_12_R1.world.WorldEditSessionImpl.setBlock(WorldEditSessionImpl.java:94)
[17:53:35 WARN]:        at com.bgsoftware.superiorskyblock.world.schematic.impl.SuperiorSchematic.lambda$pasteSchematicAsyncInternal$2(SuperiorSchematic.java:151)
[17:53:35 WARN]:        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082)
[17:53:35 WARN]:        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082)
[17:53:35 WARN]:        at com.bgsoftware.superiorskyblock.world.schematic.impl.SuperiorSchematic.pasteSchematicAsyncInternal(SuperiorSchematic.java:145)
[17:53:35 WARN]:        at com.bgsoftware.superiorskyblock.world.schematic.impl.SuperiorSchematic.pasteSchematic(SuperiorSchematic.java:130)
[17:53:35 WARN]:        at com.bgsoftware.superiorskyblock.world.schematic.impl.SuperiorSchematic.lambda$pasteSchematic$0(SuperiorSchematic.java:121)
[17:53:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[17:53:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[17:53:35 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:53:35 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[17:53:35 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

**Comment by OmerBenGera** [comment]
Been reported on the AcidIslands module :)
