### ISSUE TITLE
Generator.jar of Acidisland module not work with SSB2 ver 1.12.x

### ISSUE THREAD

**Issue by MynamisTG** [BG-Software-LLC/SuperiorSkyblock2#2192]
### Minecraft's Version

1.12

### Plugin's Version

AcidIsand devbuild
SSB2 devbuild

### Describe the bug

Generator.jar Error With SSB2

### To Reproduce

[17:53:35 INFO]: [SuperiorSkyblock2] GridManagerImpl::createIslandInternalAsync Tigerr_VN {0} {0} {nac} {true} {PLAINS} {normal}
[17:53:35 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while creating an island:
[17:53:35 WARN]: at com.bgsoftware.superiorskyblock.nms.v1_12_R1.world.WorldEditSessionImpl.setBlock(WorldEditSessionImpl.java:94)
[17:53:35 WARN]: at com.bgsoftware.superiorskyblock.world.schematic.impl.SuperiorSchematic.lambda$pasteSchematicAsyncInternal$2(SuperiorSchematic.java:151)
[17:53:35 WARN]: at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082)
[17:53:35 WARN]: at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082)
[17:53:35 WARN]: at com.bgsoftware.superiorskyblock.world.schematic.impl.SuperiorSchematic.pasteSchematicAsyncInternal(SuperiorSchematic.java:145)
[17:53:35 WARN]: at com.bgsoftware.superiorskyblock.world.schematic.impl.SuperiorSchematic.pasteSchematic(SuperiorSchematic.java:130)
[17:53:35 WARN]: at com.bgsoftware.superiorskyblock.world.schematic.impl.SuperiorSchematic.lambda$pasteSchematic$0(SuperiorSchematic.java:121)
[17:53:35 WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[17:53:35 WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[17:53:35 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:53:35 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[17:53:35 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by MynamisTG** [comment]
Fixed, Thank you. But it still drops tps 1-10 and made crash when the player has finished creating the island and probably the process of generating water. 
Link video: https://drive.google.com/file/d/1H-aHysENKb__8hFVvCcJEE9edzIkHQEa/view?usp=sharing
Log Crash:
 [10:46:06 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[10:46:06 ERROR]: The server has not responded for 10 seconds! Creating thread dump
[10:46:06 ERROR]: ------------------------------
[10:46:06 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[10:46:06 ERROR]: ------------------------------
[10:46:06 ERROR]: Current Thread: Server thread
[10:46:06 ERROR]:       PID: 29 | Suspended: false | Native: false | State: RUNNABLE
[10:46:06 ERROR]:       Stack:
[10:46:06 ERROR]:               com.bgsoftware.ssbacidislands.WaterGenerator.generateChunkData(WaterGenerator.java:112)
[10:46:06 ERROR]:               org.bukkit.craftbukkit.v1_12_R1.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:52)
[10:46:06 ERROR]:               com.bgsoftware.superiorskyblock.nms.v1_12_R1.NMSChunksImpl.removeBlocks(NMSChunksImpl.java:81)
[10:46:06 ERROR]:               com.bgsoftware.superiorskyblock.nms.v1_12_R1.NMSChunksImpl.access$100(NMSChunksImpl.java:57)
[10:46:06 ERROR]:               com.bgsoftware.superiorskyblock.nms.v1_12_R1.NMSChunksImpl$2.onChunk(NMSChunksImpl.java:146)
[10:46:06 ERROR]:               com.bgsoftware.superiorskyblock.nms.v1_12_R1.NMSUtils.lambda$runActionOnChunksInternal$3(NMSUtils.java:90)
[10:46:06 ERROR]:               com.bgsoftware.superiorskyblock.nms.v1_12_R1.NMSUtils$$Lambda$840/1029193025.accept(Unknown Source)
[10:46:06 ERROR]:               java.lang.Iterable.forEach(Unknown Source)
[10:46:06 ERROR]:               com.bgsoftware.superiorskyblock.nms.v1_12_R1.NMSUtils.runActionOnChunksInternal(NMSUtils.java:89)
[10:46:06 ERROR]:               com.bgsoftware.superiorskyblock.nms.v1_12_R1.NMSUtils.runActionOnChunks(NMSUtils.java:65)
[10:46:06 ERROR]:               com.bgsoftware.superiorskyblock.nms.v1_12_R1.NMSChunksImpl.deleteChunks(NMSChunksImpl.java:132)
[10:46:06 ERROR]:               com.bgsoftware.superiorskyblock.island.IslandUtils.deleteChunks(IslandUtils.java:246)
[10:46:06 ERROR]:               com.bgsoftware.superiorskyblock.island.SIsland.resetChunks(SIsland.java:1255)
[10:46:06 ERROR]:               com.bgsoftware.superiorskyblock.island.SIsland.disbandIsland(SIsland.java:1698)
[10:46:06 ERROR]:               com.bgsoftware.superiorskyblock.core.menu.button.impl.DisbandButton.onButtonClick(DisbandButton.java:52)
[10:46:06 ERROR]:               com.bgsoftware.superiorskyblock.api.menu.BaseMenu.onClick(BaseMenu.java:156)
[10:46:06 ERROR]:               com.bgsoftware.superiorskyblock.core.menu.AbstractMenu.onClick(AbstractMenu.java:48)
[10:46:06 ERROR]:               com.bgsoftware.superiorskyblock.core.menu.AbstractMenu.onClick(AbstractMenu.java:21)
[10:46:06 ERROR]:               com.bgsoftware.superiorskyblock.listener.MenusListener.onMenuClick(MenusListener.java:64)
[10:46:06 ERROR]:               java.lang.invoke.LambdaForm$DMH/537346910.invokeVirtual_LL_V(LambdaForm$DMH)
[10:46:06 ERROR]:               java.lang.invoke.LambdaForm$BMH/1747829262.reinvoke(LambdaForm$BMH)
[10:46:06 ERROR]:               java.lang.invoke.LambdaForm$MH/847981466.invoke_MT(LambdaForm$MH)
[10:46:06 ERROR]:               com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35)
[10:46:06 ERROR]:               co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[10:46:06 ERROR]:               org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[10:46:06 ERROR]:               org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[10:46:06 ERROR]:               net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2002)
[10:46:06 ERROR]:               net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
[10:46:06 ERROR]:               net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
[10:46:06 ERROR]:               net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[10:46:06 ERROR]:               net.minecraft.server.v1_12_R1.PlayerConnectionUtils$$Lambda$647/167407512.run(Unknown Source)
[10:46:06 ERROR]:               java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[10:46:06 ERROR]:               java.util.concurrent.FutureTask.run(Unknown Source)
[10:46:06 ERROR]:               net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[10:46:06 ERROR]:               net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[10:46:06 ERROR]:               net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[10:46:06 ERROR]:               net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[10:46:06 ERROR]:               net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[10:46:06 ERROR]:               java.lang.Thread.run(Unknown Source)
[10:46:06 ERROR]: ------------------------------
[10:46:06 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[10:46:06 ERROR]: ------------------------------

**Comment by MynamisTG** [comment]
Big Water chunk falling: https://gyazo.com/30e599101daee6ac48c67edadc6dd1bc

**Comment by OmerBenGera** [comment]
Check out latest dev build of SSB & AcidModule, let me know if it is better

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed
If the issue still occurs, let me know
