### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by xiej1** [BG-Software-LLC/SuperiorSkyblock2#2211]
### Minecraft's Version

1.18.1 Paper

### Plugin's Version

2024.2

### Describe the bug

I never seen that before.

### To Reproduce

[15:42:40] [Craft Scheduler Thread - 629 - SuperiorSkyblock2/ERROR]: [SuperiorSkyblock2] An unexpected error occurred while interacting with unloaded chunk SuperiorWorld, -791, 678:
[15:42:40] [Craft Scheduler Thread - 629 - SuperiorSkyblock2/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 513
[15:42:40] [Craft Scheduler Thread - 629 - SuperiorSkyblock2/WARN]: at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap.rehash(Long2ObjectLinkedOpenHashMap.java:1861)
[15:42:40] [Craft Scheduler Thread - 629 - SuperiorSkyblock2/WARN]: at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap.insert(Long2ObjectLinkedOpenHashMap.java:344)
[15:42:40] [Craft Scheduler Thread - 629 - SuperiorSkyblock2/WARN]: at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap.put(Long2ObjectLinkedOpenHashMap.java:352)
[15:42:40] [Craft Scheduler Thread - 629 - SuperiorSkyblock2/WARN]: at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.core.collections.creator.FastUtilCollectionsCreator$Long2ObjectFastUtilMapView.put(FastUtilCollectionsCreator.java:291)
[15:42:40] [Craft Scheduler Thread - 629 - SuperiorSkyblock2/WARN]: at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.core.collections.Chunk2ObjectMap.put(Chunk2ObjectMap.java:90)
[15:42:40] [Craft Scheduler Thread - 629 - SuperiorSkyblock2/WARN]: at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.core.collections.Chunk2ObjectMap.put(Chunk2ObjectMap.java:82)
[15:42:40] [Craft Scheduler Thread - 629 - SuperiorSkyblock2/WARN]: at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.core.collections.Chunk2ObjectMap.put(Chunk2ObjectMap.java:21)
[15:42:40] [Craft Scheduler Thread - 629 - SuperiorSkyblock2/WARN]: at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.nms.v1_18.NMSChunksImpl$3.onUnloadedChunk(NMSChunksImpl.java:369)
[15:42:40] [Craft Scheduler Thread - 629 - SuperiorSkyblock2/WARN]: at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.nms.v1_18.NMSUtils.lambda$runActionOnUnloadedChunks$3(NMSUtils.java:176)
[15:42:40] [Craft Scheduler Thread - 629 - SuperiorSkyblock2/WARN]: at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[15:42:40] [Craft Scheduler Thread - 629 - SuperiorSkyblock2/WARN]: at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.nms.v1_18.NMSUtils.lambda$runActionOnUnloadedChunks$4(NMSUtils.java:159)
[15:42:40] [Craft Scheduler Thread - 629 - SuperiorSkyblock2/WARN]: at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.core.threads.BukkitExecutor$NestedTask.lambda$null$4(BukkitExecutor.java:145)
[15:42:40] [Craft Scheduler Thread - 629 - SuperiorSkyblock2/WARN]: at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[15:42:40] [Craft Scheduler Thread - 629 - SuperiorSkyblock2/WARN]: at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[15:42:40] [Craft Scheduler Thread - 629 - SuperiorSkyblock2/WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:42:40] [Craft Scheduler Thread - 629 - SuperiorSkyblock2/WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:42:40] [Craft Scheduler Thread - 629 - SuperiorSkyblock2/WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:42:40] [Craft Scheduler Thread - 629 - SuperiorSkyblock2/WARN]: at java.base/java.lang.Thread.run(Thread.java:1583)
[15:42:40] [Craft Scheduler Thread - 838 - SuperiorSkyblock2/ERROR]: [SuperiorSkyblock2] An unexpected error occurred while interacting with unloaded chunk SuperiorWorld, 409, -72:
[15:42:40] [Craft Scheduler Thread - 838 - SuperiorSkyblock2/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 513
[15:42:40] [Craft Scheduler Thread - 838 - SuperiorSkyblock2/WARN]: at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap.rehash(Long2ObjectLinkedOpenHashMap.java:1861)
[15:42:40] [Craft Scheduler Thread - 838 - SuperiorSkyblock2/WARN]: at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap.insert(Long2ObjectLinkedOpenHashMap.java:344)
[15:42:40] [Craft Scheduler Thread - 838 - SuperiorSkyblock2/WARN]: at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap.put(Long2ObjectLinkedOpenHashMap.java:352)
[15:42:40] [Craft Scheduler Thread - 838 - SuperiorSkyblock2/WARN]: at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.core.collections.creator.FastUtilCollectionsCreator$Long2ObjectFastUtilMapView.put(FastUtilCollectionsCreator.java:291)
[15:42:40] [Craft Scheduler Thread - 838 - SuperiorSkyblock2/WARN]: at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.core.collections.Chunk2ObjectMap.put(Chunk2ObjectMap.java:90)
[15:42:40] [Craft Scheduler Thread - 838 - SuperiorSkyblock2/WARN]: at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.core.collections.Chunk2ObjectMap.put(Chunk2ObjectMap.java:82)
[15:42:40] [Craft Scheduler Thread - 838 - SuperiorSkyblock2/WARN]: at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.core.collections.Chunk2ObjectMap.put(Chunk2ObjectMap.java:21)
[15:42:40] [Craft Scheduler Thread - 838 - SuperiorSkyblock2/WARN]: at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.nms.v1_18.NMSChunksImpl$3.onUnloadedChunk(NMSChunksImpl.java:369)
[15:42:40] [Craft Scheduler Thread - 838 - SuperiorSkyblock2/WARN]: at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.nms.v1_18.NMSUtils.lambda$runActionOnUnloadedChunks$3(NMSUtils.java:176)
[15:42:40] [Craft Scheduler Thread - 838 - SuperiorSkyblock2/WARN]: at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[15:42:40] [Craft Scheduler Thread - 838 - SuperiorSkyblock2/WARN]: at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.nms.v1_18.NMSUtils.lambda$runActionOnUnloadedChunks$4(NMSUtils.java:159)
[15:42:40] [Craft Scheduler Thread - 838 - SuperiorSkyblock2/WARN]: at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.core.threads.BukkitExecutor$NestedTask.lambda$null$4(BukkitExecutor.java:145)
[15:42:40] [Craft Scheduler Thread - 838 - SuperiorSkyblock2/WARN]: at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[15:42:40] [Craft Scheduler Thread - 838 - SuperiorSkyblock2/WARN]: at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[15:42:40] [Craft Scheduler Thread - 838 - SuperiorSkyblock2/WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:42:40] [Craft Scheduler Thread - 838 - SuperiorSkyblock2/WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:42:40] [Craft Scheduler Thread - 838 - SuperiorSkyblock2/WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:42:40] [Craft Scheduler Thread - 838 - SuperiorSkyblock2/WARN]: at java.base/java.lang.Thread.run(Thread.java:1583)
[15:42:40] [Craft Scheduler Thread - 638 - SuperiorSkyblock2/ERROR]: [SuperiorSkyblock2] An unexpected error occurred while interacting with unloaded chunk SuperiorWorld, -861, -826:
[15:42:40] [Craft Scheduler Thread - 638 - SuperiorSkyblock2/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 513
[15:42:40] [Craft Scheduler Thread - 638 - SuperiorSkyblock2/WARN]: at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap.rehash(Long2ObjectLinkedOpenHashMap.java:1861)
[15:42:40] [Craft Scheduler Thread - 638 - SuperiorSkyblock2/WARN]: at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap.insert(Long2ObjectLinkedOpenHashMap.java:344)
[15:42:40] [Craft Scheduler Thread - 638 - SuperiorSkyblock2/WARN]: at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap.put(Long2ObjectLinkedOpenHashMap.java:352)
[15:42:40] [Craft Scheduler Thread - 638 - SuperiorSkyblock2/WARN]: at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.core.collections.creator.FastUtilCollectionsCreator$Long2ObjectFastUtilMapView.put(FastUtilCollectionsCreator.java:291)
[15:42:40] [Craft Scheduler Thread - 638 - SuperiorSkyblock2/WARN]: at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.core.collections.Chunk2ObjectMap.put(Chunk2ObjectMap.java:90)
[15:42:40] [Craft Scheduler Thread - 638 - SuperiorSkyblock2/WARN]: at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.core.collections.Chunk2ObjectMap.put(Chunk2ObjectMap.java:82)
[15:42:40] [Craft Scheduler Thread - 638 - SuperiorSkyblock2/WARN]: at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.core.collections.Chunk2ObjectMap.put(Chunk2ObjectMap.java:21)
[15:42:40] [Craft Scheduler Thread - 638 - SuperiorSkyblock2/WARN]: at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.nms.v1_18.NMSChunksImpl$3.onUnloadedChunk(NMSChunksImpl.java:369)
[15:42:40] [Craft Scheduler Thread - 638 - SuperiorSkyblock2/WARN]: at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.nms.v1_18.NMSUtils.lambda$runActionOnUnloadedChunks$3(NMSUtils.java:176)
[15:42:40] [Craft Scheduler Thread - 638 - SuperiorSkyblock2/WARN]: at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[15:42:40] [Craft Scheduler Thread - 638 - SuperiorSkyblock2/WARN]: at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.nms.v1_18.NMSUtils.lambda$runActionOnUnloadedChunks$4(NMSUtils.java:159)
[15:42:40] [Craft Scheduler Thread - 638 - SuperiorSkyblock2/WARN]: at SuperiorSkyblock2-2024.2.jar//com.bgsoftware.superiorskyblock.core.threads.BukkitExecutor$NestedTask.lambda$null$4(BukkitExecutor.java:145)
[15:42:40] [Craft Scheduler Thread - 638 - SuperiorSkyblock2/WARN]: at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[15:42:40] [Craft Scheduler Thread - 638 - SuperiorSkyblock2/WARN]: at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
SuperiorWorld, 412, -74:
[15:42:40] [Craft Scheduler Thread - 838 - SuperiorSkyblock2/WARN]: java.lang.ArrayIndexOutOfBoundsException
[15:42:40] [Craft Scheduler Thread - 629 - SuperiorSkyblock2/ERROR]: [SuperiorSkyblock2] An unexpected error occurred while interacting with unloaded chunk SuperiorWorld, -787, 671:
[15:42:40] [Craft Scheduler Thread - 629 - SuperiorSkyblock2/WARN]: java.lang.ArrayIndexOutOfBoundsException
[15:42:40] [Craft Scheduler Thread - 838 - SuperiorSkyblock2/ERROR]: [SuperiorSkyblock2] An unexpected error occurred while interacting with unloaded chunk SuperiorWorld, 412, -73:
[15:42:40] [Craft Scheduler Thread - 838 - SuperiorSkyblock2/WARN]: java.lang.ArrayIndexOutOfBoundsException
[15:42:40] [Craft Scheduler Thread - 629 - SuperiorSkyblock2/ERROR]: [SuperiorSkyblock2] An unexpected error occurred while interacting with unloaded chunk SuperiorWorld, -787, 672:

**Comment by xiej1** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

What is this lol

**Comment by Srcsm** [comment]
> > Download ........ password: changeme In the installer menu, select "gcc."
> 
> What is this lol

Do not download that, wait for Ome_R to address the issue. Running the link through VirusTotal and it gets flagged.

**Comment by xiej1** [comment]
Again servers is crashed.... i need help...

**Comment by OmerBenGera** [comment]
Update to latest dev build, fixed already
