### ISSUE TITLE
database doesn't like "$"-symbol in island-names when creating, island removed after restart

### ISSUE THREAD

**Issue by leon37921** [BG-Software-LLC/SuperiorSkyblock2#2218]
### Minecraft's Version

This server is running Paper version git-Paper-435 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 681bbff)

### Plugin's Version

SuperiorSkyblock2 version 2024.2-b315

### Describe the bug

When creating an island with the "$"-symbol in the name, the Island gets "removed" from the database.
The player can no longer teleport to that island and has to create a new one.

### To Reproduce

1. create Island `/is create $hello`
2. restart server

### Additional Information

renaming the island with the command `/is rename $hello` works fine. The island will not be removed.

Command /is create $hello: 
```
[23:06:03 WARN]: java.lang.IllegalArgumentException: Illegal group reference
[23:06:03 WARN]: 	at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1067)
[23:06:03 WARN]: 	at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:997)
[23:06:03 WARN]: 	at java.base/java.util.regex.Matcher.replaceFirst(Matcher.java:1407)
[23:06:03 WARN]: 	at SuperiorSkyblock2-2024.2-b315.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.addObject(SQLTransactionProcessor.java:105)
[23:06:03 WARN]: 	at SuperiorSkyblock2-2024.2-b315.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.populateStatement(SQLTransactionProcessor.java:96)
[23:06:03 WARN]: 	at SuperiorSkyblock2-2024.2-b315.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.executeTransaction(SQLTransactionProcessor.java:84)
[23:06:03 WARN]: 	at SuperiorSkyblock2-2024.2-b315.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.lambda$processTransaction$0(SQLTransactionProcessor.java:41)
[23:06:03 WARN]: 	at SuperiorSkyblock2-2024.2-b315.jar//com.bgsoftware.superiorskyblock.core.database.sql.session.QueryResult.complete(QueryResult.java:35)
[23:06:03 WARN]: 	at SuperiorSkyblock2-2024.2-b315.jar//com.bgsoftware.superiorskyblock.core.database.sql.session.impl.SQLiteSession.customQuery(SQLiteSession.java:170)
[23:06:03 WARN]: 	at SuperiorSkyblock2-2024.2-b315.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLHelper.customQuery(SQLHelper.java:91)
[23:06:03 WARN]: 	at SuperiorSkyblock2-2024.2-b315.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.executeQuery(SQLTransactionProcessor.java:110)
[23:06:03 WARN]: 	at SuperiorSkyblock2-2024.2-b315.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.processTransaction(SQLTransactionProcessor.java:36)
[23:06:03 WARN]: 	at SuperiorSkyblock2-2024.2-b315.jar//com.bgsoftware.superiorskyblock.core.database.transaction.DatabaseTransactionsExecutor.processTransaction(DatabaseTransactionsExecutor.java:115)
[23:06:03 WARN]: 	at SuperiorSkyblock2-2024.2-b315.jar//com.bgsoftware.superiorskyblock.core.database.transaction.DatabaseTransactionsExecutor.handleNextTransactionSafe(DatabaseTransactionsExecutor.java:105)
[23:06:03 WARN]: 	at SuperiorSkyblock2-2024.2-b315.jar//com.bgsoftware.superiorskyblock.core.database.transaction.DatabaseTransactionsExecutor.transactionsHandler(DatabaseTransactionsExecutor.java:83)
[23:06:03 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by leon37921** [comment]
fixed with b317, thank you
