### ISSUE TITLE
Cannot turn on SlimeWorldIslands

### ISSUE THREAD

**Issue by yhdev7935** [BG-Software-LLC/SuperiorSkyblock2#2229]
### Minecraft's Version

AdvancedSlimePaper version 1.21.1-16327-paper_upstream@89c4901 (2024-09-08T20:18:05Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Plugin's Version

2024.3 build

### Describe the bug

I've got an unexpected error while turning on the module SlimeWorldIslands.

I think the problem is that AdvancedSlimePaper changed the [plugin](https://infernalsuite.com/docs/asp/migrating/) itself when it came to version 1.21.1
I'm wondering if Ome_R will change their api for this version or if we should use a different method.

Thanks for supporting.

#### References
- https://infernalsuite.com/docs/asp/migrating/
- https://ci.infernalsuite.com/buildConfiguration/AdvancedSlimePaper_Build/2560?buildTab=artifacts

```
[11:02:45] [Server thread/INFO]: [SuperiorSkyblock2] Enabling the module SlimeWorldIslands...
[11:02:45] [Server thread/ERROR]: [SuperiorSkyblock2] An unexpected error occurred while enabling the module SlimeWorldIslands.
[11:02:45] [Server thread/ERROR]: [SuperiorSkyblock2] Contact Ome_R regarding this, this has nothing to do with the plugin.
[11:02:45] [Server thread/WARN]: java.lang.NoClassDefFoundError: com/grinderwolf/swm/api/exceptions/CorruptedWorldException
[11:02:45] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[11:02:45] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:534)
[11:02:45] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:513)
[11:02:45] [Server thread/WARN]: 	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68)
[11:02:45] [Server thread/WARN]: 	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source)
[11:02:45] [Server thread/WARN]: 	at com.bgsoftware.ssbslimeworldmanager.SlimeWorldModule.createAdapterInstance(SlimeWorldModule.java:153)
[11:02:45] [Server thread/WARN]: 	at com.bgsoftware.ssbslimeworldmanager.SlimeWorldModule.loadAdapter(SlimeWorldModule.java:134)
[11:02:45] [Server thread/WARN]: 	at com.bgsoftware.ssbslimeworldmanager.SlimeWorldModule.onEnable(SlimeWorldModule.java:45)
[11:02:45] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModule(ModulesManagerImpl.java:139)
[11:02:45] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[11:02:45] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[11:02:45] [Server thread/WARN]: 	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1249)
[11:02:45] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[11:02:45] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[11:02:45] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[11:02:45] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[11:02:45] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[11:02:45] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[11:02:45] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModulesInternal(ModulesManagerImpl.java:193)
[11:02:45] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.runModuleLifecycle(ModulesManagerImpl.java:184)
[11:02:45] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:236)
[11:02:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[11:02:45] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:211)
[11:02:45] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[11:02:45] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[11:02:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:641)
[11:02:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:590)
[11:02:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:769)
[11:02:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516)
[11:02:45] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[11:02:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230)
[11:02:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[11:02:45] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[11:02:45] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: com.grinderwolf.swm.api.exceptions.CorruptedWorldException
[11:02:45] [Server thread/WARN]: 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
[11:02:45] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.core.io.FileClassLoader.findClass(FileClassLoader.java:101)
[11:02:45] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
[11:02:45] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[11:02:45] [Server thread/WARN]: 	... 33 more
[11:02:45] [Server thread/INFO]: [SuperiorSkyblock2] Disabling the module SlimeWorldIslands...
```

### To Reproduce

1. Install AdvancedSlimePaper version 1.21.1-16327-paper_upstream
2. Install SuperiorSkyBlock2 2024.3 build
3. got the error while turning on the server

**Comment by OmerBenGera** [comment]
Make sure you install the ASP plugin as well on your server, alongside of the ASP spigot software itself.

**Comment by yhdev7935** [comment]
As I mentioned before, with the release of Minecraft 1.21.1, the ASP plugin has been completely reworked.
<img width="974" alt="image" src="https://github.com/user-attachments/assets/ae5a3657-27f9-45d5-83ed-df48fefea7d8">
https://infernalsuite.com/docs/asp/migrating/

**Comment by OmerBenGera** [comment]
You should still use it for now.
Hopefully in the future the need of the plugin will be removed.

**Comment by yhdev7935** [comment]
I understand that they have integrated it to avoid using the plugin even now. It's just that the API has been reworked in the integrated version, which makes ASP and superiorskyblock2 incompatible in the current 1.21 version.

I wish I could use it too. Unfortunately, it's not currently available at all.... :|

**Comment by OmerBenGera** [comment]
Just install the plugin... It works fine.
I will work on integrating the module with the new v3 API soon.

Closing this for now
