### ISSUE TITLE
Impossible to boot the server due to a ClassNotFoundException

### ISSUE THREAD

**Issue by lumi-git** [BG-Software-LLC/SuperiorSkyblock2#2232]
## Minecraft:
1.21

## JAVA:
java version "22.0.1" 2024-04-16
Java(TM) SE Runtime Environment (build 22.0.1+8-16)
Java HotSpot(TM) 64-Bit Server VM (build 22.0.1+8-16, mixed mode, sharing)

### Plugin's Version

v2024.3-b323 

### Describe the bug

Impossible to boot the server due to this error in the startup console: 

```
[17:48:13] [Server thread/ERROR]: net/kyori/adventure/text/Component initializing SuperiorSkyblock2 v2024.3-b323 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/text/Component
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:413) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:404) ~[?:?]
        at com.bgsoftware.superiorskyblock.libs.com.bgsoftware.common.nmsloader.method.BuiltinNMSHandlersFactoryMethod$BuiltinNMSLoader.findImplementationClass(BuiltinNMSHandlersFactoryMethod.java:55) ~[?:?]
        at com.bgsoftware.superiorskyblock.libs.com.bgsoftware.common.nmsloader.internal.BaseNMSLoader.loadNMSHandler(BaseNMSLoader.java:19) ~[?:?]
        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.loadNMSAdapter(SuperiorSkyblockPlugin.java:402) ~[?:?]
        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onLoad(SuperiorSkyblockPlugin.java:164) ~[?:?]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.loadPlugins(CraftServer.java:461) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:236) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.Component
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:160) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:112) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 12 more
```
Less detailed error here: 
```
[17:48:39] [Server thread/INFO]: [SuperiorSkyblock2] Enabling SuperiorSkyblock2 v2024.3-b323
[17:48:39] [Server thread/ERROR]: [SuperiorSkyblock2] ################################################
[17:48:39] [Server thread/ERROR]: [SuperiorSkyblock2] ##                                            ##
[17:48:39] [Server thread/ERROR]: [SuperiorSkyblock2] ## An error occured while loading the plugin! ##
[17:48:39] [Server thread/ERROR]: [SuperiorSkyblock2] ##                                            ##
[17:48:39] [Server thread/ERROR]: [SuperiorSkyblock2] ################################################
[17:48:39] [Server thread/ERROR]: [SuperiorSkyblock2]
[17:48:39] [Server thread/ERROR]: [SuperiorSkyblock2] Failed to load SuperiorSkyblock2.
[17:48:39] [Server thread/ERROR]: [SuperiorSkyblock2] Failed on NMS_INITIALIZED
[17:48:39] [Server thread/ERROR]: [SuperiorSkyblock2]
[17:48:39] [Server thread/ERROR]: [SuperiorSkyblock2] Shutting down the server...
[17:48:39] [Server thread/ERROR]: [SuperiorSkyblock2]
[17:48:39] [Server thread/ERROR]: [SuperiorSkyblock2] Stack Trace:
[17:48:39] [Server thread/ERROR]: [SuperiorSkyblock2]   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[17:48:39] [Server thread/ERROR]: [SuperiorSkyblock2]   at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[17:48:39] [Server thread/ERROR]: [SuperiorSkyblock2]   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492)
[17:48:39] [Server thread/ERROR]: [SuperiorSkyblock2]   at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:567)
[17:48:39] [Server thread/ERROR]: [SuperiorSkyblock2]   at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:481)
[17:48:39] [Server thread/ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641)
[17:48:39] [Server thread/ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426)
[17:48:39] [Server thread/ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:269)
[17:48:39] [Server thread/ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017)
[17:48:39] [Server thread/ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[17:48:39] [Server thread/ERROR]: [SuperiorSkyblock2]   at java.base/java.lang.Thread.run(Thread.java:1570)
[17:48:39] [Server thread/ERROR]: [SuperiorSkyblock2]
[17:48:39] [Server thread/ERROR]: [SuperiorSkyblock2] ################################################
```

### To Reproduce

1. Add the .jar in the plugin folder
2. run the server
3. bug fires

### Additional Information

My server works fine/no error in the console, if i remove the plugin.

**Comment by OmerBenGera** [comment]
Use Paper for now, and I will look into it

**Comment by lumi-git** [comment]
I is working under paper !

**Comment by OmerBenGera** [comment]
Fixed in latest dev build.
I recommend you to stay with Paper anyways :)
