### ISSUE TITLE
AdvancedSlimePaper world is already loaded

### ISSUE THREAD

**Issue by JanReich** [BG-Software-LLC/SuperiorSkyblock2#2237]
### Minecraft's Version

1.21.1

### Plugin's Version

2024.3-b323

### Describe the bug

[00:03:43 WARN]: [SuperiorSkyblock2] Task #110 for SuperiorSkyblock2 v2024.3-b323 generated an exception
java.lang.IllegalArgumentException: World island_5455aa8b-26c4-4c06-8e79-d91fabcd232c_normal is already loaded
	at com.infernalsuite.aswm.AdvancedSlimePaper.loadWorld(AdvancedSlimePaper.java:84) ~[slimeworldmanager-1.21.1.jar:1.21.1-16338-9ad4b57]
	at com.bgsoftware.ssbslimeworldmanager.swm.impl.asp3.SWMAdapter.generateWorld(SWMAdapter.java:122) ~[?:?]
	at com.bgsoftware.ssbslimeworldmanager.hook.SlimeWorldsProvider.generateWorld(SlimeWorldsProvider.java:255) ~[?:?]
	at com.bgsoftware.ssbslimeworldmanager.hook.SlimeWorldsProvider.lambda$null$3(SlimeWorldsProvider.java:240) ~[?:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[slimeworldmanager-1.21.1.jar:1.21.1-16338-9ad4b57]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[slimeworldmanager-1.21.1.jar:1.21.1-16338-9ad4b57]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1741) ~[slimeworldmanager-1.21.1.jar:1.21.1-16338-9ad4b57]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[slimeworldmanager-1.21.1.jar:1.21.1-16338-9ad4b57]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1613) ~[slimeworldmanager-1.21.1.jar:1.21.1-16338-9ad4b57]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1319) ~[slimeworldmanager-1.21.1.jar:1.21.1-16338-9ad4b57]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[slimeworldmanager-1.21.1.jar:1.21.1-16338-9ad4b57]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### To Reproduce

Use another Plugin that works With slime-world and loads world while joining.

### Additional Information

Additional Question: Is there a reason why SSB2 dont uses the SlimeWorld API v3?

**Comment by OmerBenGera** [comment]
Check out latest dev build, should be fixed.
Regarding your question, SSB uses the SlimeWorld API v3 (the slime worlds module).

**Comment by JanReich** [comment]
This issue is fixed but I ranned into a new critical bug/issue and made a new [Bugreport #70](https://github.com/BG-Software-LLC/SSB-SlimeWorldManager/issues/70)

**Comment by OmerBenGera** [comment]
I will look into it :)
