### ISSUE TITLE
creating an island error + island is not being created

### ISSUE THREAD

**Issue by homerek111** [BG-Software-LLC/SuperiorSkyblock2#2241]
### Minecraft's Version

This server is running Paper version 1.21.1-77-master@4ff58c4 (2024-09-12T18:05:09Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Plugin's Version

2024.3-b330

oneblock version: 60

### Describe the bug

when trying to create an island it does not work + error happens 
if you try create it again it works good (first time always error)

after deleting and creating island again it works good (only the first create is broken)

BUT if you restart the server and then delete + create again your island bug happens again

### To Reproduce

[22:02:22 INFO]: → tester321
[22:02:25 INFO]: tester321 issued server command: /is
[22:02:28 INFO]: OneBlock » Pomyślnie zmieniono biom na Plains dla wyspy tester321.
[22:02:28 INFO]: OneBlock » Pomyślnie zaktualizowano poziom generator-rates dla wyspy tester321.
[22:02:28 INFO]: OneBlock » Pomyślnie wysłano wiadomosc do czlonków wyspy tester321!
[22:02:28 INFO]: OneBlock » Pomyślnie wysłano wiadomosc do czlonków wyspy tester321!
[22:02:28 INFO]: OneBlock » Pomyślnie wysłano wiadomosc do czlonków wyspy tester321!
[22:02:28 INFO]: OneBlock » Pomyślnie wysłano wiadomosc do czlonków wyspy tester321!
[22:02:28 INFO]: OneBlock » Pomyślnie wysłano wiadomosc do czlonków wyspy tester321!
[22:02:28 INFO]: OneBlock » Pomyślnie wysłano wiadomosc do czlonków wyspy tester321!
[22:02:28 INFO]: Changed title display times for tester321
[22:02:28 INFO]: Showing new subtitle for tester321
[22:02:28 INFO]: Showing new title for tester321
[22:02:28 INFO]: [NBTAPI] [NBTAPI] Found Minecraft: 1.21.1! Trying to find NMS support
[22:02:28 INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_21_R1' loaded!
[22:02:28 INFO]: [NBTAPI] [NBTAPI] Using the plugin 'CommandPanels' to create a bStats instance!
[22:02:28 INFO]: [SuperiorSkyblock2] GridManagerImpl::createIslandInternalAsync tester321 {0} {0} {} {true} {PLAINS} {normal}
[22:02:28 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while creating an island:
[22:02:28 WARN]: java.lang.NullPointerException
[22:02:28 WARN]:        at java.base/java.util.Objects.requireNonNull(Objects.java:233)
[22:02:28 WARN]:        at SuperiorSkyblock2-2024.3-b330.jar//com.bgsoftware.superiorskyblock.nms.v1_21.world.WorldEditSessionImpl.applyBlocks(WorldEditSessionImpl.java:171)
[22:02:28 WARN]:        at SuperiorSkyblock2-2024.3-b330.jar//com.bgsoftware.superiorskyblock.world.schematic.impl.SuperiorSchematic.lambda$null$3(SuperiorSchematic.java:171)
[22:02:28 WARN]:        at SuperiorSkyblock2-2024.3-b330.jar//com.bgsoftware.superiorskyblock.world.chunk.ChunksProvider.lambda$processPendingChunkLoadRequest$0(ChunksProvider.java:132)
[22:02:28 WARN]:        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[22:02:28 WARN]:        at SuperiorSkyblock2-2024.3-b330.jar//com.bgsoftware.superiorskyblock.world.chunk.ChunksProvider.processPendingChunkLoadRequest(ChunksProvider.java:132)
[22:02:28 WARN]:        at SuperiorSkyblock2-2024.3-b330.jar//com.bgsoftware.superiorskyblock.world.chunk.ChunksProvider.access$400(ChunksProvider.java:21)
[22:02:28 WARN]:        at SuperiorSkyblock2-2024.3-b330.jar//com.bgsoftware.superiorskyblock.world.chunk.ChunksProvider$ChunkLoadWorker.finishLoad(ChunksProvider.java:121)
[22:02:28 WARN]:        at SuperiorSkyblock2-2024.3-b330.jar//com.bgsoftware.superiorskyblock.world.chunk.ChunksProvider$ChunkLoadWorker.lambda$work$0(ChunksProvider.java:110)
[22:02:28 WARN]:        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
[22:02:28 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
[22:02:28 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[22:02:28 WARN]:        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
[22:02:28 WARN]:        at org.bukkit.craftbukkit.CraftWorld.lambda$getChunkAtAsync$13(CraftWorld.java:2434)
[22:02:28 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[22:02:28 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[22:02:28 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[22:02:28 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537)
[22:02:28 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[22:02:28 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[22:02:28 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514)
[22:02:28 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507)
[22:02:28 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[22:02:28 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466)
[22:02:28 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1588)
[22:02:28 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304)
[22:02:28 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[22:02:28 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by OmerBenGera** [comment]
Check out latest dev build, this should be fixed

**Comment by homerek111** [comment]
> Check out latest dev build, this should be fixed

It is fixed - I forgot to tell u
