### ISSUE TITLE
After upgrade to dev, cannot reset island and create new.

### ISSUE THREAD

**Issue by DarkRiderSVK** [BG-Software-LLC/SuperiorSkyblock2#2243]
### Minecraft's Version

Spigot 1.21.1

### Plugin's Version

latest dev

### Describe the bug

[10:56:10] [Server thread/INFO]: DarkRider issued server command: /is reset
[10:56:12] [Server thread/ERROR]: Could not pass event InventoryClickEvent to SuperiorSkyblock2 v2024.3-b330
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2763) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:71) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:14) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:35) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:162) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1270) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:203) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.util.thread.IAsyncTaskHandler.B(SourceFile:136) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.server.MinecraftServer.bv(MinecraftServer.java:1249) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.server.MinecraftServer.B(MinecraftServer.java:1242) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:145) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1207) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.server.MinecraftServer.v_(MinecraftServer.java:1214) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1078) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.lang.NoSuchFieldError: Class net.minecraft.server.MinecraftServer does not have member field 'net.minecraft.server.MinecraftServer$RollingAverage tps1'
        at com.bgsoftware.superiorskyblock.nms.v1_21.NMSAlgorithmsImpl.getCurrentTps(NMSAlgorithmsImpl.java:199) ~[?:?]
        at com.bgsoftware.superiorskyblock.core.profiler.ProfilerSession$Data.<init>(ProfilerSession.java:75) ~[?:?]
        at com.bgsoftware.superiorskyblock.core.profiler.ProfilerSession.<init>(ProfilerSession.java:29) ~[?:?]
        at com.bgsoftware.superiorskyblock.core.profiler.Profiler.start(Profiler.java:35) ~[?:?]
        at com.bgsoftware.superiorskyblock.core.profiler.Profiler.start(Profiler.java:31) ~[?:?]
        at com.bgsoftware.superiorskyblock.island.SIsland.disbandIsland(SIsland.java:1685) ~[?:?]
        at com.bgsoftware.superiorskyblock.core.menu.button.impl.DisbandButton.onButtonClick(DisbandButton.java:52) ~[?:?]
        at com.bgsoftware.superiorskyblock.api.menu.BaseMenu.onClick(BaseMenu.java:156) ~[?:?]
        at com.bgsoftware.superiorskyblock.core.menu.AbstractMenu.onClick(AbstractMenu.java:48) ~[?:?]
        at com.bgsoftware.superiorskyblock.core.menu.AbstractMenu.onClick(AbstractMenu.java:21) ~[?:?]
        at com.bgsoftware.superiorskyblock.listener.MenusListener.onMenuClick(MenusListener.java:64) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 21 more

NEXT BUG in insland CREATE

[10:59:25] [Server thread/INFO]: Ronnie issued server command: /is create Ronnie
[10:59:29] [Server thread/INFO]: [SuperiorSkyblock2] GridManagerImpl::createIsland ENTER {Ronnie} {normal} {PLAINS} {true}
[10:59:29] [Server thread/ERROR]: [SuperiorSkyblock2] An unexpected error occurred while creating an island:
[10:59:29] [Server thread/WARN]: java.lang.NoSuchFieldError: Class net.minecraft.server.MinecraftServer does not have member field 'net.minecraft.server.MinecraftServer$RollingAverage tps1'
[10:59:29] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.nms.v1_21.NMSAlgorithmsImpl.getCurrentTps(NMSAlgorithmsImpl.java:199)
[10:59:29] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.core.profiler.ProfilerSession$Data.<init>(ProfilerSession.java:75)
[10:59:29] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.core.profiler.ProfilerSession.<init>(ProfilerSession.java:29)
[10:59:29] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.core.profiler.Profiler.start(Profiler.java:35)
[10:59:29] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.core.profiler.Profiler.start(Profiler.java:27)
[10:59:29] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.island.algorithm.DefaultIslandCreationAlgorithm.createIsland(DefaultIslandCreationAlgorithm.java:76)
[10:59:29] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.island.GridManagerImpl.createIslandInternalAsync(GridManagerImpl.java:256)
[10:59:29] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.island.GridManagerImpl.createIsland(GridManagerImpl.java:227)
[10:59:29] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.island.GridManagerImpl.createIsland(GridManagerImpl.java:198)
[10:59:29] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.core.menu.impl.MenuIslandCreation.simulateClick(MenuIslandCreation.java:94)
[10:59:29] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.core.menu.button.impl.IslandCreationButton.onButtonClick(IslandCreationButton.java:47)
[10:59:29] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.api.menu.BaseMenu.onClick(BaseMenu.java:156)
[10:59:29] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.core.menu.AbstractMenu.onClick(AbstractMenu.java:48)
[10:59:29] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.core.menu.AbstractMenu.onClick(AbstractMenu.java:21)
[10:59:29] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.listener.MenusListener.onMenuClick(MenusListener.java:64)
[10:59:29] [Server thread/WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[10:59:29] [Server thread/WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[10:59:29] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[10:59:29] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[10:59:29] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601)
[10:59:29] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588)
[10:59:29] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2763)
[10:59:29] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:71)
[10:59:29] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:14)
[10:59:29] [Server thread/WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:35)
[10:59:29] [Server thread/WARN]:        at net.minecraft.server.TickTask.run(SourceFile:18)
[10:59:29] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:162)
[10:59:29] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
[10:59:29] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1270)
[10:59:29] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:203)
[10:59:29] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.B(SourceFile:136)
[10:59:29] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.bv(MinecraftServer.java:1249)
[10:59:29] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.B(MinecraftServer.java:1242)
[10:59:29] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:145)
[10:59:29] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1207)
[10:59:29] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.v_(MinecraftServer.java:1214)
[10:59:29] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1078)
[10:59:29] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[10:59:29] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
[10:59:47] [Server thread/INFO]: Ronnie lost connection: Disconnected
[10:59:47] [Server thread/WARN]: Now saving stats of player Ronnie
[10:59:47] [Server thread/INFO]: Ronnie left the game

### To Reproduce

/is reset
/is create

### Additional Information

The stable version of this plugin works fine on version 1.21.1. The only problem that is in the stable version is the problem with UnloadChunk. The dev version has many more problems, is unstable and unusable for players. Bugs with island generation, island reset etc...

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by DarkRiderSVK** [comment]
I can create and reset island now. But console spamming this:

`[13:26:16] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to SuperiorSkyblock2 v2024.3-b333
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.chunk.Chunk.unloadCallback(Chunk.java:595) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.server.level.PlayerChunk.lambda$updateFutures$7(PlayerChunk.java:324) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.server.level.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:167) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.server.level.PlayerChunk.a(PlayerChunk.java:334) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.server.level.ChunkMapDistance.lambda$runAllUpdates$1(ChunkMapDistance.java:128) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at net.minecraft.server.level.ChunkMapDistance.a(ChunkMapDistance.java:127) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.server.level.ChunkProviderServer.s(ChunkProviderServer.java:290) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.server.level.ChunkProviderServer$b.B(ChunkProviderServer.java:614) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.server.level.ChunkProviderServer.d(ChunkProviderServer.java:286) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.server.MinecraftServer.bv(MinecraftServer.java:1258) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.server.MinecraftServer.B(MinecraftServer.java:1242) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:145) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1207) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.server.MinecraftServer.v_(MinecraftServer.java:1214) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1078) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.lang.IllegalStateException: Chunk not there when requested: Unloaded chunk
        at net.minecraft.server.level.ChunkProviderServer.a(ChunkProviderServer.java:156) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at net.minecraft.world.level.World.a(World.java:298) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4314-Spigot-a759b62-bbb30e7]
        at com.bgsoftware.superiorskyblock.nms.v1_21.NMSUtils.getCraftChunkHandle(NMSUtils.java:387) ~[?:?]
        at com.bgsoftware.superiorskyblock.nms.v1_21.NMSChunksImpl.isChunkEmpty(NMSChunksImpl.java:429) ~[?:?]
        at com.bgsoftware.superiorskyblock.listener.ChunksListener.handleIslandChunkUnload(ChunksListener.java:87) ~[?:?]
        at com.bgsoftware.superiorskyblock.listener.ChunksListener.lambda$handleChunkUnload$0(ChunksListener.java:79) ~[?:?]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1117) ~[?:?]
        at com.bgsoftware.superiorskyblock.listener.ChunksListener.handleChunkUnload(ChunksListener.java:77) ~[?:?]
        at com.bgsoftware.superiorskyblock.listener.ChunksListener.onChunkUnloadMonitor(ChunksListener.java:60) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 21 more`

**Comment by OmerBenGera** [comment]
Already fixed in latest dev build.
If it still occurs, open a new issue.
