### ISSUE TITLE
console error spams quite a lot

### ISSUE THREAD

**Issue by homerek111** [BG-Software-LLC/SuperiorSkyblock2#2244]
### Minecraft's Version

This server is running Paper version 1.21.1-100-master@20ec622 (2024-09-26T23:53:46Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Plugin's Version

2024.3-b330

### Describe the bug

[13:32:38 ERROR]: [SuperiorSkyblock2] An error occurred while uploading stats:
[13:32:38 WARN]: java.lang.RuntimeException: Received error when submitting stats: MySQL Connection not available
[13:32:38 WARN]:        at SuperiorSkyblock2-2024.3-b330.jar//com.bgsoftware.superiorskyblock.core.stats.StatsClient.submitStats(StatsClient.java:117)
[13:32:38 WARN]:        at SuperiorSkyblock2-2024.3-b330.jar//com.bgsoftware.superiorskyblock.core.stats.StatsClient.collectStatsTask(StatsClient.java:84)
[13:32:38 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[13:32:38 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
[13:32:38 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[13:32:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[13:32:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[13:32:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

### To Reproduce

idk when it happens - players are just playing

**Comment by OmerBenGera** [comment]
The error is harmless, so don't worry about that.
Anyways, I hopefully fixed it. You don't need to update anything.
If it still occurs, let me know.
