### ISSUE TITLE
Command /is admin setbiome makes the server crash

### ISSUE THREAD

**Issue by UneVentouse2** [BG-Software-LLC/SuperiorSkyblock2#226]
**Minecraft's Version**
TacoSpigot (is a paper fork) - 1.8.8 - Java 8

**Plugin's Version**: -
Version 1.5.2

**Describe the bug**
When I run the command /is admin setbiome (player) (biome) in order to modify the biome of an island, it makes the server crash completely and it stops by itself but on the other hand after the restart the biome is correctly set on the island in question.

**To Reproduce**
Run the command /is admin setbiome (player) (biome)

**Additional information**
Error in the console before the server stops :

```
[18:40:28 ERROR]: stopTiming called async for Islands - syncChunkLoad - Data
[18:40:28 WARN]:        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:114)
[18:40:28 WARN]:        at net.minecraft.server.v1_8_R3.ChunkRegionLoader.a(ChunkRegionLoader.java:48)
[18:40:28 WARN]:        at com.bgsoftware.superiorskyblock.nms.NMSBlocks_v1_8_R3.runActionOnChunk(NMSBlocks_v1_8_R3.java:348)
[18:40:28 WARN]:        at com.bgsoftware.superiorskyblock.nms.NMSBlocks_v1_8_R3.runActionOnChunk(NMSBlocks_v1_8_R3.java:330)
[18:40:28 WARN]:        at com.bgsoftware.superiorskyblock.nms.NMSBlocks_v1_8_R3.setChunkBiome(NMSBlocks_v1_8_R3.java:323)
[18:40:28 WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.lambda$setBiome$61(SIsland.java:1376)
[18:40:28 WARN]:        at java.util.ArrayList.forEach(ArrayList.java:1259)
[18:40:28 WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.setBiome(SIsland.java:1375)
[18:40:28 WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.setBiome(SIsland.java:1364)
[18:40:28 WARN]:        at com.bgsoftware.superiorskyblock.commands.admin.CmdAdminSetBiome.lambda$null$0(CmdAdminSetBiome.java:72)
[18:40:28 WARN]:        at java.util.ArrayList.forEach(ArrayList.java:1259)
[18:40:28 WARN]:        at com.bgsoftware.superiorskyblock.commands.admin.CmdAdminSetBiome.lambda$execute$1(CmdAdminSetBiome.java:72)
[18:40:28 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[18:40:28 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[18:40:28 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by OmerBenGera** [comment]
Should be fixed in latest build.
