### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Xitryne** [BG-Software-LLC/SuperiorSkyblock2#2262]
### Minecraft's Version

Paper 1.20.4

### Plugin's Version

2024.3

### Describe the bug

```
[06:15:41] [Thread-7/ERROR]: [SuperiorSkyblock2] Detected crash. SuperiorSkyblock will attempt to save data...
[06:15:41] [Thread-7/WARN]: [SuperiorSkyblock2] Trying to cancel all island previews asynchronous. Stack trace:
[06:15:41] [Thread-7/WARN]: java.lang.Exception
[06:15:41] [Thread-7/WARN]: 	at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.island.GridManagerImpl.cancelAllIslandPreviewsSync(GridManagerImpl.java:431)
[06:15:41] [Thread-7/WARN]: 	at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.core.threads.BukkitExecutor.sync(BukkitExecutor.java:45)
[06:15:41] [Thread-7/WARN]: 	at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.core.threads.BukkitExecutor.sync(BukkitExecutor.java:37)
[06:15:41] [Thread-7/WARN]: 	at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.island.GridManagerImpl.cancelAllIslandPreviews(GridManagerImpl.java:422)
[06:15:41] [Thread-7/WARN]: 	at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.island.GridManagerImpl.disablePlugin(GridManagerImpl.java:927)
[06:15:41] [Thread-7/WARN]: 	at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onDisable(SuperiorSkyblockPlugin.java:333)
[06:15:41] [Thread-7/WARN]: 	at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.core.task.ShutdownTask.run(ShutdownTask.java:18)
```

### To Reproduce

I have no idea

**Comment by OmerBenGera** [comment]
Upload the entire stack trace to pastebin and send a link to it here

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue still occurs, let me know
