### ISSUE TITLE
java.lang.NoSuchFieldError: Class org.bukkit.craftbukkit.util.CraftMagicNumbers does not have member field 'org.bukkit.UnsafeValues INSTANCE'

### ISSUE THREAD

**Issue by topg-org** [BG-Software-LLC/SuperiorSkyblock2#2264]
### Minecraft's Version

1.21.1

### Plugin's Version

SuperiorSkyblock2 (2024.3-b341) dev I tried even latest stable version same issue

### Describe the bug

[10:41:12] [Server thread/ERROR]: [SuperiorSkyblock2] An unexpected error occurred while enabling the plugin:
[10:41:12] [Server thread/WARN]: java.lang.NoSuchFieldError: Class org.bukkit.craftbukkit.util.CraftMagicNumbers does not have member field 'org.bukkit.UnsafeValues INSTANCE'
[10:41:12] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.3-b341.jar//com.bgsoftware.superiorskyblock.nms.v1_21.NMSTagsImpl.serializeItem(NMSTagsImpl.java:46)
[10:41:12] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.3-b341.jar//com.bgsoftware.superiorskyblock.config.SettingsContainer.<init>(SettingsContainer.java:428)
[10:41:12] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.3-b341.jar//com.bgsoftware.superiorskyblock.config.SettingsManagerImpl.loadContainerFromConfig(SettingsManagerImpl.java:603)
[10:41:12] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.3-b341.jar//com.bgsoftware.superiorskyblock.config.SettingsManagerImpl.loadData(SettingsManagerImpl.java:83)
[10:41:12] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.3-b341.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:216)
[10:41:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[10:41:12] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[10:41:12] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[10:41:12] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[10:41:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:641)
[10:41:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:590)
[10:41:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753)
[10:41:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515)
[10:41:12] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[10:41:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
[10:41:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[10:41:12] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)

### To Reproduce

Paper 1.21.1-128

**Comment by topg-org** [comment]
Duplicate
