### ISSUE TITLE
java.lang.IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by topg-org** [BG-Software-LLC/SuperiorSkyblock2#2270]
### Minecraft's Version

paper-1.21-103

### Plugin's Version

SuperiorSkyblock2 v2024.3-b341 (dev)

### Describe the bug

[Server thread/INFO]: [!] Island → Recalculating all islands...
[WARN]: [SuperiorSkyblock2] Plugin SuperiorSkyblock2 v2024.3-b341 generated an exception while executing task 8472
java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.base/java.util.TimSort.mergeLo(TimSort.java:781) ~[?:?]
        at java.base/java.util.TimSort.mergeAt(TimSort.java:518) ~[?:?]
        at java.base/java.util.TimSort.mergeForceCollapse(TimSort.java:461) ~[?:?]
        at java.base/java.util.TimSort.sort(TimSort.java:254) ~[?:?]
        at java.base/java.util.Arrays.sort(Arrays.java:1308) ~[?:?]
        at java.base/java.util.ArrayList.sort(ArrayList.java:1804) ~[?:?]
        at SuperiorSkyblock2-2024.3-b341.jar/com.bgsoftware.superiorskyblock.island.container.DefaultIslandsContainer.sortIslandsInternal(DefaultIslandsContainer.java:187) ~[SuperiorSkyblock2-2024.3-b341.jar:?]
        at SuperiorSkyblock2-2024.3-b341.jar/com.bgsoftware.superiorskyblock.island.container.DefaultIslandsContainer.lambda$sortIslands$8(DefaultIslandsContainer.java:150) ~[SuperiorSkyblock2-2024.3-b341.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.jar:1.21-103-aa3b356]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.jar:1.21-103-aa3b356]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### To Reproduce

Idk exactly, all data is in mysql, nothing weird no null or absent values

**Comment by OmerBenGera** [comment]
I don't know why it occurs, but I added debug message to when it occurs to print more information regarding the error.
Please update to latest dev build and report back once it occurs again so I can look at the debug data that is printed.

**Comment by topg-org** [comment]
[15:37:10 INFO]: [!] Island → Successfully finished recalculating all islands.
[15:37:10 WARN]: [SuperiorSkyblock2] Plugin SuperiorSkyblock2 v2024.3-b361 generated an exception while executing task 344232
java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.base/java.util.TimSort.mergeLo(TimSort.java:781) ~[?:?]
        at java.base/java.util.TimSort.mergeAt(TimSort.java:518) ~[?:?]
        at java.base/java.util.TimSort.mergeCollapse(TimSort.java:448) ~[?:?]
        at java.base/java.util.TimSort.sort(TimSort.java:245) ~[?:?]
        at java.base/java.util.Arrays.sort(Arrays.java:1308) ~[?:?]
        at java.base/java.util.ArrayList.sort(ArrayList.java:1804) ~[?:?]
        at SuperiorSkyblock2-2024.3-b361.jar/com.bgsoftware.superiorskyblock.island.container.DefaultIslandsContainer.sortIslandsInternal(DefaultIslandsContainer.java:189) ~[SuperiorSkyblock2-2024.3-b361.jar:?]
        at SuperiorSkyblock2-2024.3-b361.jar/com.bgsoftware.superiorskyblock.island.container.DefaultIslandsContainer.lambda$sortIslands$8(DefaultIslandsContainer.java:151) ~[SuperiorSkyblock2-2024.3-b361.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
>

**Comment by topg-org** [comment]
Idk if it's worth mentioning but I use MariaDB as storage

**Comment by OmerBenGera** [comment]
> DefaultIslandsContainer

I don't see the warning message I added.
Are you sure this is the entire error? 
Do you see in the logs the following message? `An error occurred while sorting islands for sorting-type`

**Comment by topg-org** [comment]
Yes that’s the whole error, it just repeats it self

**Comment by OmerBenGera** [comment]
> Yes that’s the whole error, it just repeats it self

Can you send me your latest.log file?

**Comment by topg-org** [comment]
Sure, here you go: https://paste.denizenscript.com/View/128404

**Comment by OmerBenGera** [comment]
Check out latest dev build, should be fixed

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue still occurs, let me know
