### ISSUE TITLE
The plugin seem to not working on 1.21.1

### ISSUE THREAD

**Issue by TitouBonnie** [BG-Software-LLC/SuperiorSkyblock2#2279]
### Minecraft's Version

Paper 1.21.1

### Plugin's Version

Latest

### Describe the bug

It look like the plugin is not working with 1.21.1
I tried updating it from 1.20.4 but some error message appear and the plugin won't load

### To Reproduce

Idk cause it's not working in game

### Additional Information

```
[16:01:00 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while enabling the plugin:
[16:01:00 WARN]: java.lang.NoSuchFieldError: Class org.bukkit.craftbukkit.util.CraftMagicNumbers does not have member field 'org.bukkit.UnsafeValues INSTANCE'
[16:01:00 WARN]:        at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.nms.v1_21.NMSTagsImpl.serializeItem(NMSTagsImpl.java:46)
[16:01:00 WARN]:        at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.config.SettingsContainer.<init>(SettingsContainer.java:428)
[16:01:00 WARN]:        at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.config.SettingsManagerImpl.loadContainerFromConfig(SettingsManagerImpl.java:598)
[16:01:00 WARN]:        at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.config.SettingsManagerImpl.loadData(SettingsManagerImpl.java:83)
[16:01:00 WARN]:        at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:213)
[16:01:00 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[16:01:00 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[16:01:00 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[16:01:00 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[16:01:00 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:641)
[16:01:00 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:590)
[16:01:00 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753)
[16:01:00 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515)
[16:01:00 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[16:01:00 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
[16:01:00 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[16:01:00 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by OmerBenGera** [comment]
Use latest dev build, this was fixed already.
