### ISSUE TITLE
Error SuperiorSkyblock  is not working on paper 1.21

### ISSUE THREAD

**Issue by elhadesgamer97** [BG-Software-LLC/SuperiorSkyblock2#2282]
### Minecraft's Version

paper1.21.1-131

### Plugin's Version

SuperiorSkyblock2-2024.3.jar

### Describe the bug

I updated my server to 1.21.1 and the Superiorskyblock2 plugin stopped working

[20:46:07 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while enabling the plugin:
[20:46:07 WARN]: java.lang.NoSuchFieldError: Class org.bukkit.craftbukkit.util.CraftMagicNumbers does not have member field 'org.bukkit.UnsafeValues INSTANCE'
[20:46:07 WARN]:        at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.nms.v1_21.NMSTagsImpl.serializeItem(NMSTagsImpl.java:46)
[20:46:07 WARN]:        at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.config.SettingsContainer.<init>(SettingsContainer.java:428)
[20:46:07 WARN]:        at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.config.SettingsManagerImpl.loadContainerFromConfig(SettingsManagerImpl.java:598)
[20:46:07 WARN]:        at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.config.SettingsManagerImpl.loadData(SettingsManagerImpl.java:83)
[20:46:07 WARN]:        at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:213)
[20:46:07 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[20:46:07 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[20:46:07 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[20:46:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[20:46:07 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:641)
[20:46:07 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:590)
[20:46:07 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753)
[20:46:07 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515)
[20:46:07 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[20:46:07 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
[20:46:07 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[20:46:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

### To Reproduce

[20:46:07 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while enabling the plugin:
[20:46:07 WARN]: java.lang.NoSuchFieldError: Class org.bukkit.craftbukkit.util.CraftMagicNumbers does not have member field 'org.bukkit.UnsafeValues INSTANCE'
[20:46:07 WARN]:        at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.nms.v1_21.NMSTagsImpl.serializeItem(NMSTagsImpl.java:46)
[20:46:07 WARN]:        at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.config.SettingsContainer.<init>(SettingsContainer.java:428)
[20:46:07 WARN]:        at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.config.SettingsManagerImpl.loadContainerFromConfig(SettingsManagerImpl.java:598)
[20:46:07 WARN]:        at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.config.SettingsManagerImpl.loadData(SettingsManagerImpl.java:83)
[20:46:07 WARN]:        at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:213)
[20:46:07 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[20:46:07 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[20:46:07 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[20:46:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[20:46:07 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:641)
[20:46:07 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:590)
[20:46:07 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753)
[20:46:07 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515)
[20:46:07 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[20:46:07 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
[20:46:07 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[20:46:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

### Additional Information

When you start the server, it restarts automatically due to that plugin error.

**Comment by OmerBenGera** [comment]
Update to latest dev build

**Comment by elhadesgamer97** [comment]
I downloaded the latest version that appears on the page and I still get that error.


[21:04:15 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while enabling the plugin:
[21:04:15 WARN]: java.lang.NoSuchFieldError: Class org.bukkit.craftbukkit.util.CraftMagicNumbers does not have member field 'org.bukkit.UnsafeValues INSTANCE'
[21:04:15 WARN]:        at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.nms.v1_21.NMSTagsImpl.serializeItem(NMSTagsImpl.java:46)
[21:04:15 WARN]:        at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.config.SettingsContainer.<init>(SettingsContainer.java:428)
[21:04:15 WARN]:        at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.config.SettingsManagerImpl.loadContainerFromConfig(SettingsManagerImpl.java:598)
[21:04:15 WARN]:        at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.config.SettingsManagerImpl.loadData(SettingsManagerImpl.java:83)
[21:04:15 WARN]:        at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:213)
[21:04:15 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[21:04:15 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[21:04:15 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[21:04:15 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[21:04:15 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:641)
[21:04:15 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:590)
[21:04:15 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753)
[21:04:15 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515)
[21:04:15 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[21:04:15 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
[21:04:15 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[21:04:15 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by elhadesgamer97** [comment]
> Update to latest dev build

I downloaded the latest version that appears on the page and I still get that error.

[21:04:15 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while enabling the plugin:
[21:04:15 WARN]: java.lang.NoSuchFieldError: Class org.bukkit.craftbukkit.util.CraftMagicNumbers does not have member field 'org.bukkit.UnsafeValues INSTANCE'
[21:04:15 WARN]: at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.nms.v1_21.NMSTagsImpl.serializeItem(NMSTagsImpl.java:46)
[21:04:15 WARN]: at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.config.SettingsContainer.(SettingsContainer.java:428)
[21:04:15 WARN]: at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.config.SettingsManagerImpl.loadContainerFromConfig(SettingsManagerImpl.java:598)
[21:04:15 WARN]: at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.config.SettingsManagerImpl.loadData(SettingsManagerImpl.java:83)
[21:04:15 WARN]: at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:213)
[21:04:15 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[21:04:15 WARN]: at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[21:04:15 WARN]: at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[21:04:15 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[21:04:15 WARN]: at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:641)
[21:04:15 WARN]: at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:590)
[21:04:15 WARN]: at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753)
[21:04:15 WARN]: at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515)
[21:04:15 WARN]: at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[21:04:15 WARN]: at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
[21:04:15 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[21:04:15 WARN]: at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by OmerBenGera** [comment]
> > Update to latest dev build
> 
> I downloaded the latest version that appears on the page and I still get that error.
> 
> [21:04:15 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while enabling the plugin: [21:04:15 WARN]: java.lang.NoSuchFieldError: Class org.bukkit.craftbukkit.util.CraftMagicNumbers does not have member field 'org.bukkit.UnsafeValues INSTANCE' [21:04:15 WARN]: at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.nms.v1_21.NMSTagsImpl.serializeItem(NMSTagsImpl.java:46) [21:04:15 WARN]: at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.config.SettingsContainer.(SettingsContainer.java:428) [21:04:15 WARN]: at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.config.SettingsManagerImpl.loadContainerFromConfig(SettingsManagerImpl.java:598) [21:04:15 WARN]: at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.config.SettingsManagerImpl.loadData(SettingsManagerImpl.java:83) [21:04:15 WARN]: at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:213) [21:04:15 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) [21:04:15 WARN]: at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) [21:04:15 WARN]: at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) [21:04:15 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) [21:04:15 WARN]: at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:641) [21:04:15 WARN]: at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:590) [21:04:15 WARN]: at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) [21:04:15 WARN]: at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) [21:04:15 WARN]: at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) [21:04:15 WARN]: at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) [21:04:15 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) [21:04:15 WARN]: at java.base/java.lang.Thread.run(Thread.java:1583)

This is from latest stable build, not latest dev build

**Comment by elhadesgamer97** [comment]
> > > Update to latest dev build
> > 
> > 
> > I downloaded the latest version that appears on the page and I still get that error.
> > [21:04:15 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while enabling the plugin: [21:04:15 WARN]: java.lang.NoSuchFieldError: Class org.bukkit.craftbukkit.util.CraftMagicNumbers does not have member field 'org.bukkit.UnsafeValues INSTANCE' [21:04:15 WARN]: at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.nms.v1_21.NMSTagsImpl.serializeItem(NMSTagsImpl.java:46) [21:04:15 WARN]: at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.config.SettingsContainer.(SettingsContainer.java:428) [21:04:15 WARN]: at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.config.SettingsManagerImpl.loadContainerFromConfig(SettingsManagerImpl.java:598) [21:04:15 WARN]: at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.config.SettingsManagerImpl.loadData(SettingsManagerImpl.java:83) [21:04:15 WARN]: at SuperiorSkyblock2-2024.3.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:213) [21:04:15 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) [21:04:15 WARN]: at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) [21:04:15 WARN]: at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) [21:04:15 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) [21:04:15 WARN]: at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:641) [21:04:15 WARN]: at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:590) [21:04:15 WARN]: at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) [21:04:15 WARN]: at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) [21:04:15 WARN]: at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) [21:04:15 WARN]: at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) [21:04:15 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) [21:04:15 WARN]: at java.base/java.lang.Thread.run(Thread.java:1583)
> 
> This is from latest stable build, not latest dev build

![image](https://github.com/user-attachments/assets/eb530377-9ac1-4906-8395-7f70b3a962c9)
