### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by HyNO-IR** [BG-Software-LLC/SuperiorSkyblock2#2292]
### Minecraft's Version

1.20.1

### Plugin's Version

2024.4

### Describe the bug

[13:48:22 INFO]: [SuperiorSkyblock2] Enabling SuperiorSkyblock2 v2024.4
[13:48:22 ERROR]: [SuperiorSkyblock2] ################################################
[13:48:22 ERROR]: [SuperiorSkyblock2] ##                                            ##
[13:48:22 ERROR]: [SuperiorSkyblock2] ## An error occured while loading the plugin! ##
[13:48:22 ERROR]: [SuperiorSkyblock2] ##                                            ##
[13:48:22 ERROR]: [SuperiorSkyblock2] ################################################
[13:48:22 ERROR]: [SuperiorSkyblock2]  
[13:48:22 ERROR]: [SuperiorSkyblock2] Failed to load SuperiorSkyblock2.
[13:48:22 ERROR]: [SuperiorSkyblock2] Failed on NMS_INITIALIZED
[13:48:22 ERROR]: [SuperiorSkyblock2] 
[13:48:22 ERROR]: [SuperiorSkyblock2] Shutting down the server...
[13:48:22 ERROR]: [SuperiorSkyblock2]  
[13:48:22 ERROR]: [SuperiorSkyblock2] Stack Trace:
[13:48:22 ERROR]: [SuperiorSkyblock2]   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[13:48:22 ERROR]: [SuperiorSkyblock2]   at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[13:48:22 ERROR]: [SuperiorSkyblock2]   at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[13:48:22 ERROR]: [SuperiorSkyblock2]   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[13:48:22 ERROR]: [SuperiorSkyblock2]   at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
[13:48:22 ERROR]: [SuperiorSkyblock2]   at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
[13:48:22 ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
[13:48:22 ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
[13:48:22 ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[13:48:22 ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
[13:48:22 ERROR]: [SuperiorSkyblock2]   at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[13:48:22 ERROR]: [SuperiorSkyblock2]   at java.base/java.lang.Thread.run(Thread.java:1583)
[13:48:22 ERROR]: [SuperiorSkyblock2]  
[13:48:22 ERROR]: [SuperiorSkyblock2] ################################################

### To Reproduce

wehen i put the plugin in plugins folder and run the server i got this error

**Comment by z0roday** [comment]
kiram dahanet
