### ISSUE TITLE
Bug with yml

### ISSUE THREAD

**Issue by Killer15CZE** [BG-Software-LLC/SuperiorSkyblock2#2302]
### Minecraft's Version

![image](https://github.com/user-attachments/assets/2469edd9-b49b-4af3-86b7-42a292bbcb03)

### Plugin's Version

![image](https://github.com/user-attachments/assets/38cbd051-a2d3-4446-89ab-7f92fd049311)

### Describe the bug

[11:51:38 WARN]: org.bukkit.configuration.InvalidConfigurationException: while scanning for the next token
[11:51:38 WARN]: found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
[11:51:38 WARN]:  in 'reader', line 14, column 1:
[11:51:38 WARN]:     
[11:51:38 WARN]:     ^
[11:51:38 WARN]: 
[11:51:38 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:111)
[11:51:38 WARN]:        at SuperiorSkyblock2-2024.4.jar//com.bgsoftware.superiorskyblock.libs.com.bgsoftware.common.config.CommentedConfiguration.loadFromString(CommentedConfiguration.java:137)
[11:51:38 WARN]:        at SuperiorSkyblock2-2024.4.jar//com.bgsoftware.superiorskyblock.libs.com.bgsoftware.common.config.CommentedConfiguration.loadConfiguration(CommentedConfiguration.java:325)
[11:51:38 WARN]:        at SuperiorSkyblock2-2024.4.jar//com.bgsoftware.superiorskyblock.libs.com.bgsoftware.common.config.CommentedConfiguration.loadConfiguration(CommentedConfiguration.java:291)
[11:51:38 WARN]:        at SuperiorSkyblock2-2024.4.jar//com.bgsoftware.superiorskyblock.module.BuiltinModule.onPluginInit(BuiltinModule.java:63)
[11:51:38 WARN]:        at SuperiorSkyblock2-2024.4.jar//com.bgsoftware.superiorskyblock.module.generators.GeneratorsModule.onPluginInit(GeneratorsModule.java:27)
[11:51:38 WARN]:        at SuperiorSkyblock2-2024.4.jar//com.bgsoftware.superiorskyblock.module.BuiltinModule.onReload(BuiltinModule.java:89)
[11:51:38 WARN]:        at SuperiorSkyblock2-2024.4.jar//com.bgsoftware.superiorskyblock.module.BuiltinModule.onReload(BuiltinModule.java:29)
[11:51:38 WARN]:        at SuperiorSkyblock2-2024.4.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.reloadModuleInternal(ModulesManagerImpl.java:201)
[11:51:38 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[11:51:38 WARN]:        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[11:51:38 WARN]:        at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1249)
[11:51:38 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[11:51:38 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[11:51:38 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[11:51:38 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[11:51:38 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[11:51:38 WARN]:        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[11:51:38 WARN]:        at SuperiorSkyblock2-2024.4.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.reloadModulesInternal(ModulesManagerImpl.java:192)
[11:51:38 WARN]:        at SuperiorSkyblock2-2024.4.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.runModuleLifecycle(ModulesManagerImpl.java:185)
[11:51:38 WARN]:        at SuperiorSkyblock2-2024.4.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:452)
[11:51:38 WARN]:        at SuperiorSkyblock2-2024.4.jar//com.bgsoftware.superiorskyblock.commands.admin.CmdAdminReload.execute(CmdAdminReload.java:56)
[11:51:38 WARN]:        at SuperiorSkyblock2-2024.4.jar//com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.execute(ISuperiorCommand.java:18)
[11:51:38 WARN]:        at SuperiorSkyblock2-2024.4.jar//com.bgsoftware.superiorskyblock.commands.player.CmdAdmin.execute(CmdAdmin.java:82)
[11:51:38 WARN]:        at SuperiorSkyblock2-2024.4.jar//com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.execute(ISuperiorCommand.java:18)
[11:51:38 WARN]:        at SuperiorSkyblock2-2024.4.jar//com.bgsoftware.superiorskyblock.commands.CommandsManagerImpl$PluginCommand.execute(CommandsManagerImpl.java:308)
[11:51:38 WARN]:        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
[11:51:38 WARN]:        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[11:51:38 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30)
[11:51:38 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13)
[11:51:38 WARN]:        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[11:51:38 WARN]:        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
[11:51:38 WARN]:        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
[11:51:38 WARN]:        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:451)
[11:51:38 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:358)
[11:51:38 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:345)
[11:51:38 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:340)
[11:51:38 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2297)
[11:51:38 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2271)
[11:51:38 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[11:51:38 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[11:51:38 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[11:51:38 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581)
[11:51:38 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[11:51:38 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[11:51:38 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558)
[11:51:38 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551)
[11:51:38 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[11:51:38 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1510)
[11:51:38 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1517)
[11:51:38 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1362)
[11:51:38 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[11:51:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[11:51:38 WARN]: Caused by: while scanning for the next token
[11:51:38 WARN]: found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
[11:51:38 WARN]:  in 'reader', line 14, column 1:
[11:51:38 WARN]:     
[11:51:38 WARN]:     ^
[11:51:38 WARN]: 
[11:51:38 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:445)
[11:51:38 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:238)
[11:51:38 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:637)
[11:51:38 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
[11:51:38 WARN]:        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57)
[11:51:38 WARN]:        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43)
[11:51:38 WARN]:        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136)
[11:51:38 WARN]:        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116)
[11:51:38 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:241)
[11:51:38 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:205)
[11:51:38 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
[11:51:38 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
[11:51:38 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
[11:51:38 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
[11:51:38 WARN]:        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:131)
[11:51:38 WARN]:        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:157)
[11:51:38 WARN]:        at org.yaml.snakeyaml.Yaml.compose(Yaml.java:575)
[11:51:38 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104)
[11:51:38 WARN]:        ... 52 more

### To Reproduce

![image](https://github.com/user-attachments/assets/a2f89de3-1384-4a7a-8647-0a42f46f817a)

**Comment by OmerBenGera** [comment]
How is it a bug with the plugin? You should not use tabs (\t) in your yaml file.

**Comment by Killer15CZE** [comment]
I don't know where the error could be, I didn't use \t anywhere

**Comment by OmerBenGera** [comment]
Regenerate the config file by deleting it, you should have no error.
Then, edit the config file again and make sure you don't use TABs.

**Comment by Killer15CZE** [comment]
Okay, I'll try... But in the config I only added aliases for the OB addon

**Comment by Killer15CZE** [comment]
Newly generated config.yml... so where is the error?

![image](https://github.com/user-attachments/assets/c37446ef-d472-4130-9947-4f07a74754d2)

**Comment by OmerBenGera** [comment]
In the config file of the generators module

**Comment by Killer15CZE** [comment]
yess! thanks
