### ISSUE TITLE
Error when creating island

### ISSUE THREAD

**Issue by RelativeSure** [BG-Software-LLC/SuperiorSkyblock2#243]
**Minecraft's Version**
This server is running Paper version git-Paper-639 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Plugin's Version**: -
SuperiorSkyblock2-1.6.0

**Describe the bug**
Everytime I try to create an island, this pops up in the console: 
[11:02:46 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
[11:02:46 WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.lambda$getTeleportLocations$40(SIsland.java:720)
[11:02:46 WARN]:        at com.bgsoftware.superiorskyblock.utils.threads.SyncedObject.readAndGet(SyncedObject.java:63)
[11:02:46 WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.getTeleportLocations(SIsland.java:717)
[11:02:46 WARN]:        at com.bgsoftware.superiorskyblock.island.data.SIslandDataHandler.executeInsertStatement(SIslandDataHandler.java:457)
[11:02:46 WARN]:        at com.bgsoftware.superiorskyblock.handlers.DataHandler.insertIsland(DataHandler.java:368)
[11:02:46 WARN]:        at com.bgsoftware.superiorskyblock.handlers.GridHandler.lambda$createIsland$4(GridHandler.java:177)
[11:02:46 WARN]:        at com.bgsoftware.superiorskyblock.schematics.SuperiorSchematic.lambda$pasteSchematic$1(SuperiorSchematic.java:195)
[11:02:46 WARN]:        at com.bgsoftware.superiorskyblock.utils.blocks.BlockChangeTask.lambda$submitUpdate$4(BlockChangeTask.java:74)
[11:02:46 WARN]:        at com.bgsoftware.superiorskyblock.utils.chunks.ChunksProvider.lambda$finishLoad$2(ChunksProvider.java:88)
[11:02:46 WARN]:        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[11:02:46 WARN]:        at com.bgsoftware.superiorskyblock.utils.chunks.ChunksProvider.finishLoad(ChunksProvider.java:88)
[11:02:46 WARN]:        at com.bgsoftware.superiorskyblock.utils.chunks.ChunksProvider.lambda$null$0(ChunksProvider.java:80)
[11:02:46 WARN]:        at com.bgsoftware.superiorskyblock.hooks.AsyncProvider_Paper.lambda$loadChunk$0(AsyncProvider_Paper.java:16)
[11:02:46 WARN]:        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
[11:02:46 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
[11:02:46 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
[11:02:46 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
[11:02:46 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
[11:02:46 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[11:02:46 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.execute(IAsyncTaskHandler.java:89)
[11:02:46 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
[11:02:46 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1069)
[11:02:46 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
[11:02:46 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
[11:02:46 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
[11:02:46 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[11:02:46 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[11:02:46 WARN]:        at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:1027)
[11:02:46 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[11:02:46 WARN]:        at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1074)
[11:02:46 WARN]:        at net.minecraft.server.v1_16_R3.ChunkProviderServer.runTasks(ChunkProviderServer.java:660)
[11:02:46 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271)
[11:02:46 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1255)
[11:02:46 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[11:02:46 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1216)
[11:02:46 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130)
[11:02:46 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
[11:02:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)

**To Reproduce**
/island create <name> normal. It happens with different names.

**Additional information**
It creates the island even though that error pops up. I've tried to delete the superior world and deleted the plugin folder to start fresh, but still the same

**Comment by RelativeSure** [comment]
Just switched to SuperiorSkyblock2-b133, works fine now with creating islands
