### ISSUE TITLE
Island Chest error thrown on mission completion.

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#263]
**Minecraft's Version**
1.16.5 Purpur

**Plugin's Version**: -
Dev build 133

**Describe the bug**
Bug thrown when awarding island chest upgrades.

**To Reproduce**
Complete a mission that awards island chest upgrades.

**Additional information**
[06:14:06 INFO]: Island | Successfully sent to SlipperyCheetah's island members the title!
[06:14:06 INFO]: Bank | You deposited $50,000 into SlipperyCheetah's island bank.
[06:14:06 INFO]: Chest | Successfully updated the rows of page #11 to 3 for SlipperyCheetah's island.
[06:14:06 INFO]: Chest | Successfully updated the rows of page #12 to 3 for SlipperyCheetah's island.
[06:14:06 INFO]: Chest | Successfully updated the rows of page #13 to 3 for SlipperyCheetah's island.
[06:14:06 INFO]: Chest | Successfully updated the rows of page #14 to 3 for SlipperyCheetah's island.
[06:14:06 INFO]: Chest | Successfully updated the rows of page #15 to 3 for SlipperyCheetah's island.
[06:14:06 WARN]: Exception in thread "SuperiorSkyblock Database Thread 0" java.lang.NullPointerException
[06:14:06 WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.setChestRows(SIsland.java:3267)
[06:14:06 WARN]:        at com.bgsoftware.superiorskyblock.commands.admin.CmdAdminSetChestRow.lambda$null$0(CmdAdminSetChestRow.java:87)
[06:14:06 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
[06:14:06 WARN]:        at com.bgsoftware.superiorskyblock.commands.admin.CmdAdminSetChestRow.lambda$execute$1(CmdAdminSetChestRow.java:87)
[06:14:06 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[06:14:06 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[06:14:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by OmerBenGera** [comment]
Use latest dev build, the lines aren't matching the lines of the latest dev build and I can't find the cause.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Skizzles** [comment]
Fixed in latest build
