### ISSUE TITLE
playerRole parameter cannot be null

### ISSUE THREAD

**Issue by ExAlePloit** [BG-Software-LLC/SuperiorSkyblock2#285]
**Minecraft's Version**
Previous version: git-Paper-670 (MC: 1.16.5)

**Plugin's Version**: -
1.6.7
dev 147
dev 156 

**Describe the bug**
Cant start the server, plugin not working

```
[20:09:15] [Craft Scheduler Thread - 3/WARN]: [SuperiorSkyblock2] Plugin SuperiorSkyblock2 v1.6.0-DEVb156 generated an exception while executing task 317
java.lang.NullPointerException: playerRole parameter cannot be null.
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[patched_1.16.5.jar:git-Paper-704]
	at com.bgsoftware.superiorskyblock.player.SSuperiorPlayer.setPlayerRole(SSuperiorPlayer.java:458) ~[?:?]
	at com.bgsoftware.superiorskyblock.player.SSuperiorPlayer.getPlayerRole(SSuperiorPlayer.java:451) ~[?:?]
	at com.bgsoftware.superiorskyblock.island.data.SPlayerDataHandler.executeInsertStatement(SPlayerDataHandler.java:153) ~[?:?]
	at com.bgsoftware.superiorskyblock.handlers.DataHandler.insertPlayer(DataHandler.java:381) ~[?:?]
	at com.bgsoftware.superiorskyblock.handlers.PlayersHandler.lambda$getSuperiorPlayer$0(PlayersHandler.java:84) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-704]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-704]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-704]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**To Reproduce**
Idk I just restarted the server with /stop and cant restart anymore

**Comment by OmerBenGera** [comment]
Seems like the plugin can't find the guest role.
Did you change it by any chance?

**Comment by ExAlePloit** [comment]
no I didnt touched anything
Now I just removed the database to fix

**Comment by OmerBenGera** [comment]
Does it still occur?

**Comment by ExAlePloit** [comment]
the problem was the java version. I used java 16 and.. errorsssss. Fixed with java 11

**Comment by OmerBenGera** [comment]
I will check it out in Java 16

**Comment by OmerBenGera** [comment]
I managed to replicate the issue, and it was due to the script engine not loaded correctly.
Check out latest version of the [NashronScript](https://github.com/BG-Software-LLC/SuperiorSkyblock2-NashornEngine/releases/tag/1.0.2), and it will work as it should.
