### ISSUE TITLE
Error occurred while creating your island and database does not work

### ISSUE THREAD

**Issue by ricoricc** [BG-Software-LLC/SuperiorSkyblock2#292]
Creating new world will give this error on console

[14:09:32 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
[14:09:32 WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.lambda$getTeleportLocations$40(SIsland.java:720)
[14:09:32 WARN]:        at com.bgsoftware.superiorskyblock.utils.threads.SyncedObject.readAndGet(SyncedObject.java:63)
[14:09:32 WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.getTeleportLocations(SIsland.java:717)
[14:09:32 WARN]:        at com.bgsoftware.superiorskyblock.island.data.SIslandDataHandler.executeInsertStatement(SIslandDataHandler.java:457)
[14:09:32 WARN]:        at com.bgsoftware.superiorskyblock.handlers.DataHandler.insertIsland(DataHandler.java:368)
[14:09:32 WARN]:        at com.bgsoftware.superiorskyblock.handlers.GridHandler.lambda$createIsland$4(GridHandler.java:177)
[14:09:32 WARN]:        at com.bgsoftware.superiorskyblock.schematics.SuperiorSchematic.lambda$pasteSchematic$1(SuperiorSchematic.java:195)
[14:09:32 WARN]:        at com.bgsoftware.superiorskyblock.utils.blocks.BlockChangeTask.lambda$submitUpdate$4(BlockChangeTask.java:74)
[14:09:32 WARN]:        at com.bgsoftware.superiorskyblock.utils.chunks.ChunksProvider.lambda$finishLoad$2(ChunksProvider.java:88)
[14:09:32 WARN]:        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[14:09:32 WARN]:        at com.bgsoftware.superiorskyblock.utils.chunks.ChunksProvider.finishLoad(ChunksProvider.java:88)
[14:09:32 WARN]:        at com.bgsoftware.superiorskyblock.utils.chunks.ChunksProvider.lambda$null$0(ChunksProvider.java:80)
[14:09:32 WARN]:        at com.bgsoftware.superiorskyblock.hooks.AsyncProvider_Paper.lambda$loadChunk$0(AsyncProvider_Paper.java:16)
[14:09:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
[14:09:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
[14:09:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
[14:09:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
[14:09:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
[14:09:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[14:09:32 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.execute(IAsyncTaskHandler.java:89)
[14:09:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
[14:09:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1069)
[14:09:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
[14:09:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
[14:09:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
[14:09:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[14:09:32 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[14:09:32 WARN]:        at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:1243)
[14:09:32 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[14:09:32 WARN]:        at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1258)
[14:09:32 WARN]:        at net.minecraft.server.v1_16_R3.ChunkProviderServer.runTasks(ChunkProviderServer.java:838)
[14:09:32 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1335)
[14:09:32 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1318)
[14:09:32 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[14:09:32 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1294)
[14:09:32 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1138)
[14:09:32 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292)
[14:09:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)

the island working tho, but after server restart, all the progress is gone, like island is reseted and also the Island Upgrade

How can I fix this ya?

**Comment by OmerBenGera** [comment]
Update SSB.
Also next time use the issues format.
