### ISSUE TITLE
SkinsRestorer hook

### ISSUE THREAD

**Issue by juancruzdal** [BG-Software-LLC/SuperiorSkyblock2#293]
**Minecraft's Version**
Paper 1.8.8
**Plugin's Version**: -
SS2: 1.6.0-DEVb156
SkinsRestorer: i tried with the version 13 and 14
**Describe the bug**
Console error when a player join, in the /is top and /is warps menu i cant see the heads skins
**To Reproduce**
Join to the server

**Additional information**
[19:51:59] [Craft Scheduler Thread - 24/WARN]: java.lang.NullPointerException
[19:51:59] [Craft Scheduler Thread - 24/WARN]: 	at net.skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:162)
[19:51:59] [Craft Scheduler Thread - 24/WARN]: 	at com.bgsoftware.superiorskyblock.hooks.SkinsRestorerHook$SkinsRestorerNew.getSkin(SkinsRestorerHook.java:100)
[19:51:59] [Craft Scheduler Thread - 24/WARN]: 	at com.bgsoftware.superiorskyblock.hooks.SkinsRestorerHook.setSkinTexture(SkinsRestorerHook.java:26)
[19:51:59] [Craft Scheduler Thread - 24/WARN]: 	at com.bgsoftware.superiorskyblock.hooks.SkinsRestorerHook.lambda$setSkinTexture$0(SkinsRestorerHook.java:22)
[19:51:59] [Craft Scheduler Thread - 24/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[19:51:59] [Craft Scheduler Thread - 24/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[19:51:59] [Craft Scheduler Thread - 24/WARN]: 	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[19:51:59] [Craft Scheduler Thread - 24/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[19:51:59] [Craft Scheduler Thread - 24/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[19:51:59] [Craft Scheduler Thread - 24/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by OmerBenGera** [comment]
Issue with SkinsRestorer, cant do anything regarding this

**Comment by xknat** [comment]
Hey there! SR here.
After looking at your code, i did notice the following:
- Since v14.1.0, we changed the api from  `skinsRestorerAPI.getSkinName(p)` to `SkinsRestorerAPI.getApi().getSkinName(name);`
- I did notice that you hooking into our skinStorage directly, this should not have been done since skinStorage is subject to change without any notice as it's part of our backend.
- If your missing any api, we plan on expanding the api right now, so if your missing any API, please contact us.

**Comment by OmerBenGera** [comment]
> 
> 
> Hey there! SR here.
> After looking at your code, i did notice the following:
> 
>     * Since v14.1.0, we changed the api from  `skinsRestorerAPI.getSkinName(p)` to `SkinsRestorerAPI.getApi().getSkinName(name);`
> 
>     * I did notice that you hooking into our skinStorage directly, this should not have been done since skinStorage is subject to change without any notice as it's part of our backend.
> 
>     * If your missing any api, we plan on expanding the api right now, so if your missing any API, please contact us.

How is it related to the issue?
The API doesn't work well when the SkinsRestorer is installed on Bungeecord.

**Comment by xknat** [comment]
> How is it related to the issue?
> The API doesn't work well when the SkinsRestorer is installed on Bungeecord.
When sr is in bungee mode, it will use the bungee cord as main and the backend will be child.
This means that only bungee cord will contain the data folders.

There are currently 2 options:
1. Use bungeemessagechannel
2. Wait for me to finish a module that does allow this.
