### ISSUE TITLE
Interaction with half of the island is impossible when creating a new island

### ISSUE THREAD

**Issue by PenDal-IT** [BG-Software-LLC/SuperiorSkyblock2#307]
**Minecraft's Version**
Paper(1618) 1.12.2-R0.1

**Plugin's Version**: -
1.7.0

**Describe the bug**
If you create a new island, half of the island will not be recognized as your own.

I can't break the block even though it's my own island.

Changing the setting of the island to night alternates morning and night when it leaves the center of the island.

The latest change was made to the island upgrade settings.

I only changed the increase from 50*50 per upgrade to 40*40, but there are no other changes.

**To Reproduce**
1) Create a new island.

2) Break the blocks.

3) It won't break!!!!!!!!!

**Additional information**
[SuperiorSkyblock2.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/6680182/SuperiorSkyblock2.zip)

In addition, deleting database files seems to work fine, but I should not delete users data.

I'm sorry if the translation was weird, and I'll wait for a quick reply, thank you!

**Comment by OmerBenGera** [comment]
Take a video of the issue please

**Comment by PenDal-IT** [comment]
https://youtu.be/mAFG171poiQ
(/is = **/superiorskyblock2:is create %player% default**)

**Comment by OmerBenGera** [comment]
what does this message say?
You get a warning message when you break the blocks. Is it a message from SSB?

**Comment by PenDal-IT** [comment]
yes
it is
**DESTROY_OUTSIDE_ISLAND**: '&b:: &fJINI FARM &b:: &f보호 범위 밖에서는 파괴 할 수 없습니다.'

**Comment by PenDal-IT** [comment]
In addition, the same phenomenon occurred when only SSB was applied.

**Comment by OmerBenGera** [comment]
Are you able to replicate the issue with the default files of the plugin as well?

**Comment by PenDal-IT** [comment]
I don't quite understand....
What can I do for you?

**Comment by OmerBenGera** [comment]
> 
> 
> I don't quite understand....
> What can I do for you?

Try replicating the issue with the default config files of the plugin on another server

**Comment by PenDal-IT** [comment]
~~1) apply database~~
....
The same problem occurred when I applied database file without any other plug-ins!

**Comment by OmerBenGera** [comment]
Please do what I say, otherwise I won't be able to help you solve the issue.

**Comment by PenDal-IT** [comment]
It was understood that "make a new config on a different server and try to create the same problem".
Is there something I misunderstood?

**Comment by OmerBenGera** [comment]
> 
> 
> It was understood that "make a new config on a different server and try to create the same problem".
> Is there something I misunderstood?

Just try it on another server with the default files of the plugin. Don't create any special files, that's all

**Comment by PenDal-IT** [comment]
After the server is enabled, an error like this occurs.

[11:02:32] [Server thread/INFO]: [SuperiorSkyblock2] ################################################
[11:02:32] [Server thread/INFO]: [SuperiorSkyblock2] ##                                            ##
[11:02:32] [Server thread/INFO]: [SuperiorSkyblock2] ## An error occured while loading the plugin! ##
[11:02:32] [Server thread/INFO]: [SuperiorSkyblock2] ##                                            ##
[11:02:32] [Server thread/INFO]: [SuperiorSkyblock2] ################################################
[11:02:32] [Server thread/INFO]: [SuperiorSkyblock2] 
[11:02:32] [Server thread/INFO]: [SuperiorSkyblock2] Error:
[11:02:32] [Server thread/INFO]: [SuperiorSkyblock2] Exception generating new chunk
[11:02:32] [Server thread/INFO]: [SuperiorSkyblock2] 
[11:02:32] [Server thread/INFO]: [SuperiorSkyblock2] StackTrace:
[11:02:32] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)

[11:02:32] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)

[11:02:32] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)

[11:02:32] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)

[11:02:32] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)

[11:02:32] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)

[11:02:32] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)

[11:02:32] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)

[11:02:32] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)

[11:02:32] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)

[11:02:32] [Server thread/INFO]: [SuperiorSkyblock2] 	at java.lang.Thread.run(Unknown Source)

[11:02:32] [Server thread/INFO]: [SuperiorSkyblock2] 
[11:02:32] [Server thread/INFO]: [SuperiorSkyblock2] ################################################

**Comment by PenDal-IT** [comment]
I only set config.yml as the default, so it works fine!
Thanks for making a good plugin!
