### ISSUE TITLE
I cant join server and its spamming errors

### ISSUE THREAD

**Issue by russianpeanut** [BG-Software-LLC/SuperiorSkyblock2#331]
Paper 1.16.5 but i cant even type any commands in console

**Plugin's Version**: -
Latest stable version 1.7.0

**Describe the bug**
i installed the plugin and i cant join the server and its saying this error in console
https://pastebin.com/wBftQgBn

**To Reproduce**
sorry i am not sure what that means in am bad at english

i dont have any additions info

**Comment by OmerBenGera** [comment]
Restart the server.
This is not an issue with the plugin.

**Comment by russianpeanut** [comment]
it probably is because i removed the plugin and everything is ok

**Comment by russianpeanut** [comment]
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] ################################################
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] ##                                            ##
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] ## An error occured while loading the plugin! ##
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] ##                                            ##
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] ################################################
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] 
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] Error:
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] It seems like the script engine of the plugin is corrupted.
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] This may occur by one of the following reasons:
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] 1. You have a module/plugin that sets a custom script that doesn't work well.
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] 2. You're using Java 16 without installing an external module engine.
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] If that's the case, check out the following link:
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] https://github.com/BG-Software-LLC/SuperiorSkyblock2-NashornEngine
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] 
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] StackTrace:
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] 	at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:193)
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] 	at java.base/java.lang.Thread.run(Thread.java:831)
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] 
[16:16:57] [Server thread/INFO]: [SuperiorSkyblock2] ################################################

**Comment by OmerBenGera** [comment]
I answered you in the other issue.
