### ISSUE TITLE
Problem with slimeworldmanager

### ISSUE THREAD

**Issue by Kartooofel** [BG-Software-LLC/SuperiorSkyblock2#345]
Hi, I installed swm and swm addon for superior skyblock. When player disband his island this happens in console:

`[10:18:23 INFO]: [SWM] Loading world island_ad7bbf97-22aa-48b7-8862-c4188cdacab9_normal.
[10:18:23 ERROR]: Could not pass event ChunkUnloadEvent to SuperiorSkyblock2 v1.7.0-DEVb167
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:352) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:234) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:770) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.RuntimeException: com.grinderwolf.swm.api.exceptions.UnknownWorldException: Unknown world island_ad7bbf97-22aa-48b7-8862-c4188cdacab9_normal
        at com.bgsoftware.ssbslimeworldmanager.SlimeUtils.loadAndGetWorld(SlimeUtils.java:79) ~[?:?]
        at com.bgsoftware.ssbslimeworldmanager.SlimeUtils.loadAndGetWorld(SlimeUtils.java:51) ~[?:?]
        at com.bgsoftware.ssbslimeworldmanager.SlimeUtils.loadAndGetWorld(SlimeUtils.java:47) ~[?:?]
        at com.bgsoftware.ssbslimeworldmanager.SSBWorldManager$SlimeWorldsProvider.getIslandsWorld(SSBWorldManager.java:27) ~[?:?]
        at com.bgsoftware.superiorskyblock.handlers.ProvidersHandler.getIslandsWorld(ProvidersHandler.java:319) ~[?:?]
        at com.bgsoftware.superiorskyblock.handlers.GridHandler.getIslandsWorld(GridHandler.java:394) ~[?:?]
        at com.bgsoftware.superiorskyblock.island.SIsland.getCenter(SIsland.java:678) ~[?:?]
        at com.bgsoftware.superiorskyblock.island.SIsland.getMinimum(SIsland.java:765) ~[?:?]
        at com.bgsoftware.superiorskyblock.island.SIsland.isInside(SIsland.java:902) ~[?:?]
        at com.bgsoftware.superiorskyblock.registry.IslandRegistry.get(IslandRegistry.java:31) ~[?:?]
        at com.bgsoftware.superiorskyblock.handlers.GridHandler.getIslandAt(GridHandler.java:353) ~[?:?]
        at com.bgsoftware.superiorskyblock.handlers.GridHandler.getIslandAt(GridHandler.java:364) ~[?:?]
        at com.bgsoftware.superiorskyblock.listeners.ChunksListener.onChunkUnloadMonitor(ChunksListener.java:75) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        ... 10 more
Caused by: com.grinderwolf.swm.api.exceptions.UnknownWorldException: Unknown world island_ad7bbf97-22aa-48b7-8862-c4188cdacab9_normal
        at com.grinderwolf.swm.plugin.loaders.file.FileLoader.loadWorld(FileLoader.java:44) ~[?:?]
        at com.grinderwolf.swm.plugin.SWMPlugin.loadWorld(SWMPlugin.java:241) ~[?:?]
        at com.bgsoftware.ssbslimeworldmanager.SlimeUtils.loadAndGetWorld(SlimeUtils.java:73) ~[?:?]
        at com.bgsoftware.ssbslimeworldmanager.SlimeUtils.loadAndGetWorld(SlimeUtils.java:51) ~[?:?]
        at com.bgsoftware.ssbslimeworldmanager.SlimeUtils.loadAndGetWorld(SlimeUtils.java:47) ~[?:?]
        at com.bgsoftware.ssbslimeworldmanager.SSBWorldManager$SlimeWorldsProvider.getIslandsWorld(SSBWorldManager.java:27) ~[?:?]
        at com.bgsoftware.superiorskyblock.handlers.ProvidersHandler.getIslandsWorld(ProvidersHandler.java:319) ~[?:?]
        at com.bgsoftware.superiorskyblock.handlers.GridHandler.getIslandsWorld(GridHandler.java:394) ~[?:?]
        at com.bgsoftware.superiorskyblock.island.SIsland.getCenter(SIsland.java:678) ~[?:?]
        at com.bgsoftware.superiorskyblock.island.SIsland.getMinimum(SIsland.java:765) ~[?:?]
        at com.bgsoftware.superiorskyblock.island.SIsland.isInside(SIsland.java:902) ~[?:?]
        at com.bgsoftware.superiorskyblock.registry.IslandRegistry.get(IslandRegistry.java:31) ~[?:?]
        at com.bgsoftware.superiorskyblock.handlers.GridHandler.getIslandAt(GridHandler.java:353) ~[?:?]
        at com.bgsoftware.superiorskyblock.handlers.GridHandler.getIslandAt(GridHandler.java:364) ~[?:?]
        at com.bgsoftware.superiorskyblock.listeners.ChunksListener.onChunkUnloadMonitor(ChunksListener.java:75) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        ... 10 more`

I’m on paper 1.8.8, newest version of ssb, classic swm and newest version of `addon.`

**Comment by OmerBenGera** [comment]
There are a lot of issues with the addon, however I don't have the time to fix them.
You are more than welcome to make PRs to the SlimeWorldManager addon and fix them :)
