### ISSUE TITLE
SuperiorSkyblock Island disappears with 1.17

### ISSUE THREAD

**Issue by SbirTeo** [BG-Software-LLC/SuperiorSkyblock2#346]
Paper or Spigot 1.17

SuperiorSkyblock latest version with the expansion for java 15 on modules folder.

When i create an island and stop the server... when i re login attemps this:

[20:58:18] [Server thread/INFO]: Attempted to place a tile entity (net.minecraft.world.level.block.entity.TileEntityChest@38c3ea20) at 5,100,599 (Block{minecraft:air}) where there was no entity tile!
[20:58:18] [Server thread/INFO]: Chunk coordinates: 0,592
[20:58:18] [Server thread/WARN]: java.lang.Exception
[20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.chunk.Chunk.setTileEntity(Chunk.java:496)
[20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:459)
[20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.lambda$6(ChunkRegionLoader.java:165)
[20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.chunk.Chunk.addEntities(Chunk.java:573)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.level.PlayerChunkMap.lambda$33(PlayerChunkMap.java:699)
[20:58:18] [Server thread/WARN]:        at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162)
[20:58:18] [Server thread/WARN]:        at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[20:58:18] [Server thread/WARN]:        at com.mojang.datafixers.util.Either.mapLeft(Either.java:162)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.level.PlayerChunkMap.lambda$31(PlayerChunkMap.java:682)
[20:58:18] [Server thread/WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
[20:58:18] [Server thread/WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.level.ChunkTaskQueueSorter.b(SourceFile:58)
[20:58:18] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.level.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:606)
[20:58:18] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.level.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:617)
[20:58:18] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.level.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:160)
[20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.World.getChunkAt(World.java:278)
[20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.IWorldReader.getChunkAt(SourceFile:140)
[20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.World.getChunkAt(World.java:272)
[20:58:18] [Server thread/WARN]:        at net.minecraft.world.entity.Entity.g(Entity.java:1458)
[20:58:18] [Server thread/WARN]:        at net.minecraft.world.entity.Entity.setLocation(Entity.java:1443)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.players.PlayerList.a(PlayerList.java:225)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.network.LoginListener.a(LoginListener.java:192)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.network.LoginListener.c(LoginListener.java:179)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.network.LoginListener.tick(LoginListener.java:74)
[20:58:18] [Server thread/WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:246)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:172)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1321)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1202)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1035)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303)
[20:58:18] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[20:58:18] [Server thread/INFO]: Attempted to place a tile entity (net.minecraft.world.level.block.entity.TileEntitySign@6ecc46cb) at 3,100,600 (Block{minecraft:air}) where there was no entity tile!
[20:58:18] [Server thread/INFO]: Chunk coordinates: 0,592
[20:58:18] [Server thread/WARN]: java.lang.Exception
[20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.chunk.Chunk.setTileEntity(Chunk.java:496)
[20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:459)
[20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.lambda$6(ChunkRegionLoader.java:165)
[20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.chunk.Chunk.addEntities(Chunk.java:573)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.level.PlayerChunkMap.lambda$33(PlayerChunkMap.java:699)
[20:58:18] [Server thread/WARN]:        at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162)
[20:58:18] [Server thread/WARN]:        at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[20:58:18] [Server thread/WARN]:        at com.mojang.datafixers.util.Either.mapLeft(Either.java:162)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.level.PlayerChunkMap.lambda$31(PlayerChunkMap.java:682)
[20:58:18] [Server thread/WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
[20:58:18] [Server thread/WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.level.ChunkTaskQueueSorter.b(SourceFile:58)
[20:58:18] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.level.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:606)
[20:58:18] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.level.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:617)
[20:58:18] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.level.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:160)
[20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.World.getChunkAt(World.java:278)
[20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.IWorldReader.getChunkAt(SourceFile:140)
[20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.World.getChunkAt(World.java:272)
[20:58:18] [Server thread/WARN]:        at net.minecraft.world.entity.Entity.g(Entity.java:1458)
[20:58:18] [Server thread/WARN]:        at net.minecraft.world.entity.Entity.setLocation(Entity.java:1443)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.players.PlayerList.a(PlayerList.java:225)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.network.LoginListener.a(LoginListener.java:192)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.network.LoginListener.c(LoginListener.java:179)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.network.LoginListener.tick(LoginListener.java:74)
[20:58:18] [Server thread/WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:246)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:172)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1321)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1202)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1035)
[20:58:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303)
[20:58:18] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[20:58:19] [Server thread/INFO]: SbirTeo[/82.48.94.52:41949] logged in with entity id 190 at ([SuperiorWorld]3.3805297538402805, 100.0, 601.7716500322332)

I tried allowing remove-corrupt-tile-entities on paper.yml but nothing. Island disappears.

**Comment by WolverStones** [comment]
> Paper or Spigot 1.17
> 
> 
> 
> SuperiorSkyblock latest version with the expansion for java 15 on modules folder.
> 
> 
> 
> When i create an island and stop the server... when i re login attemps this:
> 
> 
> 
> [20:58:18] [Server thread/INFO]: Attempted to place a tile entity (net.minecraft.world.level.block.entity.TileEntityChest@38c3ea20) at 5,100,599 (Block{minecraft:air}) where there was no entity tile!
> 
> [20:58:18] [Server thread/INFO]: Chunk coordinates: 0,592
> 
> [20:58:18] [Server thread/WARN]: java.lang.Exception
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.chunk.Chunk.setTileEntity(Chunk.java:496)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:459)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.lambda$6(ChunkRegionLoader.java:165)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.chunk.Chunk.addEntities(Chunk.java:573)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.level.PlayerChunkMap.lambda$33(PlayerChunkMap.java:699)
> 
> [20:58:18] [Server thread/WARN]:        at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162)
> 
> [20:58:18] [Server thread/WARN]:        at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
> 
> [20:58:18] [Server thread/WARN]:        at com.mojang.datafixers.util.Either.mapLeft(Either.java:162)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.level.PlayerChunkMap.lambda$31(PlayerChunkMap.java:682)
> 
> [20:58:18] [Server thread/WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
> 
> [20:58:18] [Server thread/WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.level.ChunkTaskQueueSorter.b(SourceFile:58)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.level.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:606)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.level.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:617)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.level.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:160)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.World.getChunkAt(World.java:278)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.IWorldReader.getChunkAt(SourceFile:140)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.World.getChunkAt(World.java:272)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.world.entity.Entity.g(Entity.java:1458)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.world.entity.Entity.setLocation(Entity.java:1443)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.players.PlayerList.a(PlayerList.java:225)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.network.LoginListener.a(LoginListener.java:192)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.network.LoginListener.c(LoginListener.java:179)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.network.LoginListener.tick(LoginListener.java:74)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:246)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:172)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1321)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1202)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1035)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303)
> 
> [20:58:18] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
> 
> [20:58:18] [Server thread/INFO]: Attempted to place a tile entity (net.minecraft.world.level.block.entity.TileEntitySign@6ecc46cb) at 3,100,600 (Block{minecraft:air}) where there was no entity tile!
> 
> [20:58:18] [Server thread/INFO]: Chunk coordinates: 0,592
> 
> [20:58:18] [Server thread/WARN]: java.lang.Exception
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.chunk.Chunk.setTileEntity(Chunk.java:496)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:459)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.lambda$6(ChunkRegionLoader.java:165)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.chunk.Chunk.addEntities(Chunk.java:573)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.level.PlayerChunkMap.lambda$33(PlayerChunkMap.java:699)
> 
> [20:58:18] [Server thread/WARN]:        at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162)
> 
> [20:58:18] [Server thread/WARN]:        at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
> 
> [20:58:18] [Server thread/WARN]:        at com.mojang.datafixers.util.Either.mapLeft(Either.java:162)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.level.PlayerChunkMap.lambda$31(PlayerChunkMap.java:682)
> 
> [20:58:18] [Server thread/WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
> 
> [20:58:18] [Server thread/WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.level.ChunkTaskQueueSorter.b(SourceFile:58)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.level.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:606)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.level.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:617)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.level.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:160)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.World.getChunkAt(World.java:278)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.IWorldReader.getChunkAt(SourceFile:140)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.world.level.World.getChunkAt(World.java:272)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.world.entity.Entity.g(Entity.java:1458)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.world.entity.Entity.setLocation(Entity.java:1443)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.players.PlayerList.a(PlayerList.java:225)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.network.LoginListener.a(LoginListener.java:192)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.network.LoginListener.c(LoginListener.java:179)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.network.LoginListener.tick(LoginListener.java:74)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:246)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:172)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1321)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1202)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1035)
> 
> [20:58:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303)
> 
> [20:58:18] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
> 
> [20:58:19] [Server thread/INFO]: SbirTeo[/82.48.94.52:41949] logged in with entity id 190 at ([SuperiorWorld]3.3805297538402805, 100.0, 601.7716500322332)
> 
> 
> 
> I tried allowing remove-corrupt-tile-entities on paper.yml but nothing. Island disappears.
> 
> 

Minecraft 1.17 require java 16 not 15 https://www.spigotmc.org/threads/spigot-bungeecord-1-17-1-17-1.510208/

**Comment by SbirTeo** [comment]
I use java 16...

**Comment by SbirTeo** [comment]
Plugin works, but when i stop the server island disappears

**Comment by SbirTeo** [comment]
http://prntscr.com/19bhkyv

**Comment by OmerBenGera** [comment]
Use latest dev build from our website.
If the issue still persists, let me know.
