### ISSUE TITLE
Console error at starting, reloading plugin or creating islands

### ISSUE THREAD

**Issue by SbirTeo** [BG-Software-LLC/SuperiorSkyblock2#353]
### Minecraft's Version

1.17.1

### Plugin's Version

1.7.0 devb188

### Describe the bug

[21:47:39 INFO]: [SuperiorSkyblock2] Successfully loaded schematic normal.schematic (SuperiorSkyblock)
[21:47:39 WARN]: java.lang.NoClassDefFoundError: net/skinsrestorer/shared/exception/SkinRequestException
[21:47:39 WARN]:        at com.bgsoftware.superiorskyblock.hooks.SkinsRestorerHook.register(SkinsRestorerHook.java:39)
[21:47:39 WARN]:        at com.bgsoftware.superiorskyblock.handlers.ProvidersHandler.lambda$null$3(ProvidersHandler.java:102)
[21:47:39 WARN]:        at com.bgsoftware.superiorskyblock.handlers.ProvidersHandler.runSafe(ProvidersHandler.java:210)
[21:47:39 WARN]:        at com.bgsoftware.superiorskyblock.handlers.ProvidersHandler.lambda$loadData$24(ProvidersHandler.java:102)
[21:47:39 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100)
[21:47:39 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[21:47:39 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1490)
[21:47:39 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
[21:47:39 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1406)
[21:47:39 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188)
[21:47:39 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[21:47:39 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[21:47:39 WARN]: Caused by: java.lang.ClassNotFoundException: net.skinsrestorer.shared.exception.SkinRequestException
[21:47:39 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
[21:47:39 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[21:47:39 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[21:47:39 WARN]:        ... 12 more

### To Reproduce

none

**Comment by OmerBenGera** [comment]
What version of SkinsRestorer are you using?

**Comment by SbirTeo** [comment]
Latest

Il giorno ven 9 lug 2021 alle ore 22:01 Ome_R ***@***.***> ha
scritto:

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
