### ISSUE TITLE
Nether Biome not Setting

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#354]
### Minecraft's Version

1.17.1 Purpur dev 1260

### Plugin's Version

Build 187

### Describe the bug

Biome won't set to nether.

### To Reproduce

Attempt clicking Nether biome in GUI
Biome fails to set

### Additional Information

[00:23:21] [Server thread/ERROR]: Could not pass event InventoryClickEvent to SuperiorSkyblock2 v1.7.0-DEVb187
java.lang.IllegalArgumentException: No enum constant org.bukkit.block.Biome.NETHER
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
	at org.bukkit.block.Biome.valueOf(Biome.java:11) ~[patched_1.17.1.jar:git-Purpur-1260]
	at com.bgsoftware.superiorskyblock.island.SIsland.setBiome(SIsland.java:1456) ~[?:?]
	at com.bgsoftware.superiorskyblock.island.SIsland.setBiome(SIsland.java:1437) ~[?:?]
	at com.bgsoftware.superiorskyblock.menu.MenuBiomes.onPlayerClick(MenuBiomes.java:61) ~[?:?]
	at com.bgsoftware.superiorskyblock.menu.SuperiorMenu.onClick(SuperiorMenu.java:187) ~[?:?]
	at com.bgsoftware.superiorskyblock.listeners.MenusListener.onMenuClick(MenusListener.java:72) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1034.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1260]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1260]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1260]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1260]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2843) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:55) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:11) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1260]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1422) ~[patched_1.17.1.jar:git-Purpur-1260]
	at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Purpur-1260]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1400) ~[patched_1.17.1.jar:git-Purpur-1260]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1393) ~[patched_1.17.1.jar:git-Purpur-1260]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1369) ~[patched_1.17.1.jar:git-Purpur-1260]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1280) ~[patched_1.17.1.jar:git-Purpur-1260]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1260]
	at java.lang.Thread.run(Thread.java:831) [?:?]
	
	
	'&':
    biome: NETHER_WASTES
    required-permission: 'superior.island.biome.nether'
    access:
      type: PLAYER_HEAD
      skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTU2Y2E1YzY3OTMzNmRkNGYzMjYyZjRmYmMyM2MxYTJlZTBkODJhN2ZkODFlNmU2MjMzN2U1ZmQ1YzcifX19'
      name: '&eNether Wastes Biome &a(Available)'
      lore:
        - '&7Change your island biome to the nether.'
        - '&cWarning ice, snow and water must go!'
    no-access:
      type: PLAYER_HEAD
      skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTU2Y2E1YzY3OTMzNmRkNGYzMjYyZjRmYmMyM2MxYTJlZTBkODJhN2ZkODFlNmU2MjMzN2U1ZmQ1YzcifX19'
      name: '&eNether Wastes Biome &c(Unavailable)'
      lore:
        - '&7Change your island biome to the nether.'
        - '&cWarning ice snow, and water must go!'
        - '&fRequires &5Immortal&f/&5Eternal'

**Comment by OmerBenGera** [comment]
You try to set the biome to "NETHER", which doesn't exist.

**Comment by OmerBenGera** [comment]
Make sure you update the biome in the config files from "NETHER" to "NETHER_WASTES", and it will work again

**Comment by Skizzles** [comment]
@OmerBenGera the biomes file has it set to NETHER_WASTES

**Comment by Skizzles** [comment]
'&':
biome: **NETHER_WASTES**
required-permission: 'superior.island.biome.nether'
access:
  type: PLAYER_HEAD
  skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTU2Y2E1YzY3OTMzNmRkNGYzMjYyZjRmYmMyM2MxYTJlZTBkODJhN2ZkODFlNmU2MjMzN2U1ZmQ1YzcifX19'
  name: '&eNether Wastes Biome &a(Available)'
  lore:
    - '&7Change your island biome to the nether.'
    - '&cWarning ice, snow and water must go!'
no-access:
  type: PLAYER_HEAD
  skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTU2Y2E1YzY3OTMzNmRkNGYzMjYyZjRmYmMyM2MxYTJlZTBkODJhN2ZkODFlNmU2MjMzN2U1ZmQ1YzcifX19'
  name: '&eNether Wastes Biome &c(Unavailable)'
  lore:
    - '&7Change your island biome to the nether.'
    - '&cWarning ice snow, and water must go!'
    - '&fRequires &5Immortal&f/&5Eternal'

**Comment by OmerBenGera** [comment]
> 
> 
> @OmerBenGera the biomes file has it set to NETHER_WASTES

then probably not, as the plugin still sees the biome being "NETHER".
Make sure you make a full restart and make sure the file is actually updated.

**Comment by Skizzles** [comment]
My file has been this way since 1.16. so not sure what else to update?

**Comment by OmerBenGera** [comment]
I made another look in the code and there seemed to be an issue with detection of nether biomes.
Check out latest dev build, it should be fixed.
