### ISSUE TITLE
Hoppers not sending items

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#355]
### Minecraft's Version

Purpur 1.17.1 build 1260

### Plugin's Version

Build 187

### Describe the bug

Hoppers are not sending items

### To Reproduce

Attempt to send items through hoppers from a chest to another chest

### Additional Information

[05:08:27] [Server thread/ERROR]: Could not pass event BlockFromToEvent to SuperiorSkyblock2 v1.7.0-DEVb187
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "entityPlayer.clientViewDistance" is null
	at com.bgsoftware.superiorskyblock.nms.NMSBlocks_v1_17_R1.sendPacketToRelevantPlayers(NMSBlocks_v1_17_R1.java:733) ~[?:?]
	at com.bgsoftware.superiorskyblock.nms.NMSBlocks_v1_17_R1.setBlock(NMSBlocks_v1_17_R1.java:232) ~[?:?]
	at com.bgsoftware.superiorskyblock.modules.generators.listeners.GeneratorsListener.onBlockFormEvent(GeneratorsListener.java:90) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor977.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1260]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1260]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1260]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1260]
	at net.minecraft.world.level.material.FlowingFluid.spreadToSides(FlowingFluid.java:186) ~[?:?]
	at net.minecraft.world.level.material.FlowingFluid.spread(FlowingFluid.java:157) ~[?:?]
	at net.minecraft.world.level.material.FlowingFluid.tick(FlowingFluid.java:515) ~[?:?]
	at net.minecraft.world.level.material.FluidState.tick(FluidState.java:77) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickLiquid(ServerLevel.java:1174) ~[?:?]
	at com.destroystokyo.paper.server.ticklist.PaperTickList.tick(PaperTickList.java:306) ~[patched_1.17.1.jar:git-Purpur-1260]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:796) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1629) ~[patched_1.17.1.jar:git-Purpur-1260]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.1.jar:git-Purpur-1260]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Purpur-1260]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1260]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1260]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by OmerBenGera** [comment]
The error you reported has nothing to do with hoppers, but with custom generators throwning an error when the packets are sent to nearby players.
I fixed it in latest dev build
