### ISSUE TITLE
Setting biome through /is biome is causing Out of memory issue

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#369]
### Minecraft's Version

1.17.1 Purpur dev 1265

### Plugin's Version

Dev 196

### Describe the bug

When using /is biome it causes the server to run out of memory. I tested this on multiple server software and it happened across all them.

### To Reproduce

Run /is biome and set to a specific biome, see the server run out of memory.

### Additional Information

[14:06:44 INFO]: ISkizzlesI issued server command: /is biome
[14:06:45 INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_17_R1! Trying to find NMS support
[14:06:45 INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_17_R1' loaded!
[14:06:45 INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[14:06:46 INFO]: [NBTAPI] [NBTAPI] The NBT-API seems to be up-to-date!
>....[32975.543s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[32975.543s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[14:06:46 WARN]: Exception in thread "Craft Async Scheduler Management Thread" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
[14:06:46 WARN]:        at java.base/java.lang.Thread.start0(Native Method)
[14:06:46 WARN]:        at java.base/java.lang.Thread.start(Thread.java:800)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:939)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1007)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[14:06:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
>....[32975.612s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[32975.613s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[14:06:46 WARN]: Exception in thread "Craft Async Scheduler Management Thread" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
[14:06:46 WARN]:        at java.base/java.lang.Thread.start0(Native Method)
[14:06:46 WARN]:        at java.base/java.lang.Thread.start(Thread.java:800)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:939)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1007)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[14:06:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
>....[32975.637s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[32975.637s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[14:06:46 WARN]: Exception in thread "Craft Async Scheduler Management Thread" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
[14:06:46 WARN]:        at java.base/java.lang.Thread.start0(Native Method)
[14:06:46 WARN]:        at java.base/java.lang.Thread.start(Thread.java:800)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:939)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1007)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[14:06:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
>....[32975.713s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[32975.714s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[14:06:46 WARN]: Exception in thread "Craft Async Scheduler Management Thread" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
[14:06:46 WARN]:        at java.base/java.lang.Thread.start0(Native Method)
[14:06:46 WARN]:        at java.base/java.lang.Thread.start(Thread.java:800)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:939)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1007)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[14:06:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
>....[32975.737s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[32975.738s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[14:06:46 WARN]: Exception in thread "Craft Async Scheduler Management Thread" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
[14:06:46 WARN]:        at java.base/java.lang.Thread.start0(Native Method)
[14:06:46 WARN]:        at java.base/java.lang.Thread.start(Thread.java:800)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:939)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1007)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[14:06:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
>....[32975.787s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[32975.788s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[14:06:46 WARN]: Exception in thread "Craft Async Scheduler Management Thread" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
[14:06:46 WARN]:        at java.base/java.lang.Thread.start0(Native Method)
[14:06:46 WARN]:        at java.base/java.lang.Thread.start(Thread.java:800)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:939)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1007)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[14:06:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
>....[32975.836s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[32975.837s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[14:06:46 WARN]: Exception in thread "Craft Async Scheduler Management Thread" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
[14:06:46 WARN]:        at java.base/java.lang.Thread.start0(Native Method)
[14:06:46 WARN]:        at java.base/java.lang.Thread.start(Thread.java:800)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:939)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1007)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[14:06:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
>....[32975.887s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[32975.887s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[14:06:46 WARN]: Exception in thread "Craft Async Scheduler Management Thread" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
[14:06:46 WARN]:        at java.base/java.lang.Thread.start0(Native Method)
[14:06:46 WARN]:        at java.base/java.lang.Thread.start(Thread.java:800)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:939)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1007)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[14:06:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
>....[32975.937s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[32975.938s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[14:06:46 WARN]: Exception in thread "Craft Async Scheduler Management Thread" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
[14:06:46 WARN]:        at java.base/java.lang.Thread.start0(Native Method)
[14:06:46 WARN]:        at java.base/java.lang.Thread.start(Thread.java:800)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:939)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1007)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[14:06:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[14:06:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by OmerBenGera** [comment]
Does it happen when you are far away from your island, or it also happens when you're inside it?
I think I know what the issue is - when the chunks are not loaded, SSB loads the chunks from disk on another thread, but it opens a thread for each chunk, and that might cause the issue.
If it only happens when the island is not loaded, then that's the issue, otherwise I have no clue atm and I'll need to look into this further. Therefore, let me know when it happens as well :)

**Comment by Skizzles** [comment]
@OmerBenGera I tested while on my island.

**Comment by OmerBenGera** [comment]
> @OmerBenGera I tested while on my island.

Gotcha, Anyways I will try to patch the thing I said above, and maybe it will help

**Comment by OmerBenGera** [comment]
Are you using pterodactyl by any chance?

**Comment by Skizzles** [comment]
@OmerBenGera I do, however I don't see how increasing the container limit is good... thats already a ton of resources being pushed for the process.

**Comment by Skizzles** [comment]
Mine is already set 512 as well:
container_pid_limit: 512

**Comment by WarnDangerous** [comment]
> Mine is already set 512 as well:
> container_pid_limit: 512

I had the same issue, I had to set it to "0" to fix the issues

**Comment by Skizzles** [comment]
> > Mine is already set 512 as well:
> > container_pid_limit: 512
> 
> I had the same issue, I had to set it to "0" to fix the issues

Setting to 0 can overload the machine which would in turn cause more problems. Due to also hosting other users I want to avoid setting to 0.

**Comment by OmerBenGera** [comment]
@Skizzles that's a temporary fix for the time being of course.
It will be fixed on my side as well, don't worry.

**Comment by OmerBenGera** [comment]
Check out latest dev build, should be better.

**Comment by Skizzles** [comment]
@OmerBenGera This is resolved, tested and no further issues on my end. Closing this out for you
