### ISSUE TITLE
Error thrown when running /is admin resetworld custom "Couldn't find world for environment CUSTOM."

### ISSUE THREAD

**Issue by brasilcraft54** [BG-Software-LLC/SuperiorSkyblock2#389]
### Minecraft's Version

git-paper-104 1.17.1

### Plugin's Version

SuperiorSkyblock2-b199.jar and SuperiorSkyblock2-NashornEngine

### Describe the bug

[15:10:01 INFO]: SrMonsterYT issued server command: /is admin resetworld SrMonsterYT custom
[15:10:01 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'is admin resetworld SrMonsterYT custom' in com.bgsoftware.superiorskyblock.handlers.CommandsHandler$PluginCommand(island)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.17.1.jar:git-Paper-104]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.1.jar:git-Paper-104]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2170) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1981) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1962) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-104]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[patched_1.17.1.jar:git-Paper-104]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Paper-104]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[patched_1.17.1.jar:git-Paper-104]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[patched_1.17.1.jar:git-Paper-104]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1458) ~[patched_1.17.1.jar:git-Paper-104]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-104]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-104]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Couldn't find world for environment CUSTOM.
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[patched_1.17.1.jar:git-Paper-104]
        at com.bgsoftware.superiorskyblock.island.SIsland.getCenter(SIsland.java:683) ~[?:?]
        at com.bgsoftware.superiorskyblock.commands.admin.CmdAdminResetWorld.lambda$execute$1(CmdAdminResetWorld.java:78) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at com.bgsoftware.superiorskyblock.commands.admin.CmdAdminResetWorld.execute(CmdAdminResetWorld.java:77) ~[?:?]
        at com.bgsoftware.superiorskyblock.commands.IAdminIslandCommand.execute(IAdminIslandCommand.java:26) ~[?:?]
        at com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.execute(ISuperiorCommand.java:13) ~[?:?]
        at com.bgsoftware.superiorskyblock.commands.CmdAdmin.execute(CmdAdmin.java:154) ~[?:?]
        at com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.execute(ISuperiorCommand.java:13) ~[?:?]
        at com.bgsoftware.superiorskyblock.handlers.CommandsHandler$PluginCommand.execute(CommandsHandler.java:361) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-104]
        ... 20 more

### To Reproduce

/is admin resetworld name custom

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
