### ISSUE TITLE
delay when deleting an island

### ISSUE THREAD

**Issue by brasilcraft54** [BG-Software-LLC/SuperiorSkyblock2#394]
### Minecraft's Version

git-paper-104 1.17.1

### Plugin's Version

SuperiorSkyblock2-b199.jar and SuperiorSkyblock2-NashornEngine

### Describe the bug

[17:53:56 INFO]: SrMonsterYT issued server command: /is reset
[17:54:07 WARN]: Can't keep up! Is the server overloaded? Running 9945ms or 198 ticks behind
[17:54:07 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-104 (MC: 1.17.1) ---
[17:54:07 ERROR]: The server has not responded for 10 seconds! Creating thread dump
[17:54:07 ERROR]: ------------------------------
[17:54:07 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[17:54:07 ERROR]: ------------------------------
[17:54:07 ERROR]: Current Thread: Server thread
[17:54:07 ERROR]:       PID: 28 | Suspended: false | Native: false | State: RUNNABLE
[17:54:07 ERROR]:       Stack:
[17:54:07 ERROR]:               app//it.unimi.dsi.fastutil.longs.LongOpenHashSet.rehash(LongOpenHashSet.java:603)
[17:54:07 ERROR]:               app//it.unimi.dsi.fastutil.longs.LongOpenHashSet.add(LongOpenHashSet.java:308)
[17:54:07 ERROR]:               app//net.minecraft.server.level.DistanceManager$PlayerTicketTracker.onLevelChange(DistanceManager.java:657)
[17:54:07 ERROR]:               app//net.minecraft.server.level.DistanceManager$FixedPlayerDistanceChunkTracker.setLevel(DistanceManager.java:592)
[17:54:07 ERROR]:               app//net.minecraft.world.level.lighting.DynamicGraphMinFixedPoint.runUpdates(DynamicGraphMinFixedPoint.java:215)
[17:54:07 ERROR]:               app//net.minecraft.server.level.DistanceManager$FixedPlayerDistanceChunkTracker.runAllUpdates(DistanceManager.java:609)
[17:54:07 ERROR]:               app//net.minecraft.server.level.DistanceManager$PlayerTicketTracker.runAllUpdates(DistanceManager.java:733)
[17:54:07 ERROR]:               app//net.minecraft.server.level.DistanceManager.runAllUpdates(DistanceManager.java:116)
[17:54:07 ERROR]:               app//net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:666)
[17:54:07 ERROR]:               app//net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:748)
[17:54:07 ERROR]:               app//net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:555)
[17:54:07 ERROR]:               app//net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1553)
[17:54:07 ERROR]:               app//net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479)
[17:54:07 ERROR]:               app//net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406)
[17:54:07 ERROR]:               app//net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188)
[17:54:07 ERROR]:               app//net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[17:54:07 ERROR]:               app//net.minecraft.server.MinecraftServer$$Lambda$3653/0x00000008013a7910.run(Unknown Source)
[17:54:07 ERROR]:               java.base@16.0.1/java.lang.Thread.run(Thread.java:831)
[17:54:07 ERROR]: ------------------------------
[17:54:07 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[17:54:07 ERROR]: ------------------------------
[17:54:12 INFO]: SrMonsterYT issued server command: /is
[17:54:15 INFO]: SrMonsterYT issued server command: /is create top

### To Reproduce

/is reset

### Additional Information

I am having problems only with this plugin in the matter of deleting the island I tested another and had no problem wanted to know how to solve this for when a player her the island generates a delay in the server and that has only me in the world and I put only a few blocks and have reset to test and already gave a rollback on the server is my server is a dedicated i7 9°, 64GB RAM, SSD 480. is there any way to solve this bug delay in deleting island?

**Comment by brasilcraft54** [comment]
[20:31:18 INFO]: SrMonsterYT issued server command: /is reset
[20:31:29 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-104 (MC: 1.17.1) ---
[20:31:29 ERROR]: The server has not responded for 10 seconds! Creating thread dump
[20:31:29 ERROR]: ------------------------------
[20:31:29 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[20:31:29 ERROR]: Chunk wait task info below: 
[20:31:29 ERROR]: 7,62 in 'skyblockend:
[20:31:29 ERROR]: Load Task - none
[20:31:29 ERROR]: Save Task - none
[20:31:29 ERROR]: Chunk Holder - non-null
[20:31:29 ERROR]: Chunk Status - minecraft:features
[20:31:29 ERROR]: Chunk Ticket Status - minecraft:full
[20:31:29 ERROR]: Chunk Holder Status - minecraft:features
[20:31:29 ERROR]: Chunk Holder Priority - 2
[20:31:29 ERROR]: Chunk Neighbors: 
[20:31:29 ERROR]:   8,63 in skyblockend:
[20:31:29 ERROR]:   Chunk Holder - non-null
[20:31:29 ERROR]:   Chunk Status - minecraft:liquid_carvers
[20:31:29 ERROR]:   Chunk Ticket Status - minecraft:features
[20:31:29 ERROR]:   Chunk Holder Status - minecraft:liquid_carvers
[20:31:29 ERROR]:   Chunk Holder Priority - 3
[20:31:29 ERROR]:   Chunk Neighbors: 
[20:31:29 ERROR]:     9,63 in skyblockend:
[20:31:29 ERROR]:     Chunk Holder - non-null
[20:31:29 ERROR]:     Chunk Status - minecraft:structure_starts
[20:31:29 ERROR]:     Chunk Ticket Status - minecraft:liquid_carvers
[20:31:29 ERROR]:     Chunk Holder Status - minecraft:structure_starts
[20:31:29 ERROR]:     Chunk Holder Priority - 4
[20:31:29 ERROR]:     Chunk Neighbors: 
[20:31:29 ERROR]:       17,71 in skyblockend:
[20:31:29 ERROR]:       Chunk Holder - non-null
[20:31:29 ERROR]:       Chunk Status - null chunk
[20:31:29 ERROR]:       Chunk Ticket Status - minecraft:structure_starts
[20:31:29 ERROR]:       Chunk Holder Status - null
[20:31:29 ERROR]:       Chunk Holder Priority - 5
[20:31:29 ERROR]:     9,64 in skyblockend:
[20:31:29 ERROR]:     Chunk Holder - non-null
[20:31:29 ERROR]:     Chunk Status - minecraft:structure_starts
[20:31:29 ERROR]:     Chunk Ticket Status - minecraft:liquid_carvers
[20:31:29 ERROR]:     Chunk Holder Status - minecraft:structure_starts
[20:31:29 ERROR]:     Chunk Holder Priority - 4
[20:31:29 ERROR]:     Chunk Neighbors: 
[20:31:29 ERROR]:       17,72 in skyblockend:
[20:31:29 ERROR]:       Chunk Holder - non-null
[20:31:29 ERROR]:       Chunk Status - null chunk
[20:31:29 ERROR]:       Chunk Ticket Status - minecraft:structure_starts
[20:31:29 ERROR]:       Chunk Holder Status - null
[20:31:29 ERROR]:       Chunk Holder Priority - 5
[20:31:29 ERROR]:       17,71 in skyblockend (CIRCULAR)
[20:31:29 ERROR]:   8,62 in skyblockend:
[20:31:29 ERROR]:   Chunk Holder - non-null
[20:31:29 ERROR]:   Chunk Status - minecraft:liquid_carvers
[20:31:29 ERROR]:   Chunk Ticket Status - minecraft:features
[20:31:29 ERROR]:   Chunk Holder Status - minecraft:liquid_carvers
[20:31:29 ERROR]:   Chunk Holder Priority - 3
[20:31:29 ERROR]:   Chunk Neighbors: 
[20:31:29 ERROR]:     9,63 in skyblockend (CIRCULAR)
[20:31:29 ERROR]: ------------------------------
[20:31:29 ERROR]: Current Thread: Server thread
[20:31:29 ERROR]:       PID: 28 | Suspended: false | Native: false | State: TIMED_WAITING
[20:31:29 ERROR]:       Stack:
>....[10689.182s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[10689.183s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[20:31:29 ERROR]:               java.base@16.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[20:31:29 ERROR]:               java.base@16.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
[20:31:29 ERROR]:               app//net.minecraft.util.thread.BlockableEventLoop.waitForTasks(BlockableEventLoop.java:144)
[20:31:29 ERROR]:               app//net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133)
[20:31:29 ERROR]:               app//net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:515)
[20:31:29 ERROR]:               app//net.minecraft.world.level.chunk.ChunkSource.getChunk(ChunkSource.java:14)
[20:31:29 ERROR]:               app//org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getChunkAt(CraftWorld.java:438)
[20:31:29 ERROR]:               com.bgsoftware.superiorskyblock.utils.chunks.ChunkPosition.loadChunk(ChunkPosition.java:24)
[20:31:29 ERROR]:               com.bgsoftware.superiorskyblock.island.SIsland$$Lambda$8793/0x00000008027b1000.apply(Unknown Source)
[20:31:29 ERROR]:               java.base@16.0.1/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[20:31:29 ERROR]:               java.base@16.0.1/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[20:31:29 ERROR]:               java.base@16.0.1/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[20:31:29 ERROR]:               java.base@16.0.1/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[20:31:29 ERROR]:               java.base@16.0.1/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
[20:31:29 ERROR]:               java.base@16.0.1/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[20:31:29 ERROR]:               java.base@16.0.1/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[20:31:29 ERROR]:               com.bgsoftware.superiorskyblock.island.SIsland.getAllChunks(SIsland.java:819)
[20:31:29 ERROR]:               com.bgsoftware.superiorskyblock.island.SIsland.getAllChunks(SIsland.java:812)
[20:31:29 ERROR]:               com.bgsoftware.superiorskyblock.island.SIsland.getAllChunks(SIsland.java:798)
[20:31:29 ERROR]:               com.bgsoftware.superiorskyblock.island.SIsland.getAllChunks(SIsland.java:789)
[20:31:29 ERROR]:               net.cloud.collectors.hooks.SuperiorSkyblockHook.onDisband(SuperiorSkyblockHook.java:24)
[20:31:29 ERROR]:               com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor668.execute(Unknown Source)
[20:31:29 ERROR]:               app//org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[20:31:29 ERROR]:               app//org.bukkit.plugin.EventExecutor$$Lambda$5705/0x0000000801c44000.execute(Unknown Source)
[20:31:29 ERROR]:               app//co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[20:31:29 ERROR]:               app//org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:31:29 ERROR]:               app//org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[20:31:29 ERROR]:               com.bgsoftware.superiorskyblock.utils.events.EventsCaller.callIslandDisbandEvent(EventsCaller.java:119)
[20:31:29 ERROR]:               com.bgsoftware.superiorskyblock.menu.MenuConfirmDisband.onPlayerClick(MenuConfirmDisband.java:40)
[20:31:29 ERROR]:               com.bgsoftware.superiorskyblock.menu.SuperiorMenu.onClick(SuperiorMenu.java:187)
[20:31:29 ERROR]:               com.bgsoftware.superiorskyblock.listeners.MenusListener.onMenuClick(MenusListener.java:72)
[20:31:29 ERROR]:               com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor552.execute(Unknown Source)
[20:31:29 ERROR]:               app//org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[20:31:29 ERROR]:               app//org.bukkit.plugin.EventExecutor$$Lambda$5705/0x0000000801c44000.execute(Unknown Source)
[20:31:29 ERROR]:               app//co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
>....[10689.198s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[20:31:29 ERROR]:               app//org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:31:29 ERROR]:               app//org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[20:31:29 ERROR]:               app//net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2715)
[20:31:29 ERROR]:               app//net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:55)
[20:31:29 ERROR]:               app//net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:11)
[20:31:29 ERROR]:               app//net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36)
[20:31:29 ERROR]:               app//net.minecraft.network.protocol.PlayerConnectionUtils$$Lambda$8106/0x000000080266e3a8.run(Unknown Source)
[20:31:29 ERROR]:               app//net.minecraft.server.TickTask.run(TickTask.java:18)
[20:31:29 ERROR]:               app//net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149)
[20:31:29 ERROR]:               app//net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23)
[20:31:29 ERROR]:               app//net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348)
[20:31:29 ERROR]:               app//net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190)
[20:31:29 ERROR]:               app//net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122)
[20:31:29 ERROR]:               app//net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327)
[20:31:29 ERROR]:               app//net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320)
[20:31:29 ERROR]:               app//net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132)
[20:31:29 ERROR]:               app//net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1281)
[20:31:29 ERROR]:               app//net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192)
[20:31:29 ERROR]:               app//net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[20:31:29 ERROR]:               app//net.minecraft.server.MinecraftServer$$Lambda$3653/0x00000008013a7910.run(Unknown Source)
[20:31:29 ERROR]:               java.base@16.0.1/java.lang.Thread.run(Thread.java:831)
[20:31:29 ERROR]: ------------------------------
[20:31:29 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[20:31:29 ERROR]: ------------------------------
>....[10689.230s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[10690.427s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[20:31:31 WARN]: Can't keep up! Is the server overloaded? Running 12346ms or 246 ticks behind
>....[10692.525s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[10692.562s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[10692.577s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[10692.604s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[10692.656s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[20:31:37 INFO]: SrMonsterYT issued server command: /is create top
>....[10698.465s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[10698.466s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[10698.466s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[10698.468s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[10698.490s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[10698.490s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[10698.526s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[10698.527s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[20:31:38 WARN]: Exception in thread "Craft Async Scheduler Management Thread" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
[20:31:38 WARN]:        at java.base/java.lang.Thread.start0(Native Method)
[20:31:38 WARN]:        at java.base/java.lang.Thread.start(Thread.java:800)
[20:31:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:939)
[20:31:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1007)
[20:31:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[20:31:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[20:31:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
>....[10698.555s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[10698.605s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[10698.607s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[10698.607s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[20:31:38 WARN]: Exception in thread "Craft Async Scheduler Management Thread" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
[20:31:38 WARN]:        at java.base/java.lang.Thread.start0(Native Method)
[20:31:38 WARN]:        at java.base/java.lang.Thread.start(Thread.java:800)
[20:31:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:939)
[20:31:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1007)
>....[10698.611s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[20:31:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[20:31:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[20:31:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[20:31:38 ERROR]: Encountered an unexpected exception
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
        at java.lang.Thread.start0(Native Method) ~[?:?]
        at java.lang.Thread.start(Thread.java:800) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:939) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1345) ~[?:?]
        at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:687) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncScheduler.mainThreadHeartbeat(CraftAsyncScheduler.java:73) ~[patched_1.17.1.jar:git-Paper-104]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:450) ~[patched_1.17.1.jar:git-Paper-104]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-104]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-104]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-104]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-104]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-104]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[20:31:38 ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2021-07-22_20.31.38-server.txt

**Comment by brasilcraft54** [comment]
look at this I reset the island 2 times in a row very fast and managed to crash the server there is something wrong with this plugin
