### ISSUE TITLE
I tried to change the name of ladder groups but it spam errors and does not work.

### ISSUE THREAD

**Issue by SbirTeo** [BG-Software-LLC/SuperiorSkyblock2#418]
### Minecraft's Version

1.17.1

### Plugin's Version

latest 1.7.0 devb209

### Describe the bug

I tried to change the name of the group ladders in config.yml but i doesn't work

### To Reproduce

I tried to change the name of the group ladders in config.yml but i doesn't work

**Comment by OmerBenGera** [comment]
Maybe include the errors it gives you..?

**Comment by SbirTeo** [comment]
http://prntscr.com/1iz4qnc

error: 
[12:01:15 INFO]: [SuperiorSkyblock2]  - Found 669 messages in the language files.
[12:01:15 INFO]: [SuperiorSkyblock2] Loading messages done (Took 156ms)
[12:01:15 INFO]: [SuperiorSkyblock2] Successfully loaded schematic normal.schematic (SuperiorSkyblock)
[12:01:15 WARN]: com.bgsoftware.superiorskyblock.utils.exceptions.HandlerLoadException: java.lang.IllegalArgumentException: Invalid role name: Moderator
[12:01:15 WARN]:        at com.bgsoftware.superiorskyblock.handlers.MenusHandler.loadMenu(MenusHandler.java:275)
[12:01:15 WARN]:        at com.bgsoftware.superiorskyblock.handlers.MenusHandler.loadData(MenusHandler.java:49)
[12:01:15 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:454)
[12:01:15 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:194)
[12:01:15 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[12:01:15 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[12:01:15 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[12:01:15 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
[12:01:15 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
[12:01:15 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639)
[12:01:15 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[12:01:15 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126)
[12:01:15 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[12:01:15 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[12:01:15 WARN]: Caused by: java.lang.IllegalArgumentException: Invalid role name: Moderator
[12:01:15 WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
[12:01:15 WARN]:        at com.bgsoftware.superiorskyblock.handlers.PlayersHandler.getPlayerRole(PlayersHandler.java:115)
[12:01:15 WARN]:        at com.bgsoftware.superiorskyblock.island.SPlayerRole.of(SPlayerRole.java:118)
[12:01:15 WARN]:        at com.bgsoftware.superiorskyblock.menu.MenuMemberRole.init(MenuMemberRole.java:110)
[12:01:15 WARN]:        at com.bgsoftware.superiorskyblock.handlers.MenusHandler.loadMenu(MenusHandler.java:273)
[12:01:15 WARN]:        ... 13 more
[12:01:15 INFO]: [SuperiorSkyblock2] Trying to connect to MySQL database...
[12:01:15 INFO]: [com.bgsoftware.superiorskyblock.utils.hikari.HikariDataSource] SuperiorSkyblock Pool - Starting...
[12:01:15 WARN]: [com.bgsoftware.superiorskyblock.utils.hikari.util.DriverDataSource] Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.
[12:01:15 INFO]: [com.bgsoftware.superiorskyblock.utils.hikari.HikariDataSource] SuperiorSkyblock Pool - Start completed.
[12:01:15 INFO]: [SuperiorSkyblock2] Successfully established connection with MySQL database!

**Comment by OmerBenGera** [comment]
You changed the name of roles but didnt update them in the member roles menu as well.
Fix them there as well and it will be fixed.
