### ISSUE TITLE
Errors on all events

### ISSUE THREAD

**Issue by NatsuTwin** [BG-Software-LLC/SuperiorSkyblock2#450]
### Minecraft's Version

1.12.2 Paper

### Plugin's Version

SuperiorSkyblock b221

### Describe the bug

When a player does any event (place, break, fill a bucket, when a leaf decay) i get a nullpointerexception in my console

[15:40:31 ERROR]: Could not pass event PlayerBucketFillEvent to SuperiorSkyblock2 v1.7.0-DEVb221
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1618]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.getPlayerBucketEvent(CraftEventFactory.java:187) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerBucketFillEvent(CraftEventFactory.java:164) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.ItemBucket.a(ItemBucket.java:56) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.ItemStack.a(ItemStack.java:330) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:431) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1064) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_292]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.NullPointerException
        at com.bgsoftware.superiorskyblock.handlers.BlockValuesHandler.convertValueToLevel(BlockValuesHandler.java:181) ~[?:?]
        at com.bgsoftware.superiorskyblock.handlers.BlockValuesHandler.getBlockLevel(BlockValuesHandler.java:100) ~[?:?]
        at com.bgsoftware.superiorskyblock.island.SIsland.handleBlockBreak(SIsland.java:1923) ~[?:?]
        at com.bgsoftware.superiorskyblock.island.SIsland.handleBlockBreak(SIsland.java:1914) ~[?:?]
        at com.bgsoftware.superiorskyblock.island.SIsland.handleBlockBreak(SIsland.java:1908) ~[?:?]
        at com.bgsoftware.superiorskyblock.listeners.BlocksListener.onBucketFillMonitor(BlocksListener.java:123) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor305.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1618]
        ... 20 more

### To Reproduce

Start the server
Break/place/...

### Additional Information

I think it comes from the fact that the placed block is not in the level config for block-values.

**Comment by OmerBenGera** [comment]
show me your config please

**Comment by NatsuTwin** [comment]
My config.yml file:
https://paste.gg/p/anonymous/cf5d97c6d8834e7bae642959ce2c10f2

My levels.yml file:
https://paste.gg/p/anonymous/419cf62e4ae947d48afcd8cf4d9bfa1c

**Comment by OmerBenGera** [comment]
look for the following section and set it to be:
```
# Set a formula to calculate the island level by it's worth.
# Use {} as a placeholder for worth. Make sure you only use digits and mathematical operations!
island-level-formula: '0'
```
You want levels to be 0, you can't set this formula to be empty, as it must be a valid number.
