### ISSUE TITLE
[Bug] You cannot use "/is level"

### ISSUE THREAD

**Issue by YuiDG** [BG-Software-LLC/SuperiorSkyblock2#451]
### Minecraft's Version

Server Paper 1.12.2

### Plugin's Version

SuperiorSkyBlock2 **b221**

### Describe the bug

When I use **"/is level"** my island gives an error on the console and keeps recalculating the island infinitely, except when I restart the server

I use the translator, so if I have any errors, I'm sorry :P ☕

### To Reproduce

**1.** First you create an island.
**2.** Then you use "/is level"
**3.** Right after that comes the error in the chat and in the console

### Additional Information

Console error: https://pastebin.com/EGq5HJMG
Video: 

https://user-images.githubusercontent.com/73173641/129459310-2a8f9c5d-c867-4e68-9854-2e5fda25a092.mp4

**Comment by brasilcraft54** [comment]
[21:01:12 ERROR]: Could not pass event ProjectileHitEvent to SuperiorSkyblock2 v1.7.0-DEVb221
java.lang.NullPointerException: Cannot invoke "org.bukkit.block.Block.getType()" because "hitBlock" is null
        at com.bgsoftware.superiorskyblock.listeners.SettingsListener.onBowAttackChorus(SettingsListener.java:236) ~[SuperiorSkyblock2-b221.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor634.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1311]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1311]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1311]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1311]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:1380) ~[patched_1.17.1.jar:git-Purpur-1311]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:183) ~[app:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:241) ~[app:?]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:112) ~[app:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1186) ~[app:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1034) ~[app:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$7(ServerLevel.java:803) ~[app:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[patched_1.17.1.jar:git-Purpur-1311]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:784) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1629) ~[patched_1.17.1.jar:git-Purpur-1311]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.1.jar:git-Purpur-1311]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Purpur-1311]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1311]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1311]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[21:01:19 ERROR]: Could not pass event ProjectileHitEvent to SuperiorSkyblock2 v1.7.0-DEVb221
java.lang.NullPointerException: Cannot invoke "org.bukkit.block.Block.getType()" because "hitBlock" is null
        at com.bgsoftware.superiorskyblock.listeners.SettingsListener.onBowAttackChorus(SettingsListener.java:236) ~[SuperiorSkyblock2-b221.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor634.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1311]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1311]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1311]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1311]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:1380) ~[patched_1.17.1.jar:git-Purpur-1311]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:183) ~[app:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:241) ~[app:?]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:112) ~[app:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1186) ~[app:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1034) ~[app:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$7(ServerLevel.java:803) ~[app:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[patched_1.17.1.jar:git-Purpur-1311]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:784) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1629) ~[patched_1.17.1.jar:git-Purpur-1311]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.1.jar:git-Purpur-1311]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Purpur-1311]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1311]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1311]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by brasilcraft54** [comment]
version server purpur-1.17.1

**Comment by OmerBenGera** [comment]
@basilcraft54 don't mix unrelated issues please.

**Comment by brasilcraft54** [comment]
I don't have this problem with 1.17.1

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
