### ISSUE TITLE
ProjectileHitEvent to SuperiorSkyblock2 v1.7.0-DEVb227

### ISSUE THREAD

**Issue by brasilcraft54** [BG-Software-LLC/SuperiorSkyblock2#469]
### Minecraft's Version

purpur-1.17.1

### Plugin's Version

DEVb227

### Describe the bug

[14:34:58 ERROR]: Could not pass event ProjectileHitEvent to SuperiorSkyblock2 v1.7.0-DEVb227
java.lang.NullPointerException: Cannot invoke "org.bukkit.block.Block.getType()" because "hitBlock" is null
        at com.bgsoftware.superiorskyblock.listeners.SettingsListener.onBowAttackChorus(SettingsListener.java:236) ~[SuperiorSkyblock2-b227.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor713.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1311]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1311]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1311]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1311]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:1380) ~[patched_1.17.1.jar:git-Purpur-1311]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:183) ~[app:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:241) ~[app:?]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:112) ~[app:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1186) ~[app:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1034) ~[app:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$7(ServerLevel.java:803) ~[app:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[patched_1.17.1.jar:git-Purpur-1311]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:784) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1629) ~[patched_1.17.1.jar:git-Purpur-1311]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.1.jar:git-Purpur-1311]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Purpur-1311]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1311]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1311]
        at java.lang.Thread.run(Thread.java:831) [?:?]

### To Reproduce

when you shoot an arrow at a mob.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
