### ISSUE TITLE
ConcurrentModificationException has been occured when I disabled server.

### ISSUE THREAD

**Issue by RookieAND** [BG-Software-LLC/SuperiorSkyblock2#591]
### Minecraft's Version

Paper 1.16.5 lastest build

### Plugin's Version

SS2 b-276 (dev build)

### Describe the bug

When My server is disabled. this error log always printed. I didn't know what's the problem.

```
[21:21:03] [Server thread/WARN]: java.util.ConcurrentModificationException
[21:21:03] [Server thread/WARN]: 	at java.base/java.util.HashMap$Values.forEach(HashMap.java:979)
[21:21:03] [Server thread/WARN]: 	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
[21:21:03] [Server thread/WARN]: 	at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onDisable(SuperiorSkyblockPlugin.java:313)
[21:21:03] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[21:21:03] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405)
[21:21:03] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533)
[21:21:03] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:519)
[21:21:03] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:512)
[21:21:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.disablePlugins(CraftServer.java:452)
[21:21:03] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:901)
[21:21:03] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:763)
[21:21:03] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1177)
[21:21:03] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[21:21:03] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```

### To Reproduce

First, I remove all of data in SS2 (island world either) but It doesn't disappeared.

Second, I re - write all of my config file but It doesn't solve either.

### Additional Information

Full log of server is enabled to disabled. -> https://pastebin.com/BSrLneE3

**Comment by OmerBenGera** [comment]
Update SSB, already has been fixed
