### ISSUE TITLE
Error creating island

### ISSUE THREAD

**Issue by LeAnhTuan0810** [BG-Software-LLC/SuperiorSkyblock2#605]
### Minecraft's Version

1.17.1

### Plugin's Version

b.302

### Describe the bug

error appeared when i created island, https://sourceb.in/RdGsS5wdsm
`[13:20:07 FATAL]: Failed to write chunk data for task: Task for world: 'SuperiorWorld' at 28,1 poi: false, hash: 1383025493
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTTagCompound.getCompound(String)" because "chunkData" is null
        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.getChunkCoordinate(ChunkRegionLoader.java:89) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.world.level.chunk.storage.IChunkLoader.a(IChunkLoader.java:122) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.level.PlayerChunkMap.a(PlayerChunkMap.java:1691) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.level.WorldServer$2.writeData(WorldServer.java:346) ~[patched_1.17.1.jar:git-Purpur-1385]
        at com.destroystokyo.paper.io.PaperFileIOThread$ChunkDataTask.run(PaperFileIOThread.java:566) [patched_1.17.1.jar:git-Purpur-1385]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) [patched_1.17.1.jar:git-Purpur-1385]
        at com.destroystokyo.paper.io.QueueExecutorThread.handleFlushThreads(QueueExecutorThread.java:129) [patched_1.17.1.jar:git-Purpur-1385]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:115) [patched_1.17.1.jar:git-Purpur-1385]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) [patched_1.17.1.jar:git-Purpur-1385]`

### To Reproduce

.when i create island it shows error

**Comment by OmerBenGera** [comment]
Can you send me entire logs file please.

**Comment by OmerBenGera** [comment]
Can you send me entire logs file please.

**Comment by LeAnhTuan0810** [comment]
i lost it, and i tested it again, island creation doesn't work, no spam log
