### ISSUE TITLE
SSB Error

### ISSUE THREAD

**Issue by SecretarySami** [BG-Software-LLC/SuperiorSkyblock2#608]
### Minecraft's Version

1.17.1 Minecraft 
Purpur DEV - 1385

### Plugin's Version

SuperiorSkyblock2-b260.jar

### Describe the bug

Unsure what happened to make the occur , But after sifting through some logs I noticed it 

```
[16:50:46] [Server thread/ERROR]: Could not pass event PlayerPickupArrowEvent to SuperiorSkyblock2 v1.7.0-DEVb260
java.lang.ClassCastException: class net.minecraft.world.entity.projectile.EntityTippedArrow cannot be cast to class net.minecraft.world.entity.item.EntityItem (net.minecraft.world.entity.projectile.EntityTippedArrow and net.minecraft.world.entity.item.EntityItem are in unnamed module of loader 'app')
at com.bgsoftware.superiorskyblock.nms.NMSAdapter_v1_17_R1.wasThrownByPlayer(NMSAdapter_v1_17_R1.java:395) ~[SuperiorSkyblock2-b260.jar:?]
at com.bgsoftware.superiorskyblock.utils.logic.ProtectionLogic.handlePlayerPickupItem(ProtectionLogic.java:209) ~[SuperiorSkyblock2-b260.jar:?]
at com.bgsoftware.superiorskyblock.listeners.ProtectionListener.onPlayerItemPickup(ProtectionListener.java:431) ~[SuperiorSkyblock2-b260.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1228.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1375]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1375]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1375]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1375]
at net.minecraft.world.entity.projectile.EntityArrow.pickup(EntityArrow.java:573) ~[patched_1.17.1.jar:git-Purpur-1375]
at net.minecraft.world.entity.player.EntityHuman.c(EntityHuman.java:663) ~[patched_1.17.1.jar:git-Purpur-1375]
at net.minecraft.world.entity.player.EntityHuman.movementTick(EntityHuman.java:629) ~[patched_1.17.1.jar:git-Purpur-1375]
at net.minecraft.world.entity.EntityLiving.tick(EntityLiving.java:2960) ~[patched_1.17.1.jar:git-Purpur-1375]
at net.minecraft.world.entity.player.EntityHuman.tick(EntityHuman.java:301) ~[patched_1.17.1.jar:git-Purpur-1375]
at net.minecraft.server.level.EntityPlayer.playerTick(EntityPlayer.java:689) ~[patched_1.17.1.jar:git-Purpur-1375]
at net.minecraft.server.network.PlayerConnection.tick(PlayerConnection.java:317) ~[patched_1.17.1.jar:git-Purpur-1375]
at net.minecraft.network.NetworkManager.a(NetworkManager.java:555) ~[patched_1.17.1.jar:git-Purpur-1375]
at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:201) ~[patched_1.17.1.jar:git-Purpur-1375]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1664) ~[patched_1.17.1.jar:git-Purpur-1375]
at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:493) ~[patched_1.17.1.jar:git-Purpur-1375]
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Purpur-1375]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1283) ~[patched_1.17.1.jar:git-Purpur-1375]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1375]
at java.lang.Thread.run(Thread.java:831) [?:?]


### To Reproduce

Unsure how to reproduce

### Additional Information

_No response_

**Comment by OmerBenGera** [comment]
This error was fixed ages ago, update your jar.
