### ISSUE TITLE
Creeper explosion - Server Crash

### ISSUE THREAD

**Issue by mohdnazzal** [BG-Software-LLC/SuperiorSkyblock2#609]
### Minecraft's Version

CraftBukkit version 2991-Spigot-018b9a0-f3f3094 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) false

### Plugin's Version

SuperiorSkyblock2-b127

### Describe the bug

Server crash Cannot drop air

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 9/18/21 4:13 PM
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot drop air
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at net.minecraft.server.v1_16_R3.EntityItem.setItemStack(EntityItem.java:418)
	at net.minecraft.server.v1_16_R3.EntityItem.<init>(EntityItem.java:39)
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.dropItem(CraftWorld.java:603)
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:769)
	at net.minecraft.server.v1_16_R3.EntityLiving.d(EntityLiving.java:1447)
	at net.minecraft.server.v1_16_R3.EntityLiving.die(EntityLiving.java:1395)
	at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1241)
	at net.minecraft.server.v1_16_R3.EntityMonster.damageEntity(SourceFile:73)
	at net.minecraft.server.v1_16_R3.EntityZombie.damageEntity(EntityZombie.java:235)
	at net.minecraft.server.v1_16_R3.Entity.burnFromLava(Entity.java:469)
	at net.minecraft.server.v1_16_R3.Entity.entityBaseTick(Entity.java:415)
	at net.minecraft.server.v1_16_R3.EntityLiving.entityBaseTick(EntityLiving.java:262)
	at net.minecraft.server.v1_16_R3.EntityInsentient.entityBaseTick(EntityInsentient.java:230)
	at net.minecraft.server.v1_16_R3.Entity.tick(Entity.java:364)
	at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2361)
	at net.minecraft.server.v1_16_R3.EntityInsentient.tick(EntityInsentient.java:293)
	at net.minecraft.server.v1_16_R3.EntityZombie.tick(EntityZombie.java:171)
	at net.minecraft.server.v1_16_R3.EntityZombieVillager.tick(EntityZombieVillager.java:108)
	at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:663)
	at net.minecraft.server.v1_16_R3.WorldServer$$Lambda$6890/987921630.accept(Unknown Source)
	at net.minecraft.server.v1_16_R3.World.a(World.java:718)
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:398)
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1105)
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355)
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008)
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847)
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
	at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3221/1856936085.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at net.minecraft.server.v1_16_R3.EntityItem.setItemStack(EntityItem.java:418)
	at net.minecraft.server.v1_16_R3.EntityItem.<init>(EntityItem.java:39)
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.dropItem(CraftWorld.java:603)
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:769)
	at net.minecraft.server.v1_16_R3.EntityLiving.d(EntityLiving.java:1447)
	at net.minecraft.server.v1_16_R3.EntityLiving.die(EntityLiving.java:1395)
	at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1241)
	at net.minecraft.server.v1_16_R3.EntityMonster.damageEntity(SourceFile:73)
	at net.minecraft.server.v1_16_R3.EntityZombie.damageEntity(EntityZombie.java:235)
	at net.minecraft.server.v1_16_R3.Entity.burnFromLava(Entity.java:469)
	at net.minecraft.server.v1_16_R3.Entity.entityBaseTick(Entity.java:415)
	at net.minecraft.server.v1_16_R3.EntityLiving.entityBaseTick(EntityLiving.java:262)
	at net.minecraft.server.v1_16_R3.EntityInsentient.entityBaseTick(EntityInsentient.java:230)
	at net.minecraft.server.v1_16_R3.Entity.tick(Entity.java:364)
	at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2361)
	at net.minecraft.server.v1_16_R3.EntityInsentient.tick(EntityInsentient.java:293)
	at net.minecraft.server.v1_16_R3.EntityZombie.tick(EntityZombie.java:171)
	at net.minecraft.server.v1_16_R3.EntityZombieVillager.tick(EntityZombieVillager.java:108)
	at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:663)
	at net.minecraft.server.v1_16_R3.WorldServer$$Lambda$6890/987921630.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: minecraft:zombie_villager (net.minecraft.server.v1_16_R3.EntityZombieVillager)
	Entity ID: 392
	Entity Name: Zombie Villager
	Entity's Exact location: 601.40, 97.00, 600.63
	Entity's Block location: World: (601,97,600), Chunk: (at 9,6,8 in 37,37; contains blocks 592,0,592 to 607,255,607), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Entity's Momentum: -0.00, -0.02, -0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.v1_16_R3.World.a(World.java:718)
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:398)

-- Affected level --
Details:
	All players: 1 total; [EntityPlayer['Pikatucy'/387, l='ServerLevel[SuperiorWorld]', x=613.56, y=104.47, z=604.61](Pikatucy at 613.5610790657508,104.46612822304682,604.6090264607185)]
	Chunk stats: ServerChunkCache: 8494
	Level dimension: minecraft:superiorworld
	Level spawn location: World: (0,100,0), Chunk: (at 0,6,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 4762026 game time, 4762026 day time
	Level name: SuperiorWorld
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 2992 (now: true), thunder time: 131 (now: true)
	Known server brands: Spigot
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1105)
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355)
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008)
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847)
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
	at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3221/1856936085.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

### To Reproduce

The crash occured again with skeleton arrow
--------
java.lang.IllegalArgumentException: Cannot drop air
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at net.minecraft.server.v1_16_R3.EntityItem.setItemStack(EntityItem.java:418)
	at net.minecraft.server.v1_16_R3.EntityItem.<init>(EntityItem.java:39)
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.dropItem(CraftWorld.java:603)
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:791)
	at net.minecraft.server.v1_16_R3.EntityPlayer.die(EntityPlayer.java:566)
	at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1241)
	at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:745)
	at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:719)
	at net.minecraft.server.v1_16_R3.EntityArrow.a(EntityArrow.java:320)
	at net.minecraft.server.v1_16_R3.IProjectile.a(IProjectile.java:113)
	at net.minecraft.server.v1_16_R3.EntityArrow.tick(EntityArrow.java:164)
	at net.minecraft.server.v1_16_R3.EntityTippedArrow.tick(EntityTippedArrow.java:92)
	at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:663)
	at net.minecraft.server.v1_16_R3.WorldServer$$Lambda$6881/839041554.accept(Unknown Source)
	at net.minecraft.server.v1_16_R3.World.a(World.java:718)
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:398)
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1105)
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355)
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008)
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847)
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
	at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3216/1541464431.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at net.minecraft.server.v1_16_R3.EntityItem.setItemStack(EntityItem.java:418)
	at net.minecraft.server.v1_16_R3.EntityItem.<init>(EntityItem.java:39)
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.dropItem(CraftWorld.java:603)
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:791)
	at net.minecraft.server.v1_16_R3.EntityPlayer.die(EntityPlayer.java:566)
	at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1241)
	at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:745)
	at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:719)
	at net.minecraft.server.v1_16_R3.EntityArrow.a(EntityArrow.java:320)
	at net.minecraft.server.v1_16_R3.IProjectile.a(IProjectile.java:113)
	at net.minecraft.server.v1_16_R3.EntityArrow.tick(EntityArrow.java:164)
	at net.minecraft.server.v1_16_R3.EntityTippedArrow.tick(EntityTippedArrow.java:92)
	at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:663)
	at net.minecraft.server.v1_16_R3.WorldServer$$Lambda$6881/839041554.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: minecraft:arrow (net.minecraft.server.v1_16_R3.EntityTippedArrow)
	Entity ID: 426
	Entity Name: Arrow
	Entity's Exact location: 601.55, 101.64, 605.24
	Entity's Block location: World: (601,101,605), Chunk: (at 9,6,13 in 37,37; contains blocks 592,0,592 to 607,255,607), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Entity's Momentum: 0.44, -0.86, -1.33
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.v1_16_R3.World.a(World.java:718)
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:398)

**Comment by OmerBenGera** [comment]
It's not related to the plugin, it's a bug with your spigot jar.
Use Paper instead of Spigot.
