### ISSUE TITLE
world parameter cannot be null.

### ISSUE THREAD

**Issue by StalkerArea51** [BG-Software-LLC/SuperiorSkyblock2#641]
### Minecraft's Version

1.16.5 PaperSpigot

### Plugin's Version

1.8 20/09/2021 15:28:01

### Describe the bug

[SuperiorSkyblock2] Plugin SuperiorSkyblock2 v1.8 generated an exception while executing task 649128
java.lang.NullPointerException: world parameter cannot be null.
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[patched_1.16.5.jar:git-Paper-778]
at com.bgsoftware.superiorskyblock.world.GridHandler.isIslandsWorld(GridHandler.java:404) ~[?:?]
at com.bgsoftware.superiorskyblock.api.missions.Mission.canComplete(Mission.java:151) ~[?:?]
at com.bgsoftware.superiorskyblock.missions.KillsMissions.lambda$onEntityKill$2(KillsMissions.java:190) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-778]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-778]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-778]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_301]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_301]

### To Reproduce

error saying world parameter cant be null 

try other version still the same eror

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
