### ISSUE TITLE
Nashorn Engine - Can't load

### ISSUE THREAD

**Issue by Kbryst** [BG-Software-LLC/SuperiorSkyblock2#646]
### Minecraft's Version

1.17.1 paper 295.

### Plugin's Version

Attempted on b4 and b3

### Describe the bug

`[06:51:37 ERROR]: Could not load 'plugins/SuperiorSkyblock2-NashornEngine-b4.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[patched_1.17.1.jar:git-Paper-295]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:160) ~[patched_1.17.1.jar:git-Paper-295]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:410) ~[patched_1.17.1.jar:git-Paper-295]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:276) ~[patched_1.17.1.jar:git-Paper-295]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1212) ~[patched_1.17.1.jar:git-Paper-295]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-295]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 7 more`

### To Reproduce

First time startup with the plugin.

### Additional Information

Another plugin required NashornPlus. That's about all I got.

**Comment by OmerBenGera** [comment]
https://wiki.bg-software.com/superiorskyblock/new-java-engine
