### ISSUE TITLE
FATAL ERROR

### ISSUE THREAD

**Issue by SbirTeo** [BG-Software-LLC/SuperiorSkyblock2#656]
### Minecraft's Version

1.17.1

### Plugin's Version

Latest version 

### Describe the bug

[16:23:14 FATAL]: Error executing task on Server
java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.TimSort.mergeHi(TimSort.java:903) ~[?:?]
        at java.util.TimSort.mergeAt(TimSort.java:520) ~[?:?]
        at java.util.TimSort.mergeForceCollapse(TimSort.java:461) ~[?:?]
        at java.util.TimSort.sort(TimSort.java:254) ~[?:?]
        at java.util.Arrays.sort(Arrays.java:1306) ~[?:?]
        at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:503) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at net.minecraft.server.players.GameProfileCache.save(GameProfileCache.java:300) ~[app:?]
        at net.minecraft.server.players.GameProfileCache.add(GameProfileCache.java:138) ~[app:?]
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$1(SkullBlockEntity.java:162) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-325]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1418) ~[patched_1.17.1.jar:git-Paper-325]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-325]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1396) ~[patched_1.17.1.jar:git-Paper-325]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1389) ~[patched_1.17.1.jar:git-Paper-325]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1367) ~[patched_1.17.1.jar:git-Paper-325]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1278) ~[patched_1.17.1.jar:git-Paper-325]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-325]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]

### To Reproduce

none

**Comment by OmerBenGera** [comment]
This is really not related to the plugin.
It has something to do with a skull block that causes it to happen.
