### ISSUE TITLE
Database conversion fails

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#685]
### Minecraft's Version

1.17.1 Purpur dev 1395

### Plugin's Version

Dev 338

### Describe the bug

When converting old database to the new type the conversion fails and ends up not converting the entire database.

Ome_R — 10/22/2021
I don't know what the issue is
something with MySQL being dumb as always
It refuses to insert the data even tho it's in the correct length

### To Reproduce

Unsure at this time

### Additional Information

[09:31:49] [Server thread/INFO]: [SuperiorSkyblock2] [Database-Converter] Converting players...
[09:32:07] [Server thread/INFO]: [SuperiorSkyblock2] Failed to execute query REPLACE INTO players_missions VALUES(00093c44-7b32-428c-9eaa-6d0e23974087,makingacomposter,1)
[09:32:07] [Server thread/WARN]: java.sql.BatchUpdateException: Data truncation: Data too long for column 'name' at row 1
[09:32:07] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[09:32:07] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[09:32:07] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[09:32:07] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[09:32:07] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[09:32:07] [Server thread/WARN]: 	at com.mysql.cj.util.Util.handleNewInstance(Util.java:192)
[09:32:07] [Server thread/WARN]: 	at com.mysql.cj.util.Util.getInstance(Util.java:167)
[09:32:07] [Server thread/WARN]: 	at com.mysql.cj.util.Util.getInstance(Util.java:174)
[09:32:07] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224)
[09:32:07] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:853)
[09:32:07] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:435)
[09:32:07] [Server thread/WARN]: 	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:794)
[09:32:07] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8-b331.jar//com.bgsoftware.superiorskyblock.libs.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
[09:32:07] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8-b331.jar//com.bgsoftware.superiorskyblock.libs.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
[09:32:07] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8-b331.jar//com.bgsoftware.superiorskyblock.database.sql.StatementHolder.lambda$executeBatch$1(StatementHolder.java:69)
[09:32:07] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8-b331.jar//com.bgsoftware.superiorskyblock.database.sql.SQLSession.buildStatement(SQLSession.java:183)
[09:32:07] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8-b331.jar//com.bgsoftware.superiorskyblock.database.sql.SQLHelper.buildStatement(SQLHelper.java:52)
[09:32:07] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8-b331.jar//com.bgsoftware.superiorskyblock.database.sql.StatementHolder.executeBatch(StatementHolder.java:58)
[09:32:07] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8-b331.jar//com.bgsoftware.superiorskyblock.database.loader.v1.DatabaseLoader_V1.savePlayers(DatabaseLoader_V1.java:188)
[09:32:07] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8-b331.jar//com.bgsoftware.superiorskyblock.database.loader.v1.DatabaseLoader_V1.saveData(DatabaseLoader_V1.java:141)
[09:32:07] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8-b331.jar//com.bgsoftware.superiorskyblock.database.DataHandler.loadDataWithException(DataHandler.java:56)
[09:32:07] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8-b331.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:492)
[09:32:07] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8-b331.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:247)
[09:32:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[09:32:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[09:32:07] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[09:32:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:535)
[09:32:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:449)
[09:32:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:727)
[09:32:07] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:318)
[09:32:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1216)
[09:32:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[09:32:07] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[09:32:07] [Server thread/WARN]: Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'name' at row 1
[09:32:07] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
[09:32:07] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[09:32:07] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
[09:32:07] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:832)
[09:32:07] [Server thread/WARN]: 	... 23 more

**Comment by Skizzles** [comment]
@OmerBenGera just wanted to update on this, I cloned the database onto a dev environment and attempted conversion which that was successful.

Going to be attempting conversion with production and will update if its resolved. (This is as of dev 348)

**Comment by Skizzles** [comment]
Still threw some errors. Looking further

**Comment by Skizzles** [comment]
@OmerBenGera Seems that it fails conversion only on Stacked Blocks and Missions, I can not find the cause of this.

**Comment by Skizzles** [comment]
![jiNaliZo73](https://user-images.githubusercontent.com/30563757/141786062-405ca186-34d3-487f-8bba-89f5a45a57fb.png)
These show on a converted database and new database.

**Comment by Skizzles** [comment]
![raGElOWa40](https://user-images.githubusercontent.com/30563757/141791873-97dd2b13-1e3a-4c5d-b3e8-74243eee5705.png)
Further warnings shown for even grid

**Comment by OmerBenGera** [comment]
Turned to be an issue with limits of mission-names that were too short and weren't enforced code-wise.
These have been addressed and seems to work fine on latest dev builds.
