### ISSUE TITLE
Updating database to new version 

### ISSUE THREAD

**Issue by cobrex1** [BG-Software-LLC/SuperiorSkyblock2#692]
### Minecraft's Version

1.17.1 number 353

### Plugin's Version

1.8-b338

### Describe the bug

Running the conversion from the old system (version b260) to the new system and the server stopped with the following errors:
.
.
.
[06:26:53] [Server thread/INFO]: [SuperiorSkyblock2] Registered mission 100k-worth
[06:26:53] [Server thread/INFO]: [SuperiorSkyblock2] Finished enabling the module missions (Took 1322ms)
[06:26:53] [Server thread/INFO]: [SuperiorSkyblock2] Enabling the module nashorn-engine...
[06:26:53] [Server thread/WARN]: [SuperiorSkyblock2] Loaded class org.openjdk.nashorn.api.scripting.NashornScriptEngineFactory from NashornPlus v1.1.0 which is not a depend, softdepend or loadbefore of this plugin.
[06:26:53] [Server thread/INFO]: [SuperiorSkyblock2] Finished enabling the module nashorn-engine (Took 163ms)
[06:26:53] [Server thread/INFO]: [SuperiorSkyblock2] Enabling the module generators...
[06:26:53] [Server thread/INFO]: [SuperiorSkyblock2] Finished enabling the module generators (Took 0ms)
[06:26:53] [Server thread/INFO]: [SuperiorSkyblock2] Enabling the module upgrades...
[06:26:53] [Server thread/INFO]: [SuperiorSkyblock2] Finished enabling the module upgrades (Took 8ms)
[06:26:54] [Server thread/INFO]: [SuperiorSkyblock2] Loading messages started...
[06:26:54] [Server thread/INFO]: [SuperiorSkyblock2]  - Found 676 messages in the language files.
[06:26:54] [Server thread/INFO]: [SuperiorSkyblock2] Loading messages done (Took 101ms)
[06:26:54] [Server thread/INFO]: [SuperiorSkyblock2] Schematic normal_nether.schematic was created in a different version, may cause issues.
[06:26:54] [Server thread/INFO]: [SuperiorSkyblock2] Successfully loaded schematic normal_nether.schematic (SuperiorSkyblock)
[06:26:54] [Server thread/INFO]: [SuperiorSkyblock2] Schematic normal.schematic was created in a different version, may cause issues.
[06:26:54] [Server thread/INFO]: [SuperiorSkyblock2] Successfully loaded schematic normal.schematic (SuperiorSkyblock)
[06:26:54] [Server thread/INFO]: [SuperiorSkyblock2] Schematic normal_the_end.schematic was created in a different version, may cause issues.
[06:26:54] [Server thread/INFO]: [SuperiorSkyblock2] Successfully loaded schematic normal_the_end.schematic (SuperiorSkyblock)
[06:26:54] [Server thread/INFO]: [SuperiorSkyblock2] Trying to connect to SQLite database...
[06:26:54] [Server thread/INFO]: [SuperiorSkyblock2] Successfully established connection with SQLite database!
[06:26:54] [Server thread/INFO]: [SuperiorSkyblock2] [Database-Converter] Detected old database - starting to convert data...
[06:26:54] [Server thread/INFO]: [SuperiorSkyblock2] [Database-Converter] Found 6031 players in the database.
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] [Database-Converter] Found 3855 islands in the database.
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] [Database-Converter] Found 2661 stacked blocks in the database.
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] [Database-Converter] Found 1503 bank transactions in the database.
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] [Database-Converter] Successfully created a backup for the database.
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] Trying to connect to SQLite database...
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] Successfully established connection with SQLite database!
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] [Database-Converter] Converting players...
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] [Database-Converter] Converting islands...
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] ################################################
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] ##                                            ##
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] ## An error occured while loading the plugin! ##
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] ##                                            ##
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] ################################################
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] 
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] Error:
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] &cUnexpected error occurred while saving data:
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] 
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] StackTrace:
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] 	at SuperiorSkyblock2-1.8-b338.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:494)
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] 	at SuperiorSkyblock2-1.8-b338.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:247)
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:730)
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1217)
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] 	at java.base/java.lang.Thread.run(Thread.java:831)
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] Caused by: java.lang.NullPointerException: Cannot invoke "com.bgsoftware.superiorskyblock.database.loader.v1.attributes.PlayerAttributes.getValue(java.lang.Enum)" because "playerAttributes" is null
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] 	at SuperiorSkyblock2-1.8-b338.jar//com.bgsoftware.superiorskyblock.database.loader.v1.DatabaseLoader_V1.lambda$insertIsland$11(DatabaseLoader_V1.java:368)
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] 	at SuperiorSkyblock2-1.8-b338.jar//com.bgsoftware.superiorskyblock.database.loader.v1.DatabaseLoader_V1.insertIsland(DatabaseLoader_V1.java:366)
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] 	at SuperiorSkyblock2-1.8-b338.jar//com.bgsoftware.superiorskyblock.database.loader.v1.DatabaseLoader_V1.saveIslands(DatabaseLoader_V1.java:221)
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] 	at SuperiorSkyblock2-1.8-b338.jar//com.bgsoftware.superiorskyblock.database.loader.v1.DatabaseLoader_V1.saveData(DatabaseLoader_V1.java:142)
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] 	at SuperiorSkyblock2-1.8-b338.jar//com.bgsoftware.superiorskyblock.database.DataHandler.loadDataWithException(DataHandler.java:56)
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] 	... 12 more
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] 
[06:26:55] [Server thread/INFO]: [SuperiorSkyblock2] ################################################

### To Reproduce

use version b260 and update to b338 (I assume)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build, sorry about the long waiting time.
