### ISSUE TITLE
Dragon Battle Error

### ISSUE THREAD

**Issue by exzolink** [BG-Software-LLC/SuperiorSkyblock2#700]
### Minecraft's Version

Airplane 1.16.5

### Plugin's Version

337

### Describe the bug

`[22:28:57 WARN]: [SuperiorSkyblock2] Task #132 for SuperiorSkyblock2 v1.8-DEVb337 generated an exception
java.lang.UnsupportedOperationException: null
        at java.util.Collections$UnmodifiableCollection.removeIf(Collections.java:1091) ~[?:?]
        at com.bgsoftware.superiorskyblock.nms.v1_16_R3.NMSDragonFightImpl$IslandEnderDragonBattle.updateBattlePlayers(NMSDragonFightImpl.java:466) ~[?:?]
        at com.bgsoftware.superiorskyblock.nms.v1_16_R3.NMSDragonFightImpl$IslandEnderDragonBattle.b(NMSDragonFightImpl.java:250) ~[?:?]
        at java.util.HashMap$Values.forEach(HashMap.java:1067) ~[?:?]
        at com.bgsoftware.superiorskyblock.nms.v1_16_R3.NMSDragonFightImpl.tickBattles(NMSDragonFightImpl.java:104) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Airplane-11]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485) ~[patched_1.16.5.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1489) ~[patched_1.16.5.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.16.5.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1402) ~[patched_1.16.5.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Airplane-11]
        at java.lang.Thread.run(Thread.java:831) [?:?]`

### To Reproduce

Just fight a dragon

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
