### ISSUE TITLE
Dragon fight bug

### ISSUE THREAD

**Issue by Rivils** [BG-Software-LLC/SuperiorSkyblock2#724]
### Minecraft's Version

git-Purpur-1423 (MC: 1.17.1)

### Plugin's Version

DEV-1.8.1.359

### Session Logs

https://pastebin.com/d3gsvBKU

### Describe the bug

When fighting the dragon the health on bossbar doesn't decrease, after killing the dragon with command and disbanding the island I got this error.

[22:38:47 WARN]: [SuperiorSkyblock2] Task #1023 for SuperiorSkyblock2 v1.8.1.359 generated an exception
java.util.ConcurrentModificationException: null
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1699) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at com.bgsoftware.superiorskyblock.nms.v1_17_R1.NMSDragonFightImpl$IslandEnderDragonBattle.updateBattlePlayers(NMSDragonFightImpl.java:472) ~[SuperiorSkyblock2-1.8.1-b359.jar:?]
        at com.bgsoftware.superiorskyblock.nms.v1_17_R1.NMSDragonFightImpl$IslandEnderDragonBattle.b(NMSDragonFightImpl.java:248) ~[SuperiorSkyblock2-1.8.1-b359.jar:?]
        at java.util.HashMap$Values.forEach(HashMap.java:1067) ~[?:?]
        at com.bgsoftware.superiorskyblock.nms.v1_17_R1.NMSDragonFightImpl.tickBattles(NMSDragonFightImpl.java:113) ~[SuperiorSkyblock2-1.8.1-b359.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1423]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1423]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1588) ~[patched_1.17.1.jar:git-Purpur-1423]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:528) ~[patched_1.17.1.jar:git-Purpur-1423]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1504) ~[patched_1.17.1.jar:git-Purpur-1423]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1297) ~[patched_1.17.1.jar:git-Purpur-1423]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1423]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]

### To Reproduce

attack the dragon at the end island.

**Comment by OmerBenGera** [comment]
Should be fixed in latest build

**Comment by OmerBenGera** [comment]
If it still occurs, make sure you let me know by commenting here.
