### ISSUE TITLE
Tab complete doesn't work for /is admin resetworld

### ISSUE THREAD

**Issue by Ynfuien** [BG-Software-LLC/SuperiorSkyblock2#750]
### Minecraft's Version

Airplane-Purpur git-Airplane-6 1.16.5

### Plugin's Version

1.8.1 and tested on dev 376

### Session Logs

```
[13:04:06 ERROR]: Exception when Ynfuien attempted to tab complete is admin resetworld Ynfuien
org.bukkit.command.CommandException: Unhandled exception executing tab-completer for 'is admin resetworld Ynfuien ' in com.bgsoftware.superiorskyblock.commands.CommandsHandler$PluginCommand(island)
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:263) ~[patched_1.16.5.jar:git-Airplane-6]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.tabCompleteCommand(CraftServer.java:2004) ~[patched_1.16.5.jar:git-Airplane-6]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.tabComplete(CraftServer.java:1976) ~[patched_1.16.5.jar:git-Airplane-6]
        at org.bukkit.craftbukkit.v1_16_R3.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:58) ~[patched_1.16.5.jar:git-Airplane-6]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[patched_1.16.5.jar:git-Airplane-6]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:597) ~[patched_1.16.5.jar:git-Airplane-6]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579) ~[patched_1.16.5.jar:git-Airplane-6]
        at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$7(PlayerConnection.java:862) ~[patched_1.16.5.jar:git-Airplane-6]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Airplane-6]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Airplane-6]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Airplane-6]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Airplane-6]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1339) ~[patched_1.16.5.jar:git-Airplane-6]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1332) ~[patched_1.16.5.jar:git-Airplane-6]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Airplane-6]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1308) ~[patched_1.16.5.jar:git-Airplane-6]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1152) ~[patched_1.16.5.jar:git-Airplane-6]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Airplane-6]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
        at com.bgsoftware.superiorskyblock.commands.admin.CmdAdminResetWorld.adminTabComplete(CmdAdminResetWorld.java:124) ~[?:?]
        at com.bgsoftware.superiorskyblock.commands.IAdminIslandCommand.tabComplete(IAdminIslandCommand.java:39) ~[?:?]
        at com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.tabComplete(ISuperiorCommand.java:17) ~[?:?]
        at com.bgsoftware.superiorskyblock.commands.player.CmdAdmin.tabComplete(CmdAdmin.java:137) ~[?:?]
        at com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.tabComplete(ISuperiorCommand.java:17) ~[?:?]
        at com.bgsoftware.superiorskyblock.commands.CommandsHandler$PluginCommand.tabComplete(CommandsHandler.java:301) ~[?:?]
        at org.bukkit.command.Command.tabComplete(Command.java:93) ~[patched_1.16.5.jar:git-Airplane-6]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:257) ~[patched_1.16.5.jar:git-Airplane-6]
        ... 18 more
```

### Describe the bug

After typing `/is admin resetworld <nick>`, when I try to type a world to reset, tab complete doesn't work and console throws error

### To Reproduce

Just type `/is admin resetworld <nick> `  (yes, with space at the end) and watch for error

### Additional Information

![image](https://user-images.githubusercontent.com/88110072/143580446-0770f3ae-711a-4957-bc8c-9293b16c42ef.png)

**Comment by OmerBenGera** [comment]
Fixed in latest build
