### ISSUE TITLE
database issues

### ISSUE THREAD

**Issue by Neige7** [BG-Software-LLC/SuperiorSkyblock2#770]
### Minecraft's Version

Paper(776) 1.16.5-R0.1-SNAPSHOT

### Plugin's Version

b155 to 1.8.2

### Session Logs

```
[18:45:34]: Action: Register Sorting Type, Sorting Type: WORTH
[18:45:34]: Action: Register Sorting Type, Sorting Type: LEVEL
[18:45:34]: Action: Register Sorting Type, Sorting Type: RATING
[18:45:34]: Action: Register Sorting Type, Sorting Type: PLAYERS
[18:45:34]: &aEnabling the module bank...
[18:45:34]: &eFinished enabling the module bank (Took 2ms)
[18:45:34]: &aEnabling the module missions...
[18:45:34]: &eFinished enabling the module missions (Took 0ms)
[18:45:34]: &aEnabling the module generators...
[18:45:34]: &eFinished enabling the module generators (Took 2ms)
[18:45:34]: &aEnabling the module upgrades...
[18:45:34]: &eFinished enabling the module upgrades (Took 9ms)
[18:45:34]: Loading messages started...
[18:45:34]:  - Found 674 messages in the language files.
[18:45:34]: Loading messages done (Took 55ms)
[18:45:34]: Successfully loaded schematic desert.schematic (DefaultSchematicParser)
[18:45:34]: Successfully loaded schematic desert_nether.schematic (DefaultSchematicParser)
[18:45:35]: Successfully loaded schematic desert_the_end.schematic (DefaultSchematicParser)
[18:45:35]: Successfully loaded schematic mycel.schematic (DefaultSchematicParser)
[18:45:35]: Successfully loaded schematic mycel_nether.schematic (DefaultSchematicParser)
[18:45:35]: Successfully loaded schematic mycel_the_end.schematic (DefaultSchematicParser)
[18:45:35]: Successfully loaded schematic normal.schematic (DefaultSchematicParser)
[18:45:35]: Successfully loaded schematic normal_nether.schematic (DefaultSchematicParser)
[18:45:35]: Successfully loaded schematic normal_the_end.schematic (DefaultSchematicParser)
[18:45:35]: java.lang.NullPointerException: Couldn't find an IslandPrivilege with the name check_permission.
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
	at com.bgsoftware.superiorskyblock.api.island.IslandPrivilege.getByName(IslandPrivilege.java:36)
	at com.bgsoftware.superiorskyblock.menu.impl.MenuPermissions.init(MenuPermissions.java:91)
	at com.bgsoftware.superiorskyblock.hooks.provider.MenusProvider_Default.handleExceptions(MenusProvider_Default.java:69)
	at com.bgsoftware.superiorskyblock.hooks.provider.MenusProvider_Default.initializeMenus(MenusProvider_Default.java:106)
	at com.bgsoftware.superiorskyblock.menu.MenusHandler.loadData(MenusHandler.java:26)
	at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:495)
	at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:279)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
	at java.base/java.lang.Thread.run(Thread.java:834)

[18:45:35]: &a[Database-Converter] Detected old database - starting to convert data...
[18:45:35]: &a[Database-Converter] Found 0 players in the database.
[18:45:35]: com.bgsoftware.superiorskyblock.handler.HandlerLoadException: &cUnexpected error occurred while converting data:
	at com.bgsoftware.superiorskyblock.database.DataHandler.loadDataWithException(DataHandler.java:46)
	at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:498)
	at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:279)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at com.bgsoftware.superiorskyblock.database.loader.v1.DatabaseLoader_V1.loadIsland(DatabaseLoader_V1.java:534)
	at com.bgsoftware.superiorskyblock.database.loader.v1.DatabaseLoader_V1.lambda$loadData$1(DatabaseLoader_V1.java:100)
	at com.bgsoftware.superiorskyblock.database.sql.SQLSession.executeQuery(SQLSession.java:167)
	at com.bgsoftware.superiorskyblock.database.sql.SQLSession.executeQuery(SQLSession.java:155)
	at com.bgsoftware.superiorskyblock.database.loader.v1.DatabaseLoader_V1.loadData(DatabaseLoader_V1.java:98)
	at com.bgsoftware.superiorskyblock.database.DataHandler.loadDataWithException(DataHandler.java:44)
	... 12 more
```

### Describe the bug

I upgraded SuperiorSkyblock2 to the newest version and then rolled back to the old version and now my database is corrupted. how do I fix it?
I upgraded it from b155 to 1.8.2.
At first the plugin successfully upgraded the database to the new version of the structure, but then I found that the new version of SuperiorSkyblock2 did not adapt to the old version of Slimefun, so I tried to roll back it. And then the database of SuperiorSkyblock2 broken
Now both the new version and the old version of SuperiorSkyblock2 do not recognize my database

### To Reproduce

use b155, upgrade to 1.8.2 and then roll back to b155

**Comment by OmerBenGera** [comment]
You did something that you shouldnt have done - downgrading is never supported. By updating to latest build, your database was migrated and changed, and after downgrading its not working for you.
Use latest stable version / dev build and hopefully it will work and you didnt corrupt your database.

**Comment by Neige7** [comment]
> You did something that you shouldnt have done - downgrading is never supported. By updating to latest build, your database was migrated and changed, and after downgrading its not working for you. Use latest stable version / dev build and hopefully it will work and you didnt corrupt your database. If it doesnt work, look for the backup database file (if using SQlite) or the backup tables (if using MySQL) and load them.

I haven;t got backup.
[new.sql.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/7646858/new.sql.txt)
This is my data now.
Is there a way I can fix it?

**Comment by OmerBenGera** [comment]
Are you using mysql or sqlite?

**Comment by Neige7** [comment]
> Are you using mysql or sqlite?

I use marian. it’s similar to mysql

**Comment by OmerBenGera** [comment]
> > Are you using mysql or sqlite?
> 
> I use mariadb. it’s similar to mysql

yeah that's fine.
What tables do you have in the database?

**Comment by Neige7** [comment]
bank_transactions
grid
islands
islands_banks
islands_bans
islands_block_limits
islands_chests
islands_effects
islands_entity_limits
islands_flags
islands_generators
islands_homes
islands_members
islands_missions
islands_player_permissions
islands_ratings
islands_role_limits
islands_role_permissions
islands_settings
islands_upgrades
islands_visitor_homes
islands_visitors
islands_warp_categories
islands_warps
players
players_missions
players_settings
stacked_blocks

**Comment by Neige7** [comment]
> > > Are you using mysql or sqlite?
> > 
> > 
> > I use mariadb. it’s similar to mysql
> 
> yeah that's fine. What tables do you have in the database?

bank_transactions
grid
islands
islands_banks
islands_bans
islands_block_limits
islands_chests
islands_effects
islands_entity_limits
islands_flags
islands_generators
islands_homes
islands_members
islands_missions
islands_player_permissions
islands_ratings
islands_role_limits
islands_role_permissions
islands_settings
islands_upgrades
islands_visitor_homes
islands_visitors
islands_warp_categories
islands_warps
players
players_missions
players_settings
stacked_blocks
I have uploaded the sql file in this comment https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/770#issuecomment-985212595

**Comment by OmerBenGera** [comment]
Check what columns does the `islands` table have?
