### ISSUE TITLE
Expected a com.google.gson.JsonArray but was com.google.gson.JsonPrimitive

### ISSUE THREAD

**Issue by Spaex** [BG-Software-LLC/SuperiorSkyblock2#771]
### Minecraft's Version

Paper version git-Paper-391 (MC: 1.17.1)

### Plugin's Version

1.8.2

### Session Logs

https://pastebin.com/cnJ7Mci1

### Describe the bug

When I start my server I always get the error found under Additional Information. 
Plugin still enables itself and seems to work. The error occures only directly after startup.
This all occured after the update to 1.8.2 and happens every server start.

### To Reproduce

Start your server with SuperiorSkyblock 1.8.2 installed. Haven't changed anything else then updating the .jar file to the newest one from the last release on spigotmc.org

### Additional Information

[23:40:41 WARN]: [SuperiorSkyblock2] Task #188 for SuperiorSkyblock2 v1.8.2 generated an exception
com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonArray but was com.google.gson.JsonPrimitive
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:911) ~[patched_1.17.1.jar:git-Paper-391]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[patched_1.17.1.jar:git-Paper-391]
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[patched_1.17.1.jar:git-Paper-391]
	at com.google.gson.Gson.fromJson(Gson.java:846) ~[patched_1.17.1.jar:git-Paper-391]
	at com.google.gson.Gson.fromJson(Gson.java:817) ~[patched_1.17.1.jar:git-Paper-391]
	at com.bgsoftware.superiorskyblock.database.deserializer.IslandsDeserializer.deserializeBlockCounts(IslandsDeserializer.java:152) ~[SuperiorSkyblock2-1.8.2.jar:?]
	at com.bgsoftware.superiorskyblock.island.SIsland.deserializeBlockCounts(SIsland.java:3163) ~[SuperiorSkyblock2-1.8.2.jar:?]
	at com.bgsoftware.superiorskyblock.island.SIsland.lambda$new$0(SIsland.java:219) ~[SuperiorSkyblock2-1.8.2.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-391]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-391]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-391]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-391]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-391]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-391]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
[23:40:41 WARN]: [SuperiorSkyblock2] Task #190 for SuperiorSkyblock2 v1.8.2 generated an exception
com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonArray but was com.google.gson.JsonPrimitive
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:911) ~[patched_1.17.1.jar:git-Paper-391]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[patched_1.17.1.jar:git-Paper-391]
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[patched_1.17.1.jar:git-Paper-391]
	at com.google.gson.Gson.fromJson(Gson.java:846) ~[patched_1.17.1.jar:git-Paper-391]
	at com.google.gson.Gson.fromJson(Gson.java:817) ~[patched_1.17.1.jar:git-Paper-391]
	at com.bgsoftware.superiorskyblock.database.deserializer.IslandsDeserializer.deserializeBlockCounts(IslandsDeserializer.java:152) ~[SuperiorSkyblock2-1.8.2.jar:?]
	at com.bgsoftware.superiorskyblock.island.SIsland.deserializeBlockCounts(SIsland.java:3163) ~[SuperiorSkyblock2-1.8.2.jar:?]
	at com.bgsoftware.superiorskyblock.island.SIsland.lambda$new$0(SIsland.java:219) ~[SuperiorSkyblock2-1.8.2.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-391]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-391]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-391]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-391]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-391]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-391]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
[23:40:41 WARN]: [SuperiorSkyblock2] Task #192 for SuperiorSkyblock2 v1.8.2 generated an exception
com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonArray but was com.google.gson.JsonPrimitive
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:911) ~[patched_1.17.1.jar:git-Paper-391]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[patched_1.17.1.jar:git-Paper-391]
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[patched_1.17.1.jar:git-Paper-391]
	at com.google.gson.Gson.fromJson(Gson.java:846) ~[patched_1.17.1.jar:git-Paper-391]
	at com.google.gson.Gson.fromJson(Gson.java:817) ~[patched_1.17.1.jar:git-Paper-391]
	at com.bgsoftware.superiorskyblock.database.deserializer.IslandsDeserializer.deserializeBlockCounts(IslandsDeserializer.java:152) ~[SuperiorSkyblock2-1.8.2.jar:?]
	at com.bgsoftware.superiorskyblock.island.SIsland.deserializeBlockCounts(SIsland.java:3163) ~[SuperiorSkyblock2-1.8.2.jar:?]
	at com.bgsoftware.superiorskyblock.island.SIsland.lambda$new$0(SIsland.java:219) ~[SuperiorSkyblock2-1.8.2.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-391]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-391]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-391]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-391]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-391]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-391]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]

**Comment by OmerBenGera** [comment]
Mind sending me your sqlite database file?

**Comment by Spaex** [comment]
Sure no problem:
https://drive.google.com/drive/folders/1qZmTHws83x8qE7ewDz84Gt4X9AYrMldS?usp=sharing

**Comment by OmerBenGera** [comment]
Done.
I deleted your comment for now.
You can take down the link on your own if you wish as well.

**Comment by OmerBenGera** [comment]
There are two islands that seems to not have migrated, do you know maybe why?
I am talking about the islands with the uuid `912f4606-3593-4693-ba76-aed3ca5df24b` and `c65b3566-567b-4711-bf20-b89abc74bde6`, owned by `Abendsonne` and `Luki774`

**Comment by Spaex** [comment]
Hmm idk why. But I can delete them since they both are inactive for long time now. Maybe this will help.

**Comment by Spaex** [comment]
Seems like this fixed 2 of the 3 exceptions. Now the only one is:

```
[12:36:58 WARN]: [SuperiorSkyblock2] Task #188 for SuperiorSkyblock2 v1.8.2 generated an exception
com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonArray but was com.google.gson.JsonPrimitive
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:911) ~[patched_1.17.1.jar:git-Paper-391]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[patched_1.17.1.jar:git-Paper-391]
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[patched_1.17.1.jar:git-Paper-391]
	at com.google.gson.Gson.fromJson(Gson.java:846) ~[patched_1.17.1.jar:git-Paper-391]
	at com.google.gson.Gson.fromJson(Gson.java:817) ~[patched_1.17.1.jar:git-Paper-391]
	at com.bgsoftware.superiorskyblock.database.deserializer.IslandsDeserializer.deserializeBlockCounts(IslandsDeserializer.java:152) ~[SuperiorSkyblock2-1.8.2.jar:?]
	at com.bgsoftware.superiorskyblock.island.SIsland.deserializeBlockCounts(SIsland.java:3163) ~[SuperiorSkyblock2-1.8.2.jar:?]
	at com.bgsoftware.superiorskyblock.island.SIsland.lambda$new$0(SIsland.java:219) ~[SuperiorSkyblock2-1.8.2.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-391]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-391]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-391]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-391]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-391]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-391]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

**I also did update the database.db in the shared Google Drive folder**

**Comment by OmerBenGera** [comment]
The island of `Huntleyy` seems to also have that bug, my bad.

**Comment by Spaex** [comment]
Seems fixed now thank you very much. Idk what caused them since they had normal islands.

**Comment by OmerBenGera** [comment]
If it happens again, lmk.
