### ISSUE TITLE
Unable to load plugin due to null initializing SuperiorSkyblock2

### ISSUE THREAD

**Issue by Prophet731** [BG-Software-LLC/SuperiorSkyblock2#774]
### Minecraft's Version

System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.1+12-39) 
Host: Linux 4.15.0-156-generic (amd64)
Paper Build: paper-1.18-52.jar

### Plugin's Version

Dev Build 387

### Describe the bug

```
[21:56:54 INFO]: [SuperiorSkyblock2] Loading SuperiorSkyblock2 v1.8.2
[21:56:54 ERROR]: [org.bukkit.craftbukkit.v1_18_R1.CraftServer] null initializing SuperiorSkyblock2 v1.8.2 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.bgsoftware.superiorskyblock.utils.StringUtils.translateColors(StringUtils.java:273) ~[SuperiorSkyblock2-1.8.2.jar:?]
        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.log(SuperiorSkyblockPlugin.java:154) ~[SuperiorSkyblock2-1.8.2.jar:?]
        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.loadNMSAdapter(SuperiorSkyblockPlugin.java:384) ~[SuperiorSkyblock2-1.8.2.jar:?]
        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onLoad(SuperiorSkyblockPlugin.java:184) ~[SuperiorSkyblock2-1.8.2.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:427) ~[paper-1.18.jar:git-Paper-52]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:285) ~[paper-1.18.jar:git-Paper-52]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.jar:git-Paper-52]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-52]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant com.bgsoftware.superiorskyblock.utils.ServerVersion.v1_18
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at com.bgsoftware.superiorskyblock.utils.ServerVersion.valueOf(ServerVersion.java:7) ~[SuperiorSkyblock2-1.8.2.jar:?]
        at com.bgsoftware.superiorskyblock.utils.ServerVersion.<clinit>(ServerVersion.java:29) ~[SuperiorSkyblock2-1.8.2.jar:?]
        ... 9 more
```

### To Reproduce

Just dropped plugin in a fresh install of Minecraft server.

**Comment by Prophet731** [comment]
Also to note, this is running in a dockerized container. Can provide a test server if that would help.

**Comment by OmerBenGera** [comment]
The plugin doesnt support 1.18.
