### ISSUE TITLE
Missions GUI throws an error and does not load

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#782]
### Minecraft's Version

1.17.1

### Plugin's Version

1.8.2.387 Dev

### Describe the bug

This stops the menu from loading, it only fixes when I remove the page buttons from the GUI.

pattern:
  - '# # # # # # # # #'
  - '# @ @ @ @ @ @ @ #'
  - '# @ @ @ @ @ @ @ #'
  - '# @ @ @ @ @ @ @ #'
  - '# @ @ @ @ @ @ @ #'
  - '# # # ^ & * # # #'

slots: '@'
previous-page: '^'
current-page: '&'
next-page: '*'

If I remove these from the pattern then the error and issue goes away.

### To Reproduce
Add the page buttons into the menu
Restart
MEnus do not load

### Additional Information

[20:40:42 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "itemStack" is null
[20:40:42 WARN]:        at SuperiorSkyblock2-1.8.2-b386.jar//com.bgsoftware.superiorskyblock.utils.items.ItemBuilder.<init>(ItemBuilder.java:37)
[20:40:42 WARN]:        at SuperiorSkyblock2-1.8.2-b386.jar//com.bgsoftware.superiorskyblock.menu.PagedSuperiorMenu.buildInventory(PagedSuperiorMenu.java:105)
[20:40:42 WARN]:        at SuperiorSkyblock2-1.8.2-b386.jar//com.bgsoftware.superiorskyblock.menu.impl.MenuMissionsCategory.buildInventory(MenuMissionsCategory.java:96)
[20:40:42 WARN]:        at SuperiorSkyblock2-1.8.2-b386.jar//com.bgsoftware.superiorskyblock.menu.SuperiorMenu.getInventory(SuperiorMenu.java:202)
[20:40:42 WARN]:        at SuperiorSkyblock2-1.8.2-b386.jar//com.bgsoftware.superiorskyblock.menu.SuperiorMenu.open(SuperiorMenu.java:331)
[20:40:42 WARN]:        at SuperiorSkyblock2-1.8.2-b386.jar//com.bgsoftware.superiorskyblock.menu.SuperiorMenu.lambda$open$5(SuperiorMenu.java:307)
[20:40:42 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[20:40:42 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:40:42 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:40:42 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[20:40:42 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[20:40:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by OmerBenGera** [comment]
Upload the entire menu file to pastebin and send it here

**Comment by Skizzles** [comment]
https://paste.skizzles.me/aleqobohih.yaml

**Comment by OmerBenGera** [comment]
Temp solution will be to set the buttons to a symbol that doesn't exist in the pattern, as it seems like you just don't want them in your menu.
I will fix it on the plugin's side as well - you'll see when a fix is released for this.
Closing this for now

**Comment by Skizzles** [comment]
> Temp solution will be to set the buttons to a symbol that doesn't exist in the pattern, as it seems like you just don't want them in your menu. I will fix it on the plugin's side as well - you'll see when a fix is released for this. Closing this for now

I actually really need them in the menu due to having over 400 quests.

But thanks. Will wait for a fix.

**Comment by OmerBenGera** [comment]
> > Temp solution will be to set the buttons to a symbol that doesn't exist in the pattern, as it seems like you just don't want them in your menu. I will fix it on the plugin's side as well - you'll see when a fix is released for this. Closing this for now
> 
> I actually really need them in the menu due to having over 400 quests.
> 
> But thanks. Will wait for a fix.

then setup items for them in the items section
