### ISSUE TITLE
Crash at startup (1.18.1)

### ISSUE THREAD

**Issue by Teyir** [BG-Software-LLC/SuperiorSkyblock2#791]
### Minecraft's Version

1.18.1 (pufferfish latest build)

### Plugin's Version

1.8.2-b406

### Describe the bug

When I startup my server I have this error befor crash:

```

>.... [22:08:55 INFO]: [SuperiorSkyblock2] Enabling the module nashorn-engine...
>.... [22:08:55 WARN]: [SuperiorSkyblock2] Loaded class org.openjdk.nashorn.api.scripting.NashornScriptEngineFactory from TrMenu v3.0-RC-2 which is not a depend, softdepend or loadbefore of this plugin.
>.... [22:08:55 INFO]: [SuperiorSkyblock2] Finished enabling the module nashorn-engine (Took 6ms)
>.... [22:08:55 INFO]: [SuperiorSkyblock2] Enabling the module generators...
>.... [22:08:55 INFO]: [SuperiorSkyblock2] Finished enabling the module generators (Took 4ms)
>.... [22:08:55 INFO]: [SuperiorSkyblock2] Enabling the module upgrades...
>.... [22:08:55 INFO]: [SuperiorSkyblock2] Finished enabling the module upgrades (Took 14ms)
>.... [22:08:55 WARN]: java.lang.NoClassDefFoundError: Could not initialize class org.openjdk.nashorn.internal.runtime.Context$AnonymousContextCodeInstaller
>.... [22:08:55 WARN]: at TrMenu-3.0-RC-2.jar//org.openjdk.nashorn.internal.runtime.Context.compile(Context.java:1509)
>.... [22:08:55 WARN]: at TrMenu-3.0-RC-2.jar//org.openjdk.nashorn.internal.runtime.Context.compileScript(Context.java:1449)
>.... [22:08:55 WARN]: at TrMenu-3.0-RC-2.jar//org.openjdk.nashorn.internal.runtime.Context.compileScript(Context.java:759)
>.... [22:08:55 WARN]: at TrMenu-3.0-RC-2.jar//org.openjdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:528)
>.... [22:08:55 WARN]: at TrMenu-3.0-RC-2.jar//org.openjdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:517)
>.... [22:08:55 WARN]: at TrMenu-3.0-RC-2.jar//org.openjdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:395)
>.... [22:08:55 WARN]: at TrMenu-3.0-RC-2.jar//org.openjdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:151)
>.... [22:08:55 WARN]: at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262)
>.... [22:08:55 WARN]: at com.bgsoftware.superiorskyblock.scripts.NashornScript.eval(NashornScript.java:36)
>.... [22:08:55 WARN]: at SuperiorSkyblock2-1.8.2-b406.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.testScriptEngine(SuperiorSkyblockPlugin.java:446)
>.... [22:08:55 WARN]: at SuperiorSkyblock2-1.8.2-b406.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.checkScriptEngine(SuperiorSkyblockPlugin.java:441)
>.... [22:08:55 WARN]: at SuperiorSkyblock2-1.8.2-b406.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:463)
>.... [22:08:55 WARN]: at SuperiorSkyblock2-1.8.2-b406.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:271)
>.... [22:08:55 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
>.... [22:08:55 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
>.... [22:08:55 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
>.... [22:08:55 WARN]: at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563)
>.... [22:08:55 WARN]: at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477)
>.... [22:08:55 WARN]: at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:729)
>.... [22:08:55 WARN]: at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:505)
>.... [22:08:55 WARN]: at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:315)
>.... [22:08:55 WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1204)
>.... [22:08:55 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319)
>.... [22:08:55 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)

```

And when my server want to stop I have this error

```

>.... [22:09:00 INFO]: Saving players
>.... [22:09:00 INFO]: Saving worlds
>.... [22:09:00 INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
>.... [22:09:01 INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
>.... [22:09:06 INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
>.... [22:09:07 INFO]: Saving chunks for level 'ServerLevel[SuperiorWorld]'/minecraft:superiorworld
>.... [22:09:09 ERROR]: Exception stopping the server
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com/bgsoftware/superiorskyblock/world/generator/IslandsGenerator$1
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:58) ~[?:?]
at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:91) ~[?:?]
at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:146) ~[?:?]
at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: com/bgsoftware/superiorskyblock/world/generator/IslandsGenerator$1
at com.bgsoftware.superiorskyblock.world.generator.IslandsGenerator.generateChunkData(IslandsGenerator.java:55) ~[SuperiorSkyblock2-1.8.2-b406.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.generator.CustomChunkGenerator.a(CustomChunkGenerator.java:165) ~[pufferfish-1.18.1.jar:git-Pufferfish-23]
at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:125) ~[pufferfish-1.18.1.jar:git-Pufferfish-23]
at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.doWork(ChunkStatus.java:342) ~[?:?]
at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:273) ~[pufferfish-1.18.1.jar:git-Pufferfish-23]
at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$35(ChunkMap.java:1211) ~[pufferfish-1.18.1.jar:git-Pufferfish-23]
at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[pufferfish-1.18.1.jar:?]
at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$37(ChunkMap.java:1209) ~[pufferfish-1.18.1.jar:git-Pufferfish-23]
at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]

```

### To Reproduce

I juste start my server .

### Additional Information

It's a new configuration,

I use Java 17.

My start up flags

```

java -Xms128M -Xmx11093M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar server.jar

```

this is my plugin list:

bungeeguard
buycraftX
Citizens
CMI
CMILib
Featherboard
HeadDatabase
LuckPerms
Multiverse Core
PlaceholderAPI
Plan
PlayerPoints
Quests
QuestsGUI
spark
SuperiorSkyblock
TAB
TrMenu
Vault
WorldEdit
Worldguard

**Comment by OmerBenGera** [comment]
Any issues related to the nashorn engine are not solvable on plugin's side.
You can install an external plugin that provides nashorn engine and delete the nashorn engine module of the plugin.
