### ISSUE TITLE
Spam error

### ISSUE THREAD

**Issue by Superalex0102** [BG-Software-LLC/SuperiorSkyblock2#798]
### Minecraft's Version

1.12.2

### Plugin's Version

v1.8.2.418

### Describe the bug

[15:43:00] [Server thread/WARN]: [SuperiorSkyblock2] Task #-2146233300 for SuperiorSkyblock2 v1.8.2.418 generated an exception
java.lang.NullPointerException: null
	at com.bgsoftware.common.executors.WorkerExecutor.stop(WorkerExecutor.java:128) ~[?:?]
	at com.bgsoftware.common.executors.WorkerExecutor.run(WorkerExecutor.java:160) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-77cce823]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-77cce823]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-77cce823]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-77cce823]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-77cce823]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-77cce823]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

### To Reproduce

Log

**Comment by OmerBenGera** [comment]
When did it happen..?

**Comment by Superalex0102** [comment]
I can't find any specific commands that was used after the error came up

**Comment by OmerBenGera** [comment]
Upload your logs file please and send them here.

**Comment by Superalex0102** [comment]
It is okay if I send it to the ticket? It has sensitive data

**Comment by OmerBenGera** [comment]
Yes.

**Comment by OmerBenGera** [comment]
Does it still occur after you restart your server?

**Comment by Superalex0102** [comment]
> Does it still occur after you restart your server?

Nope

**Comment by OmerBenGera** [comment]
I understand.
Anyways, it should be fixed in latest build.
