### ISSUE TITLE
Island upgrade error

### ISSUE THREAD

**Issue by warzoneak** [BG-Software-LLC/SuperiorSkyblock2#806]
### Minecraft's Version

1.12.2 paper

### Plugin's Version

1.8.2.401

### Describe the bug

When i try upgrading my ore generator after reach the 4th one i get this error.

[01:18:38 INFO]: Upgrades | Successfully updated the level of generator-rates for McBlocks's island.
[01:18:38 INFO]: Island | Successfully sent to McBlocks's island members the message!
[01:18:39 INFO]: Upgrades | Successfully updated the level of generator-rates for McBlocks's island.
[01:18:39 INFO]: Island | Successfully sent to McBlocks's island members the message!
[01:18:40 INFO]: Upgrades | Successfully updated the level of generator-rates for McBlocks's island.
[01:18:40 INFO]: Island | Successfully sent to McBlocks's island members the message!
[01:18:40 ERROR]: Could not pass event InventoryClickEvent to SuperiorSkyblock2 v1.8.2.401
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1619]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1619]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1619]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1619]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2002) ~[patched_1.12.2.jar:git-Paper-1619]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.12.2.jar:git-Paper-1619]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1619]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1619]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_291]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_291]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1619]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1619]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1619]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1619]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1619]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
Caused by: java.lang.NullPointerException
        at com.bgsoftware.superiorskyblock.module.upgrades.commands.CmdRankup.execute(CmdRankup.java:132) ~[?:?]
        at com.bgsoftware.superiorskyblock.commands.IPermissibleCommand.execute(IPermissibleCommand.java:38) ~[?:?]
        at com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.execute(ISuperiorCommand.java:18) ~[?:?]
        at com.bgsoftware.superiorskyblock.commands.CommandsHandler$PluginCommand.execute(CommandsHandler.java:261) ~[?:?]
        at com.bgsoftware.superiorskyblock.commands.CommandsHandler.dispatchSubCommand(CommandsHandler.java:139) ~[?:?]
        at com.bgsoftware.superiorskyblock.menu.impl.MenuUpgrades.onPlayerClick(MenuUpgrades.java:177) ~[?:?]
        at com.bgsoftware.superiorskyblock.menu.SuperiorMenu.onClick(SuperiorMenu.java:249) ~[?:?]
        at com.bgsoftware.superiorskyblock.listeners.MenusListener.onMenuClick(MenusListener.java:66) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor415.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1619]
        ... 15 more

### To Reproduce

im not sure tbh.

**Comment by OmerBenGera** [comment]
You probably have a faulty configuration of upgrades.
Upload your upgrades file to pastebin and send it here.

**Comment by warzoneak** [comment]
just wanna add to this. it appears the upgrades did go through that happened when you try to upgrade passed max upgrades.

Also with this error even after restarting the server the icon for this upgrade that would normally say maxed is gone.
https://gyazo.com/445d8ec138461d258c5f5d94d0fd0894

you replied while i was typing this so here is the config you requested. I didnt actually change the rates i was just setting it up to see if i did it correctly.

`generator-rates:
    '1':
      price: 25000.0
      price-type: "Money"
      generator-rates:
        normal:
          STONE: 95
          COAL_ORE: 5
      commands:
        - 'island admin setupgrade %player% generator-rates 2'
        - 'island admin msgall %player% &e&lSuperiorSkyblock &7Your generator was upgraded to level 2!'
    '2':
      price: 75000.0
      price-type: "Money"
      generator-rates:
        normal:
          STONE: 92
          COAL_ORE: 5
          REDSTONE_ORE: 3
      commands:
        - 'island admin setupgrade %player% generator-rates 3'
        - 'island admin msgall %player% &e&lSuperiorSkyblock &7Your generator was upgraded to level 3!'
    '3':
      price: 150000.0
      price-type: "Money"
      permission: 'upgrade.gen.donor'
      generator-rates:
        normal:
          STONE: 80
          COAL_ORE: 8
          REDSTONE_ORE: 6
          LAPIS_ORE: 4
          IRON_ORE: 2
      commands:
        - 'island admin setupgrade %player% generator-rates 4'
        - 'island admin msgall %player% &e&lSuperiorSkyblock &7Your generator was upgraded to level 4!'
    '4':
      price: 150000.0
      price-type: "Money"
      permission: 'upgrade.gen.donor'
      generator-rates:
        normal:
          STONE: 80
          COAL_ORE: 8
          REDSTONE_ORE: 6
          LAPIS_ORE: 4
          IRON_ORE: 2
      commands:
        - 'island admin setupgrade %player% generator-rates 5'
        - 'island admin msgall %player% &e&lSuperiorSkyblock &7Your generator was upgraded to level 5!'
    '5':
      price: 150000.0
      price-type: "Money"
      permission: 'upgrade.gen.donor'
      generator-rates:
        normal:
          STONE: 80
          COAL_ORE: 8
          REDSTONE_ORE: 6
          LAPIS_ORE: 4
          IRON_ORE: 2
      commands:
        - 'island admin setupgrade %player% generator-rates 6'
        - 'island admin msgall %player% &e&lSuperiorSkyblock &7Your generator was upgraded to level 6!'
    '6':
      price: 0.0
      price-type: "Money"
      generator-rates:
        normal:
          STONE: 65
          COAL_ORE: 10
          REDSTONE_ORE: 9
          LAPIS_ORE: 6
          IRON_ORE: 4
          GOLD_ORE: 3
          DIAMOND_ORE: 2
          EMERALD_ORE: 1
      commands:
        - 'island admin msg %player% &e&lSuperiorSkyblock &7You have reached the maximum upgrade for generator.'`

**Comment by OmerBenGera** [comment]
Looks fine for me.
When does it happen? When you upgrade from level 5 to 6 or when you try to upgrade while having level 6 already?

**Comment by OmerBenGera** [comment]
Ah I think its because you didnt configure menu items for these levels. Check it out, let me know if thats the case

**Comment by warzoneak** [comment]
yea it was the menu, im sorry for wasting your time man. i did follow the wiki but it didnt say anything about the menu even though its the next page on the wiki lol i honestly should have clued in myself. This 100% fixed my issue

**Comment by OmerBenGera** [comment]
Perfect :)
