### ISSUE TITLE
IllegalStateException from key duplicate 

### ISSUE THREAD

**Issue by aaa8881** [BG-Software-LLC/SuperiorSkyblock2#809]
### Minecraft's Version

1.17

### Plugin's Version

latest

### Describe the bug

/is admin show player , gives IllegalStateException , log attached as additional information

I can see key is bit messed up somewhere for blocklimit.
It could have happened from me using ItemStack as Key to set custom blocklimit through API last time. 

However, I manually tried to delete all blocklimit via in-game command for the user, and issue still persists. 
DB doesn't contain entry of blocklimit for the specific user.  

### To Reproduce

Not totally sure 

### Additional Information

org.bukkit.command.CommandException: Unhandled exception executing 'is admin show changwonfirebird' in com.bgsoftware.superiorskyblock.commands.CommandsHandler$PluginCommand(is)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.17.1.jar:git-Paper-402]
    at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Paper-402]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2262) ~[app:?]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2073) ~[app:?]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2054) ~[app:?]
    at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
    at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[app:?]
    at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
    at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-402]
    at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
    at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
    at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-402]
    at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-402]
    at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
    at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-402]
    at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-402]
    at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
    at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[patched_1.17.1.jar:git-Paper-402]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1286) ~[patched_1.17.1.jar:git-Paper-402]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-402]
    at java.lang.Thread.run(Thread.java:831) ~[?:?]

Caused by: java.lang.IllegalStateException: Duplicate key 1
    at com.bgsoftware.superiorskyblock.key.dataset.KeyMap.lambda$getCollector$2(KeyMap.java:139) ~[SuperiorSkyblock2-1.8.1-b353.jar:?]
    at java.util.Map.merge(Map.java:1271) ~[?:?]
    at java.util.stream.Collectors.lambda$toMap$68(Collectors.java:1666) ~[?:?]
    at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
    at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1837) ~[?:?]
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
    at com.bgsoftware.superiorskyblock.island.SIsland.getBlocksLimits(SIsland.java:2087) ~[SuperiorSkyblock2-1.8.1-b353.jar:?]
    at com.bgsoftware.superiorskyblock.commands.admin.CmdAdminShow.execute(CmdAdminShow.java:231) ~[SuperiorSkyblock2-1.8.1-b353.jar:?]
    at com.bgsoftware.superiorskyblock.commands.IAdminIslandCommand.execute(IAdminIslandCommand.java:19) ~[SuperiorSkyblock2-1.8.1-b353.jar:?]
    at com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.execute(ISuperiorCommand.java:13) ~[SuperiorSkyblock2-1.8.1-b353.jar:?]
    at com.bgsoftware.superiorskyblock.commands.player.CmdAdmin.execute(CmdAdmin.java:75) ~[SuperiorSkyblock2-1.8.1-b353.jar:?]
    at com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.execute(ISuperiorCommand.java:13) ~[SuperiorSkyblock2-1.8.1-b353.jar:?]
    at com.bgsoftware.superiorskyblock.commands.CommandsHandler$PluginCommand.execute(CommandsHandler.java:261) ~[SuperiorSkyblock2-1.8.1-b353.jar:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-402]
    ... 20 more

**Comment by OmerBenGera** [comment]
What limits does the Island have?
How to replicate the issue?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by aaa8881** [comment]
Hey, The error message is resolved after reboot, so no replication. However, spawner count not properly working from other issue still persists. closing this one.
