### ISSUE TITLE
Problem with create Island

### ISSUE THREAD

**Issue by Rap3erka** [BG-Software-LLC/SuperiorSkyblock2#811]
### Minecraft's Version

Airplane 1.17.1

### Plugin's Version

1.8.3

### Describe the bug

[06:11:45] [Server thread/INFO]: Rap3erka issued server command: /superiorskyblock2:is create Rap3erka
[06:11:46] [Server thread/ERROR]: Could not pass event IslandSchematicPasteEvent to SuperiorSkyblock2 v1.8.3
java.lang.AssertionError: Failed generating bytecode for <eval>:1
	at org.openjdk.nashorn.internal.codegen.CompilationPhase$BytecodeGenerationPhase.transform(CompilationPhase.java:437) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CompilationPhase.apply(CompilationPhase.java:614) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.Compiler.compile(Compiler.java:641) ~[?:?]
	at org.openjdk.nashorn.internal.runtime.Context.compile(Context.java:1531) ~[?:?]
	at org.openjdk.nashorn.internal.runtime.Context.compileScript(Context.java:1451) ~[?:?]
	at org.openjdk.nashorn.internal.runtime.Context.compileScript(Context.java:761) ~[?:?]
	at org.openjdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:528) ~[?:?]
	at org.openjdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:517) ~[?:?]
	at org.openjdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:395) ~[?:?]
	at org.openjdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:151) ~[?:?]
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233) ~[java.scripting:?]
	at com.bgsoftware.superiorskyblock.scripts.NashornScript.eval(NashornScript.java:41) ~[?:?]
	at com.bgsoftware.superiorskyblock.missions.IslandMissions.tryComplete(IslandMissions.java:210) ~[?:?]
	at com.bgsoftware.superiorskyblock.missions.IslandMissions.tryComplete(IslandMissions.java:196) ~[?:?]
	at com.bgsoftware.superiorskyblock.missions.IslandMissions.onIslandWorthUpdate(IslandMissions.java:192) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor322.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Airplane-55]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Airplane-55]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Airplane-55]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Airplane-55]
	at com.bgsoftware.superiorskyblock.utils.events.EventsCaller.callIslandSchematicPasteEvent(EventsCaller.java:169) ~[?:?]
	at com.bgsoftware.superiorskyblock.schematic.impl.SuperiorSchematic.lambda$pasteSchematic$1(SuperiorSchematic.java:324) ~[?:?]
	at com.bgsoftware.superiorskyblock.world.blocks.BlockChangeTask.lambda$submitUpdate$5(BlockChangeTask.java:77) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2143) ~[?:?]
	at com.bgsoftware.superiorskyblock.world.chunks.ChunksProvider$ChunkLoadWorker.finishLoad(ChunksProvider.java:86) ~[?:?]
	at com.bgsoftware.superiorskyblock.hooks.provider.AsyncProvider_Paper.lambda$loadChunk$0(AsyncProvider_Paper.java:16) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:100) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1143) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.doRunTask(ServerChunkCache.java:1221) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1236) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:836) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1395) ~[patched_1.17.1.jar:git-Airplane-55]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1378) ~[patched_1.17.1.jar:git-Airplane-55]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1354) ~[patched_1.17.1.jar:git-Airplane-55]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1265) ~[patched_1.17.1.jar:git-Airplane-55]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[patched_1.17.1.jar:git-Airplane-55]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalAccessError: failed to access class org.openjdk.nashorn.internal.codegen.CodeGenerator$3$4 from class org.openjdk.nashorn.internal.codegen.CodeGenerator$3 (org.openjdk.nashorn.internal.codegen.CodeGenerator$3$4 is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @4fd6418d; org.openjdk.nashorn.internal.codegen.CodeGenerator$3 is in unnamed module of loader com.bgsoftware.superiorskyblock.module.ModuleClassLoader @30058095)
	at org.openjdk.nashorn.internal.codegen.CodeGenerator$3.enterAccessNode(CodeGenerator.java:1590) ~[?:?]
	at org.openjdk.nashorn.internal.ir.AccessNode.accept(AccessNode.java:67) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator.loadCallNode(CodeGenerator.java:1435) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator$2.enterCallNode(CodeGenerator.java:1002) ~[?:?]
	at org.openjdk.nashorn.internal.ir.CallNode.accept(CallNode.java:177) ~[?:?]
	at org.openjdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57) ~[?:?]
	at org.openjdk.nashorn.internal.ir.LexicalContextExpression.accept(LexicalContextExpression.java:47) ~[?:?]
	at org.openjdk.nashorn.internal.ir.CallNode.accept(CallNode.java:41) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator.loadExpression(CodeGenerator.java:857) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator.loadExpression(CodeGenerator.java:833) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator.loadExpressionAsType(CodeGenerator.java:828) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator$15.evaluate(CodeGenerator.java:3934) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator$Store.store(CodeGenerator.java:4581) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator.loadASSIGN(CodeGenerator.java:3936) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator$2.enterASSIGN(CodeGenerator.java:919) ~[?:?]
	at org.openjdk.nashorn.internal.ir.visitor.NodeOperatorVisitor.enterBinaryNode(NodeOperatorVisitor.java:113) ~[?:?]
	at org.openjdk.nashorn.internal.ir.BinaryNode.accept(BinaryNode.java:329) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator.loadExpression(CodeGenerator.java:857) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator.loadExpression(CodeGenerator.java:833) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator.loadAndDiscard(CodeGenerator.java:3680) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator.enterExpressionStatement(CodeGenerator.java:1716) ~[?:?]
	at org.openjdk.nashorn.internal.ir.ExpressionStatement.accept(ExpressionStatement.java:81) ~[?:?]
	at org.openjdk.nashorn.internal.ir.Node.accept(Node.java:286) ~[?:?]
	at org.openjdk.nashorn.internal.ir.Block.accept(Block.java:236) ~[?:?]
	at org.openjdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57) ~[?:?]
	at org.openjdk.nashorn.internal.ir.Block.accept(Block.java:507) ~[?:?]
	at org.openjdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:405) ~[?:?]
	at org.openjdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57) ~[?:?]
	at org.openjdk.nashorn.internal.ir.LexicalContextExpression.accept(LexicalContextExpression.java:47) ~[?:?]
	at org.openjdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:57) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CompilationPhase.transformFunction(CompilationPhase.java:618) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CompilationPhase$BytecodeGenerationPhase.transform(CompilationPhase.java:424) ~[?:?]
	... 53 more
[06:11:46] [Server thread/ERROR]: Could not pass event IslandSchematicPasteEvent to SuperiorSkyblock2 v1.8.3
java.lang.AssertionError: Failed generating bytecode for <eval>:1
	at org.openjdk.nashorn.internal.codegen.CompilationPhase$BytecodeGenerationPhase.transform(CompilationPhase.java:437) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CompilationPhase.apply(CompilationPhase.java:614) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.Compiler.compile(Compiler.java:641) ~[?:?]
	at org.openjdk.nashorn.internal.runtime.Context.compile(Context.java:1531) ~[?:?]
	at org.openjdk.nashorn.internal.runtime.Context.compileScript(Context.java:1451) ~[?:?]
	at org.openjdk.nashorn.internal.runtime.Context.compileScript(Context.java:761) ~[?:?]
	at org.openjdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:528) ~[?:?]
	at org.openjdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:517) ~[?:?]
	at org.openjdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:395) ~[?:?]
	at org.openjdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:151) ~[?:?]
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233) ~[java.scripting:?]
	at com.bgsoftware.superiorskyblock.scripts.NashornScript.eval(NashornScript.java:41) ~[?:?]
	at com.bgsoftware.superiorskyblock.missions.IslandMissions.tryComplete(IslandMissions.java:210) ~[?:?]
	at com.bgsoftware.superiorskyblock.missions.IslandMissions.tryComplete(IslandMissions.java:196) ~[?:?]
	at com.bgsoftware.superiorskyblock.missions.IslandMissions.onIslandWorthUpdate(IslandMissions.java:192) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor341.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Airplane-55]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Airplane-55]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Airplane-55]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Airplane-55]
	at com.bgsoftware.superiorskyblock.utils.events.EventsCaller.callIslandSchematicPasteEvent(EventsCaller.java:169) ~[?:?]
	at com.bgsoftware.superiorskyblock.schematic.impl.SuperiorSchematic.lambda$pasteSchematic$1(SuperiorSchematic.java:324) ~[?:?]
	at com.bgsoftware.superiorskyblock.world.blocks.BlockChangeTask.lambda$submitUpdate$5(BlockChangeTask.java:77) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2143) ~[?:?]
	at com.bgsoftware.superiorskyblock.world.chunks.ChunksProvider$ChunkLoadWorker.finishLoad(ChunksProvider.java:86) ~[?:?]
	at com.bgsoftware.superiorskyblock.hooks.provider.AsyncProvider_Paper.lambda$loadChunk$0(AsyncProvider_Paper.java:16) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:100) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1143) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.doRunTask(ServerChunkCache.java:1221) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1236) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:836) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1395) ~[patched_1.17.1.jar:git-Airplane-55]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1378) ~[patched_1.17.1.jar:git-Airplane-55]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1354) ~[patched_1.17.1.jar:git-Airplane-55]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1265) ~[patched_1.17.1.jar:git-Airplane-55]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[patched_1.17.1.jar:git-Airplane-55]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalAccessError: failed to access class org.openjdk.nashorn.internal.codegen.CodeGenerator$3$4 from class org.openjdk.nashorn.internal.codegen.CodeGenerator$3 (org.openjdk.nashorn.internal.codegen.CodeGenerator$3$4 is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @4fd6418d; org.openjdk.nashorn.internal.codegen.CodeGenerator$3 is in unnamed module of loader com.bgsoftware.superiorskyblock.module.ModuleClassLoader @30058095)
	at org.openjdk.nashorn.internal.codegen.CodeGenerator$3.enterAccessNode(CodeGenerator.java:1590) ~[?:?]
	at org.openjdk.nashorn.internal.ir.AccessNode.accept(AccessNode.java:67) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator.loadCallNode(CodeGenerator.java:1435) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator$2.enterCallNode(CodeGenerator.java:1002) ~[?:?]
	at org.openjdk.nashorn.internal.ir.CallNode.accept(CallNode.java:177) ~[?:?]
	at org.openjdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57) ~[?:?]
	at org.openjdk.nashorn.internal.ir.LexicalContextExpression.accept(LexicalContextExpression.java:47) ~[?:?]
	at org.openjdk.nashorn.internal.ir.CallNode.accept(CallNode.java:41) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator.loadExpression(CodeGenerator.java:857) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator.loadExpression(CodeGenerator.java:833) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator.loadExpressionAsType(CodeGenerator.java:828) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator$15.evaluate(CodeGenerator.java:3934) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator$Store.store(CodeGenerator.java:4581) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator.loadASSIGN(CodeGenerator.java:3936) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator$2.enterASSIGN(CodeGenerator.java:919) ~[?:?]
	at org.openjdk.nashorn.internal.ir.visitor.NodeOperatorVisitor.enterBinaryNode(NodeOperatorVisitor.java:113) ~[?:?]
	at org.openjdk.nashorn.internal.ir.BinaryNode.accept(BinaryNode.java:329) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator.loadExpression(CodeGenerator.java:857) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator.loadExpression(CodeGenerator.java:833) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator.loadAndDiscard(CodeGenerator.java:3680) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CodeGenerator.enterExpressionStatement(CodeGenerator.java:1716) ~[?:?]
	at org.openjdk.nashorn.internal.ir.ExpressionStatement.accept(ExpressionStatement.java:81) ~[?:?]
	at org.openjdk.nashorn.internal.ir.Node.accept(Node.java:286) ~[?:?]
	at org.openjdk.nashorn.internal.ir.Block.accept(Block.java:236) ~[?:?]
	at org.openjdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57) ~[?:?]
	at org.openjdk.nashorn.internal.ir.Block.accept(Block.java:507) ~[?:?]
	at org.openjdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:405) ~[?:?]
	at org.openjdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57) ~[?:?]
	at org.openjdk.nashorn.internal.ir.LexicalContextExpression.accept(LexicalContextExpression.java:47) ~[?:?]
	at org.openjdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:57) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CompilationPhase.transformFunction(CompilationPhase.java:618) ~[?:?]
	at org.openjdk.nashorn.internal.codegen.CompilationPhase$BytecodeGenerationPhase.transform(CompilationPhase.java:424) ~[?:?]
	... 53 more

### To Reproduce

When I want create island

**Comment by OmerBenGera** [comment]
Did you edit your missions?

**Comment by OmerBenGera** [comment]
Any news regarding this?
