### ISSUE TITLE
Could not pass event SpawnerStackedEntitySpawnEvent to SuperiorSkyblock2 v1.8.3

### ISSUE THREAD

**Issue by Aathoss** [BG-Software-LLC/SuperiorSkyblock2#856]
### Minecraft's Version

This server is running Paper version git-Paper-165 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 128691a)
You are running the latest version
Previous version: git-Paper-150 (MC: 1.18.1)

### Plugin's Version

[18:11:12 INFO]: SuperiorSkyblock2 version 1.8.3
[18:11:12 INFO]: Feature packed Skyblock core.
[18:11:12 INFO]: Website: https://bg-software.com/
[18:11:12 INFO]: Author: Ome_R

### Describe the bug

I am using WildStacker, when spawning any entity with the generator
I get the following error in the console

```[18:14:54 ERROR]: Could not pass event SpawnerStackedEntitySpawnEvent to SuperiorSkyblock2 v1.8.3
java.lang.NullPointerException: Cannot invoke "com.bgsoftware.superiorskyblock.module.upgrades.listeners.UpgradesListener.handleSpawnerSpawn(org.bukkit.block.CreatureSpawner)" because "com.bgsoftware.superiorskyblock.module.upgrades.listeners.UpgradesListener.IMP" is null
        at com.bgsoftware.superiorskyblock.module.upgrades.listeners.WildStackerListener.onWildStackerStackSpawn(WildStackerListener.java:10) ~[SuperiorSkyblock2-1.8.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor593.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-165]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at com.bgsoftware.wildstacker.utils.events.EventsCaller.callSpawnerStackedEntitySpawnEvent(EventsCaller.java:127) ~[WildStacker-3.6.2.jar:?]
        at com.bgsoftware.wildstacker.nms.NMSSpawners_v1_18_R1$StackedMobSpawner.a(NMSSpawners_v1_18_R1.java:355) ~[WildStacker-3.6.2.jar:?]
        at net.minecraft.world.level.block.entity.SpawnerBlockEntity.serverTick(SpawnerBlockEntity.java:54) ~[?:?]
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1167) ~[?:?]
        at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1119) ~[?:?]
        at net.minecraft.world.level.Level.tickBlockEntities(Level.java:956) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:679) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[paper-1.18.1.jar:git-Paper-165]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-165]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-165]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-165]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-165]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]```

### To Reproduce

No idea yet
I have the impression that the problem comes from the passage under paper #150

### Additional Information

_No response_

**Comment by OmerBenGera** [comment]
Update to latest dev build, the issue is already fixed :)
