### ISSUE TITLE
Database error - Unable to start up server

### ISSUE THREAD

**Issue by Kbryst** [BG-Software-LLC/SuperiorSkyblock2#866]
### Minecraft's Version

Paper 169, 1.18.1. Java 17

### Plugin's Version

Dev b482

### Describe the bug

Error happens on startup. Tried SQLite and MySQL. Tried fresh install. 

[13:22:44 INFO]: [SuperiorSkyblock2] Trying to connect to local database (SQLite)...
[13:22:44 INFO]: [SuperiorSkyblock2] ################################################
[13:22:44 INFO]: [SuperiorSkyblock2] ##                                            ##
[13:22:44 INFO]: [SuperiorSkyblock2] ## An error occured while loading the plugin! ##
[13:22:44 INFO]: [SuperiorSkyblock2] ##                                            ##
[13:22:44 INFO]: [SuperiorSkyblock2] ################################################
[13:22:44 INFO]: [SuperiorSkyblock2] 
[13:22:44 INFO]: [SuperiorSkyblock2] Error:
[13:22:44 INFO]: [SuperiorSkyblock2] Couldn't connect to the database.
[13:22:44 INFO]: [SuperiorSkyblock2] Make sure all information is correct.
[13:22:44 INFO]: [SuperiorSkyblock2] 
[13:22:44 INFO]: [SuperiorSkyblock2] StackTrace:
[13:22:44 INFO]: [SuperiorSkyblock2]    at SuperiorSkyblock2-1.8.3-b482.jar//com.bgsoftware.superiorskyblock.database.DataHandler.loadData(DataHandler.java:51)
[13:22:44 INFO]: [SuperiorSkyblock2]    at SuperiorSkyblock2-1.8.3-b482.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:493)
[13:22:44 INFO]: [SuperiorSkyblock2]    at SuperiorSkyblock2-1.8.3-b482.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:270)
[13:22:44 INFO]: [SuperiorSkyblock2]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:22:44 INFO]: [SuperiorSkyblock2]    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[13:22:44 INFO]: [SuperiorSkyblock2]    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[13:22:44 INFO]: [SuperiorSkyblock2]    at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[13:22:44 INFO]: [SuperiorSkyblock2]    at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[13:22:44 INFO]: [SuperiorSkyblock2]    at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[13:22:44 INFO]: [SuperiorSkyblock2]    at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[13:22:44 INFO]: [SuperiorSkyblock2]    at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[13:22:44 INFO]: [SuperiorSkyblock2]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[13:22:44 INFO]: [SuperiorSkyblock2]    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[13:22:44 INFO]: [SuperiorSkyblock2]    at java.base/java.lang.Thread.run(Thread.java:833)
[13:22:44 INFO]: [SuperiorSkyblock2] 
[13:22:44 INFO]: [SuperiorSkyblock2] ################################################

### To Reproduce

Starting up my server, even with default files, generates this error.
I attempted swapping to SQL and I still get the same error.
Server shuts down once it completes its startup and cannot stay on. 
*I did remove the plugin to confirm it is the cause of the server shutting off after startup.

**Comment by OmerBenGera** [comment]
Install latest dev build, and send me the new errors that appeared.
The new version should also print a message that tells what failed.

**Comment by OmerBenGera** [comment]
I managed to replicate the issue myself, I am looking into a fix right now.

**Comment by Kbryst** [comment]
Thanks so much!
I went ahead and tried the latest dev build, here's the output


[14:02:57] [Server thread/INFO]: [SuperiorSkyblock2] Enabling SuperiorSkyblock2 v1.8.3.483
[14:02:59] [Server thread/INFO]: Preparing start region for dimension minecraft:superiorworld
[14:02:59] [Server thread/INFO]: Preparing spawn area: 0%
[14:02:59] [Server thread/INFO]: Time elapsed: 289 ms
[14:02:59] [Server thread/INFO]: [WorldGuard] (SuperiorWorld) TNT ignition is PERMITTED.
[14:02:59] [Server thread/INFO]: [WorldGuard] (SuperiorWorld) Lighters are PERMITTED.
[14:02:59] [Server thread/INFO]: [WorldGuard] (SuperiorWorld) Lava fire is PERMITTED.
[14:02:59] [Server thread/INFO]: [WorldGuard] (SuperiorWorld) Fire spread is UNRESTRICTED.
[14:02:59] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'SuperiorWorld'
[14:02:59] [Server thread/INFO]: [dynmap] Loaded 3 maps of world 'SuperiorWorld'.
[14:02:59] [Server thread/INFO]: [dynmap] Loaded 268 pending tile renders for world 'SuperiorWorld'
[14:02:59] [Server thread/INFO]: [SuperiorSkyblock2] Enabling the module bank...
[14:02:59] [Server thread/INFO]: [SuperiorSkyblock2] Finished enabling the module bank (Took 5ms)
[14:02:59] [Server thread/INFO]: [SuperiorSkyblock2] Enabling the module missions...
[14:03:00] [Server thread/INFO]: [SuperiorSkyblock2] Registered mission miner_2
[14:03:00] [Server thread/INFO]: [SuperiorSkyblock2] Registered mission miner_3
[14:03:00] [Server thread/INFO]: [SuperiorSkyblock2] Registered mission miner_5
[14:03:00] [Server thread/INFO]: [SuperiorSkyblock2] Registered mission miner_1
[14:03:00] [Server thread/INFO]: [SuperiorSkyblock2] Registered mission miner_4
[14:03:00] [Server thread/INFO]: [SuperiorSkyblock2] Registered mission slayer_4
[14:03:00] [Server thread/INFO]: [SuperiorSkyblock2] Registered mission slayer_2
[14:03:00] [Server thread/INFO]: [SuperiorSkyblock2] Registered mission slayer_3
[14:03:00] [Server thread/INFO]: [SuperiorSkyblock2] Registered mission slayer_1
[14:03:00] [Server thread/INFO]: [SuperiorSkyblock2] Registered mission farmer_1
[14:03:00] [Server thread/INFO]: [SuperiorSkyblock2] Registered mission farmer_4
[14:03:00] [Server thread/INFO]: [SuperiorSkyblock2] Registered mission farmer_3
[14:03:00] [Server thread/INFO]: [SuperiorSkyblock2] Registered mission farmer_5
[14:03:00] [Server thread/INFO]: [SuperiorSkyblock2] Registered mission farmer_2
[14:03:00] [Server thread/INFO]: [SuperiorSkyblock2] Registered mission fisherman_2
[14:03:00] [Server thread/INFO]: [SuperiorSkyblock2] Registered mission fisherman_3
[14:03:00] [Server thread/INFO]: [SuperiorSkyblock2] Registered mission fisherman_1
[14:03:01] [Server thread/INFO]: [SuperiorSkyblock2] Registered mission explorer_2
[14:03:01] [Server thread/INFO]: [SuperiorSkyblock2] Registered mission explorer_1
[14:03:01] [Server thread/INFO]: [SuperiorSkyblock2] Finished enabling the module missions (Took 1170ms)
[14:03:01] [Server thread/INFO]: [SuperiorSkyblock2] Enabling the module nashorn-engine...
[14:03:03] [Server thread/INFO]: [SuperiorSkyblock2] Finished enabling the module nashorn-engine (Took 2182ms)
[14:03:03] [Server thread/INFO]: [SuperiorSkyblock2] Enabling the module generators...
[14:03:03] [Server thread/INFO]: [SuperiorSkyblock2] Finished enabling the module generators (Took 6ms)
[14:03:03] [Server thread/INFO]: [SuperiorSkyblock2] Enabling the module upgrades...
[14:03:03] [Server thread/INFO]: [SuperiorSkyblock2] Finished enabling the module upgrades (Took 9ms)
[14:03:04] [Server thread/INFO]: [SuperiorSkyblock2] Loading messages started...
[14:03:04] [Server thread/INFO]: [SuperiorSkyblock2]  - Found 676 messages in the language files.
[14:03:04] [Server thread/INFO]: [SuperiorSkyblock2] Loading messages done (Took 189ms)
[14:03:05] [Server thread/INFO]: [SuperiorSkyblock2] Schematic normal was created in a different version, may cause issues.
[14:03:05] [Server thread/INFO]: [SuperiorSkyblock2] Successfully loaded schematic normal.schematic (DefaultSchematicParser)
[14:03:05] [Server thread/INFO]: [SuperiorSkyblock2] Schematic mycel_the_end was created in a different version, may cause issues.
[14:03:05] [Server thread/INFO]: [SuperiorSkyblock2] Successfully loaded schematic mycel_the_end.schematic (DefaultSchematicParser)
[14:03:05] [Server thread/INFO]: [SuperiorSkyblock2] Schematic mycel_nether was created in a different version, may cause issues.
[14:03:05] [Server thread/INFO]: [SuperiorSkyblock2] Successfully loaded schematic mycel_nether.schematic (DefaultSchematicParser)
[14:03:05] [Server thread/INFO]: [SuperiorSkyblock2] Schematic mycel was created in a different version, may cause issues.
[14:03:05] [Server thread/INFO]: [SuperiorSkyblock2] Successfully loaded schematic mycel.schematic (DefaultSchematicParser)
[14:03:05] [Server thread/INFO]: [SuperiorSkyblock2] Schematic normal_the_end was created in a different version, may cause issues.
[14:03:05] [Server thread/INFO]: [SuperiorSkyblock2] Successfully loaded schematic normal_the_end.schematic (DefaultSchematicParser)
[14:03:05] [Server thread/INFO]: [SuperiorSkyblock2] Schematic desert was created in a different version, may cause issues.
[14:03:05] [Server thread/INFO]: [SuperiorSkyblock2] Successfully loaded schematic desert.schematic (DefaultSchematicParser)
[14:03:05] [Server thread/INFO]: [SuperiorSkyblock2] Schematic desert_nether was created in a different version, may cause issues.
[14:03:05] [Server thread/INFO]: [SuperiorSkyblock2] Successfully loaded schematic desert_nether.schematic (DefaultSchematicParser)
[14:03:05] [Server thread/INFO]: [SuperiorSkyblock2] Schematic normal_nether was created in a different version, may cause issues.
[14:03:05] [Server thread/INFO]: [SuperiorSkyblock2] Successfully loaded schematic normal_nether.schematic (DefaultSchematicParser)
[14:03:05] [Server thread/INFO]: [SuperiorSkyblock2] Schematic desert_the_end was created in a different version, may cause issues.
[14:03:05] [Server thread/INFO]: [SuperiorSkyblock2] Successfully loaded schematic desert_the_end.schematic (DefaultSchematicParser)
[14:03:05] [Server thread/INFO]: [SuperiorSkyblock2] Biome 'NETHER' is not valid, skipping...
[14:03:05] [Server thread/INFO]: [SuperiorSkyblock2] Biome 'WOODED_HILLS' is not valid, skipping...
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] Trying to connect to local database (SQLite)...
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] Failed to create parent folder directories.
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] ################################################
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] ##                                            ##
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] ## An error occured while loading the plugin! ##
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] ##                                            ##
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] ################################################
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] 
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] Error:
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] Couldn't connect to the database.
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] Make sure all information is correct.
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] 
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] StackTrace:
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] 	at SuperiorSkyblock2-1.8.3-b483.jar//com.bgsoftware.superiorskyblock.database.DataHandler.loadData(DataHandler.java:51)
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] 	at SuperiorSkyblock2-1.8.3-b483.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:493)
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] 	at SuperiorSkyblock2-1.8.3-b483.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:270)
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] 	at java.base/java.lang.Thread.run(Thread.java:833)
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] 
[14:03:06] [Server thread/INFO]: [SuperiorSkyblock2] ################################################

**Comment by OmerBenGera** [comment]
I've just published a fix :)

**Comment by Kbryst** [comment]
Thank you! Confirmed it worked for me.
