### ISSUE TITLE
Task #469, Exception with Slimefun

### ISSUE THREAD

**Issue by Kbryst** [BG-Software-LLC/SuperiorSkyblock2#867]
### Minecraft's Version

Paper 168, MC 1.18.1, Java 17

### Plugin's Version

Dev b484

### Describe the bug

Just an exception error on startup with Slimefun.
Current slimefun version Dev 999.

[14:15:47 WARN]: [SuperiorSkyblock2] Task #469 for SuperiorSkyblock2 v1.8.3.484 generated an exception
java.lang.NoSuchMethodError: 'void io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.registerModule(org.bukkit.Server, java.lang.String, java.util.function.Function)'
        at com.bgsoftware.superiorskyblock.hooks.support.SlimefunHook$Slimefun4RelocationsProtectionModule.lambda$register$1(SlimefunHook.java:172) ~[SuperiorSkyblock2-1.8.3-b484.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-169]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-169]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-169]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-169]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-169]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-169]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-169]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### To Reproduce

Happens on startup. Unsure if it causes any issues in-game.

**Comment by Skizzles** [comment]
Able to confirm this issue as well @Kbryst I suggest reverting ur build as this causes machines and cargo nodes to be interactable by anyone regardless of island member status.

**Comment by OmerBenGera** [comment]
And of course, once again Slimefun broke their own API...
I will look into fixing it :)

**Comment by OmerBenGera** [comment]
There are currently 4 different workarounds for supporting Slimefun at this moment.
I am not gonna put more effort in fixing it anymore.
I will open an issue on their github, hopefully they will stop breaking their API.

On another note, fixed in latest dev build, so I am closing this one for now.
