### ISSUE TITLE
Server was keeps restarted 

### ISSUE THREAD

**Issue by NCSV** [BG-Software-LLC/SuperiorSkyblock2#868]
### Minecraft's Version

1.18.1 Ro.1

### Plugin's Version

SuperiorSkyblock2-1.8.3-b484

### Describe the bug

when start server, server was restart Infinitely.
so i downloaded lastest dev build of superior skyblock,
server was loaded, but all user data was not loaded.

### To Reproduce

apply SuperiorSkyblock2-1.8.3-(b470) -> lastest dev build (b484)

**Comment by Skizzles** [comment]
I am able to confirm this issue in build 470+

[14:28:58] [Server thread/INFO]: [SuperiorSkyblock2] Successfully established connection with MySQL database!
[14:28:58] [Server thread/WARN]: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'PRAGMA journal_mode=MEMORY' at line 1
[14:28:58] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[14:28:58] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[14:28:58] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[14:28:58] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.libs.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.libs.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.sql.SQLSession.executeQuery(SQLSession.java:167)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.sql.SQLSession.executeQuery(SQLSession.java:156)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.sql.SQLHelper.executeQuery(SQLHelper.java:58)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.sql.SQLDatabaseInitializer.setJournalMode(SQLDatabaseInitializer.java:132)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.DataHandler.loadData(DataHandler.java:63)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:493)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:270)
[14:28:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[14:28:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:28:58] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:28:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[14:28:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[14:28:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:736)
[14:28:58] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:353)
[14:28:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1233)
[14:28:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[14:28:58] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[14:28:58] [Server thread/INFO]: [SuperiorSkyblock2] Starting to load players...
[14:28:58] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.util.Map.put(Object, Object)" because "cachedPlayerInfo.completedMissions" is null
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.serialization.PlayersDeserializer.lambda$deserializeMissions$0(PlayersDeserializer.java:54)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.sql.SQLDatabaseBridge.lambda$loadAllObjects$0(SQLDatabaseBridge.java:45)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.sql.SQLSession.executeQuery(SQLSession.java:168)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.sql.SQLSession.executeQuery(SQLSession.java:156)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.sql.SQLHelper.executeQuery(SQLHelper.java:58)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.sql.SQLDatabaseBridge.loadAllObjects(SQLDatabaseBridge.java:42)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.serialization.PlayersDeserializer.deserializeMissions(PlayersDeserializer.java:24)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.DataHandler.loadPlayers(DataHandler.java:125)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.DataHandler.loadData(DataHandler.java:66)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:493)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:270)
[14:28:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[14:28:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:28:58] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:28:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[14:28:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[14:28:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:736)
[14:28:58] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:353)
[14:28:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1233)
[14:28:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[14:28:58] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[14:28:58] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.util.Map.put(Object, Object)" because "cachedPlayerInfo.completedMissions" is null
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.serialization.PlayersDeserializer.lambda$deserializeMissions$0(PlayersDeserializer.java:54)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.sql.SQLDatabaseBridge.lambda$loadAllObjects$0(SQLDatabaseBridge.java:45)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.sql.SQLSession.executeQuery(SQLSession.java:168)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.sql.SQLSession.executeQuery(SQLSession.java:156)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.sql.SQLHelper.executeQuery(SQLHelper.java:58)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.sql.SQLDatabaseBridge.loadAllObjects(SQLDatabaseBridge.java:42)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.serialization.PlayersDeserializer.deserializeMissions(PlayersDeserializer.java:24)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.DataHandler.loadPlayers(DataHandler.java:125)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.DataHandler.loadData(DataHandler.java:66)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:493)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:270)
[14:28:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[14:28:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:28:58] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:28:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[14:28:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[14:28:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:736)
[14:28:58] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:353)
[14:28:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1233)
[14:28:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[14:28:58] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[14:28:58] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.util.Map.put(Object, Object)" because "cachedPlayerInfo.completedMissions" is null
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.serialization.PlayersDeserializer.lambda$deserializeMissions$0(PlayersDeserializer.java:54)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.sql.SQLDatabaseBridge.lambda$loadAllObjects$0(SQLDatabaseBridge.java:45)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.sql.SQLSession.executeQuery(SQLSession.java:168)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.sql.SQLSession.executeQuery(SQLSession.java:156)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.sql.SQLHelper.executeQuery(SQLHelper.java:58)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.sql.SQLDatabaseBridge.loadAllObjects(SQLDatabaseBridge.java:42)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.serialization.PlayersDeserializer.deserializeMissions(PlayersDeserializer.java:24)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.DataHandler.loadPlayers(DataHandler.java:125)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.database.DataHandler.loadData(DataHandler.java:66)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:493)
[14:28:58] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b470.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:270)
[14:28:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[14:28:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:28:58] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:28:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[14:28:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[14:28:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:736)
[14:28:58] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:353)
[14:28:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1233)
[14:28:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[14:28:58] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by Skizzles** [comment]
@NCSV Use build 469 until Omer is available to look into this.

**Comment by NCSV** [comment]
> @NCSV Use build 469 until Omer is available to look into this.

how to download older than #475?
![1](https://user-images.githubusercontent.com/25452835/150657787-8bbc2c35-9555-4d87-a253-fcffee9d5c16.PNG)

**Comment by Skizzles** [comment]
@NCSV https://hub.bg-software.com/

**Comment by Trinchezito** [comment]
Same issue. Use The Build #469 to not lose player data and be able to connect to remote servers.

**Comment by NCSV** [comment]
> Same issue. Use The Build #469 to not lose player data and be able to connect to remote servers.
![3](https://user-images.githubusercontent.com/25452835/150658246-8328cd35-d2bf-43bb-a883-bd087f7c0186.PNG)
still same issue in #469 Did the db file break because of the version update?

**Comment by Skizzles** [comment]
@NCSV I believe that is due to yaml parsing being updated and the older build not yet having that fix. the database is not stored in yaml format.

what build were you using before updating?

**Comment by NCSV** [comment]
> apply SuperiorSkyblock2-1.8.3-(b470) -> lastest dev build (b484)

apply SuperiorSkyblock2-1.8.3-(b470)

**Comment by NCSV** [comment]
> > apply SuperiorSkyblock2-1.8.3-(b470) -> lastest dev build (b484)
> 
> SuperiorSkyblock2-1.8.3-(b470)

**Comment by NCSV** [comment]
oh i see it's a compatibility with newer dev version's config. i fixed. thx

**Comment by OmerBenGera** [comment]
Chexk out latest dev build, lmk if it works now.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build, sorry about that.
