### ISSUE TITLE
Island Border disappears forcing people to not be able to teleport to their island

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#894]
### Minecraft's Version

purpur-1.18.1-1467.jar

### Plugin's Version

SuperiorSkyblock2-1.8.4-b499.jar

### Describe the bug

Island border disappears on older islands, after checking multiple islands only ones created recently did not have this issue occur. When the border disappears it teleports users back to the spawn since they can not move outside the border.

### To Reproduce

Load up a new build
Enter into your server
All players are instantly teleported to spawn because they are outside the border
After viewing the islands with /is admin bypass I noticed some islands were missing their border completely (NO BORDER SHOWN)

### Additional Information

The database reflects -1 which should use the upgrades value. Confirmed this with Omer.

**Comment by WarnDa** [comment]
That's the issue I had
https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/861

but for me it's fixed using #496

**Comment by Skizzles** [comment]
If it was fixed I wouldnt open the issue. Already spoke with Omer directly on this.

**Comment by Skizzles** [comment]
Was fixed on latest dev build.

**Comment by Skizzles** [comment]
Upon further testing this is still present.

**Comment by Skizzles** [comment]
Error when trying to set leader, may be related.

[11:23:57 INFO]: ISkizzlesI issued server command: /is admin setleader ISkizzlesI SlipperyCheetah
[11:23:57 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'is admin setleader ISkizzlesI SlipperyCheetah' in com.bgsoftware.superiorskyblock.commands.CommandsHandler$PluginCommand(island)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:182) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897) ~[purpur-1.18.1.jar:git-Purpur-1467]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2353) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2164) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2145) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.1.jar:git-Purpur-1467]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1437) ~[purpur-1.18.1.jar:git-Purpur-1467]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[purpur-1.18.1.jar:git-Purpur-1467]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1415) ~[purpur-1.18.1.jar:git-Purpur-1467]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1408) ~[purpur-1.18.1.jar:git-Purpur-1467]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1386) ~[purpur-1.18.1.jar:git-Purpur-1467]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1292) ~[purpur-1.18.1.jar:git-Purpur-1467]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.18.1.jar:git-Purpur-1467]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException
        at java.util.concurrent.ConcurrentSkipListMap.doPut(ConcurrentSkipListMap.java:598) ~[?:?]
        at java.util.concurrent.ConcurrentSkipListMap.putIfAbsent(ConcurrentSkipListMap.java:1787) ~[?:?]
        at java.util.concurrent.ConcurrentSkipListSet.add(ConcurrentSkipListSet.java:243) ~[?:?]
        at com.bgsoftware.superiorskyblock.structure.SortedRegistry.put(SortedRegistry.java:39) ~[SuperiorSkyblock2-1.8.4-b525.jar:?]
        at com.bgsoftware.superiorskyblock.island.container.DefaultIslandsContainer.transferIsland(DefaultIslandsContainer.java:112) ~[SuperiorSkyblock2-1.8.4-b525.jar:?]
        at com.bgsoftware.superiorskyblock.world.GridHandler.transferIsland(GridHandler.java:395) ~[SuperiorSkyblock2-1.8.4-b525.jar:?]
        at com.bgsoftware.superiorskyblock.island.SIsland.transferIsland(SIsland.java:1276) ~[SuperiorSkyblock2-1.8.4-b525.jar:?]
        at com.bgsoftware.superiorskyblock.commands.admin.CmdAdminSetLeader.execute(CmdAdminSetLeader.java:91) ~[SuperiorSkyblock2-1.8.4-b525.jar:?]
        at com.bgsoftware.superiorskyblock.commands.IAdminPlayerCommand.execute(IAdminPlayerCommand.java:26) ~[SuperiorSkyblock2-1.8.4-b525.jar:?]
        at com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.execute(ISuperiorCommand.java:18) ~[SuperiorSkyblock2-1.8.4-b525.jar:?]
        at com.bgsoftware.superiorskyblock.commands.player.CmdAdmin.execute(CmdAdmin.java:75) ~[SuperiorSkyblock2-1.8.4-b525.jar:?]
        at com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.execute(ISuperiorCommand.java:18) ~[SuperiorSkyblock2-1.8.4-b525.jar:?]
        at com.bgsoftware.superiorskyblock.commands.CommandsHandler$PluginCommand.execute(CommandsHandler.java:262) ~[SuperiorSkyblock2-1.8.4-b525.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 20 more

**Comment by OmerBenGera** [comment]
The issue turned to be an issue with a faulty configuration.
If it occurs to you, look for errors from when islands are loaded from database and report them.
