### ISSUE TITLE
island upgrades is resetting when server is restarting

### ISSUE THREAD

**Issue by JoshuaPHYT** [BG-Software-LLC/SuperiorSkyblock2#913]
### Minecraft's Version

[11:00:15 INFO]: Current: git-Purpur-1547 (MC: 1.18.1)*
[11:00:15 INFO]: Previous: git-Purpur-1505 (MC: 1.18.1)
[11:00:15 INFO]: * You are running the latest version

### Plugin's Version

[11:00:39 INFO]: SuperiorSkyblock2 version 1.8.4.510

### Describe the bug

when im restarting my skyblock server. all of my players island upgrades is resetting idk why is happening

im using also one block addon

### To Reproduce

when im restarting my skyblock server. all of my players island upgrades is resetting idk why is happening

im using also one block addon

**Comment by JoshuaPHYT** [comment]
[09:58:00] [Server thread/INFO]: [com.bgsoftware.ssboneblock.OneBlockModule] [OneBlock] Failed to parse data for element: {"island":"a339c0ec-c065-3d22-b564-afc2309c3a46","phase-level":0,"phase-block":153}
[09:58:00] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.util.Locale.getLanguage()" because "userLocale" is null
[09:58:00] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.4-b510.jar//com.bgsoftware.superiorskyblock.database.bridge.PlayersDatabaseBridge.insertPlayer(PlayersDatabaseBridge.java:101)
[09:58:00] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.4-b510.jar//com.bgsoftware.superiorskyblock.player.PlayersHandler.getSuperiorPlayer(PlayersHandler.java:61)
[09:58:00] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.4-b510.jar//com.bgsoftware.superiorskyblock.api.SuperiorSkyblockAPI.getPlayer(SuperiorSkyblockAPI.java:66)
[09:58:00] [Server thread/WARN]: 	at com.bgsoftware.ssboneblock.handler.PhasesHandler.loadIslandData(PhasesHandler.java:114)
[09:58:00] [Server thread/WARN]: 	at com.bgsoftware.ssboneblock.handler.DataHandler.loadDatabase(DataHandler.java:39)
[09:58:00] [Server thread/WARN]: 	at com.bgsoftware.ssboneblock.handler.DataHandler.<init>(DataHandler.java:20)
[09:58:00] [Server thread/WARN]: 	at com.bgsoftware.ssboneblock.OneBlockModule.onEnable(OneBlockModule.java:45)
[09:58:00] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.4-b510.jar//com.bgsoftware.superiorskyblock.module.ModulesHandler.enableModule(ModulesHandler.java:106)
[09:58:00] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[09:58:00] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[09:58:00] [Server thread/WARN]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[09:58:00] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[09:58:00] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[09:58:00] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[09:58:00] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[09:58:00] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[09:58:00] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[09:58:00] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.4-b510.jar//com.bgsoftware.superiorskyblock.module.ModulesHandler.enableModules(ModulesHandler.java:140)
[09:58:00] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.4-b510.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:471)
[09:58:00] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.4-b510.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:236)
[09:58:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[09:58:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[09:58:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[09:58:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[09:58:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[09:58:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:732)
[09:58:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:508)
[09:58:00] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:349)
[09:58:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1218)
[09:58:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[09:58:00] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by JoshuaPHYT** [comment]
this is spamming on my console its happening everytime

**Comment by JoshuaPHYT** [comment]
[latest (3).log](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/8014697/latest.3.log)

**Comment by JoshuaPHYT** [comment]
I don't know if that error that is related. Because someone also reported a bug on Discord same with mine

**Comment by OmerBenGera** [comment]
> [09:58:00] [Server thread/INFO]: [com.bgsoftware.ssboneblock.OneBlockModule] [OneBlock] Failed to parse data for element: {"island":"a339c0ec-c065-3d22-b564-afc2309c3a46","phase-level":0,"phase-block":153} [09:58:00] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.util.Locale.getLanguage()" because "userLocale" is null [09:58:00] [Server thread/WARN]: at SuperiorSkyblock2-1.8.4-b510.jar//com.bgsoftware.superiorskyblock.database.bridge.PlayersDatabaseBridge.insertPlayer(PlayersDatabaseBridge.java:101) [09:58:00] [Server thread/WARN]: at SuperiorSkyblock2-1.8.4-b510.jar//com.bgsoftware.superiorskyblock.player.PlayersHandler.getSuperiorPlayer(PlayersHandler.java:61) [09:58:00] [Server thread/WARN]: at SuperiorSkyblock2-1.8.4-b510.jar//com.bgsoftware.superiorskyblock.api.SuperiorSkyblockAPI.getPlayer(SuperiorSkyblockAPI.java:66) [09:58:00] [Server thread/WARN]: at com.bgsoftware.ssboneblock.handler.PhasesHandler.loadIslandData(PhasesHandler.java:114) [09:58:00] [Server thread/WARN]: at com.bgsoftware.ssboneblock.handler.DataHandler.loadDatabase(DataHandler.java:39) [09:58:00] [Server thread/WARN]: at com.bgsoftware.ssboneblock.handler.DataHandler.(DataHandler.java:20) [09:58:00] [Server thread/WARN]: at com.bgsoftware.ssboneblock.OneBlockModule.onEnable(OneBlockModule.java:45) [09:58:00] [Server thread/WARN]: at SuperiorSkyblock2-1.8.4-b510.jar//com.bgsoftware.superiorskyblock.module.ModulesHandler.enableModule(ModulesHandler.java:106) [09:58:00] [Server thread/WARN]: at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) [09:58:00] [Server thread/WARN]: at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) [09:58:00] [Server thread/WARN]: at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) [09:58:00] [Server thread/WARN]: at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) [09:58:00] [Server thread/WARN]: at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) [09:58:00] [Server thread/WARN]: at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) [09:58:00] [Server thread/WARN]: at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) [09:58:00] [Server thread/WARN]: at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [09:58:00] [Server thread/WARN]: at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) [09:58:00] [Server thread/WARN]: at SuperiorSkyblock2-1.8.4-b510.jar//com.bgsoftware.superiorskyblock.module.ModulesHandler.enableModules(ModulesHandler.java:140) [09:58:00] [Server thread/WARN]: at SuperiorSkyblock2-1.8.4-b510.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:471) [09:58:00] [Server thread/WARN]: at SuperiorSkyblock2-1.8.4-b510.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:236) [09:58:00] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [09:58:00] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) [09:58:00] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) [09:58:00] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) [09:58:00] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) [09:58:00] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:732) [09:58:00] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:508) [09:58:00] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:349) [09:58:00] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1218) [09:58:00] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) [09:58:00] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:833)

Do not mix issues.
This error was already reported.

**Comment by OmerBenGera** [comment]
About upgrades resetting, this was already addressed and will not occur again in the future.

**Comment by JoshuaPHYT** [comment]
but its happening every restart tho
