### ISSUE TITLE
Weird Bug

### ISSUE THREAD

**Issue by FantonFancy** [BG-Software-LLC/SuperiorSkyblock2#964]
### Minecraft's Version

1.8.8 Paper

### Plugin's Version

1.8.4

### Describe the bug

```
[20:00:53 INFO]: [SuperiorSkyblock2] Enabling the module bank...
[20:00:53 INFO]: [SuperiorSkyblock2] Finished enabling the module bank (Took 8ms)
[20:00:53 INFO]: [SuperiorSkyblock2] Enabling the module missions...
[20:00:53 INFO]: [SuperiorSkyblock2] Registered mission miner_2
[20:00:53 INFO]: [SuperiorSkyblock2] Registered mission miner_3
[20:00:53 INFO]: [SuperiorSkyblock2] Registered mission miner_4
[20:00:53 INFO]: [SuperiorSkyblock2] Registered mission miner_1
[20:00:53 INFO]: [SuperiorSkyblock2] Registered mission miner_5
[20:00:53 INFO]: [SuperiorSkyblock2] Registered mission slayer_1
[20:00:53 INFO]: [SuperiorSkyblock2] Registered mission slayer_3
[20:00:53 INFO]: [SuperiorSkyblock2] Registered mission slayer_2
[20:00:53 INFO]: [SuperiorSkyblock2] Registered mission slayer_4
[20:00:53 INFO]: [SuperiorSkyblock2] Registered mission farmer_5
[20:00:53 INFO]: [SuperiorSkyblock2] Registered mission farmer_3
[20:00:53 INFO]: [SuperiorSkyblock2] Registered mission farmer_4
[20:00:53 INFO]: [SuperiorSkyblock2] [config.yml] Couldn't convert rewards.items.1 into an itemstack. Check type & data sections!
[20:00:53 INFO]: [SuperiorSkyblock2] Couldn't register mission farmer_1: 
[20:00:53 WARN]: com.bgsoftware.superiorskyblock.handler.HandlerLoadException: Couldn't register mission farmer_1.
[20:00:53 WARN]:        at com.bgsoftware.superiorskyblock.mission.MissionsHandler.loadMission(MissionsHandler.java:418)
[20:00:53 WARN]:        at com.bgsoftware.superiorskyblock.module.missions.MissionsModule.canLoadCategory(MissionsModule.java:225)
[20:00:53 WARN]:        at com.bgsoftware.superiorskyblock.module.missions.MissionsModule.onEnable(MissionsModule.java:122)
[20:00:53 WARN]:        at com.bgsoftware.superiorskyblock.module.BuiltinModule.onEnable(BuiltinModule.java:24)
[20:00:53 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesHandler.enableModule(ModulesHandler.java:106)
[20:00:53 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[20:00:53 WARN]:        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[20:00:53 WARN]:        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
[20:00:53 WARN]:        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[20:00:53 WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[20:00:53 WARN]:        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[20:00:53 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[20:00:53 WARN]:        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[20:00:53 WARN]:        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
[20:00:53 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesHandler.enableModules(ModulesHandler.java:140)
[20:00:53 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:460)
[20:00:53 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:270)
[20:00:53 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[20:00:53 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[20:00:53 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[20:00:53 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[20:00:53 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[20:00:53 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[20:00:53 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[20:00:53 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[20:00:53 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[20:00:53 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[20:00:53 WARN]:        at java.lang.Thread.run(Thread.java:748)
[20:00:53 WARN]: Caused by: java.lang.NullPointerException
[20:00:53 WARN]:        at com.bgsoftware.superiorskyblock.mission.MissionData.<init>(MissionData.java:40)
[20:00:53 WARN]:        at com.bgsoftware.superiorskyblock.mission.MissionsHandler.loadMission(MissionsHandler.java:413)
[20:00:53 WARN]:        ... 27 more
[20:00:53 INFO]: [SuperiorSkyblock2] Registered mission farmer_2
[20:00:53 INFO]: [SuperiorSkyblock2] Registered mission fisherman_3
[20:00:53 INFO]: [SuperiorSkyblock2] Registered mission fisherman_1
[20:00:53 INFO]: [SuperiorSkyblock2] Registered mission fisherman_2
[20:00:53 INFO]: [SuperiorSkyblock2] Registered mission explorer_1
[20:00:53 INFO]: [SuperiorSkyblock2] Registered mission explorer_2
[20:00:53 INFO]: [SuperiorSkyblock2] Finished enabling the module missions (Took 157ms)
[20:00:53 INFO]: [SuperiorSkyblock2] Enabling the module generators...
[20:00:53 INFO]: [SuperiorSkyblock2] Finished enabling the module generators (Took 5ms)
[20:00:53 INFO]: [SuperiorSkyblock2] Enabling the module upgrades...
[20:00:53 ERROR]: [SuperiorSkyblock2] Plugin SuperiorSkyblock2 v1.8.4 has failed to register events for class com.bgsoftware.superiorskyblock.module.upgrades.type.UpgradeTypeIslandEffects$IslandEffectsListener because org/bukkit/event/entity/EntityPotionEffectEvent does not exist.
[20:00:53 INFO]: [SuperiorSkyblock2] Finished enabling the module upgrades (Took 14ms)
[20:00:53 INFO]: [SuperiorSkyblock2] Loading messages started...
[20:00:54 INFO]: [SuperiorSkyblock2]  - Found 676 messages in the language files.
[20:00:54 INFO]: [SuperiorSkyblock2] Loading messages done (Took 878ms)
[20:00:55 INFO]: [SuperiorSkyblock2] Successfully loaded schematic desert_the_end.schematic (DefaultSchematicParser)
[20:00:55 INFO]: [SuperiorSkyblock2] Successfully loaded schematic mycel_the_end.schematic (DefaultSchematicParser)
[20:00:56 INFO]: [SuperiorSkyblock2] Successfully loaded schematic mycel_nether.schematic (DefaultSchematicParser)
[20:00:56 INFO]: [SuperiorSkyblock2] Successfully loaded schematic mycel.schematic (DefaultSchematicParser)
[20:00:57 INFO]: [SuperiorSkyblock2] Successfully loaded schematic normal_nether.schematic (DefaultSchematicParser)
[20:00:57 INFO]: [SuperiorSkyblock2] Successfully loaded schematic normal.schematic (DefaultSchematicParser)
[20:00:58 INFO]: [SuperiorSkyblock2] Successfully loaded schematic desert_nether.schematic (DefaultSchematicParser)
[20:00:58 INFO]: [SuperiorSkyblock2] Successfully loaded schematic normal_the_end.schematic (DefaultSchematicParser)
[20:00:59 INFO]: [SuperiorSkyblock2] Successfully loaded schematic desert.schematic (DefaultSchematicParser)
[20:00:59 WARN]: com.bgsoftware.superiorskyblock.handler.HandlerLoadException: java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.BLOCK_ANVIL_PLACE
[20:00:59 WARN]:        at com.bgsoftware.superiorskyblock.hooks.provider.MenusProvider_Default.handleExceptions(MenusProvider_Default.java:72)
[20:00:59 WARN]:        at com.bgsoftware.superiorskyblock.hooks.provider.MenusProvider_Default.initializeMenus(MenusProvider_Default.java:83)
[20:00:59 WARN]:        at com.bgsoftware.superiorskyblock.menu.MenusHandler.loadData(MenusHandler.java:26)
[20:00:59 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:490)
[20:00:59 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:270)
[20:00:59 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[20:00:59 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[20:00:59 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[20:00:59 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[20:00:59 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[20:00:59 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[20:00:59 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[20:00:59 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[20:00:59 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[20:00:59 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[20:00:59 WARN]:        at java.lang.Thread.run(Thread.java:748)
[20:00:59 WARN]: Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.BLOCK_ANVIL_PLACE
[20:00:59 WARN]:        at java.lang.Enum.valueOf(Enum.java:238)
[20:00:59 WARN]:        at org.bukkit.Sound.valueOf(Sound.java:1)
[20:00:59 WARN]:        at com.bgsoftware.superiorskyblock.menu.impl.internal.SuperiorMenuBlank.init(SuperiorMenuBlank.java:44)
[20:00:59 WARN]:        at com.bgsoftware.superiorskyblock.hooks.provider.MenusProvider_Default.handleExceptions(MenusProvider_Default.java:70)
[20:00:59 WARN]:        ... 15 more
[20:00:59 INFO]: [SuperiorSkyblock2] Trying to connect to local database (SQLite)...
```

when i startup server this happens

### To Reproduce

Download latest plugin from spigot, run it on 1.8.8 paper and you will probably see this error 

### Additional Information

N/A

**Comment by OmerBenGera** [comment]
Use latest dev build
