### ISSUE TITLE
Player islands keep getting lost from his player data

### ISSUE THREAD

**Issue by Trinchezito** [BG-Software-LLC/SuperiorSkyblock2#981]
### Minecraft's Version

1.18.2

### Plugin's Version

latest 

### Describe the bug

`[03:22:50] [Server thread/ERROR]: Could not pass event PlayerLoginEvent to SuperiorSkyblock2 v1.8.4.539
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentSkipListMap.doPut(ConcurrentSkipListMap.java:598) ~[?:?]
	at java.util.concurrent.ConcurrentSkipListMap.putIfAbsent(ConcurrentSkipListMap.java:1787) ~[?:?]
	at java.util.concurrent.ConcurrentSkipListSet.add(ConcurrentSkipListSet.java:243) ~[?:?]
	at com.bgsoftware.superiorskyblock.structure.SortedRegistry.put(SortedRegistry.java:39) ~[SuperiorSkyblock2-1.8.4-b539.jar:?]
	at com.bgsoftware.superiorskyblock.island.container.DefaultIslandsContainer.transferIsland(DefaultIslandsContainer.java:112) ~[SuperiorSkyblock2-1.8.4-b539.jar:?]
	at com.bgsoftware.superiorskyblock.world.GridHandler.transferIsland(GridHandler.java:395) ~[SuperiorSkyblock2-1.8.4-b539.jar:?]
	at com.bgsoftware.superiorskyblock.island.SIsland.replacePlayers(SIsland.java:1301) ~[SuperiorSkyblock2-1.8.4-b539.jar:?]
	at com.bgsoftware.superiorskyblock.player.PlayersHandler.replacePlayers(PlayersHandler.java:147) ~[SuperiorSkyblock2-1.8.4-b539.jar:?]
	at com.bgsoftware.superiorskyblock.listeners.PlayersListener.onPlayerLogin(PlayersListener.java:113) ~[SuperiorSkyblock2-1.8.4-b539.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1482.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1566]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.canPlayerLogin(PlayerList.java:774) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:177) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:88) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:555) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1674) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:519) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1507) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1294) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

### To Reproduce

1 player got this message and now their island is always removed somehow. They create an island but when they rejoin the island on their player gets disbanded but the island is still there but they don't have permission to edit it. Is like their island didn't got removed but they rejoin as a new player with no island.

**Comment by Trinchezito** [comment]
`[05:11:46] [Server thread/INFO]: [SuperiorSkyblock2] Changing UUID of JugadorNinja to 120b4a28-335a-465d-91a9-1a233c48b0eb
[05:11:46] [Server thread/ERROR]: Could not pass event PlayerLoginEvent to SuperiorSkyblock2 v1.8.4.539
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentSkipListMap.doPut(ConcurrentSkipListMap.java:598) ~[?:?]
	at java.util.concurrent.ConcurrentSkipListMap.putIfAbsent(ConcurrentSkipListMap.java:1787) ~[?:?]
	at java.util.concurrent.ConcurrentSkipListSet.add(ConcurrentSkipListSet.java:243) ~[?:?]
	at com.bgsoftware.superiorskyblock.structure.SortedRegistry.put(SortedRegistry.java:39) ~[SuperiorSkyblock2-1.8.4-b539.jar:?]
	at com.bgsoftware.superiorskyblock.island.container.DefaultIslandsContainer.transferIsland(DefaultIslandsContainer.java:112) ~[SuperiorSkyblock2-1.8.4-b539.jar:?]
	at com.bgsoftware.superiorskyblock.world.GridHandler.transferIsland(GridHandler.java:395) ~[SuperiorSkyblock2-1.8.4-b539.jar:?]
	at com.bgsoftware.superiorskyblock.island.SIsland.replacePlayers(SIsland.java:1301) ~[SuperiorSkyblock2-1.8.4-b539.jar:?]
	at com.bgsoftware.superiorskyblock.player.PlayersHandler.replacePlayers(PlayersHandler.java:147) ~[SuperiorSkyblock2-1.8.4-b539.jar:?]
	at com.bgsoftware.superiorskyblock.listeners.PlayersListener.onPlayerLogin(PlayersListener.java:113) ~[SuperiorSkyblock2-1.8.4-b539.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1482.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1566]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.canPlayerLogin(PlayerList.java:774) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:177) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:88) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:555) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1674) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:519) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1507) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1294) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by Skizzles** [comment]
As you can see by the error message, something on your server is changing the user's UUID and SSB is expecting a different one.

Are you in offline mode and did the user change their name? Please provide a list of plugins.

**Comment by Trinchezito** [comment]
> As you can see by the error message, something on your server is changing the user's UUID and SSB is expecting a different one.
> 
> Are you in offline mode and did the user change their name? Please provide a list of plugins.

Actually, yes. I got the user to tell me what happened. I did some changed already.

We support premium and offline premiums. But players have to use /premium to set their account to premium. The player didn't and tried to do so after creating an island with a the non-premium session. Which is why i guess is trying to change the uuid.

I don't know if you can help, otherwise i guess you can close this since non premium issues aren't yours lol

**Comment by OmerBenGera** [comment]
> > As you can see by the error message, something on your server is changing the user's UUID and SSB is expecting a different one.
> > Are you in offline mode and did the user change their name? Please provide a list of plugins.
> 
> Actually, yes. I got the user to tell me what happened. I did some changed already.
> 
> We support premium and offline premiums. But players have to use /premium to set their account to premium. The player didn't and tried to do so after creating an island with a the non-premium session. Which is why i guess is trying to change the uuid.
> 
> I don't know if you can help, otherwise i guess you can close this since non premium issues aren't yours lol

Are you able to replicate the issue yourself using the `/premium` command?

**Comment by Trinchezito** [comment]
Yes, i was able to replicate this. 
To fix it i had to look up both UUIDs of the offline and premium and delete them in the world, essentials and Superiorskyblock files.

So to replicate this, log in with a cracked account, create an island.

Once you have an island, activate the /premium account. Then it happens, superiorskyblock i think tries to change the offline uuid to premium and fails. 

> > > As you can see by the error message, something on your server is changing the user's UUID and SSB is expecting a different one.
> 
> > > Are you in offline mode and did the user change their name? Please provide a list of plugins.
> 
> > 
> 
> > Actually, yes. I got the user to tell me what happened. I did some changed already.
> 
> > 
> 
> > We support premium and offline premiums. But players have to use /premium to set their account to premium. The player didn't and tried to do so after creating an island with a the non-premium session. Which is why i guess is trying to change the uuid.
> 
> > 
> 
> > I don't know if you can help, otherwise i guess you can close this since non premium issues aren't yours lol
> 
> 
> 
> Are you able to replicate the issue yourself using the `/premium` command?

**Comment by OmerBenGera** [comment]
> Yes, i was able to replicate this. To fix it i had to look up both UUIDs of the offline and premium and delete them in the world, essentials and Superiorskyblock files.
> 
> So to replicate this, log in with a cracked account, create an island.
> 
> Once you have an island, activate the /premium account. Then it happens, superiorskyblock i think tries to change the offline uuid to premium and fails.
> 
> > > > As you can see by the error message, something on your server is changing the user's UUID and SSB is expecting a different one.
> > 
> > 
> > > > Are you in offline mode and did the user change their name? Please provide a list of plugins.
> > 
> > 
> > > 
> > 
> > 
> > > Actually, yes. I got the user to tell me what happened. I did some changed already.
> > 
> > 
> > > 
> > 
> > 
> > > We support premium and offline premiums. But players have to use /premium to set their account to premium. The player didn't and tried to do so after creating an island with a the non-premium session. Which is why i guess is trying to change the uuid.
> > 
> > 
> > > 
> > 
> > 
> > > I don't know if you can help, otherwise i guess you can close this since non premium issues aren't yours lol
> > 
> > 
> > Are you able to replicate the issue yourself using the `/premium` command?

What plugin are you using for the `/premium` feature?

**Comment by Trinchezito** [comment]
I'm using latest fastlogin with authme and velocity at mc.meloncito.net

**Comment by XHealthy** [comment]
I have the same problem.

**Comment by OmerBenGera** [comment]
It must be a cracked account?
As I tried with my premium account and it seems to work.

**Comment by XHealthy** [comment]
It was happening on my account too. I have minecraft premium.

**Comment by OmerBenGera** [comment]
> It was happening on my account too. I have minecraft premium.

Was it related to the issue above?
If so, I couldn't replicate it. I ran `/premium` and everything was the same.

**Comment by XHealthy** [comment]
I somehow fixed it 2 weeks ago. Now I just wrote that it also happened on the premium version.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response.
If it still occurs, lmk by replying
