### ISSUE TITLE
Console error on removing item frame due to limit

### ISSUE THREAD

**Issue by Ynfuien** [BG-Software-LLC/SuperiorSkyblock2#987]
### Minecraft's Version

Latest Purpur 1.17.1

### Plugin's Version

Latest (d543)

### Describe the bug

An error logs in console when plugin removes item frame due to limit.

### To Reproduce

- Set limit of (glow) item frame in island
- Place one more item frame than setted limit

### Additional Information

```
[01:59:53 FATAL]: Thread Craft Scheduler Thread - 15 - SuperiorSkyblock2 failed main thread check: Entity remove
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager$Callback.onRemove(PersistentEntitySectionManager.java:607) ~[app:?]
        at net.minecraft.world.entity.Entity.setRemoved(Entity.java:4285) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.world.entity.Entity.remove(Entity.java:629) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.world.entity.Entity.discard(Entity.java:611) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftEntity.remove(CraftEntity.java:674) ~[patched_1.17.1.jar:git-Purpur-1428]
        at com.bgsoftware.superiorskyblock.module.upgrades.type.UpgradeTypeEntityLimits$BlockLimitsListener.lambda$onHangingPlace$2(UpgradeTypeEntityLimits.java:96) ~[SuperiorSkyblock2-1.8.4-b543.jar:?]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
        at com.bgsoftware.superiorskyblock.island.SIsland.lambda$hasReachedEntityLimit$65(SIsland.java:2297) ~[SuperiorSkyblock2-1.8.4-b543.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Purpur-1428]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
![image](https://user-images.githubusercontent.com/88110072/157781737-55bd6270-93a6-42a4-bda9-e725390136c7.png)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
