### ISSUE TITLE
EntityDeathEvent

### ISSUE THREAD

**Issue by ProfessorDeBroglie** [BG-Software-LLC/SuperiorSkyblock2#995]
### Minecraft's Version

1.18.2

### Plugin's Version

dev #552

### Describe the bug

[22:59:27] [Server thread/ERROR]: Could not pass event EntityDeathEvent to SuperiorSkyblock2 v1.8.4.552
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$null$3(DeathSimulation.java:162) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1285) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:429) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1237) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1047) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "tag" is null
        at com.bgsoftware.superiorskyblock.tag.CompoundTag.fromNBT(CompoundTag.java:76) ~[?:?]
        at com.bgsoftware.superiorskyblock.nms.v1_18_R2.NMSTagsImpl.getNBTTag(NMSTagsImpl.java:38) ~[?:?]
        at com.bgsoftware.superiorskyblock.module.upgrades.type.UpgradeTypeMobDrops$MobDropsListener.onEntityDeath(UpgradeTypeMobDrops.java:91) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor401.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 12 more

### To Reproduce

killing a animal

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
