### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by ProfessorDeBroglie** [BG-Software-LLC/SuperiorSkyblock2#996]
### Minecraft's Version

1.18.2

### Plugin's Version

dev #552

### Describe the bug

[01:40:28] [Server thread/WARN]: java.lang.NoSuchMethodError: 'void net.minecraft.world.level.chunk.DataPaletteBlock.<init>(net.minecraft.core.Registry, java.lang.Object, net.minecraft.world.level.chunk.DataPaletteBlock$e, java.lang.Object[])'
[01:40:28] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.nms.v1_18_R2.NMSWorldImpl.setBiome(NMSWorldImpl.java:195)
[01:40:28] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.world.blocks.BlockChangeTask.lambda$submitUpdate$4(BlockChangeTask.java:74)
[01:40:28] [Server thread/WARN]:        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[01:40:28] [Server thread/WARN]:        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
[01:40:28] [Server thread/WARN]:        at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
[01:40:28] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.world.chunks.ChunksProvider$ChunkLoadWorker.work(ChunksProvider.java:77)
[01:40:28] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
[01:40:28] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:429)
[01:40:28] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1237)
[01:40:28] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)

### To Reproduce

/is create <schematic>

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
