### ISSUE TITLE
y out of range

### ISSUE THREAD

**Issue by ProfessorDeBroglie** [BG-Software-LLC/SuperiorSkyblock2#997]
### Minecraft's Version

1.18.2

### Plugin's Version

dev #554

### Describe the bug

[03:13:42] [Craft Scheduler Thread - 45/WARN]: [SuperiorSkyblock2] Plugin SuperiorSkyblock2 v1.8.4.552 generated an exception while executing task 51410
java.lang.IllegalArgumentException: y out of range (expected -64-320, got -65)
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:453) ~[guava-31.0.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftChunk.validateChunkCoordinates(CraftChunk.java:373) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at org.bukkit.craftbukkit.v1_18_R2.CraftChunkSnapshot.validateChunkCoordinates(CraftChunkSnapshot.java:171) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at org.bukkit.craftbukkit.v1_18_R2.CraftChunkSnapshot.getBlockData(CraftChunkSnapshot.java:92) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at com.bgsoftware.superiorskyblock.nms.v1_18_R2.NMSWorldImpl.getBlockKey(NMSWorldImpl.java:87) ~[?:?]
        at com.bgsoftware.superiorskyblock.player.algorithm.DefaultPlayerTeleportAlgorithm.lambda$null$2(DefaultPlayerTeleportAlgorithm.java:145) ~[?:?]
        at com.bgsoftware.superiorskyblock.threads.Executor$NestedTask.lambda$null$4(Executor.java:161) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

### To Reproduce

use command /is teleport

**Comment by OmerBenGera** [comment]
Please use latest dev build and send me the error you receive in this version.
Also, send it via pastebin and not directly here.

**Comment by ProfessorDeBroglie** [comment]
ok, i installed the dev #555
command /is admin visit <player>
https://pastebin.pl/view/a5884751

**Comment by OmerBenGera** [comment]
Fixed in latest dev build :)
